/*Str!! Номер пачки меняем на введенный*/
//TAM 9.11.11 I-00101757-1 - изменение номера пачки и в проводках, у которых пачка совпадает с исходным документом
// KS 22.11.2013 Предварительная адаптация под 31ю сборку

macro NUMBERPACK(paymID,NP)
	debugbreak;
	var cmd_pm, cmd_ar, query, numb_old, rs:RsdRecordset, params:TArray;
        var askdialog;
	//Узнаем валюту и старую пачку
	query = "select t_numberpack  from dpmpaym_dbt where t_paymentid = :PaymentID";
	params = makeArray(SQLParam("PaymentID", paymID));
	rs = execSQLselect(query, params, true);
	
	//меняем пачку в проводках
	if(rs.MoveNext())
		numb_old = rs.Value(0);
			cmd_ar = RSDCommand (
					     " update dacctrn_dbt set t_number_pack = ? where t_number_pack = ? and t_acctrnid in "+
                                                   "(select t_acctrnid from dpmdocs_dbt where t_paymentid = ?)"
					    );

	 end;
	 
	 //меняем пачку у платежа
	 cmd_pm = RSDCommand(
				" update dpmpaym_dbt set t_numberpack=? where T_PAYMENTID=?  "         
				);

	 GetParm(2, askdialog);       

         if((askdialog == 1) or
           (GetInt(NP,"Номер пачки",5)))
		cmd_pm.addParam("r0",RSDBP_IN, NP );
		cmd_pm.addParam("r1",RSDBP_IN, paymID );
		cmd_pm.execute;
	
		cmd_ar.addParam("r0",RSDBP_IN, NP );
		cmd_ar.addParam("r1", RSDBP_IN, numb_old);
		cmd_ar.addParam("r2",RSDBP_IN, paymID );
		cmd_ar.execute;
		SetParm(1,NP);
	 end;
end;//macro