/******************************************************************************
   ˆ¬ï ä ©« ..:       rep_mass_other_bank.mac
    §­ ç¥­¨¥.:       Œ áá®¢ë© ®âç¥â ¯® ¯« â¥¦ã ­¥Š–
   ‡ ï¢ª .....:       C-14395
   „ â .......:       30.10.2012
   €¢â®à......:       Š®â®¢ ‘¥à£¥©
   Š®¬¬¥­â à¨©:       Œ áá®¢ë© ®âç¥â
******************************************************************************/

import rsbdataset;
import "rep_paym_other_bank.mac";
import SbCrdInter;

private var nameout = GetTxtFileName("rep_mass_Report");

macro getMassRepLife(dt_start, dt_end)

  private var query = "", r, cmd, statusid, status,
              cnt_all = 0, sum_all = $0,
              cnt_cls = 0, sum_cls = $0,
              closetime:datetime;

  //SetOutput(nameout,false);

  // ‘®§¤ ­¨¥ ¢á¯®¬®£ â¥«ì­®© â ¡«¨æë
  InitProgress( -1, "†¤¨â¥", "®«ãç¥­¨¥ ®âç¥â " );

  cmd = rsdcommand("truncate table USR_PMPAYM_STATUS_TMP"); // ç¨áâª  ¢á¯®¬®£ â¥«ì­®© â ¡«¨æë
  cmd.execute();

  query = "select pmpaym.t_paymentid" + "\n" +
          "  from dpmpaym_dbt  pmpaym, dpmprop_dbt pmprop, doproper_dbt op, doprstep_dbt st" + "\n" +
          " where pmpaym.t_CloseDate between " + GetSQLDate(dt_start) + " and " + GetSQLDate(dt_end)  + "\n" +
          "   and pmpaym.t_dockind in (16, 201, 320, 322)" + "\n" +
          "   and op.t_documentid = lpad(pmpaym.t_paymentid, 34, '0')" + "\n" +
          "   and op.t_dockind = pmpaym.t_dockind" + "\n" +
          "   and op.t_id_operation = st.t_id_operation" + "\n" +
          "   and st.t_blockid = 10000145" + "\n" +
          "   and st.t_number_step = 190" + "\n" +
          "   and st.t_isexecute = 'X'" + "\n" +
//          "   and pmpaym.t_paymentid = 74501808" + "\n" +
          "   and pmpaym.t_paymentid = pmprop.t_paymentid" + "\n" +
          "   and pmprop.t_debetcredit = 1" + "\n" +
// KS 31.10.2012 KS start ®¯à ¢«î ¤«ï ‚“‡ 
/*
          "   and pmprop.t_corschem not in" + "\n" +
          "       (select t_corschem" + "\n" +
          "          from usr_me_time_paym_dbt" + "\n" + "\n" +
          "         where t_timebegin_out_our = t_timeend_out_our)" + "\n" +
*/
          "   and pmprop.t_corschem in" + "\n" +
          "       (select c.t_number" + "\n" +
          "          from dcorschem_dbt c" + "\n" +
          "         where c.t_fiid = 0" + "\n" +
          "           and (exists (select 1 from usr_me_time_paym_dbt where t_corschem = 0) or" + "\n" +
          "                c.t_number in (select t_corschem" + "\n" +
          "                                        from usr_me_time_paym_dbt" + "\n" +
          "                                       where t_timebegin_out_our != t_timeend_out_our" + "\n" +
          "                                         and t_corschem != 0))" + "\n" +
          "           and c.t_number not in" + "\n" +
          "               (select t_corschem" + "\n" +
          "                  from usr_me_time_paym_dbt" + "\n" +
          "                 where t_timebegin_out_our = t_timeend_out_our))" + "\n" +
// KS 31.10.2012 KS end
          "   and pmprop.t_payfiid = 0";

  r = rsdrecordset (query);

  while (r.movenext())

    closetime = null;
    cmd = rsdcommand("insert into USR_PMPAYM_STATUS_TMP values (?,?,?)"); // ç¨áâª  ¢á¯®¬®£ â¥«ì­®© â ¡«¨æë
    cmd.addparam("",RSDBP_IN,int(r.value(0)));
    cmd.addparam("",RSDBP_IN,int(GetPaymentStatus(int(r.value(0)),closetime)));
    cmd.addparam("",RSDBP_IN,closetime);
    cmd.execute();

    cnt_all = cnt_all + 1;
    UseProgress( cnt_all );

  end;

  RemProgress();

  InitProgress( cnt_all, "†¤¨â¥", "‚ë¢®¤ ®âç¥â " ); // ‚ë¢®¤

  cnt_all = 0;

  query = "select pmpaym.t_paymentid, pmpaym.t_CloseDate, pmrmprop.t_number, pmpaym.t_numberpack," + "\n" +
          "       pmprop.t_bankcode, pmpaym.t_payeraccount, pmpaym.t_receiveraccount, pmpaym.t_amount," + "\n" +
          "       stat.t_paymstatus, nvl(to_char(stat.t_closetime,'DD.MM.YYYY HH24:MI:SS'),' ') t_closetime" + "\n" +
          "  from dpmpaym_dbt  pmpaym, dpmrmprop_dbt pmrmprop, dpmprop_dbt pmprop, USR_PMPAYM_STATUS_TMP stat" + "\n" +
          " where pmpaym.t_paymentid = stat.t_paymentid" + "\n" +
          "   and pmpaym.t_paymentid = pmrmprop.t_paymentid" + "\n" +
          "   and pmpaym.t_paymentid = pmprop.t_paymentid" + "\n" +
          "   and pmprop.t_debetcredit = 1" + "\n" +
          " order by decode(stat.t_paymstatus,32000,32000,0), stat.t_closetime, pmprop.t_bankcode," + "\n" +
          "          pmpaym.t_CloseDate, lpad(pmrmprop.t_number,20,'0'), pmpaym.t_amount";

  r = rsdrecordset (query);

 [¬ áá®¢ë© ®âç¥â ¯® áâ â¨áâ¨ª¥ ¯à®å®¦¤¥­¨ï ­ ç «ì­ëå ¯« â¥¦¥© §  ¯¥à¨®¤ c ########## ¯® ##########
  ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
  ³„ â  § ªàëâ¨ï³   ®¬¥à   ³®¬¥à ¯ çª¨³   ˆŠ   ³  ‘ç¥â ¯« â¥«ìé¨ª   ³  ‘ç¥â ¯®«ãç â¥«ï   ³     ‘ã¬¬      ³‘â âãá ¤®ªã¬¥­â ³„ â /¢à¥¬ï § ªàëâ¨ï³
  ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´]
 (date(dt_start), date(dt_end));

  // ­ ¡¨à ¥¬ â¥ªáâ ¯¨áì¬ 
  while (r.movenext())

    statusid = r.value(8);
    if (statusid < 0)
      status = "è¨¡ª !!!"; // ¥®¡å®¤¨¬® ¯®¯à®¡®¢ âì ¢ë¯ãáâ¨âì ¥¤¨­¨ç­ë© ®âç¥â
    elif (statusid == 32000)
      status = "‡ ªàëâ";
      cnt_cls = cnt_cls + 1;
      sum_cls = sum_cls + money(r.value(7));
    else
      status = "¥ § ªàëâ";
    end;

    cnt_all = cnt_all + 1;
    sum_all = sum_all + money(r.value(7));
    UseProgress( cnt_all );

 [³#############³###########³###########³#########³####################³####################³###############³################³###################³]
   (date(r.value(1)):r,
    r.value(2):r,
    r.value(3):r,
    r.value(4):r,
    r.value(5):r,
    r.value(6):r,
    money(r.value(7)):r,
    status,
    ternary( statusid == 32000, r.value(9), " "):r
   );
  end;

 [ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
  ³ˆâ®£®        ³           ³           ³         ³                    ³                    ³               ³                ³                   ³
  ³        ¢á¥£®³###########³           ³         ³                    ³                    ³###############³                ³                   ³
  ³     § ªàëâëå³###########³           ³         ³                    ³                    ³###############³                ³                   ³
  ³   ­¥§ ªàëâëå³###########³           ³         ³                    ³                    ³###############³                ³                   ³
  ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
 ](cnt_all, money(sum_all),
   cnt_cls, money(sum_cls),
   cnt_all-cnt_cls, money(sum_all-sum_cls));

  RemProgress();

  //SetOutput(null,true);
  //ViewFile(nameout);

  return 0;

OnError
  return -1;
end;

private var dateBegin = {CurDate}, dateEnd = {CurDate};
if (‚¢¥áâ¨¥à¨®¤„ â (dateBegin, dateEnd, "âç¥â ¯® áâ â¨áâ¨ª¥ ¯à®å®¦¤¥­¨ï ¯« â¥¦¥©"))
    getMassRepLife (dateBegin, dateEnd);
end;
