// -------------------------------------------------------------------------------------------------
// @filename: xr_note.mac v.1
// @author  : 2013-05-01 zip_z. 
// @desc    : ТК Life - примечания
// @changes : none
// -------------------------------------------------------------------------------------------------
import bankinter;
import xr_core;

macro usr_set_note (p_objecttype      :integer // тип объекта
                   ,p_objectid        :string  // идентификатор объекта
                   ,p_notekind        :integer // вид примечания
                   ,p_notevalue       :variant // значение примечания
                   ):TXReturnValueStruct
    
    var p_uniid = makeFastUniId (p_objecttype, p_objectid);
    var stat    = (EXIT_SUCCESS == AddNoteForObject (p_objecttype, p_uniid, p_notekind, p_notevalue, {curdate}));
    
    return iif (stat, TXReturnValueStruct (p_objectid, EXIT_SUCCESS      , EMPTY_STRING ),
                      TXReturnValueStruct (p_objectid, EXIT_LOGICAL_ERROR, getErrMsg ()));
end;

macro usr_del_note (p_objecttype      :integer // тип объекта
                   ,p_objectid        :string  // идентификатор объекта
                   ,p_notekind        :integer // вид примечания
                   ):TXReturnValueStruct
                   
    var p_uniid = makeFastUniId (p_objecttype, p_objectid);
    var stat    = (EXIT_SUCCESS == RemoveNoteForObject (p_objecttype, p_uniid, p_notekind));
    
    return iif (stat, TXReturnValueStruct (p_objectid, EXIT_SUCCESS      , EMPTY_STRING ),
                      TXReturnValueStruct (p_objectid, EXIT_LOGICAL_ERROR, getErrMsg ()));
end;