/* ──────────────────────────────────────────────────────────────────────────┐
   RS-Bank V6                                                 R-Style Softlab
   Файл подсистемы "Регламентированная отчетность"

   Форма 134. Доступ к операциям формы.

   CREATED : 17.07.12 Ser.
└────────────────────────────────────────────────────────────────────────── */
/**
 *  Общебанковские интеры и модули
 */

/**
 *  Интеры и модели подсистемы
 */
import f134import;

/**
 *  Запуск операции расчета отчета
 */
macro executeCalculationOperation()
    var profiler = TSQLProfiler(getTxtFileName("!F134CalculateProfile"));
//    profiler.clear();
//    profiler.on();
    
    objectFactoryInstance.createReportCalculateController().calculate();
    objectFactoryInstance.createNormalizationController().normalize();
end;

/**
 *  Запуск операции окончательного расчета отчета
 */
macro executeFinalCalculationOperation()
    var profiler = TSQLProfiler(getTxtFileName("!F134FinalCalculateProfile"));
    profiler.clear();
    profiler.on();

    objectFactoryInstance.createReportFinalCalculateController().calculate();
    objectFactoryInstance.createNormalizationController().normalize();
end;

/**
 *  Запуск операции окончательного расчета отчета
 */
macro defineUserAttribute()
    objectFactoryInstance.createReport().defineUserInput();  
    RcbApplication.TransactionManager.commit();
end;

/**
 *  Запуск операции печати отчета
 */
macro executePrintOperation()
    objectFactoryInstance.createReportPrintController().print();
    RcbApplication.TransactionManager.rollBack();
end;

/**
 *  Пересчет после свода
 */

macro executeReclaculateValuesOperation()
    msgBox("Еще не реализовано!");
end;

/**
 *  Запуск операции экспорта в Kliko.exe
 */
macro executeKlikoExportOperation()
    objectFactoryInstance.createKlikoExportController().execute();
    RcbApplication.TransactionManager.rollBack();
end;

/**
 *  Запуск операции экспорта в ПТК ПСД
 */
macro executePtkPsdExportOperation()
    objectFactoryInstance.createPtkPsdExportController().execute();
    RcbApplication.TransactionManager.rollBack();
end;

установитьФлагВозврата(OK_MACRO_FLAG);
exit(1);
