/* ──────────────────────────────────────────────────────────────────────────┐
   RS-Bank V6                                                 R-Style Softlab
   Файл подсистемы "Регламентированная отчетность"

   Форма 134. Представление протокола расчета.

   CREATED : 17.07.12 Ser.
└────────────────────────────────────────────────────────────────────────── */
class (RcbDataProtocolView) F134CbDocumentProtocolData()
    initRcbDataProtocolView("CbDocument", false);

    macro printBottom()
        m_table.printBottom();
    end;

    macro printSeparator()
        m_table.printSeparator();
    end;

    macro printHead(attribute : RcbAttributeBase, description : String)
        printLn("\nДанные ГК. Переменная " + attribute.getId() + ternary(description == null, "", ". " + description) + ".");
        m_table.printHead();
    end;

    macro printString(dataSet : Object)
        m_table.printStringTransferByWord(dataSet.debetaccount,
                                          dataSet.creditaccount,
                                          dataSet.sum);
    end;

    macro printItog(dataSet : Object)
        const VALUE_COLUMN_NUMBER = 3;
        m_table.printStringExt("Итого:", 
                                VALUE_COLUMN_NUMBER - 1, 
                                dataSet.sum);
    end;

    private macro initialize()
        m_table.addColumn("Счет дебета",    25);
        m_table.addColumn("Счет кредита",   25);
        m_table.addColumn("Сумма|в|рублях", 17);
    end;
end;

class (RcbDataProtocolView) F134CbAccountProtocolData()
    initRcbDataProtocolView("CbAccount", false);

    macro printBottom()
        m_table.printBottom();
    end;

    macro printSeparator()
        m_table.printSeparator();
    end;

    macro printHead(attribute : RcbAttributeBase, description : String)
        printLn("\nДанные ГК. Переменная " + attribute.getId() + ternary(description == null, "", ". " + description) + ".");
        m_table.printHead();
    end;

    macro printString(dataSet : Object)
        m_table.printStringTransferByWord(dataSet.account,
                                          dataSet.rest);
    end;

    macro printItog(dataSet : Object)
        const VALUE_COLUMN_NUMBER = 2;
        m_table.printStringExt("Итого:", 
                                VALUE_COLUMN_NUMBER - 1, 
                                dataSet.rest);
    end;

    private macro initialize()
        m_table.addColumn("Лицевой счет",    25);
        m_table.addColumn("Сумма|в|рублях", 17);
    end;
end;

class (RcbCalculateProtocolView)   F134CalculateProtocolView(protocolName : String)
    initRcbCalculateProtocolView(null, protocolName);

    private macro initialize()
        m_dataProtocolViewPull.push_back(F134CbDocumentProtocolData());
        m_dataProtocolViewPull.push_back(F134CbAccountProtocolData());
    end;
end;