/*ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒø
  RS-Bank V6                                                  R-Style Softlab
  î†©´ ØÆ§·®·‚•¨Î "ê•£´†¨•≠‚®‡„•¨†Ô Æ‚Á•‚≠Æ·‚Ï"

  è•Á†‚Ï Ø‡®´Æ¶•≠®Ô 8. É´†¢† 3.

  ëÆß§†≠: 23.05.2005
¿ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒ*/
import pr_prl8;

class (RRG_PRL8_Report) RRG_PRL8_Report3()

    private var I99998 ;
    private var I99999 ;


    macro ProcessBalance( Balance : RRG_PRL8_Balance, Parm : RRG_PRL8_Parm, level2Itog , level1Itog , partitionItog  )

        if   ( Balance.Balance() == "99998" )
            I99998.AddB(Balance);
        elif ( Balance.Balance() == "99999" )
            I99999.AddB(Balance);
        else
        end;
        ProcessBalance( Balance, Parm, level2Itog, level1Itog, partitionItog );

    end;

    macro PrintItogActive( Parm : RRG_PRL8_Parm, Itog  )

        [#]( RRG_PRL8_MakeStringInExcel( " à‚Æ£Æ ØÆ †™‚®¢„:" ) );
        PrintStringInExcel("", "", "",                                                                               
                                                Pr( Itog.Sums()[RRG_IS], Parm ),
                                                Pr( Itog.Sums()[RRG_DR], Parm ),
                                                Pr( Itog.Sums()[RRG_DV], Parm ),
                                                Pr( Itog.Sums()[RRG_DS], Parm ),
                                                Pr( Itog.Sums()[RRG_CR], Parm ),
                                                Pr( Itog.Sums()[RRG_CV], Parm ),
                                                Pr( Itog.Sums()[RRG_CS], Parm ),
                                                Pr( Itog.Sums()[RRG_OS], Parm ));
/*
        [#]( RRG_PRL8_MakeString( " 99998 " ) );
        m_tableReport.PrintStringTransferByWord("", "", "",                                                                               
                                                Pr( I99998.Sums()[RRG_IS], Parm ),
                                                Pr( I99998.Sums()[RRG_DR], Parm ),
                                                Pr( I99998.Sums()[RRG_DV], Parm ),
                                                Pr( I99998.Sums()[RRG_DS], Parm ),
                                                Pr( I99998.Sums()[RRG_CR], Parm ),
                                                Pr( I99998.Sums()[RRG_CV], Parm ),
                                                Pr( I99998.Sums()[RRG_CS], Parm ),
                                                Pr( I99998.Sums()[RRG_OS], Parm ));*/
        PrintSeparator();        
    end;

    macro PrintItogPassive( Parm : RRG_PRL8_Parm, Itog  )

        [#]( RRG_PRL8_MakeStringInExcel( " à‚Æ£Æ ØÆ Ø†··®¢„:" ) );
        PrintStringInExcel("", "", "",                                                                               
                                                Pr( Itog.Sums()[RRG_IS], Parm ),
                                                Pr( Itog.Sums()[RRG_DR], Parm ),
                                                Pr( Itog.Sums()[RRG_DV], Parm ),
                                                Pr( Itog.Sums()[RRG_DS], Parm ),
                                                Pr( Itog.Sums()[RRG_CR], Parm ),
                                                Pr( Itog.Sums()[RRG_CV], Parm ),
                                                Pr( Itog.Sums()[RRG_CS], Parm ),
                                                Pr( Itog.Sums()[RRG_OS], Parm ));
/*
        [#]( RRG_PRL8_MakeString( " 99999 " ) );
        m_tableReport.PrintStringTransferByWord("", "", "",                                                                               
                                                Pr( I99999.Sums()[RRG_IS], Parm ),
                                                Pr( I99999.Sums()[RRG_DR], Parm ),
                                                Pr( I99999.Sums()[RRG_DV], Parm ),
                                                Pr( I99999.Sums()[RRG_DS], Parm ),
                                                Pr( I99999.Sums()[RRG_CR], Parm ),
                                                Pr( I99999.Sums()[RRG_CV], Parm ),
                                                Pr( I99999.Sums()[RRG_CS], Parm ),
                                                Pr( I99999.Sums()[RRG_OS], Parm ));*/
        PrintSeparator();        
    end;

    InitRRG_PRL8_Report();

    I99998 = createItog();
    I99999 = createItog();
end;

class (RRG_PRL8_Report_Spod) RRG_PRL8_Report3Spod()

    private var I99998 ;
    private var I99999 ;

    macro ProcessBalance( Balance : RRG_PRL8_Balance, Parm : RRG_PRL8_Parm, level2Itog , level1Itog , partitionItog  )

        if   ( Balance.Balance() == "99998" )
            I99998.AddB(Balance);
        elif ( Balance.Balance() == "99999" )
            I99999.AddB(Balance);
        end;
        ProcessBalance( Balance, Parm, level2Itog, level1Itog, partitionItog );

    end;

    macro PrintItogActive( Parm : RRG_PRL8_Parm, Itog  )

        [#]( RRG_PRL8_MakeStringInExcel( " à‚Æ£Æ ØÆ †™‚®¢„:" ) );
        PrintStringInExcel("", "", "",                                                                               
                                                Pr( Itog.Sums()[RRG_IS], Parm ),
                                                Pr( Itog.Sums()[RRG_DR], Parm ),
                                                Pr( Itog.Sums()[RRG_DV], Parm ),
                                                Pr( Itog.Sums()[RRG_DS], Parm ),
                                                Pr( Itog.Sums()[RRG_CR], Parm ),
                                                Pr( Itog.Sums()[RRG_CV], Parm ),
                                                Pr( Itog.Sums()[RRG_CS], Parm ),
                                                Pr( Itog.Sums()[RRG_OS], Parm ));
/*
        [#]( RRG_PRL8_MakeString( " 99998 " ) );
        m_tableReport.PrintStringTransferByWord("", "", "",                                                                               
                                                Pr( I99998.Sums()[RRG_IS], Parm ),
                                                Pr( I99998.Sums()[RRG_DR], Parm ),
                                                Pr( I99998.Sums()[RRG_DV], Parm ),
                                                Pr( I99998.Sums()[RRG_DS], Parm ),
                                                Pr( I99998.Sums()[RRG_CR], Parm ),
                                                Pr( I99998.Sums()[RRG_CV], Parm ),
                                                Pr( I99998.Sums()[RRG_CS], Parm ),
                                                Pr( I99998.Sums()[RRG_OS], Parm ));*/

        printSpod(RRG_PRL8_Parm, Itog);
        
        PrintSeparator();        
    end;

    macro PrintItogPassive( Parm : RRG_PRL8_Parm, Itog  )

        [#]( RRG_PRL8_MakeStringInExcel( " à‚Æ£Æ ØÆ Ø†··®¢„:" ) );
        PrintStringInExcel("", "", "",
                                                Pr( Itog.Sums()[RRG_IS], Parm ),
                                                Pr( Itog.Sums()[RRG_DR], Parm ),
                                                Pr( Itog.Sums()[RRG_DV], Parm ),
                                                Pr( Itog.Sums()[RRG_DS], Parm ),
                                                Pr( Itog.Sums()[RRG_CR], Parm ),
                                                Pr( Itog.Sums()[RRG_CV], Parm ),
                                                Pr( Itog.Sums()[RRG_CS], Parm ),
                                                Pr( Itog.Sums()[RRG_OS], Parm ));
/*
        [#]( RRG_PRL8_MakeString( " 99999 " ) );
        m_tableReport.PrintStringTransferByWord("", "", "",
                                                Pr( I99999.Sums()[RRG_IS], Parm ),
                                                Pr( I99999.Sums()[RRG_DR], Parm ),
                                                Pr( I99999.Sums()[RRG_DV], Parm ),
                                                Pr( I99999.Sums()[RRG_DS], Parm ),
                                                Pr( I99999.Sums()[RRG_CR], Parm ),
                                                Pr( I99999.Sums()[RRG_CV], Parm ),
                                                Pr( I99999.Sums()[RRG_CS], Parm ),
                                                Pr( I99999.Sums()[RRG_OS], Parm ));*/
        PrintSeparator();

        printSpod(RRG_PRL8_Parm, Itog);

        PrintSeparator();        
    end;

    InitRRG_PRL8_Report();

    I99998 = createItog();
    I99999 = createItog();
end;
