/****************************************************************************************************************************
Дополнительные пользовательские функции, вынесенные из fm_scan.mac, для большего удобства сравнения последнего с дистрибутивом 
Создан 06.07.2011 в рамках перевода ПРББ на 2030. Автор Лавренов А.А.

   ChangeLog:

 //RR 17.01.2012 Дополнительная проверка для устранения проблемы I-00312666-3, для этого была добавлена функция CheckUnclarifiedAmount
 //Chesnokov D.S. 03.02.2014 Адаптация под 31 патч
 //RR 29.10.2014 Адаптирую CheckUnclarifiedAmount, забыли убрать arhdoc
*****************************************************************************************************************************/
import rsbdataset;

MACRO GetChapter(acc)
  var balacc, chapter;

  if(strbrk(acc, "ОВП") > 0)
     return 1;
  else
     balacc = int(SUBSTR (acc, 1, 5));
  end;

  IF ((balacc >= 98000) AND (balacc <= 98090))
      chapter = 5;
  ELIF ((balacc >= 93001) AND (balacc <= 97001))
      chapter = 4;
  ELIF (   ((balacc >= 90601) AND (balacc <= 91904))
        OR (balacc == 99999) OR (balacc == 99998))
      chapter = 3;
  ELIF ((balacc >= 80101) AND (balacc <= 85501))
      chapter = 2;
  ELSE
     chapter = 1;
  END;

 return chapter;
END;

MACRO AccountExists(acc)
  var rs, str;
  str = "SELECT t_account " +
        "  FROM daccount_dbt " +
        " WHERE t_account = '"+acc+"' " + 
        " and t_chapter = "+ getchapter(acc);

  rs = trsbdataset(str);
  if(rs and rs.movenext)
     return true;
  else
     return false;
  end;
END;

MACRO IsCorrAccount(acc)
  var rs, str;
  str = "SELECT t_type_account " +
        "  FROM daccount_dbt " +
        " WHERE t_account = '"+acc+"' " + 
        " and t_chapter = "+ getchapter(acc);

  rs = trsbdataset(str);
  if(rs and rs.movenext)
     if (index(rs.t_type_account,"К")> 0)
        return true;
     else
        return false;
     end;
  else
     return false;
  end;
END;

macro USR_GetPartyReg(ptid, ListKind_Ref, DocKindID)
var rs, str;
str = "SELECT objrgdoc.*, " +
      "       (SELECT partcode.t_code " +
      "        FROM dpartcode_dbt partcode " +
      "        WHERE partcode.t_codekind = objalreg.t_codekind " +
      "              AND partcode.t_partyid = objrgdoc.t_objectid) t_code " +
      "FROM dobjrgdoc_dbt objrgdoc, dobjalreg_dbt objalreg " +
      "WHERE     objrgdoc.t_objecttype = 3 " +
      "      AND objrgdoc.t_objectid = " + ptid +
      "      AND objrgdoc.t_regpartykind =  " + ListKind_Ref +
      "      AND objrgdoc.t_regdockind = " + DocKindID +
      "      AND objrgdoc.t_isclosed = CHR (0) " +
      "      AND objrgdoc.t_docdate = " +
      "            (SELECT MAX (t.t_docdate) " +
      "             FROM dobjrgdoc_dbt t " +
      "             WHERE     t.t_objecttype = 3 " +
      "                   AND t.t_objectid = " + ptid +
      "                   AND t.t_regpartykind = " + ListKind_Ref +
      "                   AND t.t_regdockind = " + DocKindID +
      "                   AND t.t_isclosed = CHR (0)) " +
      "      AND objalreg.t_objecttype = objrgdoc.t_objecttype " +
      "      AND objalreg.t_regpartykind = objrgdoc.t_regpartykind " +
      "      AND objalreg.t_regdockind = objrgdoc.t_regdockind " +
      "      AND objalreg.t_partyid = 0 " +
      "      AND ROWNUM = 1 ";
  rs = trsbdataset(str);
 
  return rs;
END;

MACRO GetPartyByAccount(acc)
  var rs, str;
  str = "SELECT t_client " +
        "  FROM daccount_dbt " +
        " WHERE t_account = '"+acc+"' " + 
        " and t_chapter = "+ getchapter(acc);

  rs = trsbdataset(str);
  if(rs and rs.movenext)
     return rs.client;
  else
     return -1;
  end;
END;

MACRO GetPartyType(ptid)
  var rs, str;
  str = "SELECT pt.t_legalform, ps.t_isemployer " +
        "  FROM dparty_dbt pt, dpersn_dbt ps " +
        " WHERE pt.t_partyid = " + ptid + 
        "   AND ps.t_personid(+) = pt.t_partyid " ;

  rs = trsbdataset(str);
  if(rs and rs.movenext)
     if(rs.legalform == 1)
        return "Ю";
     else
        if(rs.t_isemployer == "X")
           return "П";
        else
           return "Ф";
        end;
     end;
  else
     return "Н";
  end;
END;

MACRO GetDocNumber(paymid)
 var rs, str;
 str = "SELECT t_number " +
       "  FROM dpmrmprop_dbt " +
       " WHERE t_paymentid = "+paymid ;
 rs = trsbdataset(str);
 if(rs and rs.movenext)
    return rs.number;
 else
    return "";
 end;
END;

MACRO GetDocDate(paymid)
 var rs, str;
 str = "SELECT t_date " +
       "  FROM dpmrmprop_dbt " +
       " WHERE t_paymentid = "+paymid ;
 rs = trsbdataset(str);
 if(rs and rs.movenext)
    return rs.date;
 else
    return "";
 end;
END;

MACRO GetPartyNameByDoc(paymid, ispayer)
 var rs, str;
 str = "SELECT t_payername, t_receivername " +
       "  FROM dpmrmprop_dbt " +
       " WHERE t_paymentid = "+paymid ;
 rs = trsbdataset(str);
 if(rs and rs.movenext)
    if(ispayer)
       return rs.payername;
    else
       return rs.receivername;
    end;
 else
    return "";
 end;
END;
//ВЕЛОСИПЕДЫ! в каждом макросе фм своя процедура нахождения имени LAO
MACRO USR_GetPartyName(partyid)
 var rs, str;
 str = "SELECT t_name " +
       "  FROM dparty_dbt " +
       " WHERE t_partyid = "+partyid;

 rs = trsbdataset(str);
 if(rs and rs.movenext)
    return rs.name;
 else
    return "";
 end;
END;

MACRO GetRegion(ptid, adrtype)
  var rs, str;
  var region="", province="";
  str = "SELECT t_coderegion, t_region, t_codeprovince, t_province " +
        "  FROM dadress_dbt " +
        " WHERE t_partyid = "+ ptid +
        "   AND t_type = "+ adrtype ;
  rs = trsbdataset(str);
  if(rs and rs.movenext)
     if((valtype(rs.t_coderegion) != 0) and (strlen(trim(rs.t_coderegion)) > 0))
        region = rs.t_coderegion;
     end;
     if((valtype(rs.t_region) != 0) and (strlen(trim(rs.t_region)) > 0))
        region = region +" "+ rs.t_region;
     else
        region = "";
     end;

     if((valtype(rs.t_codeprovince) != 0) and (strlen(trim(rs.t_codeprovince)) > 0))
        province = rs.t_codeprovince;
     end;
     if((valtype(rs.t_province) != 0) and (strlen(trim(rs.t_province)) > 0))
        province = province +" "+ rs.t_province;
     else
        province = "";
     end;

     if((strlen(region)>0) and (strlen(province)>0))
        return trim(trim(region) +", "+trim(province));
     elif(strlen(region)>0)
        return trim(region);
     elif(strlen(province)>0)
        return trim(province);
     end;
  end;
  return "";
END;

MACRO GetCity(ptid, adrtype)
  var rs, str;
  var DISTRICT="", PLACE="";
  str = "SELECT T_CODEDISTRICT, T_DISTRICT, T_CODEPLACE, T_PLACE " +
        "  FROM dadress_dbt " +
        " WHERE t_partyid = "+ ptid +
        "   AND t_type = "+ adrtype ;
  rs = trsbdataset(str);
  if(rs and rs.movenext)
     if((valtype(rs.T_CODEDISTRICT) != 0) and (strlen(trim(rs.T_CODEDISTRICT)) > 0))
        DISTRICT = rs.T_CODEDISTRICT;
     end;
     if((valtype(rs.T_DISTRICT) != 0) and (strlen(trim(rs.T_DISTRICT)) > 0))
        DISTRICT = DISTRICT +" "+ rs.T_DISTRICT;
     else
        DISTRICT = "";
     end;

     if((valtype(rs.T_CODEPLACE) != 0) and (strlen(trim(rs.T_CODEPLACE)) > 0))
        PLACE = rs.T_CODEPLACE;
     end;
     if((valtype(rs.T_PLACE) != 0) and (strlen(trim(rs.T_PLACE)) > 0))
        PLACE = PLACE +" "+ rs.T_PLACE;
     else
        PLACE = "";
     end;

     if((strlen(DISTRICT)>0) and (strlen(PLACE)>0))
        return trim(trim(DISTRICT) +", "+trim(PLACE));
     elif(strlen(DISTRICT)>0)
        return trim(DISTRICT);
     elif(strlen(PLACE)>0)
        return trim(PLACE);
     end;
  end;
  return "";
END;

MACRO CheckUnclarifiedAmount(PID)
 var rs, str, cmd;
 str = " SELECT   A.T_ACCOUNT_RECEIVER " +
       "   FROM   dpmpaym_dbt p, dpmdocs_dbt d, dacctrn_dbt a " +
       "  WHERE       p.T_PAYMENTID = ? " +
                " AND D.T_PAYMENTID = p.T_PAYMENTID " +
                " AND A.T_ACCTRNID = D.T_ACCTRNID " +
                " AND INSTR (A.T_ACCOUNT_PAYER, '47416') != 0" ;
 cmd = RsdCommand(str);
 cmd.addParam( "", RSDBP_IN, PID );
 rs  = RsdRecordSet(cmd);
 if (rs and rs.movenext())
   return rs.value(0);
 end;
END;
