/****************************************************************************/
/*                     R-Style SoftLab, RS-Bank V6                          */
/****************************************************************************/
/*                  Подсистема "Межбанковские расчеты"                      */
/*          Работа с пользовательской таблицей dbsgvbranch_dbt              */
/*                                                                          */
/*  Имя файла: bsgvbranch.mac                                               */
/*  Создан:   19.12.08                                      Лавренов А.А.   */
/****************************************************************************/

/*Для запсука из модуля использовать fm_terr_imp.mac */

//RR 26.2013 Ввиду отключения RSAPP2 убрана константа
 import rsbdataset, bankinter, compare, globals, календарь, rsexts, ptinter;

 

 record dlg1 (chk_ter, "fm_ter.lbr") dialog;

 var outfile, ecode;// = "..\\txtfile\\terr"+strsubst(string(date()),".","")+{oper}+".txt";

 array kinddoc;
 kinddoc(0)= "Начальные";
 kinddoc(1)= "Ответные";
 kinddoc(2)= "Внутренние";
 var start_date, end_date, doc_kind, prizn;
 var count = 0;

macro STR_LPad (st, len, c, td)
private var n;
  if (Valtype(td) == V_Undef)
     td = FALSE;
  end;
  n = StrLen(st);
  while (n < len)
     st = c + st;
     n = StrLen(st);
  end;
  if(td and (n > len))
    st = SubStr(st, n - len + 1)
  end;
  return st;
end;


 MACRO ШАПКА(startdate, enddate, dockind)
  var str1, str2;
  str1 = substr(strlwr(dockind),1,strlen(dockind)-1)+"х";
  if(startdate==enddate)
     str2 = "за "+ startdate +" г.";
  elif(startdate==date("00.00.0000"))
     str2 =  "за период 00.00.0000 - "+ enddate +" г.";
  else
     str2 =  "за период "+ startdate +" - "+ enddate +" г.";
  end;


  [                                   Список ########### документов, совпадающих с перечнем экстремистов и лиц причастных к терроризму    #

  --------------T-------------T---------T--------------T------------------T--------------------------------------------------------------------------------T-------T-------------------------T---------┐
  │ Код клиента │ Код клиента │  № Док. │     Дата     │      Сумма       │                             Стоп фраза                                         │  Коэф.│   Имя поля документа    │   Вид   │
  │ плательщика │ получателя  │         │              │                  │                                                                                │       │                         │документа│
](str1:c, str2);

 END;

/* MACRO СписокТеррористов(stopfrase)
  var rs, str, itogstring;
  str = "SELECT t.* " +
        "  FROM dstopfrase_dbt sf, dterrinfo_dbt t " +
        " WHERE t.t_terroristid = sf.t_terroristid " +
        "   AND t.t_number = 1 " +
        "   AND sf.t_stopfrase = '"+stopfrase+"' " ;
 [+-------------+-------------+---------+--------------+------------------+--------------------------------------------------------------------------------+-------+-------------------------+---------+];
//   msgbox(str);
   rs = trsbdataset(str);
   while(rs and rs.movenext)
      itogstring = rs.T_NAME;
      if(strlen(rs.T_ADDRESS)>0)    
         itogstring = itogstring + " Адрес: "+ rs.T_ADDRESS;
      end;
      if(strlen(rs.T_NAMEDOCUM)>0)    
         itogstring = itogstring + " Документ: "+ rs.T_NAMEDOCUM;
      end;
      if(strlen(rs.T_PAPERSERIES)>0)    
         itogstring = itogstring + " Серия: "+ rs.T_PAPERSERIES;
      end;
      if(strlen(rs.T_PAPERNUMBER)>0)    
         itogstring = itogstring + " Номер: "+ rs.T_PAPERNUMBER;
      end;
      if(strlen(rs.T_OKPO)>0)    
         itogstring = itogstring + " ОКПО: "+ rs.T_OKPO;
      end;
      if(strlen(rs.T_REGNUMBER)>0)    
         itogstring = itogstring + " Рег. номег: "+ rs.T_REGNUMBER;
      end;
      if(strlen(rs.T_BIRTHPLACE)>0)    
         itogstring = itogstring + " Место рождения: "+ rs.T_BIRTHPLACE;
      end;

      [│             │             │         │              │                  │################################################################################│       │                         │         │]
      (itogstring:w);
   end;
 END;
*/
 MACRO СписокТеррористов(stopfrase)
  var rs, str, itogstring;
  str = "SELECT * " +
        "  FROM dstop_dbt t " +
        " WHERE t.t_str = '"+stopfrase+"' " ;
 [+-------------+-------------+---------+--------------+------------------+--------------------------------------------------------------------------------+-------+-------------------------+---------+];
//   msgbox(str);
   rs = trsbdataset(str);
   while(rs and rs.movenext)
   if(valtype(rs.text) == 0)
      itogstring = " ";
   else
      itogstring = rs.text;
   end;


      [│             │             │         │              │                  │################################################################################│       │                         │         │]
      (itogstring:w);
   end;
 END;


MACRO ТЕЛО(startdate, enddate, codekind, Prizn)
 var rs, str, terr, rs1,sovp;
 var query, inside=""; 
 var cnt = 0;

 // EVG 31/1/2014 Переход на 2031 {SelfId} -> {OurBank}
 if (codekind == "Начальные")
   query = "  (t_dockind >322 or t_dockind < 320) and t_receiverbankid != "+ {OurBank} ;
 elif(codekind == "Ответные")
   query = " t_dockind in (320, 322) " ;
 else //Внутренние
   query = "  (t_dockind >322 or t_dockind < 320) and t_receiverbankid = "+ {OurBank} +
           " and pm.t_chapter = 1 "+
           " and (  ( instr(' 401 402 403 404 405 406 407 408 423 426 ', SubStr(pm.t_Payeraccount,1,3)) != 0) " + 
           "  or ( instr(' 30230 30231 30109 40911 47416 60312 ', SubStr(pm.t_Payeraccount,1,5)) != 0)) " +
           " and ( instr(' 40813 40814 40815 ', SubStr(pm.t_Payeraccount,1,5)) = 0) " +
           " and (  ( instr(' 401 402 403 404 405 406 407 408 423 426 ', SubStr(pm.t_receiveraccount,1,3)) != 0)  " +
           "  or ( instr(' 30230 30231 30109 40911 47422 60311 60312 ', SubStr(pm.t_receiveraccount,1,5)) != 0) ) " +
           " and ( instr(' 40813 40814 40815 ', SubStr(pm.t_receiveraccount,1,5)) = 0) ";


 end;

 str = "SELECT pm.t_valuedate, rm.t_date, pm.t_amount, rm.t_number, decode(pm.t_payer,-1,' ',pm.t_payer) t_payer, " +
       "       rm.t_payername, decode(pm.t_receiver,-1,' ',pm.t_receiver) t_receiver, rm.t_receivername, rm.t_ground, " +
       "       pm.t_paymentid, pm.t_dockind, pm.t_paymentid " +
       "  FROM dpmpaym_dbt pm, dpmrmprop_dbt rm " +
       " WHERE " + query +
       "   AND rm.t_paymentid = pm.t_paymentid " +
       "   AND pm.t_valuedate BETWEEN TO_DATE ('"+startdate+"', 'dd.mm.yyyy') " +
       "                          AND TO_DATE ('"+enddate+"', 'dd.mm.yyyy') " ;
if(prizn == "Да")

 str = str + "AND not EXISTS ( " +
       "          SELECT * " +
       "            FROM dnotetext_dbt t " +
       "           WHERE t.t_notekind = 999 " +
       "             AND t.t_objecttype = 501 " +
       "             AND t.t_documentid =lpad('pm.t_paymentid',10,0)) " ;

end;

/* terr = "SELECT DISTINCT t_stopfrase, t_factor " +
        "           FROM dstopfrase_dbt; " ;*/

 terr = "SELECT DISTINCT t_str t_stopfrase, t_factor  " +
        "                  FROM dstop_dbt " +
        "                  where length (t_str) > 0 " +
        "                    and t_terror != 0 " +
        "                    and t_number != 0 " ;





//  msgbox(str);
 rs = trsbdataset(str);
 initprogress(-1, "Обработка документов","Обработка документов");
 while (rs and rs.movenext)
    rs1 = trsbdataset(terr);
    while (rs1 and rs1.movenext)
        if(codekind != "Внутренние")
           if(strlen(rs.payername) > 0)
              sovp = similarity( strlen(rs1.stopfrase), StrUpr(rs.payername), StrUpr(rs1.stopfrase));
              if(sovp > rs1.factor)
                 [+-------------+-------------+---------+--------------+------------------+--------------------------------------------------------------------------------+-------+-------------------------+---------+
                  │#############│#############│#########│##############│##################│################################################################################│#######│                         │  #####  │]
                 ( получитькодсубъекта(int(rs.t_payer),1), получитькодсубъекта(int(rs.t_receiver),1), rs.t_number, substr(string(rs.t_date),1,10), rs.t_amount, rs1.stopfrase, sovp, rs.dockind:c );

                 СписокТеррористов(rs1.stopfrase);

                 [+-------------+-------------+---------+--------------+------------------+--------------------------------------------------------------------------------+-------+-------------------------+---------+
                  │             │             │         │              │                  │################################################################################│       │ ####################### │         │]
                 (rs.t_payername:w, "Плательщик");

                 count = count + 1;
                 if(prizn== "Да")
                    addNoteForObject (501, str_lpad(rs.paymentid, 10, "0"), 999, "X");
                 end;
              end;
           end;

           if(strlen(rs.receivername) > 0)
              sovp = similarity( strlen(rs1.stopfrase), StrUpr(rs.receivername), StrUpr(rs1.stopfrase));
              if(sovp > rs1.factor)
                 [+-------------+-------------+---------+--------------+------------------+--------------------------------------------------------------------------------+-------+-------------------------+---------+
                  │#############│#############│#########│##############│##################│################################################################################│#######│                         │  #####  │]
                 ( получитькодсубъекта(int(rs.t_payer),1), получитькодсубъекта(int(rs.t_receiver),1), rs.t_number, substr(string(rs.t_date),1,10), rs.t_amount, rs1.stopfrase, sovp, rs.dockind:c );

                 СписокТеррористов(rs1.stopfrase);
        
                 [+-------------+-------------+---------+--------------+------------------+--------------------------------------------------------------------------------+-------+-------------------------+---------+
                  │             │             │         │              │                  │################################################################################│       │ ####################### │         │]
                 (rs.t_receivername:w, "Получатель");

                 count = count + 1;
                 if(prizn== "Да")
                    addNoteForObject (501, str_lpad(rs.paymentid, 10, "0"), 999, "X");
                 end;
              end;
           end;
        end;
        if(strlen(rs.ground) > 0)
           sovp = similarity( strlen(rs1.stopfrase), StrUpr(rs.ground), StrUpr(rs1.stopfrase));
           if(sovp > rs1.factor)
              [+-------------+-------------+---------+--------------+------------------+--------------------------------------------------------------------------------+-------+-------------------------+---------+
               │#############│#############│#########│##############│##################│################################################################################│#######│                         │  #####  │]
              ( получитькодсубъекта(int(rs.t_payer),1), получитькодсубъекта(int(rs.t_receiver),1), rs.t_number, substr(string(rs.t_date),1,10), rs.t_amount, rs1.stopfrase, sovp, rs.dockind:c );

              СписокТеррористов(rs1.stopfrase);

              [+-------------+-------------+---------+--------------+------------------+--------------------------------------------------------------------------------+-------+-------------------------+---------+
               │             │             │         │              │                  │################################################################################│       │ ####################### │         │]
              (rs.t_ground:w, "Основание");

              count = count + 1;
              if(prizn== "Да")
                 addNoteForObject (501, str_lpad(rs.paymentid, 10, "0"), 999, "X");
              end;
           end;
        end;

    end;
    useprogress(cnt);
    cnt = cnt+1;
 end;
 remprogress;
END;


MACRO ТАПКИ()
[+-------------+-------------+---------+--------------+------------------+--------------------------------------------------------------------------------+-------+-------------------------+---------+  
 │ ИТОГО       │  ####################   записей отобрано                                                                                                                                             │ 
 L-------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+]
 (count);

END;

//Обработчик для панели
 macro fm_ter_dlg (dlg, cmd, id, key)
   var choice;
   if ( cmd == DLG_INIT )
      dlg.startdate = {curdate};
      dlg.enddate   = {curdate};
      dlg.dockind   = "Начальные";
      dlg.prizn     = "Нет";
      message("Esc Выход F3 Список Пробел Переключение F2(F9) Запуск ");
      UpdateFields(dlg);
   elif ( cmd == DLG_REMFOCUS ) 
      if (id==0)
         UpdateFields(dlg);
      elif (id==1)
         UpdateFields(dlg);
      end;
      return CM_IGNORE;

   elif( cmd == DLG_KEY ) //Проверки на нажатие клавиш
      if( key == 27 ) //Esc
         exit(1);
         return CM_CANCEL;
      elif ( key == 32 ) //Пробел
      if (id==3)
         if(dlg.prizn=="Да")
             dlg.prizn="Нет"
         else
             dlg.prizn="Да"
         end;
      end;
        UpdateFields(dlg);
      elif ( key == 317 ) //F3
      if (id==0)
        dlg.startdate = getdatebycalendar(dlg.startdate);
        UpdateFields(dlg);
      elif (id==1)
        dlg.enddate = getdatebycalendar(dlg.enddate);
        UpdateFields(dlg);
      elif (id==2)
        choice = menu(kinddoc,"","Вид документов");
        if(choice >=0)
        dlg.dockind = kinddoc(choice);
        end;
        UpdateFields(dlg);
      end;

         return CM_IGNORE;
      elif ( (key == 316) or (key == 323) ) //F2 F9
         
         if(dlg.startdate == "")
            start_date = "01.01.0001";
         else
            start_date = dlg.startdate;
         end; 
         if(dlg.enddate == "")
            end_date = "01.01.0001";
         else
            end_date   = dlg.enddate;
         end; 
         doc_kind   = dlg.dockind;
         prizn      = dlg.prizn;

         return CM_SAVE;
      end;
   end;
   return CM_DEFAULT;
 END;

var t1;//= time();

macro fm_run()

  outfile = GetTxtFileName ("terr"+strsubst(strsubst(string(date),".","")," ","0")+strsubst(string(time),":",""));
  
  //пересоздаем файл
  setoutput(outfile,false);
  setoutput(null,true);

  RunDialog (dlg1, @fm_ter_dlg);

//  t1= time();
  setoutput(outfile,true);
  ШАПКА(start_date, end_date, doc_kind);
  ТЕЛО(start_date, end_date, doc_kind, prizn);
  ТАПКИ();
  setoutput(null,true);
  viewfile(outfile);
end;


fm_run();

//msgbox(time - t1);

  
