/*Отчет "Матрешками", заявка I-030918
выполнила Козина */

import rsd, ActiveX, globals, Календарь;

var SQL, RS, RSD;
const KEY_F2=316;
const KEY_F3=317;
const KEY_SPACE = 32;
const KEY_ESC= 27;
const KEY_F9= 323;

var i,
    Client = "",
    LegalForm = 1,
    startperiod: date,
    endperiod  : date;

var ex, ob, obBook, obSheet;  

var Fulloutput, out, output = "Rep_Matrehy.lbr";

GetRegistryValue("BANK_INI\\ОБЩИЕ ПАРАМЕТРЫ\\ДИРЕКТОРИИ\\LBRDIR",2,out);
Fulloutput = FindPath(output, out);
  if (not Fulloutput)
    msgbox("Не найдена LBR");
    exit();
  end;


startperiod = {curdate};
endperiod = {curdate};

var dlg;
dlg = TRecHandler("MATR", fulloutput, TRUE);
//record dlg("matr", "\\\\RSAPP2\\mac.usr\\lbr\\Rep_Matrehy.lbr" ) dialog;
//Обработчик команд для диалогового окна

macro DlgHandler( dlg, cmd, id, key )

  if( Cmd == DLG_INIT ) /*Установка значения в поле*/
        dlg.rec.startdate = {CURDATE};
        dlg.rec.enddate = {CURDATE};
        dlg.rec.UL = "X";
        UpdateFields(dlg);

 elif(Cmd == DLG_KEY) 
     if (Key == KEY_F3)  /*Вызов листалки и заполнение FldShowValue и FldRealValue*/
       if (FldName(dlg,id) == "Startdate") 
         dlg.rec.startdate =  GetDateByCalendar( dlg.rec.startdate );
         elif(FldName(dlg,id) == "Enddate") 
           dlg.rec.enddate =  GetDateByCalendar( dlg.rec.enddate );
       end;
        //UpdateFields(dlg);

 elif (KEY == KEY_SPACE)
          /*Сброс установок*/
          if (FldName(dlg,id) == "UL")
            if (dlg.rec.UL == "X")
             dlg.rec.UL = "";
             dlg.rec.FL = "X";
             else
              dlg.rec.UL = "X";
              dlg.rec.FL = "";
            end; 
            UpdateFields(dlg);
          end;
    elif (KEY == KEY_ESC)
       return exit(1);//CM_CANCEL;
       
     elif ((Key == KEY_F2) or (Key == KEY_F9))
         if (dlg.rec.UL == "X")
            LegalForm = 1
            else
             LegalForm = 2; 
           end;
        Startperiod = dlg.rec.startdate;
        Endperiod = dlg.rec.enddate;
        return CM_SAVE;
     end;       
  end;
  return CM_DEFAULT;
  
end;

 RunDialog(dlg, "DlgHandler");


SQL = "begin usr_contrINN(to_date('"+startperiod +"','dd.mm.yyyy'), to_date('"+ endperiod +"','dd.mm.yyyy')); end;";
RS = RSDCommand(SQL);
RS.Execute();

SQL="SELECT distinct usr_get_inn(rm.t_payerinn), RM.T_NUMBER,   "+
" paym.t_valuedate, rm.t_payername, usr_get_inn(rm.t_payerinn), "+
" code1.t_code, paym.t_payeraccount, rm.t_receivername,         "+
" usr_get_inn(rm.t_receiverinn), code2.t_code,                  "+
" paym.t_receiveraccount, paym.t_amount, rm.t_ground            "+
"            FROM user_contrinn1_tmp t1,                        "+
"                user_contrinn1_tmp t2,                         "+
"                dpmpaym_dbt paym,                              "+
"                dpmrmprop_dbt rm,                              "+
"                dobjcode_dbt code1,                            "+
"                dobjcode_dbt code2                             "+
"          WHERE t1.t_payerinn = t2.t_receiverinn               "+
"            and t2.t_payerinn = t1.t_receiverinn               "+
"            AND t1.t_paymentid <> t2.t_paymentid               "+
"            AND paym.t_paymentid = rm.t_paymentid              "+
"            AND paym.t_chapter = 1                             "+
"            AND paym.t_valuedate >= to_date('"+ startperiod +"','dd.mm.yyyy') "+
"            AND paym.t_valuedate <= to_date('"+ endperiod   +"','dd.mm.yyyy') "+
"            AND paym.t_paymstatus = 32000                      "+
"            AND rm.t_paymentid = t1.t_paymentid                "+
"            and code1.t_objecttype = 3                         "+
"            and code2.t_objecttype = 3                         "+
"            and CODE1.T_CODEKIND = 3                           "+
"            and CODE2.T_CODEKIND = 3                           "+
"            and CODE1.T_OBJECTID = paym.t_payerbankid          "+
"            and code2.t_objectid = paym.t_receiverbankid       "+
"            and code1.t_state = 0                              "+
"            and code2.t_state = 0                              "+
"union                                                          "+
"SELECT distinct usr_get_inn(rm.t_receiverinn), RM.T_NUMBER,    "+
" paym.t_valuedate, rm.t_payername, usr_get_inn(rm.t_payerinn), "+
" code1.t_code, paym.t_payeraccount, rm.t_receivername,         "+
" usr_get_inn(rm.t_receiverinn), code2.t_code,                  "+
" paym.t_receiveraccount, paym.t_amount, rm.t_ground            "+
"            FROM user_contrinn1_tmp t1,                        "+
"                user_contrinn1_tmp t2,                         "+
"                dpmpaym_dbt paym,                              "+
"                dpmrmprop_dbt rm,                              "+
"                dobjcode_dbt code1,                            "+
"                dobjcode_dbt code2                             "+
"          WHERE t1.t_payerinn = t2.t_receiverinn               "+
"            and t2.t_payerinn = t1.t_receiverinn               "+
"            AND t1.t_paymentid <> t2.t_paymentid               "+
"            AND paym.t_paymentid = rm.t_paymentid              "+
"            AND paym.t_chapter = 1                             "+
"            AND paym.t_valuedate >= to_date('"+ startperiod +"','dd.mm.yyyy')"+
"            AND paym.t_valuedate <= to_date('"+ endperiod +"','dd.mm.yyyy')"+
"            AND paym.t_paymstatus = 32000                      "+
"            AND rm.t_paymentid = t1.t_paymentid                "+
"            and code1.t_objecttype = 3                         "+
"            and code2.t_objecttype = 3                         "+
"            and CODE1.T_CODEKIND = 3                           "+
"            and CODE2.T_CODEKIND = 3                           "+
"            and CODE1.T_OBJECTID = paym.t_payerbankid          "+
"            and code2.t_objectid = paym.t_receiverbankid       "+
"            and code1.t_state = 0                              "+
"            and code2.t_state = 0;";


RS=RSDRecordset(SQL);

        if (IsStandAlone()) // Двухзвенка
                        if ((ValType(ex)!=V_UNDEF) and (ex.Visible==False))
                        ex = ActiveX("Excel.Application",NULL,false); 
                        else
                        ex = ActiveX("Excel.Application",NULL,true);
                        end;
                        else // Трехзвенка
                        ob = CreateObject ("rsax","TRsAxServer","RsAxServer",IsStandAlone());
                        ex = ob.CreateComObject ("Excel.Application",true);
                        end; 
 // В макросе фигурирует лишь имя файла   
var Templ:string = "Матрешки.xls";

var RegParam;
// Здесь мы получаем список папок в которых может лежать файл
GetRegistryValue("BANK_INI\\ОБЩИЕ ПАРАМЕТРЫ\\ДИРЕКТОРИИ\\USERTEMPLSDIR",2,RegParam);
 
// Получаем полный путь в шаблоне
var FullTempl = FindPath(Templ, RegParam);
  if (not FullTempl)
    msgbox("Не найдена LBR");
    exit();
  end;

                   
                        obBook = ex.Workbooks.open( FullTempl ); 
                        obSheet = obBook.ActiveSheet();    

i=4;

while (RS.Movenext())

 SQL="  SELECT party.t_name  "+
  " FROM dparty_dbt party, dobjcode_dbt code "+  
  " WHERE   party.t_partyid = code.t_objectid "+
  "    AND code.t_codekind = 16 "+
    "  AND "+
     "  case when instr(code.t_code, '/') > 0 then "+
    "     substr(code.t_code, 0, instr(code.t_code, '/')-1 ) "+
    "     else code.t_code    "+
    "   end   "+
    "   = '"+RS.Value(0)+"' "+
    "  AND code.t_objecttype = 3 "+
    "  AND code.t_state = 0  "+
    "  AND party.t_legalform =1 "+
    "  AND code.t_code <> '1' ";

     RSD = RSDRecordset(SQL);

//msgbox(SQL);
    if (RSD.Movenext())
       if (Client != RSD.value(0))
           Client = RSD.value(0);
           obSheet.Range("A"+i).Value = Client;
           i = i+1;
       end;

       obSheet.Range("B"+i).Value=RS.value(1);
       obSheet.Range("C"+i).Value=RS.value(2);
       obSheet.Range("D"+i).Value=RS.value(3);
       obSheet.Range("E"+i).Value=RS.value(4);
       obSheet.Range("F"+i).Value=RS.value(5);
       obSheet.Range("G"+i).Value=RS.value(6);
       obSheet.Range("H"+i).Value=RS.value(7);
       obSheet.Range("I"+i).Value=RS.value(8);
       obSheet.Range("J"+i).Value=RS.value(9);
       obSheet.Range("K"+i).Value=RS.value(10);
       obSheet.Range("L"+i).Value=RS.value(11);
       obSheet.Range("M"+i).Value=RS.value(12);

       i=i+1;
    end;   
end;

Ex.visible = true;

exit(1);

