import CTInter, globals, RsbDataSet;

record rst(r_cmagz);
FILE party(party );              /* ‘¯à ¢®ç­¨ª áã¡ê¥ªâ®¢*/

                 /* ‡­ ç¥­¨ï ¯®«ï kind áâàãªâãàë r_cmagz */
const  DEBET  = 1,     /* ¤«ï ¤®ªã¬¥­â®¢ ¯® ¯à¨å®¤ã */
       CREDIT = 2;     /* -//-           ¯® à áå®¤ã */

var    IsValueSpelledOut = false,  /*  16.01.2001 Kasatsky  */
       CodeCurrency;
var    firstDoc = FALSE;
var    maxseg = 20;       

macro SetCodeCurrency(CodeCur)       
        CodeCurrency = CodeCur;

end;
       
macro isAgreementCurrency(iso_number : string) : bool
	if (iso_number != string(int(iso_number):o:3)) 
		return true;
	else
		return false;
	end;
end;

/*  ‘ã¬¬  ¯à®¯¨áìî    16.01.2001 Kasatsky */
macro CurValSpelledOut(sum)

   file FinInstr(fininstr);

   FinInstr.FIID = CodeCurrency;
   if ( GetEQ( FinInstr ) )
		if (isAgreementCurrency(FinInstr.iso_number))
	      return string(sum) + " (Š«¨à¨­£®¢ ï ¢ «îâ )";
		else
	      return CurToStrAlt( sum, null, null, int(FinInstr.ISO_Number));
		end;
   else
      return string(sum) + " (¥¨§¢¥áâ­ ï ¢ «îâ )";
   end;

end;

macro SetSpelledOut( SpelledOut )
        IsValueSpelledOut = SpelledOut;
end;
       
MACRO GetNameOper( )
  var T, nameOper = "";
  T = TRsbDataSet( "  SELECT t_Name FROM dperson_dbt WHERE t_Oper = " + {oper} );
  if( T.MoveNext() )
    nameOper = T.Name;
  end;
  return nameOper;
END;
 /*------------------- ¥ç âì ‡ £®«®¢ª  ®âç¥â   -----------------------*/
 macro PrintHead( b, numDprt, dB, dE )
   var Superior, pt, sep, Name, Comment;
   party.PartyID = {OurBank};
   getEQ( party );       
   Superior = readNoteForObject( OBJTYPE_PARTY, UniID( party, OBJTYPE_PARTY ), 21, dE );

   [ ÄÄÄÄÄ#ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
   ](date);
  
   if(( Superior == "") or ( ValType( Superior ) == V_UNDEF ));
   else
     sep = index( Superior, "|");
     while(sep)
        [                                                           #
        ]  (substr( Superior, 1, sep-1 ):c);
        Superior = substr( Superior, sep + 1 );
        sep = index( Superior, "|");
     end;
     [ 
       ############################################################################################ ]  ( Superior:c:w );       
   end;
   
   if (CB_GetDepartmentCodeAndName(numDprt, Name, Comment) == 0) 
    println((numDprt + " " + Comment):93:c);
   end;                                                           
 
  if ( dB == dE )                                                                          
     [      

                                        Š€‘‘Ž‚›‰ †“€‹ #
                                             #                                       ] ( b , "§  "+ string(dB) );
  else
     [

                                        Š€‘‘Ž‚›‰ †“€‹ #
                                        #                                            ] ( b,  "á "+ string(dB)+ " ¯® "+ string(dE) );
  end;
 end;

 /*------------------- ¥ç âì ˜ ¯ª¨ ®âç¥â  ----------------------------*/
 macro PrintHead1( d, v, p, gp, o, go )
    firstDoc = FALSE;
[

   ‘ç¥â   ##########################  
   ‚ «îâ  ###
] ( d, v );
   if ( go == true )
[  ®¬¥à ®¯¥à æ¨®­¨áâ   #######
] ( o );
[ ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
  ³ ®¬¥à áç¥â              ³   ®¬¥à   ³  ‘¨¬¢®«   ³       ‘ã¬¬          ³           §­ ç¥­¨¥          ³
  ³                         ³ ¤®ªã¬¥­â  ³  ®âç¥â    ³                     ³                              ³
  ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
];   return;
   elif ( gp == true )
[  ®¬¥à ¯ çª¨  #######
] ( p );
   end;
[ ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
  ³ ®¬¥à áç¥â              ³   ®¬¥à   ³  ‘¨¬¢®«   ³       ‘ã¬¬          ³ Ž¯¥à -   ³           §­ ç¥­¨¥          ³
  ³                         ³ ¤®ªã¬¥­â  ³  ®âç¥â    ³                     ³ æ¨®­¨áâ  ³                              ³
  ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
];
 end;

// ’¨å®¬¨à®¢ €.. ˆé¥¬ ®á­®¢ ­¨¥ ¯® ¤®ªã¬¥­âã
macro GetGround(ApplicationKey)
  var ground;
  var cmd, rsd;
  if (CodeCurrency == NATCUR)
    cmd = rsdcommand("select t_ground from darhdoc_dbt  where t_ApplicationKey = ?");
  else
    cmd = rsdcommand("select t_ground from darhdoc$_dbt where t_ApplicationKey = ?");
  end;
  cmd.addparam("AppKey",RSDBP_IN,ApplicationKey);
  cmd.execute();
  rsd = rsdrecordset(cmd);
  if (rsd.movenext())
    ground = rsd.value(0);
  else
    ground = "";
  end;
  return ground;
end;

/*------------------- ¥ç âì á ¬®£® ®âç¥â   -----------------------*/
 macro PrintBody( a, b, needo )
  setbuff( rst, a );
  if ( firstDoc )
    firstDoc = FALSE;
[  ];
  end;
  b = trim(b);
  if ( needo )
[  ######################### ########### ########### ##################### ########## ##############################
] ( rst.Account, rst.Numb_Document, b, rst.Sum, rst.Oper, GetGround(rst.ApplicationKey));
  else
[  ######################### ########### ########### ##################### ##############################
] ( rst.Account, rst.Numb_Document, b, rst.Sum, GetGround(rst.ApplicationKey));
  end;

 end;

/*------------------- ¥ç âì á ¬®£® ®âç¥â  II -----------------------*/

 macro PrintBody1( Symbol_Cash, Sum, kind)
  if ( firstDoc )
    firstDoc = FALSE;
[  ];
  end;
[                                           ###      #####################
] ( Symbol_Cash, Sum );
 end;

/*------------------- ¥ç âì ¨â®£®¢ ¯ çª¨  -----------------------*/
 macro PrintEndPack( n,  allsum )
 var _sum;
  if(IsValueSpelledOut) _sum = CurValSpelledOut(allsum); else _sum = allsum; end;
[
   ˆâ®£® ¯® ¯ çª¥ ####### :                          #
] ( n, _sum:l );
    firstDoc = TRUE;
 end;

/*------------------- ¥ç âì ¨â®£®¢ ¯o ®¯¥àã  -----------------------*/
 macro PrintEndOper( n,  allsum )
 var _sum;
  if(IsValueSpelledOut) _sum = CurValSpelledOut(allsum); else _sum = allsum; end;
[
   ˆâ®£® ¯® ®¯¥à æ¨®­¨áâã ####### :                  #
] ( n, _sum:l );
    firstDoc = TRUE;
 end;

/*------------------- ¥ç âì ¨â®£®¢ ®âç¥â   -----------------------*/
 macro PrintEnd( allsum )
 var _sum;
  if(IsValueSpelledOut) _sum = CurValSpelledOut(allsum); else _sum = allsum; end;
[

                              ˆâ®£®:                 # ] ( _sum:l );
[

   ###############################  ###############################
   ###############################  ###############################  
   
   Š áá¨à                           ###############################]({Name_Boss}, {FIO_Boss},{Name_Book}, {FIO_Book}, GetNameOper);

 end;



 /*========== Ž¡é¨© ¦ãà­ « ¯® ¯à¨å®¤ã ¨ à áå®¤ã ===========*/

 /*------------------- ¥ç âì ‡ £®«®¢ª  ®âç¥â   -----------------------*/
 macro PrintHeadA( b, numDprt, dB, dE )
   var Superior, pt, sep, Name, Comment;
   party.PartyID = {OurBank};
   getEQ( party );
   Superior = readNoteForObject( OBJTYPE_PARTY, UniID( party, OBJTYPE_PARTY ), 21, dE );
   
   [ ÄÄÄÄÄ#ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
   ](date);

   if(( Superior == "") or ( ValType( Superior ) == V_UNDEF ));
   else
     sep = index( Superior, "|");
     while(sep)
        [                                                           #
        ]  (substr( Superior, 1, sep-1 ):c);
        Superior = substr( Superior, sep + 1 );
        sep = index( Superior, "|");
     end;                                                                                               
     [ 
       ################################################################################################################## ]  ( Superior:c:w );   
   end;

   if (CB_GetDepartmentCodeAndName(numDprt, Name, Comment) == 0) 
    println((numDprt + " " + Comment):115:c);
   end;
 
  if ( dB == dE )
     [        

                                                        Š€‘‘Ž‚›‰ †“€‹ #
                                                         #                                         ] ( b , "§  "+ string(dB) );
  else
     [

                                                        Š€‘‘Ž‚›‰ †“€‹ #
                                                  #                                                ] ( b,  "á "+ string(dB)+ " ¯® "+ string(dE) );
  end;

 end;

 /*------------------- ¥ç âì ˜ ¯ª¨ ®âç¥â  ----------------------------*/
 macro PrintHeadA1( d, v, p, gp, o, go )
    firstDoc = FALSE;
[

   ‘ç¥â   ##########################  
   ‚ «îâ  ###
] ( d, v );
   if ( go == true )
[  ®¬¥à ®¯¥à æ¨®­¨áâ   #######
] ( o );
[ ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
  ³ ®¬¥à áç¥â              ³   ®¬¥à   ³  ‘¨¬¢®«   ³       à¨å®¤        ³        áå®¤        ³           §­ ç¥­¨¥          ³
  ³                         ³ ¤®ªã¬¥­â  ³  ®âç¥â    ³                     ³                     ³                              ³
  ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
];   return;
   elif ( gp == true )
[  ®¬¥à ¯ çª¨  #######
] ( p );
   end;
[ ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
  ³ ®¬¥à áç¥â              ³   ®¬¥à   ³  ‘¨¬¢®«   ³       à¨å®¤        ³        áå®¤        ³ Ž¯¥à -  ³           §­ ç¥­¨¥          ³
  ³                         ³ ¤®ªã¬¥­â  ³  ®âç¥â    ³                     ³                     ³ æ¨®­¨áâ ³                              ³
  ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
];
 end;

/*------------------- ¥ç âì á ¬®£® ®âç¥â   -----------------------*/
 macro PrintBodyA( a, b, needo )
  setbuff( rst, a );

  if ( firstDoc )
    firstDoc = FALSE;
[  ];
  end;
  b = trim(b);
  if ( needo )
    if( rst.kind == CREDIT )
[  ######################### ########### ###########                       ##################### ######### ##############################
] ( rst.Account, rst.Numb_Document, b, rst.Sum, rst.Oper, GetGround(rst.ApplicationKey));
    else
[  ######################### ########### ########### #####################                       ######### ##############################
] ( rst.Account, rst.Numb_Document, b, rst.Sum, rst.Oper), GetGround(rst.ApplicationKey));
    end;
  else
    if( rst.kind == CREDIT )
[  ######################### ########### ###########                       ##################### ##############################
] ( rst.Account, rst.Numb_Document, b, rst.Sum, GetGround(rst.ApplicationKey));
    else
[  ######################### ########### ########### ##################### ##############################
] ( rst.Account, rst.Numb_Document, b, rst.Sum, GetGround(rst.ApplicationKey));
    end;
  end;
 end;

/*------------------- ¥ç âì á ¬®£® ®âç¥â  II -----------------------*/

 macro PrintBodyA1( Symbol_Cash, Sum, kind )
  if ( firstDoc )
    firstDoc = FALSE;
[  ];
  end;
  if( kind == CREDIT )
[                                           ###                            #####################
] ( Symbol_Cash, Sum );
  else
[                                           ###      #####################
] ( Symbol_Cash, Sum );
  end;
 end;

/*------------------- ¥ç âì ¨â®£®¢ ¯ çª¨  -----------------------*/
 macro PrintEndPackA( n, SumIn, SumOut)
 var _sumIn,_sumOut,i;
 array aSumIn,aSumOut;
  if(IsValueSpelledOut) 
   _sumIn = CurValSpelledOut(SumIn); 
   _sumOut = CurValSpelledOut(SumOut); 
   
   StrSplit(_sumIn,aSumIn,21, 21, maxseg);
   StrSplit(_sumOut,aSumOut,21, 21, maxseg);
/*   if(asize(aSumIn)>asize(aSumOut)) maxseg = asize(aSumIn); else maxseg = asize(aSumIn); end;*/
[
   ˆâ®£® ¯® ¯ çª¥  ####### :                         ##################### #####################] ( n, aSumIn[0], aSumOut[0] );
   i = 1;
   while((i<maxseg) and ((aSumIn[i]!="") or (aSumOut[i]!="") ) )
[                                                    ##################### #####################](aSumIn[i], aSumOut[i]);
    i = i+1;
   end;
  else 
[
   ˆâ®£® ¯® ¯ çª¥  ####### :                         ##################### #####################
] ( n, SumIn, SumOut );
  end;

    firstDoc = TRUE;
 end;

/*------------------- ¥ç âì ¨â®£®¢ ¯® ®¯¥àã  -----------------------*/
 macro PrintEndOperA( n, SumIn, SumOut)
 var _sumIn,_sumOut,i;
 array aSumIn,aSumOut;
  if(IsValueSpelledOut) 
   _sumIn = CurValSpelledOut(SumIn); 
   _sumOut = CurValSpelledOut(SumOut); 
   
   StrSplit(_sumIn,aSumIn,21, 21, maxseg);
   StrSplit(_sumOut,aSumOut,21, 21, maxseg);
/*   if(asize(aSumIn)>asize(aSumOut)) maxseg = asize(aSumIn); else maxseg = asize(aSumIn); end;*/
[
   ˆâ®£® ¯® ®¯¥à æ¨®­¨áâã  ####### :                 ##################### #####################] ( n, aSumIn[0], aSumOut[0] );
   i = 1;
   while((i<maxseg) and ((aSumIn[i]!="") or (aSumOut[i]!="") ) )
[                                                    ##################### #####################](aSumIn[i], aSumOut[i]);
    i = i+1;
   end;
  else 
[
   ˆâ®£® ¯® ®¯¥à æ¨®­¨áâã  ####### :                 ##################### #####################
] ( n, SumIn, SumOut );
  end;

    firstDoc = TRUE;
 end;

/*------------------- ¥ç âì ¨â®£®¢ ®âç¥â   -----------------------*/
 macro PrintEndA( SumIn, SumOut)
 var _sumIn,_sumOut,i;
 array aSumIn,aSumOut;
  if(IsValueSpelledOut) 
   _sumIn = CurValSpelledOut(SumIn); 
   _sumOut = CurValSpelledOut(SumOut);
   StrSplit(_sumIn,aSumIn,21, 21, maxseg);
   StrSplit(_sumOut,aSumOut,21, 21, maxseg);
   if(asize(aSumIn)>asize(aSumOut)) maxseg = asize(aSumIn); else maxseg = asize(aSumIn); end;    
[

                              ˆâ®£®:                 ##################### #####################] ( aSumIn[0], aSumOut[0] );
   i = 1;
   while((i<maxseg) and ((aSumIn[i]!="") or (aSumOut[i]!="") ) )
[                                                    ##################### #####################](aSumIn[i], aSumOut[i]);
    i = i+1;
   end;
  else 
[

                              ˆâ®£®:                 ##################### #####################] ( SumIn, SumOut );
  
  end;
[

   ###############################  ###############################
   ###############################  ###############################  
   
   Š áá¨à                           ###############################]({Name_Boss}, {FIO_Boss},{Name_Book}, {FIO_Book}, GetNameOper);
 end;
