/*++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

   Жаворонкова Н.С-24098 Макрос комиссии 2.19.0 за оформление платежных поручений
                         
   
   Create: 11.10.2013
   
   Тип комиссии - единовременная.
   
   Changes:
   16.05.2014 R-377979 joy Перенесена на 2031 доработка: 07.04.2014 R-359119 joy Код тарифа комиссии на признаке категории сменили на 2.19.1
   

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*/


import sfinter, ptinter, cb_sql, CTInter, OprInter, lib_compare;

/*
    Если при расчете произошла ошибка, поместить в эту переменную ненулевое значение
*/
var MacroError :integer = 0;
private var FICode_calc:string = "";

  /* Тип величины
enum SfBaseTypes{*/
private const   SF_BASETYPE_SUM     = 1;      /* Сумма*/
private const   SF_BASETYPE_QUONT   = 2;      /* Количество*/

private const NATCUR = 0;
  record sfbassum( "sfbassum.str" );
  record paym(pmpaym);


/* Номер категории, которая определяет тариф для платежей */
const TarifNumber = "2.19.1";
/* ID Категории */
const GroupID = 1018;
debugbreak;

/*
    Расчет для единовременных комиссий
*/
macro CalcCommissionSum( docKind/*Тип первички*/, Doc/*Буфер первички*/, sfcalcalusr_addr/*Алгоритм расчета*/, sfcontr_addr /*Договор обслуживания*/, beginDate, endDate  )
    record sfclusr( "sfclusr.str" );
    record sfcontr( sfcontr );
    record sfcalcal(sfcalcal);
    record payord(pspayord);

    var stat:integer; 
    var CommQuont   = $0,
        Num,
        retVal,
        error;
debugbreak;
    SetBuff( sfcalcal, sfcalcalusr_addr );
    SetBuff( sfcontr, sfcontr_addr );
    SetBuff( payord, Doc );

    Num = "";

    ClearRecord(paym);
    paym.PaymentID = payord.orderid;                    

    GetMainObjAttr (retVal, OBJTYPE_PAYMENT, UniID(paym, OBJTYPE_PAYMENT), GroupID, null, null, Num);
    
    debugbreak; 
       // Комиссия по платежным поручениям ручного ввода
    if ((docKind == PS_PAYORDER) and (Num == TarifNumber) and stringEqMask (payord.payeraccount, "405*,406*,407*,40802*,40807*,40821*" ) and (payord.origin == 1)  )
        CommQuont = 1;
    end;
    
    
        ClearRecord(sfbassum);

    sfbassum.baseType   = SF_BASETYPE_QUONT;
    sfbassum.baseQuont  = CommQuont;

    sfbassum.baseType2  = SF_BASETYPE_QUONT;
    sfbassum.baseQuont  = CommQuont;

    stat = InsertSumList(sfbassum);

    if( stat )
      MsgBox("Ошибка при вставке базовой суммы: ", GetErrMsg );
    end;

    
    
    /*return integer( 1 ); -- количество*/
    
    /*return $1; -- сумма */
    
end;/*CalcCommissionSum*/


