/*++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

   Жаворонкова Н.С-24098 Макрос комиссии 2.19.2 за оформление платежных поручений
                         в случае получения письма со счетом на оплату
                         
   
   Create: 10.12.2013
   
   Тип комиссии - периодическая.

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*/


import sfinter, ptinter, cb_sql;
import CommissLib;

/*
    Если при расчете произошла ошибка, поместить в эту переменную ненулевое значение
*/
var MacroError :integer = 0;
private var FICode_calc:string = "";

  /* Тип величины
enum SfBaseTypes{*/
private const   SF_BASETYPE_SUM     = 1;      /* Сумма*/
private const   SF_BASETYPE_QUONT   = 2;      /* Количество*/

private const NATCUR = 0;
  record sfbassum( "sfbassum.str" );
  record paym(pmpaym);


/* ID Категории "Вид тарифа комиссии за перевод средств" */
const GroupID = 1021;

/* Номер категории, которая определяет тариф для платежей */
const TarifCatNumber = 1;
debugbreak;

/* Происхождение платежа - КлиентБанк*/
const DocOrigin = 2;

const ForInvoiceIBank = true;

/*
    Расчет для периодических комиссий
*/

/*
    Расчет для периодических комиссий
*/
/* EVG Добавил приём структуры sfcontr для вызова из макроса sfacrpay.mac */
macro CalcServiceSum( sfcontr_addr/*Договор обслуживания*/, BeginDate/*Начало периода*/, EndDate/*Конец периода*/,
      sfcalcal_addr /* EVG Адрес алгоритма (sfcalcal) */, sfcontrStruc /*Cтруктура sfcontr*/, CommNumber_sfacrpay )

    record sfcontr( sfcontr );
    record calcal (sfcalcal);

    var query, rs, stat, cmd, PackValue;
    var TarifValue = 0, MinValue = 0, MaxValue = 0, TarifType = 0, OneOpCommSum = $0;
    var CommNumber, CommSum = $0, CommQuont = 0;


    debugbreak;
    /* EVG При вызове из sfacrpay.mac используем полученную структуру sfcontrStruc вместо адреса sfcontr_addr */
    if ( ValType (sfcontr_addr) != V_UNDEF )
       SetBuff( sfcontr, sfcontr_addr );
       SetBuff( calcal, sfcalcal_addr );

       CommNumber = calcal.CommNumber;               // CommNumber берём из алгоритма
    else
       Copy ( sfcontr, sfcontrStruc );
       CommNumber = CommNumber_sfacrpay;             // CommNumber берём тот, который пришёл из sfacrpay.mac
    end;

    /*  Для комиссии  заменяем функцию поиска информации по тарифу на GetTarifInfo3EbeneTarifbildung() (3-уровневая тарификация) */
    ReplaceMacro( "GetTarifInfo", "GetTarifInfo3EbeneTarifbildung" );

    /* Сформируем массив платежей, превышающих лимит */
    var PaymentsOverLimit = CollectPaymentsInformation( sfcontr, BeginDate, EndDate, CommNumber, @TarifValue, @MinValue, @MaxValue, @TarifType, @PackValue, ForInvoiceIBank, GroupID, DocOrigin );

    var n = 0;
    while( n < PaymentsOverLimit.Size )

        if( valtype(PaymentsOverLimit(n)) != V_UNDEF )  // На всякий случай

        // Тариф = Сумма
            if ( ( TarifType == 1 ) or ( TarifType == 3 ) )        

                CommSum = CommSum + TarifValue;

                // Тариф = Процент
            elif ( TarifType == 2 )        

                OneOpCommSum = PaymentsOverLimit(n).Amount * TarifValue / 100;

                if   ( (MinValue > $0) and (OneOpCommSum < MinValue) )
                    OneOpCommSum = MinValue;
                elif ( (MaxValue > $0) and (OneOpCommSum > MaxValue) )
                    OneOpCommSum = MaxValue;
                end;
                   
                CommSum = CommSum + OneOpCommSum;

            end;

        end;
    n = n + 1;

    end;

   /*14.06.2013 joy R-203308-2 Отменяем замену */
    ReplaceMacro( "GetTarifInfo");
    

    /* EVG При вызове из sfacrpay.mac возвращаем true в случае положительного результата расчёта */
    if ( ValType (sfcontrStruc) != V_UNDEF )
       if (CommQuont > 0)
          return true;
       end;
       return false;
    end;

    
    ClearRecord(sfbassum);

    sfbassum.baseType    = SF_BASETYPE_SUM;
    sfbassum.baseQuont   = CommQuont;
    sfbassum.baseSum     = CommSum;

    sfbassum.baseType2   = SF_BASETYPE_SUM;
    sfbassum.baseQuont2  = CommQuont;
    sfbassum.baseSum2    = CommSum;

    stat = InsertSumList(sfbassum);

    if( stat )
      MsgBox("Ошибка при вставке базовой суммы");
    end;

    
end;/*CalcServiceSum*/



