/*+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

   ████████   ████████
   ███   ███  ███   ███
   ███  ████  ███  ████
   ███████    ███████
   ███  ███   ███  ███
   ███   ███  ███   ███

   RR Рахмедов Р.С.

   Имя файла: com557p.mac

   Создан:    24.06.2015

   Описание:  Макрос расчета комиссии за использование услуги Экспресс-инкассация
              
   ChangeLog:
-----------------------------------------------------------------------------------------------------------------------------------------------------
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*/

import sfinter, cb_sql, rsd;

  /* Тип величины
enum SfBaseTypes{*/
private const   SF_BASETYPE_SUM     = 1;      /* Сумма*/
private const   SF_BASETYPE_QUONT   = 2;      /* Количество*/

private const NATCUR = 0;
record sfbassum( "sfbassum.str" );
record sfcontr( sfcontr );

/* EVG Добавил приём структуры sfcontr для вызова из макроса sfacrpay.mac */
 MACRO CalcServiceSum( sfcontr_addr, BeginDate, EndDate, sAddr, sfcontrStruc, _ComNumber)
  debugbreak;
  var stat, cmd, rs;
  var CommSum = 0;

   if ( ValType (sfcontr_addr) != V_UNDEF )
      SetBuff( sfcontr, sfcontr_addr );
   else
      Copy ( sfcontr, sfcontrStruc );
   end;
   
   cmd = RSDCommand(" SELECT   SUM (p.t_amount) SUM, COUNT (1) COUNT " +
                    "   FROM   dpmpaym_dbt p, daccount_dbt acc " +
                    "  WHERE   p.t_valuedate = :1 " +
                    "    AND REGEXP_LIKE (p.t_payeraccount, '^20208810.08') " +
                    "    AND REGEXP_LIKE (p.t_receiveraccount, '^(40[5-7]|4080[2\\7])') " +
                    "    AND P.T_PAYMSTATUS = 32000 " +
                    "    AND ACC.T_ACCOUNT = P.T_RECEIVERACCOUNT " +
                    "    AND ACC.T_CHAPTER = 1 " +
                    "    AND INSTR (ACC.T_USERTYPEACCOUNT, 'D') = 0 " +
                    "    AND SUBSTR (ACC.T_ACCOUNT, 11, 1) != 9 " +
                    "    AND SUBSTR (ACC.T_ACCOUNT, 12, 1) != 9 " +
                    "    AND P.T_RECEIVERACCOUNT = :2 ");
   cmd.AddParam("1", RSDBP_IN,EndDate);
   cmd.AddParam("2", RSDBP_IN,sfcontr.object);
   
   rs = RSDRecordSet(cmd);
   rs.movenext();
   CommSum = rs.value("SUM");
   
   if ( ValType (sfcontrStruc) != V_UNDEF )
      if (CommSum > 0)
         return true;
      end;
      return false;
   end;
    
   ClearRecord(sfbassum);

   sfbassum.baseType = SF_BASETYPE_SUM;
   sfbassum.baseSum  = CommSum;

   sfbassum.baseType2 = SF_BASETYPE_SUM;
   sfbassum.baseSum2  = CommSum;

   stat = InsertSumList(sfbassum);

   if( stat )
     MsgBox("Ошибка при вставке базовой суммы");
   end;
      

 END;/*CalcServiceSum*/