/*++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

   joy Банк ЭВ

       Макрос пользовательского алгоритма расчёта базовых сумм комиссий 5.2.9pack
       "Выдача наличных с оформлением заявки в течение предыдущего опер. дня:
         - прочее (при общей сумме снятия наличных на прочие цели свыше 5 млн.руб
            за текущий календарный месяц)

       Тип комиссии - единовременная.
       
        За основу взят макрос exv_com528pack_e.mac


++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*/

import sfinter, ptinter, cb_sql;/*InsertSumList*/
import exvComLib;

/*
    Если при расчете произошла ошибка, поместить в эту переменную ненулевое значение
*/
var MacroError :integer = 0;
private var FICode_calc:string = "";

  /* Тип величины
enum SfBaseTypes{*/
private const   SF_BASETYPE_SUM     = 1;      /* Сумма*/
private const   SF_BASETYPE_QUONT   = 2;      /* Количество*/

record sfbassum( "sfbassum.str" );

/* Символ кассы, по которому берётся данная комиссия */
CONST CommCashSymbol = "('42', '46', '47', '53', '54', '58', '59', '60', '61')";    // прочие и т.п.

/*
    Расчет для единовременных комиссий
*/
macro CalcCommissionSum( docKind/*Тип первички*/, Doc/*Буфер первички*/, sfcalcalusr_addr/*Алгоритм расчета*/, sfcontr_addr /*Договор обслуживания*/, beginDate, endDate  )
    record sfclusr( "sfclusr.str" );
    record sfcontr( sfcontr );
    record sfcalcal(sfcalcal);
    record cashDoc(pscshdoc);

    var stat:integer; 
    var query, rs;
    var CommSum   = $0,
        SymbSum   = $0,
        SumOfBases = $0,
        TotalCashSum = $0,
        UsedPack = $0;
    var TarifValue = 0, MinValue = 0, MaxValue = 0, TarifType = 0;
    var Min = $5000000.01;

        
    SetBuff( sfcalcal, sfcalcalusr_addr );
    SetBuff( sfcontr, sfcontr_addr );
    SetBuff( cashDoc, Doc );





    debugbreak;
    // Комиссия по чекам
    if ( docKind == CASH_PS_OUTORDER )
     debugbreak;
            /*Получаем глобальные параметры и разрушаем все, так как это последняя комиссия в серии комиссий 5.2.* */
        SymbSum      = GetGlobalParameter("SymbSumPackGlob"+ string (cashDoc.AutoKey), true);
        TotalCashSum = GetGlobalParameter("TotalCashSumPackGlob"+ string (cashDoc.AutoKey), true);
        SumOfBases   = GetGlobalParameter("SumOfBasesPackGlob"+ string (cashDoc.AutoKey), true); 
        UsedPack     = GetGlobalParameter ("UsedPackGlob" + string (cashDoc.AutoKey), true);
        

        if( GetTarifInfo( sfcontr, EndDate, EndDate, 3, sfcalcal.CommNumber, @TarifValue, @MinValue, @MaxValue, @TarifType ) )
            if (TotalCashSum == 0)
                if (SymbSum > Min)
                    CommSum = SymbSum - SumOfBases;
                else
                    CommSum = 0;
                end;
            else
                if (TotalCashSum > Min)
                    CommSum = SymbSum;
                else
                    if ((SymbSum - SumOfBases) > 0)
                        CommSum = SymbSum - SumOfBases;
                    else  
                        CommSum = 0;
                    end;
                end;
            end;
        end;
        
        var PackRest = MaxValue - SumOfBases - UsedPack; // Определяем остаток пакета БЕЗ УЧЕТА текущей базы комиссии
        If (PackRest > 0)
            If (CommSum <= PackRest)
                CommSum = 0;
            else 
                CommSum = CommSum - PackRest;
            end;
        end;

    end;
    
    if (( CommSum < $0 ) or (CommSum > SymbSum) ) // На всякий случай
        CommSum = $0;
    end;
    
    CommSum = CommSum * TarifValue / 100;

    ClearRecord(sfbassum);

    sfbassum.baseType  = SF_BASETYPE_SUM;
    sfbassum.baseSum   = CommSum;

    sfbassum.baseType2  = SF_BASETYPE_SUM;
    sfbassum.baseSum2   = CommSum;

    stat = InsertSumList(sfbassum);

    if( stat )
      MsgBox("Ошибка при вставке базовой суммы: ", GetErrMsg );
    end;

    
    
    /*return integer( 1 ); -- количество*/
    
    /*return $1; -- сумма */
    
end;/*CalcCommissionSum*/



