/*    Макрос процедуры отключения комиссий одного вида от всех договоров и подключения обратно только по тем, по которым
      алгоритм расчета базовых величин вернет, что комиссия должна взиматься
   Автор: Финогенов Иван
   Дата создания: 03.08.2010*/
/* пока только для комиссий вида 3.4.7 и 3.4.8*/
import cb_sql, oralib;
import bankinter;
private const Com347 = 1017, 
              Com348 = 1018,
              Com371 = 1074,
              Cat348 = 5; /*3.4.8 (i)*/
private var Comiss,FeeType, sql, sqlfull, rs, cmd, BeginDate, EndDate;




private macro Main() 
   private array a;
   private var sel, AddTable;


   a[0] = "3.4.7";
   a[1] = "3.4.8";
   a[2] = "3.7.1";

   sel = Menu(a, "Выберите вид комиссии");
   if (sel == 0)
     Comiss = Com347;
     FeeType= 1;
   elif (sel == 1)
     Comiss = Com348;
     FeeType= 1;
   elif (sel == 2)
     Comiss = Com371;
     FeeType= 1;
   end;

   /* EVG 13/06/2012 Добавил */
   var {CurDate};
   EndDate = {CurDate};
   /* EVG 13/06/2012 end */

   GetDate(EndDate, "Введите дату окончания периода, |за который начисляется комиссия");
   BeginDate = EndDate;
   
   
   // 2012-09-10 zip_z.I-00249064-2  добавлена журнализация >
  if (not WriteFiscLog (OLSTRPROC, "ЗАПУСК ПРОЦЕДУРЫ ОТКЛЮЧЕНИЯ КОМИССИЙ ОТ ДОГОВОРОВ ОБСЛУЖИВАНИЯ\n" + 
                                   "Дата начала    : " + BeginDate + "\n"
                                   "Дата завершения: " + EndDate + "\n"
                                   "Комиссия: " + a[sel] + "\n"
                                   "Макрос: connectsfcontr2(old).mac"))
      msgbox ("Не удалось добавить запись о старте процедуры в фискальный журнал");
  end;
  // < 2012-09-10 zip_z. 

   cmd = RSDCommand("{? = call connectcomisstocontr(?,?,?,?)}");
   
   /* EVG 13/06/2012 Переменные "V_" передаются только для RSDBP_OUT / RSDBP_RETVAL 
   cmd.addparam("stat",      RSDBP_RETVAL, V_STRING );
   cmd.addparam("comiss",    RSDBP_IN,     V_integer);
   cmd.addparam("begindate", RSDBP_IN,     V_date);
   cmd.addparam("enddate",   RSDBP_IN,     V_date);
   cmd.addparam("categ",     RSDBP_IN,     V_integer);*/
   cmd.addparam("stat",      RSDBP_RETVAL, V_STRING );
   cmd.addparam("comiss",    RSDBP_IN,     comiss   );
   cmd.addparam("begindate", RSDBP_IN,     BeginDate);
   cmd.addparam("enddate",   RSDBP_IN,     EndDate  );
   cmd.addparam("categ",     RSDBP_IN,     Cat348   );

   /* EVG 13/06/2012 Так не надо
   cmd.param("comiss").value    = comiss;
   cmd.param("begindate").value = BeginDate;
   cmd.param("enddate").value   = EndDate;
   cmd.param("categ").value     = Cat348;*/

   cmd.execute();
   println(cmd.value(0));
   
  // 2012-09-10 zip_z. I-00249064-2  добавлена журнализация >
  if (not WriteFiscLog (OLFINPROC, "ОКОНЧАНИЕ ПРОЦЕДУРЫ ОТКЛЮЧЕНИЯ КОМИССИЙ ОТ ДОГОВОРОВ ОБСЛУЖИВАНИЯ\n" + 
                                   "Дата начала    : " + BeginDate + "\n"
                                   "Дата завершения: " + EndDate + "\n"
                                   "Комиссия: " + a[sel] + "\n"
                                   "Макрос: connectsfcontr2(old).mac"))
      msgbox ("Не удалось добавить запись об окончании процедуры в фискальный журнал");
  end;
  // < 2012-09-10 zip_z. 
  
onerror(x)
    println(x.module + "[" + x.line + "]:" + x.message);
    println(getRSDErrorsString(cmd));
end;
Main();
