
/*+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

   ████████   ████████
   ███   ███  ███   ███
   ███  ████  ███  ███
   ███████    ███████
   ███  ███   ███  ███
   ███   ███  ███   ███

   RR Рахмедов Р.С.

   Имя файла: Contrplan_History_Scroll.mac

   Создан:    04.03.2014

   Описание:  Пользовательский скролинг содержащий данные, об истории изменений ТП и комиссий с индивидуальными настройками.
              
   ChangeLog:
-----------------------------------------------------------------------------------------------------------------------------------------------------
   //RR 06.03.2014 Изменил формат дат в основном запросе
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*/

import ZubRunScroll, Globals;

private macro main (DateBegin, DateEnd)
    var sql = " SELECT   O.T_CODE, " +
              "          PTY.T_NAME, " +
              "          UCH.OLD_TP, " +
              "          (SELECT   T_NAME " +
              "             FROM   DSFPLAN_DBT " +
              "            WHERE   T_SFPLANID = UCH.OLD_TP) " +
              "             OLD_TP_NAME, " +
              "          UCH.CHANGE_DATE, " +
              "          UCH.NEW_TP, " +
              "          (SELECT   NVL ( (SELECT   T_NAME " +
              "                             FROM   DSFPLAN_DBT " +
              "                            WHERE   T_SFPLANID = UCH.NEW_TP), " +
              "                         'Индивидуальный') " +
              "             FROM   DUAL) " +
              "             NEW_TP_NAME, " +
              "          CM.T_CODE COMISS_CODE, " +
              "          CM.T_NAME COMISS_NAME " +
              "   FROM   USR_CONTRPLAN_HISTORY UCH, " +
              "          DSFCONTR_DBT CTR, " +
              "          DOBJCODE_DBT O, " +
              "          DPARTY_DBT PTY, " +
              "          DSFCOMISS_DBT CM " +
              "  WHERE       CTR.T_ID = UCH.SFCONTRID " +
              "          AND O.T_OBJECTID = CTR.T_PARTYID " +
              "          AND O.T_OBJECTTYPE = 3 " +
              "          AND O.T_CODEKIND = 1 " +
              "          AND O.T_STATE = 0 " +
              "          AND PTY.T_PARTYID = CTR.T_PARTYID " +
              "          AND CM.T_FEETYPE = UCH.COMISS_FEETYPE " +
              "          AND CM.T_NUMBER = UCH.COMISS_NUMBER " +
              "          AND UCH.CHANGE_DATE BETWEEN  TO_DATE ('"+DateBegin+" 00:00:00','dd.mm.yyyy hh24:mi:ss') " +
              "                                  AND  TO_DATE ('"+DateEnd+" 23:59:59','dd.mm.yyyy hh24:mi:ss') " +
              "     ORDER BY UCH.CHANGE_DATE ASC ";
             
    var scroll = ZubScroll ();

    scroll.Columns.Add ("T_CODE",      "RS-код",                      10, ZUB_SCR_COL_NONEDITABLE);
    scroll.Columns.Add ("T_NAME",      "Клиент",                      30, ZUB_SCR_COL_NONEDITABLE);
    scroll.Columns.Add ("OLD_TP",      "ID предыдущего ТП",           5,  ZUB_SCR_COL_NONEDITABLE);
    scroll.Columns.Add ("OLD_TP_NAME", "Наименование предыдущего ТП", 10, ZUB_SCR_COL_NONEDITABLE);
    scroll.Columns.Add ("CHANGE_DATE", "Дата смены ТП",               8,  ZUB_SCR_COL_NONEDITABLE);
    scroll.Columns.Add ("NEW_TP",      "ID нового ТП",                5,  ZUB_SCR_COL_NONEDITABLE);
    scroll.Columns.Add ("NEW_TP_NAME", "Наименование нового ТП",      20, ZUB_SCR_COL_NONEDITABLE);
    scroll.Columns.Add ("COMISS_CODE", "Код комиссии",                10, ZUB_SCR_COL_NONEDITABLE);
    scroll.Columns.Add ("COMISS_NAME", "Наименование комиссии",       30, ZUB_SCR_COL_NONEDITABLE);
    scroll.ScrollReadOnly = true;
    scroll.SqlText = sql;
    scroll.ScrollHead = "История изменения ТП, содержащих инд. настройки комиссий (только для чтения)";

    scroll.Scroll ();
end;

 var DateBegin = {CurDate};
 var DateEnd = {CurDate};
 
 if (   (not GetDate( DateBegin, "Пожалуйста, введите дату начала периода:" ))
     or (not GetDate( DateEnd, "Пожалуйста, введите дату  окончания периода:" )) )
    exit(1);
 end; 

main (DateBegin, DateEnd);
exit (1);