/*+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

   joy Макрос пользовательского алгоритма расчёта базовых сумм комиссии 2.2.0 для НБС
       "Единая комиссия за ведение счетов клиентов".
       
       Макрос создан на основе com220p.mac (ПРББ), однако в НБС комиссия не списывается, если есть только эти условия:
       - ограничения по счету,
       - арест,
       - наличие к2.
      Макрос работает в паре с пакетом USR_COMISS_NBS_220. В принципе, макрос готов для использования в массовом подключении\отключении
      комиссий, если такое появится в НБС.
      
       Тип комиссии - периодическая.
       
   ChangeLog:
   
   
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*/

import sfinter, ctinter, currinter, fiinter, cb_sql, rsd, Commisslib;

var CommmNumber = 1002;

  /* Тип величины
enum SfBaseTypes{*/
private const   SF_BASETYPE_SUM     = 1;      /* Сумма*/
private const   SF_BASETYPE_QUONT   = 2;      /* Количество*/

private const NATCUR = 0;
record sfbassum( "sfbassum.str" );
record sfcontr( sfcontr );

/* EVG Добавил приём структуры sfcontr для вызова из макроса sfacrpay.mac */
macro CalcServiceSum( sfcontr_addr/*Договор обслуживания*/, BeginDate/*Начало периода*/, EndDate/*Конец периода*/,
      sAddr /* EVG Какой-то ещё адрес */, sfcontrStruc /*Cтруктура sfcontr*/, _ComNumber /*FIV ID комиссии из sfacrpay*/ )
      
    var stat, cmd, rs;
    var CommQuont = 1;

    /* При вызове из sfacrpay.mac используем полученную структуру sfcontrStruc вместо адреса sfcontr_addr */
    if ( ValType (sfcontr_addr) != V_UNDEF )
       SetBuff( sfcontr, sfcontr_addr );
    else
       Copy ( sfcontr, sfcontrStruc );
    end;
  


    debugbreak;
    cmd = RSDCommand ("  SELECT   UAC220.RET_VALUE "+
                      "    FROM   usr_account_collection_220 uac220 "+
                      "   WHERE       UAC220.ACCOUNT = :1 "+
                      "     AND UAC220.PARTYID = :2 "+
                      "     AND UAC220.SFCONTRID = :3 "+
                      "     AND UAC220.DATEPERIODBEGIN = :4 "+
                      "     AND UAC220.DATEPERIODEND = :5 "+
                      "     AND UAC220.ID != 0 ");
    cmd.AddParam("1", RSDBP_IN, sfcontr.object);
    cmd.AddParam("2", RSDBP_IN, sfcontr.partyid);
    cmd.AddParam("3", RSDBP_IN, sfcontr.id);
    cmd.AddParam("4", RSDBP_IN, BeginDate);
    cmd.AddParam("5", RSDBP_IN, EndDate);
    rs = RSDRecordSet(cmd);
    if (rs and rs.movenext())
      if(rs.value(0) == 0)
        CommQuont = 0;
      end;
    else
        cmd = RSDCommand( " SELECT (USR_COMISS_NBS_220.CommissionCalculation ( account          => :1, "+
                          "                                                     partyid          => :2, "+
                          "                                                     sfcontrid        => :3, "+
                          "                                                     contrplan        => :4, "+
                          "                                                     date_reg_contr   => :5, "+
                          "                                                     begin_date       => :6, "+
                          "                                                     end_date         => :7)) "+
                          "  FROM   DUAL; ");
                  
        cmd.AddParam("1", RSDBP_IN, sfcontr.object);
        cmd.AddParam("2", RSDBP_IN, sfcontr.partyid);
        cmd.AddParam("3", RSDBP_IN, sfcontr.id);
        cmd.AddParam("4", RSDBP_IN, -1);
        cmd.AddParam("5", RSDBP_IN, sfcontr.datebegin);
        cmd.AddParam("6", RSDBP_IN, BeginDate);
        cmd.AddParam("7", RSDBP_IN, EndDate);
        rs = RSDRecordSet(cmd);
        rs.movenext();
        if (rs.value(0) == 0)
          CommQuont = 0;
        end;
    end;
    
    
    ClearRecord(sfbassum);

    sfbassum.baseType = SF_BASETYPE_QUONT;
    sfbassum.baseQuont  = CommQuont;

    sfbassum.baseType2 = SF_BASETYPE_QUONT;
    sfbassum.baseQuont2  = CommQuont;

    stat = InsertSumList(sfbassum);

    if( stat )
      MsgBox("Ошибка при вставке базовой суммы");
    end;

    
end;/*CalcServiceSum*/
