/*FIV  
 ®âç¥â ¯® á¯¨áªã ®âªàëâëå âà¥¡®¢ ­¨© ­  ®¯« âã ¢ ¬®¤ã«¥ "Š îà¨¤¨ç¥áª¨å «¨æ"
 10.11.2009*/

import  rsd, cb_sql, or_rep_h;

private macro   StartReport()
var sql, sql1, rsd, i = 0, stat = false, count= 0; 
var Rep ;
var Header=
"ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄ¿\n"+
"³     ®¬¥à ’      ³ „¥¡¥â áç¥â  ¯« â¥«ìé¨ª  ³Šà¥¤¨â áç¥â  ¯®«ãç â¥«ï ³ ¨¬¥­®¢ ­¨¥ ª«¨¥­â ³„®ªã¬¥­â                    ³ id ¤®ªã¬¥­â         ³˜ £ ®¡à ¡®âª¨ ³„ â  ¯à®¢®¤ª¨³ ‘ã¬¬  ¯à®¢®¤ª¨³®¬¥à ¯ã­ªâ  â à¨ä ³  §¢ ­¨¥ ª®¬¨áá¨¨³Š2 ³\n"+
"ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄ´";
   
    Rep = CMakeReport(Header);
SQL = "   SELECT   inv.t_docnumber numberto, ";
SQL = SQL + "           inv.t_payeraccount payeraccount, ";
SQL = SQL + "           inv.t_beneaccount beneaccount, ";
SQL = SQL + "           inv.t_payername payername, ";
SQL = SQL + "           okd.t_name docname, ";
SQL = SQL + "           pm.t_paymentid docid, ";
SQL = SQL + "           inv.t_totalamount amount, ";
SQL = SQL + "           pm.t_valuedate enddate, ";
SQL = SQL + "           com.t_code comcode, ";
SQL = SQL + "           com.t_name comname, ";
SQL = SQL + "           oks.t_name step, ";
SQL = SQL + "           (CASE WHEN oks.t_name LIKE '%ª àâ®â¥ª%ü2%' THEN 'X' ELSE ' ' END) k2 ";
SQL = SQL + "    FROM   dsfinv_dbt inv, ";
SQL = SQL + "           doprdocs_dbt od, ";
SQL = SQL + "           doproper_dbt oo, ";
SQL = SQL + "           doprstep_dbt ops, ";
SQL = SQL + "           doproper_dbt ook, ";
SQL = SQL + "           dsfdefcom_dbt dc, ";
SQL = SQL + "           dsfcomiss_dbt com, ";
SQL = SQL + "           doprkdoc_dbt okd, ";
SQL = SQL + "           doprstep_dbt os, ";
SQL = SQL + "           doprostep_dbt oks, ";
SQL = SQL + "           dpmpaym_dbt pm ";
SQL = SQL + "   WHERE       inv.t_invoicestatus <> 4 ";
SQL = SQL + "           AND inv.t_servicekind = 3 ";
SQL = SQL + "           AND oo.t_dockind = 59 ";
SQL = SQL + "           AND oo.t_documentid = LPAD (inv.t_invoiceid, 34, '0') ";
SQL = SQL + "           AND oo.t_id_operation = ops.t_id_operation ";
SQL = SQL + "           AND ops.t_id_step = 1 ";
SQL = SQL + "           AND oo.t_id_operation = od.t_id_operation ";
SQL = SQL + "           AND ops.t_id_step = od.t_id_step ";
SQL = SQL + "           AND od.t_dockind IN (29, 70, 201, 202, 15, 410, 420) ";
SQL = SQL + "           AND dc.t_invoiceid = inv.t_invoiceid ";
SQL = SQL + "           AND dc.t_commnumber = com.t_number ";
SQL = SQL + "           AND dc.t_feetype = com.t_feetype ";
SQL = SQL + "           AND okd.t_dockind = od.t_dockind ";
SQL = SQL + "           AND ook.t_documentid = od.t_documentid ";
SQL = SQL + "           AND ook.t_dockind = od.t_dockind ";
SQL = SQL + "           AND ook.t_id_operation = os.t_id_operation ";
SQL = SQL + "           AND oks.t_blockid = os.t_blockid ";
SQL = SQL + "           AND oks.t_number_step = os.t_number_step ";
SQL = SQL + "           AND oks.t_blockid = os.t_blockid ";
SQL = SQL + "           AND os.t_isexecute = 'R' ";
SQL = SQL + "           AND pm.t_documentid = ook.t_documentid ";
SQL = SQL + "           AND pm.t_dockind = ook.t_dockind ";
SQL = SQL + "ORDER BY   k2, pm.t_valuedate ";

sql1 = "select count(1) from ("+sql+")";
//println(sql1);
   rsd= RSdrecordset(sql1);
   rsd.MoveNext();
   count = rsd.Value(0);
//println(sql);
   rsd= RSdrecordset(sql);
   InitProgress(count);
 //  stat = rsd.MoveFirst();
   while (rsd.MoveNext())                                 
      Rep.AddPrintCell(rsd.Value("numberto"),0,0,":c",REP_ELEM_TABL);                  
      Rep.AddPrintCell(rsd.Value("payeraccount"),0,0,":c",REP_ELEM_TABL);                  
      Rep.AddPrintCell(rsd.Value("BENEACCOUNT"),0,0,":c",REP_ELEM_TABL);
      Rep.AddPrintCell(rsd.Value("PAYERNAME"),0,0,":c",REP_ELEM_TABL);
      Rep.AddPrintCell(rsd.Value("docname"),0,0,":c",REP_ELEM_TABL);
      Rep.AddPrintCell(rsd.Value("docid"),0,0,":c",REP_ELEM_TABL);
      Rep.AddPrintCell(rsd.Value("step"),0,0,":c",REP_ELEM_TABL);
      Rep.AddPrintCell(SQL_ConvTypeDate(rsd.Value("enddate")),0,0,":c",REP_ELEM_TABL);
      Rep.AddPrintCell(rsd.Value("amount"),0,0,":c",REP_ELEM_TABL);
      Rep.AddPrintCell(rsd.Value("comcode"),0,0,":c",REP_ELEM_TABL);
      Rep.AddPrintCell(rsd.Value("comname"),0,0,":c",REP_ELEM_TABL);
      Rep.AddPrintCell(rsd.Value("k2"),0,0,":c",REP_ELEM_TABL);
      Rep.AddStr();
//      stat = rsd.MoveNext();
      UseProgress(i);
      i = i + 1;    
   end;
   Remprogress(); 
   Rep.PrintWinRep();
   Rep.ShowWinRep();
//   Rep.PrintRep();   

end;
Startreport;