/*+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    ███████       █████      █████     ███
    █████████   ████████   ████████    ███
    ███   ███   ███        ███         ███
    ████████     ███████    ███████    ███
    ██████            ███        ███   ███
    ███ ████    █████████  █████████   ████████
    ███   ████    █████      █████     ████████

   R-Style Softlab
   
   RR Библиотека общих функций, используемых при расчёте комиссий в банке Солидарность
   
   ChangeLog:
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*/

import RsbDataSet;

 MACRO CheckPaymToPhis_2_10 ( PID )
  var rs,cmd;
   cmd = RSDCommand( " SELECT   NVL ( " +
                     " (SELECT   1 " +
                     "    FROM   DPMPAYM_DBT P, DPMRMPROP_DBT PR " +
                     "   WHERE   P.T_PAYMENTID = ?  " +
                     "           AND PR.T_PAYMENTID = P.T_PAYMENTID " +
                     "           AND (SUBSTR (P.T_PAYERACCOUNT, 1, 3) BETWEEN '405' AND '407' " +
                     "                OR SUBSTR (P.T_PAYERACCOUNT, 1, 5) IN " +
                     "                        ('40807', '40804', '40805', '40814', '40818') " +
                     "                OR (SUBSTR (P.T_PAYERACCOUNT, 1, 5) = '40821' " +
                     "                    AND LENGTH( (SELECT   CASE WHEN INSTR (T_PAYERINN, '/') != 0 " +
                     "                                               THEN SUBSTR (T_PAYERINN, 1,INSTR (T_PAYERINN, '/') - 1 ) " +
                     "                                          ELSE T_PAYERINN " +
                     "                                          END T_PAYERINN " +
                     "                                  FROM   dpmrmprop_dbt " +
                     "                                 WHERE   t_paymentid = P.T_PAYMENTID)) = 10)) " +
                     "          AND ( SUBSTR (P.T_RECEIVERACCOUNT, 1, 3)  IN  ('423', '426') " +
                     "           OR   SUBSTR (P.T_RECEIVERACCOUNT, 1, 5)  IN  ('40817', '40820')" +
                     "           OR ((SUBSTR (P.T_RECEIVERACCOUNT, 1, 5)  IN " +
                     "                         ('30301', '30232', '47422') " +
                     "                   AND (REGEXP_LIKE ('\\s' || LOWER (PR.T_GROUND),'(40817|40820|423|426)') " +
                     "                        OR REGEXP_LIKE ('\\s' || LOWER (PR.T_RECEIVERNAME),'(40817|40820|423|426)'))))) " +
                     "          AND NOT ( ( (SELECT   T_BANKCODE " +
                     "                         FROM   DPMPROP_DBT " +
                     "                        WHERE   T_PAYMENTID = P.T_PAYMENTID AND T_DEBETCREDIT = 0) = " +
                     "                      (SELECT   T_BANKCODE " +
                     "                         FROM   DPMPROP_DBT " +
                     "                        WHERE   T_PAYMENTID = P.T_PAYMENTID AND T_DEBETCREDIT = 1)) " +
                     "               AND REGEXP_LIKE ( " +
                     "                          '\\s' || LOWER (PR.T_GROUND), " +
                     "                          '(зар.{0,}плата|заработн.{0,}\\sплат.{0,}|зарплат.{0,}|з/п|алимент.{0,}|аванс.{0,}|зп|_зп_|пособи.{0,}|стипенд.{0,}|беременност.{0,}|пенс.{0,})' " +
                     "                       ))), 0) x FROM   DUAL " );
   cmd.AddParam("", RSDBP_IN, PID);
   rs = RSDRecordSet(cmd);
   rs.movenext();
   return rs.value(0);
 END;

 MACRO SumToPhis_2_10 ( Account, ValueDate )
  var rs,cmd;
   cmd = RSDCommand( " SELECT   NVL(SUM (P.T_AMOUNT), 0) " +
                     "   FROM   DPMPAYM_DBT P, DPMRMPROP_DBT PR " +
                     "  WHERE   P.T_PAYERACCOUNT = ? AND P.T_PAYMSTATUS = 32000 " +
                     "          AND P.T_VALUEDATE BETWEEN (SELECT   TRUNC(TO_DATE (?), 'MONTH') FROM DUAL) " +
                     "                                AND  (TO_DATE (?)) " +
                     "          AND PR.T_PAYMENTID = P.T_PAYMENTID " +
                     "          AND (SUBSTR (P.T_PAYERACCOUNT, 1, 3) BETWEEN '405' AND '407' " +
                     "               OR SUBSTR (P.T_PAYERACCOUNT, 1, 5) IN " +
                     "                       ('40807', '40804', '40805', '40814', '40818') " +
                     "               OR (SUBSTR (P.T_PAYERACCOUNT, 1, 5) = '40821' " +
                     "                    AND LENGTH( (SELECT   CASE WHEN INSTR (T_PAYERINN, '/') != 0 " +
                     "                                               THEN SUBSTR (T_PAYERINN, 1,INSTR (T_PAYERINN, '/') - 1 ) " +
                     "                                          ELSE T_PAYERINN " +
                     "                                          END T_PAYERINN " +
                     "                                  FROM   dpmrmprop_dbt " +
                     "                                 WHERE   t_paymentid = P.T_PAYMENTID)) = 10)) " +
                     "          AND ( SUBSTR (P.T_RECEIVERACCOUNT, 1, 3)  IN  ('423', '426') " +
                     "           OR   SUBSTR (P.T_RECEIVERACCOUNT, 1, 5)  IN  ('40817', '40820')" +
                     "           OR ((SUBSTR (P.T_RECEIVERACCOUNT, 1, 5)  IN " +
                     "                         ('30301', '30232', '47422') " +
                     "                   AND (REGEXP_LIKE ('\\s' || LOWER (PR.T_GROUND),'(40817|40820|423|426)') " +
                     "                        OR REGEXP_LIKE ('\\s' || LOWER (PR.T_RECEIVERNAME),'(40817|40820|423|426)'))))) " +
                     "          AND NOT ( ( (SELECT   T_BANKCODE " +
                     "                         FROM   DPMPROP_DBT " +
                     "                        WHERE   T_PAYMENTID = P.T_PAYMENTID AND T_DEBETCREDIT = 0) = " +
                     "                      (SELECT   T_BANKCODE " +
                     "                         FROM   DPMPROP_DBT " +
                     "                        WHERE   T_PAYMENTID = P.T_PAYMENTID AND T_DEBETCREDIT = 1)) " +
                     "               AND  REGEXP_LIKE ( " +
                     "                          '\\s' || LOWER (PR.T_GROUND), " +
                     "                          '(зар.{0,}плата|заработн.{0,\\sплат.{0,}|зарплат.{0,}|з/п|алимент.{0,}|аванс.{0,}|зп|_зп_|пособи.{0,}|стипенд.{0,}|беременност.{0,}|пенс.{0,})' " +
                     "                       )) " );
   cmd.AddParam("", RSDBP_IN, Account);
   cmd.AddParam("", RSDBP_IN, ValueDate);
   cmd.AddParam("", RSDBP_IN, ValueDate);
   rs = RSDRecordSet(cmd);
   rs.movenext();
   return rs.value(0);
 END;
 
 MACRO CheckPaymToPhis_2_11 ( PID )
  var rs,cmd;
   cmd = RSDCommand( " SELECT   NVL ( " +
                     " (SELECT   1 " +
                     "    FROM   DPMPAYM_DBT P, DPMRMPROP_DBT PR " +
                     "   WHERE   P.T_PAYMENTID = ?  " +
                     "          AND PR.T_PAYMENTID = P.T_PAYMENTID " +
                     "          AND (SUBSTR (P.T_PAYERACCOUNT, 1, 5) = '40802' " +
                     "               OR (SUBSTR (P.T_PAYERACCOUNT, 1, 5) = '40821' " +
                     "                   AND LENGTH( (SELECT   CASE " +
                     "                                            WHEN INSTR (T_PAYERINN, '/') != 0 " +
                     "                                            THEN SUBSTR (T_PAYERINN, 1, INSTR (T_PAYERINN, '/') - 1 ) " +
                     "                                         ELSE T_PAYERINN " +
                     "                                         END T_PAYERINN " +
                     "                                  FROM   dpmrmprop_dbt " +
                     "                                 WHERE   t_paymentid = P.T_PAYMENTID)) = 12)) " +
                     "          AND ( SUBSTR (P.T_RECEIVERACCOUNT, 1, 3)  IN  ('423', '426') " +
                     "           OR   SUBSTR (P.T_RECEIVERACCOUNT, 1, 5)  IN  ('40817', '40820')" +
                     "           OR ((SUBSTR (P.T_RECEIVERACCOUNT, 1, 5)  IN  ('30301', '30232', '47422') " +
                     "                   AND (REGEXP_LIKE ('\\s' || LOWER (PR.T_GROUND), '(40817|40820|423|426)') " +
                     "                        OR REGEXP_LIKE ('\\s' || LOWER (PR.T_RECEIVERNAME),'(40817|40820|423|426)'))))) " +
                     "          AND NOT ( ( (SELECT   T_BANKCODE " +
                     "                         FROM   DPMPROP_DBT " +
                     "                        WHERE   T_PAYMENTID = P.T_PAYMENTID AND T_DEBETCREDIT = 0) = " +
                     "                      (SELECT   T_BANKCODE " +
                     "                         FROM   DPMPROP_DBT " +
                     "                        WHERE   T_PAYMENTID = P.T_PAYMENTID AND T_DEBETCREDIT = 1)) " +
                     "               AND  (REGEXP_LIKE ( " +
                     "                          '\\s' || LOWER (PR.T_GROUND), " +
                     "                          '(зар.{0,}плата|заработн.{0,}\\sплат.{0,}|зарплат.{0,}|з/п|алимент.{0,}|аванс.{0,}|зп|_зп_|пособи.{0,}|стипенд.{0,}|беременност.{0,}|пенс.{0,}|кредит.{0,})' " +
                     "                       ) " +
                     "               OR  (SELECT   CASE WHEN INSTR (T_PAYERINN, '/') != 0 " +
                     "                                  THEN SUBSTR (T_PAYERINN,1,INSTR (T_PAYERINN, '/') - 1) " +
                     "                             ELSE T_PAYERINN " +
                     "                             END " +
                     "                      FROM   dpmrmprop_dbt " +
                     "                     WHERE   t_paymentid = P.T_PAYMENTID) = " +
                     "                   (SELECT   CASE WHEN INSTR (T_RECEIVERINN, '/') != 0 " +
                     "                                  THEN SUBSTR (T_RECEIVERINN,1,INSTR (T_RECEIVERINN, '/') - 1) " +
                     "                             ELSE T_RECEIVERINN " +
                     "                             END " +
                     "                      FROM   dpmrmprop_dbt " +
                     "                     WHERE   t_paymentid = P.T_PAYMENTID) ))), 0) x FROM   DUAL " );
   cmd.AddParam("", RSDBP_IN, PID);
   rs = RSDRecordSet(cmd);
   rs.movenext();
   return rs.value(0);
 END;
 
 MACRO SumToPhis_2_11 ( Account, ValueDate )
  var rs,cmd;
   cmd = RSDCommand( " SELECT   NVL (  " +
                     " (SELECT   NVL(SUM (P.T_AMOUNT), 0) " +
                     "   FROM   DPMPAYM_DBT P, DPMRMPROP_DBT PR " +
                     "  WHERE   P.T_PAYERACCOUNT = ? AND P.T_PAYMSTATUS = 32000 " +
                     "          AND P.T_VALUEDATE BETWEEN (SELECT   TRUNC (TO_DATE (?),'MONTH') FROM   DUAL) " +
                     "                                AND  (TO_DATE (?)) " +
                     "          AND PR.T_PAYMENTID = P.T_PAYMENTID " +
                     "          AND (SUBSTR (P.T_PAYERACCOUNT, 1, 5) = '40802' " +
                     "               OR (SUBSTR (P.T_PAYERACCOUNT, 1, 5) = '40821' " +
                     "                   AND LENGTH( (SELECT   CASE " +
                     "                                            WHEN INSTR (T_PAYERINN, '/') != 0 " +
                     "                                            THEN SUBSTR (T_PAYERINN, 1, INSTR (T_PAYERINN, '/') - 1 ) " +
                     "                                         ELSE T_PAYERINN " +
                     "                                         END T_PAYERINN " +
                     "                                  FROM   dpmrmprop_dbt " +
                     "                                 WHERE   t_paymentid = P.T_PAYMENTID)) = 12)) " +
                     "          AND ( SUBSTR (P.T_RECEIVERACCOUNT, 1, 3)  IN  ('423', '426') " +
                     "           OR   SUBSTR (P.T_RECEIVERACCOUNT, 1, 5)  IN  ('40817', '40820')" +
                     "           OR ((SUBSTR (P.T_RECEIVERACCOUNT, 1, 5)  IN  ('30301', '30232', '47422') " +
                     "                   AND (REGEXP_LIKE ('\\s' || LOWER (PR.T_GROUND), '(40817|40820|423|426)') " +
                     "                        OR REGEXP_LIKE ('\\s' || LOWER (PR.T_RECEIVERNAME),'(40817|40820|423|426)'))))) " +
                     "          AND NOT ( ( (SELECT   T_BANKCODE " +
                     "                         FROM   DPMPROP_DBT " +
                     "                        WHERE   T_PAYMENTID = P.T_PAYMENTID AND T_DEBETCREDIT = 0) = " +
                     "                      (SELECT   T_BANKCODE " +
                     "                         FROM   DPMPROP_DBT " +
                     "                        WHERE   T_PAYMENTID = P.T_PAYMENTID AND T_DEBETCREDIT = 1)) " +
                     "               AND  (REGEXP_LIKE ( " +
                     "                          '\\s' || LOWER (PR.T_GROUND), " +
                     "                          '(зар.{0,}плата|заработн.{0,}\\sплат.{0,}|зарплат.{0,}|з/п|алимент.{0,}|аванс.{0,}|зп|_зп_|пособи.{0,}|стипенд.{0,}|беременност.{0,}|пенс.{0,}|кредит.{0,})' " +
                     "                       ) " +
                     "               OR  (SELECT   CASE WHEN INSTR (T_PAYERINN, '/') != 0 " +
                     "                                  THEN SUBSTR (T_PAYERINN,1,INSTR (T_PAYERINN, '/') - 1) " +
                     "                             ELSE T_PAYERINN " +
                     "                             END " +
                     "                      FROM   dpmrmprop_dbt " +
                     "                     WHERE   t_paymentid = P.T_PAYMENTID) = " +
                     "                   (SELECT   CASE WHEN INSTR (T_RECEIVERINN, '/') != 0 " +
                     "                                  THEN SUBSTR (T_RECEIVERINN,1,INSTR (T_RECEIVERINN, '/') - 1) " +
                     "                             ELSE T_RECEIVERINN " +
                     "                             END " +
                     "                      FROM   dpmrmprop_dbt " +
                     "                     WHERE   t_paymentid = P.T_PAYMENTID) ))), 0) x FROM   DUAL" );
   cmd.AddParam("", RSDBP_IN, Account);
   cmd.AddParam("", RSDBP_IN, ValueDate);
   cmd.AddParam("", RSDBP_IN, ValueDate);
   rs = RSDRecordSet(cmd);
   rs.movenext();
   return rs.value(0);
 END;