// -------------------------------------------------------------------------------------------------
// @filename: FSSP_Scroll_Input_Statement.mac 
// @desc    : Скроллинг принятых запросов о движения д/c
// -------------------------------------------------------------------------------------------------
import FSSP_Scroll;

private var dateBegin = {CurDate}, dateEnd = {CurDate};
private var scrollFilter = " M.T_OPER_DATE BETWEEN :DateBegin AND :DateEnd AND M.T_MES_STATE = 0 AND M.T_MES_TYPE = 2";

if (ВвестиПериодДат(dateBegin, dateEnd))
    FSSP_Scroll.init (dateBegin, dateEnd, scrollFilter, "Список принятых запросов о движении д/c ");
end;  

exit (1);