/****************************************************************************/
/*                   R-Style SoftWare Lab, RS-Bank 6.0                      */
/****************************************************************************/
/*                  Подсистема "Межбанковские расчеты"                      */
/* Генерация сообщения по BOS                                               */
/*                                                                          */
/*  Имя файла: mnsgmbns.mac                                                 */
/*  Создан   :  27.10.11                                       Чукина Т.А.  */
/*  Изменено :  08.12.11                                     Лавренов А.А.  */
/*  Заявка   :  C-7026                                                      */
/*  Mod.     :  23.12.2011 Переименована процедура AccountExists_RUR        */
/*              : 12.01.2012 На основании письма Климахиной от 11.01.2012   */
/****************************************************************************/
                                                              
import FIInter, wldinter, globals, currinter;
import "wlgenmes.mac", "wlmnstls.mac", "mnsznousr.mac";

macro GenMes( addrMes, addrRegdec )
  SetBuff( wlmes,  addrMes );
  SetBuff( wlreq, addrRegdec );

  PrintLog(2,"Генерация сообщения по BNS"); 

  var Error = 0, Code = "", ind = 0, tmpstr = "";

  record err_wlreq(wlreq);
  var parrent_wlreq:TRecHandler = TRecHandler( "wlreq", "bank.def" );
  var Zno_Mes;
  var refnumber, errcode, docnumber;
  var Narrative, Descr_ptid; 
  
  //В Description получаем ID Субъекта если есть
  ПрочитатьтекстЗапроса_Ответа( wlreq, Narrative, Descr_ptid);
  Descr_ptid = int(Descr_ptid);

  //Получаем породивший нас запрос.
  get_parrent_wlreq(wlreq.RelatedRef, parrent_wlreq);
  //получаем породившее нас сообщение
   Zno_Mes = MnsMessageFormZNO(wlreq.RelatedRef);
  debugbreak;
  /*ИдФайл*/
  ЗаписатьПолеЛог( "ИдФайл", " " );
  /*ТипИнФ*/
  ЗаписатьПолеЛог( "ТипИнф", "НАЛСЧЕТОВ" );
  /*ВерсПрог*/
  ЗаписатьПолеЛог( "ВерсПрог", "RS-Bank V.6" );
  /*ТелОтпр*/
  ЗаписатьПолеЛог( "ТелОтпр", " " );
  /*ДолжнОтпр*/
  ЗаписатьПолеЛог( "ДолжнОтпр", " " );
  /*ФИООтпр*/
  ЗаписатьПолеЛог( "ФамОтпр", " " );
  /*КолДок*/
  ЗаписатьПолеЛог( "КолДок", "1" );
  /*ВерсФорм*/
  ЗаписатьПолеЛог( "ВерсФорм", "2.01" );
  /*ИдДок*/
  tmpstr = execStoredFunc( "sys_guid", V_STRING );
  ЗаписатьПолеЛог( "ИдДок", tmpstr ); 

  GetRegistryValue("PS\\REQOPENACC\\OPERATION\\РЕФЕРЕНС_СПРАВКАОСТ", V_INTEGER, refnumber, errCode);
  if ( errCode > 0 )
    msgbox("Проверьте наличие настройки: \"PS\\REQOPENACC\\OPERATION\\РЕФЕРЕНС_СПРАВКАОСТ\"");
    return false;
  end;
  generatereference(refnumber,docnumber);
  //msgbox(docnumber); 
  /*НомСправ*/
  ЗаписатьПолеЛог( "НомСправ", docnumber ); // !!!!РЕФЕРЕНС!!!!
  
  var FullINN = GetPartyINN(wlreq.OriginatorID, 1);
  /*ИННКО*/
  ЗаписатьПолеЛог( "ИННКО", RemoveKPP( FullINN ) );
  /*КППКО*/
  ЗаписатьПолеЛог( "КППКО", RemoveINN( FullINN ) );
  /*БИК*/
  code = ПолучитьКодСубъекта(wlreq.OriginatorID, PTCK_BIC, error, 1);
  ЗаписатьПолеЛог( "БИК", code );
  /*НаимКО*/
  ЗаписатьПолеЛог( "НаимКО", wlreq.OriginatorName );
  /*НомФ*/    
  Code = ПолучитьКодСубъекта( wlreq.OriginatorID, PTCK_BANKREGNUM, Error);
  ind = index(Code, "/");
  if ( (ind == 0) or (ind == strlen(Code) ) )
    ЗаписатьПолеЛог( "НомФ", "0" );
  else
    ЗаписатьПолеЛог( "НомФ", SubStr(Code, ind + 1) );
  end;
  /*НомЗапр*/
  ЗаписатьПолеЛог("НомЗапр", Zno_Mes.НомЗапр );
  /*ДатаЗапр*/
  ЗаписатьПолеЛог("ДатаЗапр", ДатаДДpММpГГГГ(date(Zno_Mes.ДатаЗапр)));
  /*КодНО*/
  if (wlreq.recipientID > 0)
    Code = ПолучитьКодСубъекта( wlreq.recipientID, PTCK_MNS, Error);
  else
    Code = wlreq.RecipientCode;
  end;
  ЗаписатьПолеЛог("КодНО", Code);

  /*ИНННП*/
  var INNNP, KPPNP;
  debugbreak;

  INNNP = ПолучитьКодСубъекта(Descr_ptid,16);
  splitfullinn(INNNP,INNNP,KPPNP);
  
  ЗаписатьПолеЛог("ИНННП", INNNP);
  /*КППНП*/
  if (strlen(KPPNP)==9)
    ЗаписатьПолеЛог("КППНП", KPPNP );
  elif ( strlen(INNNP) != 12 )
    ЗаписатьПолеЛог("КППНП", " ");
  end;
  /*НаимНП / ФИОИП*/
  record party(party);
  if ( strlen(INNNP) != 12 )
    if (Descr_ptid > 0)
      ПолучитьСубъекта(Descr_ptid, party);
      ЗаписатьПолеЛог("НаимНП", party.Name);
    else
      ЗаписатьПолеЛог("НаимНП", "Не найден субъект");
    end;
  else
    if (Descr_ptid > 0)
      var persn = Tbfile("persn.dbt", "r");
      persn.rec.PersonID = Descr_ptid;
      persn.GetEQ();
      ЗаписатьПолеЛог("ФИОИП", persn.rec.Name1 + "," + persn.rec.Name2 + "," + persn.rec.Name3);
    else
      ЗаписатьПолеЛог( "ФИОИП", РазделитьЗапятымиФИО(Trim("Не найден субъект")) );
    end;
  end;
  
  var rs_dp_dep = getRsDpDepByPartyID(wlreq.OriginatorID);
  rs_dp_dep.moveNext();
  /*ДолжнПрБ*/
  /*!!!GetDprtStringRegValForOPENAC( "СПРАВКИ_ИФНС_ДОЛЖ", rs_dp_dep.value("t_Code"), @tmpstr );*/
  GetRegValForOPENAC("СПРАВКИ_ИФНС_ДОЛЖ", V_STRING, tmpstr);
  ЗаписатьПолеЛог("ДолжнПрБ", tmpstr);
  /*ФИОПрБ*/
  /*!!!GetDprtStringRegValForOPENAC( "СПРАВКИ_ИФНС_ФИО", rs_dp_dep.value("t_Code"), @tmpstr );*/
  GetRegValForOPENAC("СПРАВКИ_ИФНС_ФИО", V_STRING, tmpstr);
  ЗаписатьПолеЛог( "ФИОПрБ", strsubst(РазделитьЗапятымиФИО(Trim(tmpstr)),",,","") );

  /*ДатаСправ*/
  ЗаписатьПолеЛог( "ДатаСправ", ДатаДДpММpГГГГ({curdate}) );
  /*ДатаСооб*/
  ЗаписатьПолеЛог( "ДатаСооб", ДатаДДpММpГГГГ(date) );

  /*Блок "Счет" */
  var rs_acclnk;
  record Acc(account);
  var block = "Счет";           
  
  if (Zno_Mes.ТипЗапр == "2")
    rs_acclnk = getRsWlacclnk(parrent_wlreq.rec.reqid, 505);
  else
    rs_acclnk = GetClientAccounts(Descr_ptid, Zno_Mes);
  end;
  
  while(rs_acclnk and rs_acclnk.MoveNext() )
    if (AccountExists_RUR(rs_acclnk.value("t_Account"),rs_acclnk.value("t_Chapter")))          
      ПолучитьСчет( rs_acclnk.value("t_FIID"), rs_acclnk.value("t_Account"), Acc );
      if((acc.client == Descr_ptid))
        /*НомСч*/
        ЗаписатьПолеЛогВБлок( block, "НомСч", Acc.Account );
        /*ВидСч*/
        ЗаписатьПолеЛогВБлок( block, "ВидСч", ПолучитьВидСчДляСправки(Acc.Type_Account) );
        /*ВалСч*/
        ЗаписатьПолеЛогВБлок( block, "ВалСч", ПолучитьКодФинИн_usr(Acc.Code_Currency) );
        /*ДатаОткрСч*/
        ЗаписатьПолеЛогВБлок( block, "ДатаОткрСч", ДатаДДpММpГГГГ(Acc.Open_Date) );
        /*ДатаЗакрСч*/
        if(Acc.Close_Date != date(0,0,0))
          ЗаписатьПолеЛогВБлок( block, "ДатаЗакрСч", ДатаДДpММpГГГГ(Acc.Close_Date) );
        end;
      end;
    end;
  end;

  return TRUE; /* Успешное завершение */

  OnError(er) /* обработка ошибок */
    ExeptionMessage(er);
    return FALSE;

end;

/*macro CheckObj(addrRegdec)
  SetBuff(wlregdec, addrRegdec);
  return CheckObj_FNSINFO( wlregdec );
end;*/

