//Teleshova 03.03.2015 C-34823 - генерация референса для сообщений ФНС

import oralib, likepy;

record req_open  (reqopena);
record req_close (reqclosa);

//Получить дату открытия/закрытия
macro GetDateForAccount(Account:string, Fiid:integer, IsOpen:integer):string
   var select:string = " SELECT " +
                       "    CASE :IsOpen " +
                       "      WHEN 1 THEN to_char(t_open_date,'dd.mm.yyyy') " +
                       "      ELSE to_char(t_close_date,'dd.mm.yyyy') END account_date " +
                       " FROM   daccount_dbt " +
                       " WHERE   t_account = :Account " +
                       "     AND t_code_currency = :Fiid" ;
   var params : TArray = makeArray( SQLParam("IsOpen",  IsOpen),
                                    SQLParam("Account", Account),
                                    SQLParam("Fiid", Fiid));
   var rs : RsdRecordset = execSQLselect(select, params);
   if(rs and rs.moveNext())
      return rs.value("account_date");
   end;
end;

macro GetRefMes( SeqValue, ObjKind, ObjAddr )
   debugbreak;
   var Account:string = "",
       Fiid:integer = 0,
       refer:string = "", 
       date_acc:string = "",
       IsOpen:integer = -1;
   if(ObjKind == 450) //заявление на открытие счета
      SetBuff(req_open, ObjAddr);
      Account = req_open.account;
      Fiid    = req_open.code_currency;
      IsOpen = 1;
   elif(ObjKind == 451) //заявление на закрытие счета
      SetBuff(req_close, ObjAddr);
      Account = req_close.account;
      Fiid    = req_close.code_currency;
      IsOpen = 0;
   end;
   date_acc = GetDateForAccount(Account, Fiid, IsOpen);
   refer = string(SeqValue,"-",date_acc);
   return refer;
end;