// -------------------------------------------------------------------------------------------------
// @filename: uf_scroll_ed208.mac
// @author  : 2014-03-27 Gurin S. 
// @desc    : Скроллинг квитовок ED208
// @changes : УФЭБС альбом v2.6.0
//          : Gurin S. 11.06.2014 C-25227-6 (Квитовка ED274)
// -------------------------------------------------------------------------------------------------
import BankInter, PaymInter, SbCrdInter, RCW;                     // dst.: C++
import OraLib, LikePy, TReport, Globals;                          // dst.: MAC

import uf_common;

import "ask_ed243.mac", "ask_ed244.mac", "ask_ed274.mac";

private var check = False, RetV = 2 /*Отмена*/, tool_msg = "", scroll_finish = True;
private var please_wait = "Ждите, идет обработка...", action = "F2 - Обработать | F7 - Печать"; 

class (TRecHandler) UF_Scroll_Ask ()
    var rs        :RsdRecordSet = null;        // источник данных для построения скроллинга
    var isRunning     :bool         = true;        // флаг "скроллинг запущен"
    var isRunning_add :bool         = true;        // флаг "скроллинг запущен"
    var BeginDate, EndDate;
    var Filter, AddFilter;

    const SET_CHAR   = strFor (88),  
          UNSET_CHAR = strFor (0);

    macro FastUpdateEDScroll(rs : RsdRecordset)
            rs.refreshcommand = RSDCommand(rs.command.cmdtext);
            rs.refreshcommand.AddParam("date_begin", RSDBP_IN, BeginDate, V_DATE);
            rs.refreshcommand.AddParam("date_end"  , RSDBP_IN, EndDate,   V_DATE);
            rs.refreshrecord;
            UpdateScroll(rs); 
    end;
    
    // @desc: обработчик скроллинга
    macro handleScrollEvents_add ( rs, cmd, id, key )
        file fp  () txt;
        private var ret = CM_DEFAULT;

        if   (cmd == DLG_INIT)
        
        elif (cmd == DLG_KEY) 
            if (key == 27) // Esc - выход из скроллинга
                isRunning_add = false;
                ret = CM_SELECT;
            end;
        end;
        
        return ret;
    
    onError (e)
      debugbreak ();       
    end;
    
    // @desc: обработчик скроллинга
    macro handleScrollEvents ( rs, cmd, id, key )
        file fp  () txt;
        private var ret = CM_DEFAULT;
        private var sql_add, cmd_add, rs_add, col_add, msg_add = "";
        private var scrollResult_add = false;
        private var scrollCaption_add = string ("Список подтверждений п/п по системе БЭСП за период с ", BeginDate, " по ", EndDate);
        private var sql, parm;
        Array Msg; Array Box;
        Msg(0) = "Что квитуем?";

        Box(0) = "ED243";
        Box(1) = "ED244";
        Box(2) = "ED274";
        Box(3) = "Отмена";

        if (BeginDate == EndDate)
            scrollCaption_add = string ("Список подтверждений п/п по системе БЭСП за ", EndDate);
        end;
        if (cmd == DLG_INIT)
            if (not AddMultiAction (rs, 316)) 
                msgbox ("Ошибка инициализации массового выделения сообщений");
            end;

        elif (cmd == DLG_KEY) 
            if (key == 27) // Esc - выход из скроллинга
                isRunning = false;
                ret = CM_SELECT;

            // DONE: F2(Обработка сообщения)
            elif ((key == 316) and (not scroll_finish)) // Обработка сообщения
                debugbreak;
                RetV = ConfWin( Msg, Box );

                if (RetV == 0)
                    AskED243.init(rs.value("TRN"),True);
                elif (RetV == 1)
                    AskED244.init(rs.value("TRN"),True);
                elif (RetV == 2)
                    AskED274.init(rs.value("TRN"),True);
                end;
                FastUpdateEDScroll(rs);
            // DONE: F7 (печать оригинального сообщения ED243)
            elif (key == 321)
                sql  = "select t.xmldata.extract('/').getStringVal () as xml from usr_uf_container_ask t where TRN = :TRN ";
                    parm = makeArray (SQLParam ("TRN", rs.value("TRN")));
                    sql  = execSQLSelect (sql, parm);
                    var out  = getTxtFileName ("uf_message_ed");
                    open (fp, out);
                    if (sql.moveNext ())
                        setOutput (out);
                        println (sql.value ("xml"));
                        setOutput (null, true);
                        viewFile (fp);
                    else
                        msgbox ("Не удалось получить содержимое XML-контейнера для печати принятого сообщения");
                    end;
                    close (fp);
            end;
        elif (cmd == DLG_MSEL)
            // DONE: F2(Обработка сообщения) 
            if ((key == 316) and (not scroll_finish)) 
                debugbreak;
                message(please_wait);
                if (check == False)
                    RetV = ConfWin( Msg, Box );
                    check = True;
                end;

                if (RetV == 0)
                    AskED243.init(rs.value("TRN"),True,True);
                elif (RetV == 1)
                    AskED244.init(rs.value("TRN"),True,True);
                elif (RetV == 2)
                    AskED274.init(rs.value("TRN"),True,True);
                end;
                //FastUpdateEDScroll(rs);
                return CM_MSEL_CONT_CLEAR;
            end;
        elif (Cmd == DLG_MSELEND) 
            if (RetV != 3)
                ShowED208Protocol(MsgNames);
            end;
            MsgNames = TArray();
            check = False;
            if (not scroll_finish)
                message(action);
            end;
            return CM_CANCEL;
        end;

        return ret;
    
    onError (e)
      debugbreak ();       
    end;
    
    macro init (_dateBegin, _dateEnd, _filter, _addfilter)
        BeginDate = _dateBegin;
        EndDate   = _dateEnd;
        Filter   = _filter;
        AddFilter = _addfilter;
        private var scrollCaption = string ("Список загруженных сообщений ED208/ED201 за период с ", _dateBegin, " по ", _dateEnd);
        //private var msg;
        if (index(_filter,"FLAG != CHR(88)") > 0)
            scroll_finish = False;
            tool_msg = action;
        end;
        if (_dateBegin == _dateEnd)
            scrollCaption = string ("Список загруженных сообщений ED208/ED201 за ", _dateEnd);
        end;
        
        private var scrollResult = false;
        private var cmd;
        
        private var sql = " SELECT regexp_substr (usr.xmldata.extract ('/', 'xmlns=urn:cbr-ru:ed:v2.0').getstringval (), 'ED[0-9]{3}') FORMAT, " + "\n" +
                          "        usr.TRN, " + "\n" +
                          "        CASE WHEN (regexp_substr (usr.xmldata.extract ('/', 'xmlns=urn:cbr-ru:ed:v2.0').getstringval (), 'ED[0-9]{3}') = 'ED208') " + "\n" +
                          "             THEN " + "\n" +
                          "                TO_CHAR(extractvalue (usr.xmldata, '/ED208/EDRefID/@EDNo', 'xmlns=urn:cbr-ru:ed:v2.0')) " + "\n" +
                          "             WHEN (REGEXP_SUBSTR (usr.xmldata.EXTRACT ('/','xmlns=urn:cbr-ru:ed:v2.0').getstringval (),'ED[0-9]{3}') = 'ED201') " + "\n" +
                          "             THEN " + "\n" +
                          "                TO_CHAR(extractvalue (usr.xmldata, '/ED201/EDRefID/@EDNo', 'xmlns=urn:cbr-ru:ed:v2.0')) " + "\n" +
                          "        END EDNo, " + "\n" +
                          "        CASE WHEN (regexp_substr (usr.xmldata.extract ('/', 'xmlns=urn:cbr-ru:ed:v2.0').getstringval (), 'ED[0-9]{3}') = 'ED208') " + "\n" +
                          "             THEN " + "\n" +
                          "                TO_CHAR(extractvalue (usr.xmldata, '/ED208/EDRefID/@EDDate', 'xmlns=urn:cbr-ru:ed:v2.0')) " + "\n" +
                          "             WHEN (REGEXP_SUBSTR (usr.xmldata.EXTRACT ('/','xmlns=urn:cbr-ru:ed:v2.0').getstringval (),'ED[0-9]{3}') = 'ED201') " + "\n" +
                          "             THEN " + "\n" +
                          "                TO_CHAR(extractvalue (usr.xmldata, '/ED201/EDRefID/@EDDate', 'xmlns=urn:cbr-ru:ed:v2.0')) " + "\n" +
                          "        END EDDate, " + "\n" +
                          "        CASE WHEN (regexp_substr (usr.xmldata.extract ('/', 'xmlns=urn:cbr-ru:ed:v2.0').getstringval (), 'ED[0-9]{3}') = 'ED208') " + "\n" +
                          "             THEN " + "\n" +
                          "                TO_CHAR(extractvalue (usr.xmldata, '/ED208/EDRefID/@EDAuthor', 'xmlns=urn:cbr-ru:ed:v2.0')) " + "\n" +
                          "             WHEN (REGEXP_SUBSTR (usr.xmldata.EXTRACT ('/','xmlns=urn:cbr-ru:ed:v2.0').getstringval (),'ED[0-9]{3}') = 'ED201') " + "\n" +
                          "             THEN " + "\n" +
                          "                TO_CHAR(extractvalue (usr.xmldata, '/ED201/EDRefID/@EDAuthor', 'xmlns=urn:cbr-ru:ed:v2.0')) " + "\n" +
                          "        END EDAuthor, " + "\n" +
                          "        usr.FLAG " + "\n" +
                          "   FROM USR_UF_CONTAINER_ASK usr " + "\n" +
                          "  WHERE ";
                          if (_filter)                                                                                                             
                              sql = sql + _filter;                                                                                                 
                          end;  
        
                                                                                                                                                   
        // вот так мы формируем массив колонок для скроллинга
        private var col;
            col = makeArray ("FORMAT"           ,"Форма"                , 5,  0, -1, 0,
                             "TRN"              ,"Референс"             ,25,  0, -1, 0,
                             "EDNO"             ,"EDNo"                 ,10,  0, -1, 0,
                             "EDDATE"           ,"EDDate"               ,10,  0, -1, 0,
                             "EDAUTHOR"         ,"EDAuthor"             ,20,  0, -1, 0
                             );

        // основной цикл для отрисовки скроллинга. Достопримечательности:
        //      1. инициализация RsdCommand и RsdRecordSet - только здесь. Осознанно.
        //      2. если где-то в handleScrollEvents случается установка isRunning в false, происходит выход
        while (isRunning)
            cmd = RsdCommand (sql);
            cmd.addParam("date_begin", RSDBP_IN, _dateBegin, V_DATE);
            cmd.addParam("date_end"  , RSDBP_IN, _dateEnd,   V_DATE);
            rs = RsdRecordSet (cmd, RSDVAL_CLIENT, RSDVAL_STATIC);
            scrollResult = runScroll (rs, col.size/6, col, null, r2m (this, "handleScrollEvents"), scrollCaption, tool_msg, 0,0);
        end;
        return scrollResult;
    
    onError (e)
         
    end;
end;
