  macro ValTypeString(val):string
    if(ValType(val) == V_UNDEF)
      return "V_UNDEF";
    elif(ValType(val) == V_INTEGER)
      return "V_INTEGER";
    elif(ValType(val) == V_MONEY)
      return "V_MONEY";
    elif(ValType(val) == V_DOUBLE)
      return "V_DOUBLE";
    elif(ValType(val) == V_MONEYL)
      return "V_MONEYL";
    elif(ValType(val) == V_DOUBLEL)
      return "V_DOUBLEL";
    elif(ValType(val) == V_STRING)
      return "V_STRING";
    elif(ValType(val) == V_BOOL)
      return "V_BOOL";
    elif(ValType(val) == V_DATE)
      return "V_DATE";
    elif(ValType(val) == V_TIME)
      return "V_TIME";
    elif(ValType(val) == V_FILE)
      return "V_FILE";
    elif(ValType(val) == V_STRUC)
      return "V_STRUC";
    elif(ValType(val) == V_ARRAY)
      return "V_ARRAY";
    elif(ValType(val) == V_TXTFILE)
      return "V_TXTFILE";
    elif(ValType(val) == V_DBFFILE)
      return "V_DBFFILE";
    elif(ValType(val) == V_GENOBJ)
      return "V_GENOBJ";
    else
      return ValType(val);
    end;
  end;

  private macro dbgNumFields(o)
    var n= GenPropID ( o, "size" );
    if(n !=-1 )
      return o.size();
    else
      return;
    end;
  OnError();
    return;
  end;

  macro dbgPrint(__o,__recursivePrint)

  private macro dbgPrintGenObj(o,indent):bool
    if(ValType(o) != V_GENOBJ)
      return false; end;
    var recursivePrint=false;
    if(((ValType(indent) == V_BOOL) AND indent) OR (ValType(indent) == V_INTEGER))
      recursivePrint=true; end;
    if(ValType(indent) != V_INTEGER)
      indent=0; end;
    var indentStr="";
    var i=0;
    while(i < indent)
      indentStr=indentStr + "³ ";
      i=i + 1;
    end;

    var title=string(o);
    if(indent > 0)
      println(indentStr,title);
    else
      println("\n",title); end;
    var v,n=dbgNumFields(o),prevRecurse=false;
    i=0;
    while((ValType(n) != V_INTEGER) OR (i < n))
/*      v=o[i];*/
/*      v=o()(i);*/
      v=o(i);
      if(prevRecurse)
        println(indentStr,"³ << continue of ",title," >>"); end;
      println(indentStr,"Ãprop[",i,"]","=",v,", type: ",ValTypeString(v));
      if(recursivePrint AND (ValType(v) == V_GENOBJ))
        dbgPrint/*GenObj*/(v,indent + 1);
        println(indentStr,"ÃÄÙ << end of ",v," >>");
        prevRecurse=true;
      else
        prevRecurse=false;
      end;
      i=i+1;
    end;
    if(indent == 0)
      println("Ï << end of ",title," >>"); end;
    return true;
  OnError(x)
/*    println(x.code);*/
    if(x.code != 40) /* ­¥ ­ ©¤¥­® á¢®©áâ¢® ¯® ¨­¤¥ªáã */
      RunError(); end;
    if(indent == 0)
      println("Ï << end of ",title," >>"); end;
    return true;
  end;

  private macro dbgPrintRec(o,indent):bool
    var recursivePrint=false;
    if(((ValType(indent) == V_BOOL) AND indent) OR (ValType(indent) == V_INTEGER))
      recursivePrint=true; end;
    if(ValType(indent) != V_INTEGER)
      indent=0; end;
    var indentStr="";
    var i=0;
    while(i < indent)
      indentStr=indentStr + "³ ";
      i=i + 1;
    end;

    i=0;
    var v,title;
    if((ValType(o) == V_STRUC) OR (ValType(o) == V_FILE) OR (ValType(o) == V_DBFFILE))
      title=string(o);
      if(indent > 0)
        println(indentStr,title);
      else
        println("\n",title); end;
      while(i < FldNumber(o))
        v=o(i);
        println(indentStr,"Ã",FldName(o,i),"=",v,", type: ",ValTypeString(v));
        i=i+1;
      end;
      if(indent == 0)
        println("Ï << end of ",title," >>"); end;
      return true;
    elif(ValType(o) == V_GENOBJ)
      if(IsEqClass("TBfile",o) OR IsEqClass("TRecHandler",o))
        title=string(o," ",o.TblName);
        if(indent > 0)
          println(indentStr,title);
        else
          println("\n",title); end;
        while(i < o.FldNumber())
          v=o.rec()(i);
          println(indentStr,"Ã",o.FldName(i),"=",v,", type: ",ValTypeString(v));
          i=i+1;
        end;
        if(indent == 0)
          println("Ï << end of ",title," >>"); end;
        return true;
      end;
    end;
    return false;
  end;

    if(dbgPrintRec(__o,__recursivePrint) OR dbgPrintGenObj(__o,__recursivePrint))
      return true; end;
/*    println(__o); end;*/
    println(__o,", type: ",ValTypeString(__o));
    return false;
  end;
