

//04.11.2014 I-00528841 DPN €¤ ¯â æ¨ï ¯®¤ 31-© ¯ âç



Import BankInter, RsbDataset, globals;

var BegDate = Date({curdate}-1);
var EndDate = {curdate};


var i=1;
GetDate (BegDate, "„ â  ­ ç «  ®âç¥â ");
GetDate (EndDate, "„ â  ®ª®­ç ­¨ï ®âç¥â ");
if  (EndDate>{curdate})
 EndDate={curdate};
 msgbox ("„ â  ®ª®­ç ­¨ï ­¥ ¬®¦¥â ¡ëâì ¡®«ìè¥ â¥ªãé¥©");
end;
if (BegDate>EndDate)
 msgbox ("„ â  ­ ç «  ­¥ ¬®¦¥â ¡ëâì ¡®«ìè¥ ¤ âë ª®­æ ");
 BegDate=EndDate;
end; 

//04.11.2014 I-00528841 DPN
var dataSource   = TRsbDataset ( "select  arhdoc.t_date_carry ,ARHDOC.T_NUMB_DOCUMENT, arhdoc.t_account_payer , balanceP.t_Kind_account kindP, arhdoc.t_account_receiver,  balanceR.t_Kind_account kindR,  arhdoc.t_sum_natcur, arhdoc.t_Ground" 

+ "\n" + "from dacctrn_dbt arhdoc, dbalance_dbt balanceP, dbalance_dbt balanceR                                "
+ "\n" + "where     arhdoc.t_chapter = 3                                                                       "
+ "\n" + "      and arhdoc.t_date_carry >= to_date (  '"+Begdate+"', 'DD-MM-YYYY' )                              "
+ "\n" + "      and arhdoc.t_date_carry <= to_date (  '"+EndDate+"' ,'DD-MM-YYYY' )                              "
+ "\n" + "      and arhdoc.t_result_carry!=23                                                                  "
+ "\n" + "      and  substr(arhdoc.t_account_payer,1,5)  =  '99999'                                            "
+ "\n" + "      and substr ( arhdoc.t_account_payer, 1, 5 ) != substr ( arhdoc.t_account_receiver, 1, 5 )      "
+ "\n" + "      and substr ( arhdoc.t_account_payer, 1, 5 ) = balanceP.T_balance                               "
+ "\n" + "      and substr ( arhdoc.t_account_receiver, 1, 5 ) =balanceR.T_balance                             "
+ "\n" + "      and (                                                                                          "
+ "\n" + "       (substr(arhdoc.t_account_payer,1,5)  =  '99999' and balanceR.t_Kind_account = '') or         "
+ "\n" + "       (substr(arhdoc.t_account_payer,1,5)  =  '99998' and balanceR.t_Kind_account = '€') or         "
+ "\n" + "       (substr(arhdoc.t_account_receiver,1,5)  =  '99999' and balanceP.t_Kind_account = '') or      "
+ "\n" + "       (substr(arhdoc.t_account_Receiver,1,5)  =  '99998' and balanceP.t_Kind_account = '€')         "
+ "\n" + "       )        "
+ "\n" + "      union all "
+ "\n" + " select  arhdoc.t_date_carry ,ARHDOC.T_NUMB_DOCUMENT, arhdoc.t_account_payer , balanceP.t_Kind_account kindP, arhdoc.t_account_receiver,  balanceR.t_Kind_account kindR, arhdoc.t_sum_natcur, arhdoc.t_Ground"
+ "\n" + " from dacctrn_dbt arhdoc, dbalance_dbt balanceP, dbalance_dbt balanceR                               " 
+ "\n" + "where     arhdoc.t_chapter = 3                                                                       "
+ "\n" + "      and arhdoc.t_result_carry!=23                                                                  "
+ "\n" + "      and arhdoc.t_date_carry >= to_date (  '"+Begdate+"', 'DD-MM-YYYY' )                            "
+ "\n" + "      and arhdoc.t_date_carry <= to_date (  '"+EndDate+"' ,'DD-MM-YYYY' )                            "
+ "\n" + "      and substr ( arhdoc.t_account_payer, 1, 4 ) != '9999'                                          "
+ "\n" + "      and substr ( arhdoc.t_account_receiver, 1, 4 )!='9999'                                         "
+ "\n" + "      and substr ( arhdoc.t_account_payer, 1, 5 ) != substr ( arhdoc.t_account_receiver, 1, 5 )      "
+ "\n" + "      and substr ( arhdoc.t_account_payer, 1, 5 ) = balanceP.T_balance                               "
+ "\n" + "      and substr ( arhdoc.t_account_receiver, 1, 5 ) =balanceR.T_balance                             "
+ "\n" + "      and (balanceP.t_Kind_account!=  balanceR.t_Kind_account)                                       "
                               );

var isEof = false;
isEof = not dataSource.next();
dataSource.setFieldType("sum_natcur",         V_MONEY);
dataSource.setFieldType("date_carry",        V_DATE);

 [                                                      ¥ª®àà¥ªâ­ë¥ ¯à®¢®¤ª¨ ¯® ¢­¥¡ « ­áã                                                                          ];
 [ÚÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿];
 [³ü ¯/¯ ³    „ â     ³ ®¬¥à ¤®ª.³  ‘ç¥â ¯« â¥«ìé¨ª      ³’¨¯³ ‘ç¥â ¯®«ãç â¥«ï     ³’¨¯³   ‘ã¬¬         ³        §­ ç¥­¨¥ ¯« â¥¦                                  ³];
 [ÃÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´];
while (not isEof)
 [³######³ ########## ³ ######### ³ ##################### ³ # ³ ####################³ # ³################³ #########################################################³]
 (i:r,dataSource.Date_carry, dataSource.Numb_document:l, dataSource.account_payer, dataSource.kindP,  dataSource.account_receiver, dataSource.kindR, dataSource.Sum:r,dataSource.Ground ); 
 i=i+1;
 isEof = not dataSource.next();
end;
 
 [ÀÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ];

println ("ˆâ®£® ¤®ªã¬¥­â®¢ ", i-1 );                                                  
