/************************************************************************/
/*          Автоматизированная банковская система RS-Bank v6.0          */
/*                                                                      */
/*               Copyright (c) R-Style                                  */
/*                                                                      */
/*  Имя файла        :                                                  */
/*                                                                      */
/*  Описание         : выборка предварительных данных для формы 407     */
/*                                                                      */
/*  Программист      : Вихров Д.В.                                      */
/*                                                                      */
/*  Создан           : 12.01.2010                                       */
/*                                                                      */
// 12.02.2012 vihrov по правильному выгрузка в эксель с копированием шаблона на терминал. совместно с I-00145280-1
/************************************************************************/
import globals, FIInter,rsbdataset,OprInter, "VBAconst.mac",rsexts,payminter,pm_note;
// oralib, SprAcc,"UpddateAcc.mac",
var ob,ex,obBook,obSheet;
var out, output = "407_predv.xls", fulloutput;                            
var path = "", pathfile = "",    filen = "407_predv.lbr";
GetRegistryValue("BANK_INI\\ОБЩИЕ ПАРАМЕТРЫ\\ДИРЕКТОРИИ\\LBRDIR",2,path);
pathfile = FindPath(filen,path);

//msgbox(" (Алена, сфотографируйте и пришлите мне этот экран) значение pathfile:"+pathfile);

var dlg = TRecHandler("panel",pathfile,True);
var ot4_data_begin,ot4_data_end;
var KEY_F2=316;
var KEY_F3=317;
var KEY_F9=323;
var KEY_ESC=27;
var KEY_ENTER=13;
var exel_begin_stroka:integer=6;
var exelstroka:integer=exel_begin_stroka;
var prbb_swift;
var rabota_date_begin:date;
var rabota_date_end:date;
var rabota_time_begin:time;
var rabota_time_end:time;




macro format_select;
   if (exel_begin_stroka!=exelstroka) 
     obSheet.Range("A"+exel_begin_stroka+":r"+exelstroka).select;       
     ex.Selection.Borders(xlDiagonalDown).LineStyle = xlNone;           
    ex.Selection.Borders(xlDiagonalUp).LineStyle = xlNone;             
    ex.Selection.Borders(xlEdgeLeft).LineStyle = xlContinuous;         
     ex.Selection.Borders(xlEdgeLeft).Weight = xlThin;                  
     ex.Selection.Borders(xlEdgeLeft).ColorIndex = xlAutomatic;         
    ex.Selection.Borders(xlEdgeTop).LineStyle = xlContinuous;          
    ex.Selection.Borders(xlEdgeTop).Weight = xlThin;                   
    ex.Selection.Borders(xlEdgeTop).ColorIndex = xlAutomatic;          
    ex.Selection.Borders(xlEdgeBottom).LineStyle = xlContinuous;       
    ex.Selection.Borders(xlEdgeBottom).Weight = xlThin;                
    ex.Selection.Borders(xlEdgeBottom).ColorIndex = xlAutomatic;       
    ex.Selection.Borders(xlEdgeRight).LineStyle = xlContinuous;        
    ex.Selection.Borders(xlEdgeRight).Weight = xlThin;                 
    ex.Selection.Borders(xlEdgeRight).ColorIndex = xlAutomatic;        
    ex.Selection.Borders(xlInsideVertical).LineStyle = xlContinuous;   
    ex.Selection.Borders(xlInsideVertical).Weight = xlThin;            
    ex.Selection.Borders(xlInsideVertical).ColorIndex = xlAutomatic;   
    ex.Selection.Borders(xlInsideHorizontal).LineStyle = xlContinuous; 
    ex.Selection.Borders(xlInsideHorizontal).Weight = xlThin;          
    ex.Selection.Borders(xlInsideHorizontal).ColorIndex = xlAutomatic; 
    ex.Selection.wraptext = true;                                      
  end
END;



/*
MACRO    format_cell_bank(cell)
    obSheet.Range(cell).Select;
        ex.selection.HorizontalAlignment = xlGeneral;
        ex.selection.VerticalAlignment = xlBottom;
        ex.selection.WrapText = True;
        ex.selection.Orientation = 0;
        ex.selection.AddIndent = False;
        ex.selection.IndentLevel = 0;
        ex.selection.ShrinkToFit = False;
        ex.selection.ReadingOrder = xlContext;
        ex.selection.MergeCells = False;
END;
*/
MACRO    format_cell_bank(cell)

        obSheet.Range(cell).HorizontalAlignment = xlGeneral;
        obSheet.Range(cell).VerticalAlignment = xlBottom;
        obSheet.Range(cell).WrapText = True;
        obSheet.Range(cell).Orientation = 0;
        obSheet.Range(cell).AddIndent = False;
        obSheet.Range(cell).IndentLevel = 0;
        obSheet.Range(cell).ShrinkToFit = False;
        obSheet.Range(cell).ReadingOrder = xlContext;
        obSheet.Range(cell).MergeCells = False;
END;

/*
MACRO format_perenos_po_slowam(cell)
   obSheet.Range(cell).Select;
  ex.Selection.HorizontalAlignment = xlGeneral;
  ex.Selection.VerticalAlignment = xlBottom;
  ex.Selection.WrapText = True;
  ex.Selection.Orientation = 0;
  ex.Selection.AddIndent = False;
  ex.Selection.IndentLevel = 0;
  ex.Selection.ShrinkToFit = False;
  ex.Selection.ReadingOrder = xlContext;
  ex.Selection.MergeCells = False;
END;
*/
MACRO format_perenos_po_slowam(cell)

  obSheet.Range(cell).HorizontalAlignment = xlGeneral;
  obSheet.Range(cell).VerticalAlignment = xlBottom;
  obSheet.Range(cell).WrapText = True;
  obSheet.Range(cell).Orientation = 0;
  obSheet.Range(cell).AddIndent = False;
  obSheet.Range(cell).IndentLevel = 0;
  obSheet.Range(cell).ShrinkToFit = False;
  obSheet.Range(cell).ReadingOrder = xlContext;
  obSheet.Range(cell).MergeCells = False;
END;



MACRO out_sql(s)
   private var ds;
  ds=trsbdataset(s);
  while (ds.movenext)
   obSheet.Range("a"+exelstroka).Value=ds.value("npp");
   obSheet.Range("b"+exelstroka).numberformat="@";
   obSheet.Range("b"+exelstroka).Value=ds.value("podrazdel");
   obSheet.Range("c"+exelstroka).Value=ds.value("ndoc");
   obSheet.Range("d"+exelstroka).Value=ds.value("ddoc");
   obSheet.Range("e"+exelstroka).Value=ds.value("dzn");
   obSheet.Range("f"+exelstroka).Value=ds.value("summa");
   obSheet.Range("g"+exelstroka).Value=ds.value("valuta");
   obSheet.Range("h"+exelstroka).Value=ds.value("plat");
   //format_cell_bank("h"+exelstroka);
   obSheet.Range("i"+exelstroka).numberformat="@";
   obSheet.Range("i"+exelstroka).Value=ds.value("c4_plat");
   //format_perenos_po_slowam("i"+exelstroka);
   obSheet.Range("j"+exelstroka).Value=ds.value("b_plat");
   //format_cell_bank("j"+exelstroka);
   obSheet.Range("k"+exelstroka).Value=ds.value("polu4");
   //format_cell_bank("k"+exelstroka);
   obSheet.Range("l"+exelstroka).numberformat="@";
   obSheet.Range("l"+exelstroka).Value=ds.value("c4_polu4");
   //format_perenos_po_slowam("l"+exelstroka);
   obSheet.Range("m"+exelstroka).Value=ds.value("b_polu4");
   //format_cell_bank("m"+exelstroka);
   obSheet.Range("n"+exelstroka).Value=ds.value("osnov");
   //format_cell_bank("n"+exelstroka);

   obSheet.Range("o"+exelstroka).Value=ReadNoteForPayment(ds.value("npp"),136);
   //format_cell_bank("o"+exelstroka);
   obSheet.Range("p"+exelstroka).Value=ReadNoteForPayment(ds.value("npp"),137);
   obSheet.Range("q"+exelstroka).Value=ds.value("kat117");
   obSheet.Range("r"+exelstroka).Value=ReadNoteForPayment(ds.value("npp"),139);

/*    obSheet.Range("m"+exelstroka).Value=ds.value("");
   obSheet.Range("n"+exelstroka).Value=ds.value("");
   obSheet.Range("o"+exelstroka).Value=ds.value("");
   obSheet.Range("p"+exelstroka).Value=ds.value("");
   obSheet.Range(""+exelstroka).Value=ds.value("");*/
   exelstroka=exelstroka+1;
  end;

END;

MACRO outputinexcel

	macro copyToMe(full_absolut_path)
//		getstring(tempFileNameBezPuti);
		private var m_path: string = "";
		private var tempFileNameBezPuti = output;
//		m_path = "$" + TMP_TERM_DIR + "\\" + tempFileNameBezPuti;
		m_path = "$"  + tempFileNameBezPuti;
		if (not CopyFile(full_absolut_path, m_path, TRUE))
			println ("не могу скопировать шаблон с сервера приложений на терминал.\n исходный файл: "+full_absolut_path+" \nфайл назначения: " + m_path);
			println(" останавливаюсь. Обратитесь в техподдержку. код ошибки 238 ");
			exit(1);
		end;
	end;
   
   
   private var ds;
   private var dd:date, tt:time, ii:integer, ss:string;  // это переменные для использования FileInfo

   ds=trsbdataset("select t_code from dobjcode_dbt where t_objectid='"+{OurBank}+"' and t_codekind=6 and t_objecttype=3");
   if (ds.movenext) prbb_swift=ds.value("t_code");
   else msgbox(" чото не могу выбрать swift код для банка. останавливаюсь "); exit(7);
   end;
  /*
  if (IsStandAlone()) // Двухзвенка
    if ((ValType(ex)!=V_UNDEF) and (ex.Visible==False))
      ex = ActiveX("Excel.Application",NULL,false); 
    else
      ex = ActiveX("Excel.Application",NULL,true);
    end;
  else // Трехзвенка
    ob = CreateObject ("rsax","TRsAxServer","RsAxServer",false);
    ex = ob.CreateComObject ("Excel.Application");
  end; 
  DAI для двух и трехзвенки достаточно использовать одинаковый механизм запуска офисных приложений*/
   ob = CreateObject ("rsax","TRsAxServer","RsAxServer",IsStandAlone());
   ex = ob.CreateComObject ("Excel.Application", True);

   debugbreak;

   GetRegistryValue("BANK_INI\\ОБЩИЕ ПАРАМЕТРЫ\\ДИРЕКТОРИИ\\USERTEMPLSDIR",2,out);
   Fulloutput = FindPath(output, out);                    
/*DAI Оторвите мне руки, но объясните убогому, ради чего нужно копировать шаблон из USERTEMPLSDIR на локальный диск пользователя??? 
vihrov приедеш - объясню
*/
   copyToMe(Fulloutput);
   if (not(GetFileInfo("$"+output,@dd,@tt,@ii,@ss))); //ss- то что надо. полный путь абсолютный локальный
	   msgbox("не мог найти на локальном диске файл "+output+"          \n останавливаюсь");
	   exit(1);
   end;
   ss = substr(ss,2); // откусили первый знак бакса

//   msgbox(ss);
   obBook = ex.Workbooks.open(ss); //локальный можно и нужно открывать
//   obBook = ex.Workbooks.add(ss);  //DAI Лучше не открывать файл. Могут возникнуть проблемы с доступом. А создавать новый на основе шаблона.
//   obBook = ex.Workbooks.add(Fulloutput);  //DAI Лучше не открывать файл. Могут возникнуть проблемы с доступом. А создавать новый на основе шаблона.

   obSheet = obBook.ActiveSheet(); 
  obSheet.Range("a2").Value="Начало периода  "+ot4_data_begin+"   конец периода  "+ot4_data_end;
//    ex.visible=true;

  message("------------------------------- идет построение отчета --------------------------------");
//  sql="";
var sql2111="select pmprop1.t_paymentid npp,                                                                                                           "+
            "       '2.1.1.1' podrazdel,                                                                                                                "+
            "       pmrmprop.t_number ndoc,                                                                                                             "+
            "       pmrmprop.t_date ddoc,                                                                                                               "+
            "       pmprop1.t_transferdate dzn,                                                                                                         "+
            "       paym.t_baseamount summa,                                                                                                            "+
            "       fin.t_fi_code valuta,                                                                                                               "+
            "       PMRMPROP.T_PAYERNAME plat,                                                                                                          "+
                  "       paym.t_payeraccount c4_plat, "+
            "       PMRMPROP.T_PAYERBANKNAME b_plat,                                                                                                    "+
            "       PMRMPROP.T_RECEIVERNAME polu4,                                                                                                      "+
            "           paym.t_receiveraccount c4_polu4, "+
            "       PMRMPROP.T_RECEIVERBANKNAME b_polu4,                                                                                                "+
            "       pmrmprop.t_ground osnov, zn_kat.t_nameobject kat117                                                                              "+
            "from dpmprop_dbt pmprop1,                                                                                                                  "+
            "     dpmprop_dbt pmprop2,                                                                                                                  "+
            "     dpmpaym_dbt paym, "+
            "     dpmrmprop_dbt pmrmprop,                                                                                                               "+
            "     dfininstr_dbt fin, dobjatcor_dbt kateg, dobjattr_dbt zn_kat,     dcorschem_dbt corsch                                                                                                                     "+
            "where     pmprop1.t_transferdate >= to_date ( '"+ot4_data_begin+"', 'DD.MM.RRRR' )                                                         "+
            "      and pmprop1.t_transferdate <= to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' )                                                           "+
            "      and pmprop1.t_debetcredit = 1                                                                                                        "+
            "      and pmprop1.t_group = 1                                                                                                              "+
            "      and pmprop2.t_debetcredit = 0                                                                                                        "+
            "      and ((pmprop2.t_codekind = 3  and pmprop2.t_bankcode ='"+{MFO_Bank}+"') or (pmprop2.t_codekind = 6  and pmprop2.t_bankcode ='"+prbb_swift+"')) "+
            "      and pmprop1.t_paymentid = pmprop2.t_paymentid                                                                                        "+
            "      and paym.t_paymstatus = 32000                                                                                                        "+
            "      and paym.t_paymentid = pmprop1.t_paymentid                                                                                           "+
            "      and paym.t_paymentid = pmprop2.t_paymentid                                                                                           "+
            "      and paym.t_paymentid = pmrmprop.t_paymentid                                                                                          "+
            "      and paym.t_fiid > 0                                                                                                                  "+
            "      and (   paym.t_payeraccount like '42301%' or paym.t_payeraccount like '40912%')                  "+
            "			 and not(( paym.t_payeraccount like '423%' or paym.t_payeraccount like '40807%' or paym.t_payeraccount like '40817%' ) "+
            "			 and (paym.t_receiveraccount like '423%' or paym.t_receiveraccount like '40807%' or paym.t_receiveraccount like '40817%')) "+
            "      and (corsch.t_account like '30114%' or corsch.t_account like '30220%' or corsch.t_account like '30110%' )          "+
            "      and paym.t_fiid = fin.t_fiid                                                                                                         "+
            "         and kateg.t_object(+)=lpad(pmprop1.t_paymentid,10,0) and kateg.t_objecttype(+)=501 and kateg.t_groupid(+)=117 and kateg.t_validtodate(+)>=to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' )      "+
//             "         and kateg.t_validfromdate(+)<=to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' ) "+
            "      and (kateg.t_validtodate=(select max(kateg1.t_validtodate) from dobjatcor_dbt kateg1 where kateg.t_object=kateg1.t_object and kateg1.t_objecttype=501 and kateg1.t_groupid=117) "+
            "      or kateg.t_validtodate is null) "+
            "         and zn_kat.t_objecttype(+)=501 and zn_kat.t_groupid(+)=117 and zn_kat.t_attrid(+)=kateg.t_attrid "+
            "         and corsch.t_number=abs(pmprop1.t_corschem) "+
            "         and corsch.t_fiid=pmprop1.t_payfiid "+
            "      order by paym.t_fiid      ";


var sql2112="select pmprop1.t_paymentid npp,                                                                                                           "+
            "       '2.1.1.2' podrazdel,                                                                                                               "+
            "       pmrmprop.t_number ndoc,                                                                                                            "+
            "       pmrmprop.t_date ddoc,                                                                                                              "+
            "       pmprop1.t_transferdate dzn,                                                                                                        "+
            "       paym.t_baseamount summa,                                                                                                           "+
            "       fin.t_fi_code valuta,                                                                                                              "+
            "       PMRMPROP.T_PAYERNAME plat,                                                                                                         "+
                  "       paym.t_payeraccount c4_plat, "+
            "       PMRMPROP.T_PAYERBANKNAME b_plat,                                                                                                   "+
            "       PMRMPROP.T_RECEIVERNAME polu4,                                                                                                     "+
            "           paym.t_receiveraccount c4_polu4, "+
            "       PMRMPROP.T_RECEIVERBANKNAME b_polu4,                                                                                               "+
            "       pmrmprop.t_ground osnov, zn_kat.t_nameobject kat117                                                                    "+
            "from dpmprop_dbt pmprop1,                                                                                                                 "+
            "     dpmprop_dbt pmprop2,                                                                                                                 "+
            "     dpmpaym_dbt paym,                                                                                                                    "+
            "     dpmrmprop_dbt pmrmprop,                                                                                                              "+
            "     dfininstr_dbt fin, dobjatcor_dbt kateg, dobjattr_dbt zn_kat,     dcorschem_dbt corsch                                                                                                                    "+
            "where     pmprop1.t_transferdate >= to_date ( '"+ot4_data_begin+"', 'DD.MM.RRRR' )                                                        "+
            "      and pmprop1.t_transferdate <= to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' )                                                          "+
            "      and pmprop1.t_debetcredit = 1                                                                                                       "+
            "      and pmprop1.t_group = 1                                                                                                             "+
            "      and pmprop2.t_debetcredit = 0                                                                                                       "+
            "      and ((pmprop2.t_codekind = 3  and pmprop2.t_bankcode ='"+{MFO_Bank}+"') or (pmprop2.t_codekind = 6  and pmprop2.t_bankcode ='"+prbb_swift+"')) "+
            "      and pmprop1.t_paymentid = pmprop2.t_paymentid                                                                                       "+
            "      and paym.t_paymstatus = 32000                                                                                                       "+
            "      and paym.t_paymentid = pmprop1.t_paymentid                                                                                          "+
            "      and paym.t_paymentid = pmprop2.t_paymentid                                                                                          "+
            "      and paym.t_paymentid = pmrmprop.t_paymentid                                                                                         "+
            "      and paym.t_fiid = 0                                                                                                                 "+
            "      and (   paym.t_payeraccount like '42301%'                                                                                           "+
            "           or paym.t_payeraccount like '40912%'                                                                                           "+
            "           or paym.t_payeraccount like '40817%' )                                                                                         "+
            "			 and not(( paym.t_payeraccount like '423%' or paym.t_payeraccount like '40807%' or paym.t_payeraccount like '40817%' ) "+
            "			 and (paym.t_receiveraccount like '423%' or paym.t_receiveraccount like '40807%' or paym.t_receiveraccount like '40817%')) "+
            "      and corsch.t_account like '30111%'                                                                                            "+
            "      and paym.t_fiid = fin.t_fiid                                                                                                        ";
            "        and kateg.t_object(+)=lpad(pmprop1.t_paymentid,10,0) and kateg.t_objecttype(+)=501 and kateg.t_groupid(+)=117 and kateg.t_validtodate(+)>=to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' )      "+
//            "         and kateg.t_validfromdate(+)<=to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' )                                                                                                                  "+
            "        and (kateg.t_validtodate=(select max(kateg1.t_validtodate) from dobjatcor_dbt kateg1 where kateg.t_object=kateg1.t_object and kateg1.t_objecttype=501 and kateg1.t_groupid=117)       "+
            "     or kateg.t_validtodate is null)                                                                                                                                                   "+
            "        and zn_kat.t_objecttype(+)=501 and zn_kat.t_groupid(+)=117 and zn_kat.t_attrid(+)=kateg.t_attrid                                                                                      "+
            "       and corsch.t_number=abs(pmprop1.t_corschem) "+
            "        and corsch.t_fiid=pmprop1.t_payfiid ";

var sql2121="select pmprop1.t_paymentid npp,                                                                                "+
            "       '2.1.2.1' podrazdel,                                                                                    "+
            "       pmrmprop.t_number ndoc,                                                                                 "+
            "       pmrmprop.t_date ddoc,                                                                                   "+
            "       pmprop1.t_transferdate dzn,                                                                             "+
            "       paym.t_baseamount summa,                                                                                "+
            "       fin.t_fi_code valuta,                                                                                   "+
            "       pmrmprop.t_payername plat,                                                                              "+
                  "       paym.t_payeraccount c4_plat, "+
            "       pmrmprop.t_payerbankname b_plat,                                                                        "+
            "       pmrmprop.t_receivername polu4,                                                                          "+
            "           paym.t_receiveraccount c4_polu4, "+
            "       pmrmprop.t_receiverbankname b_polu4,                                                                    "+
            "       pmrmprop.t_ground osnov, zn_kat.t_nameobject  kat117                                                   "+
            "from dpmprop_dbt pmprop1, dpmprop_dbt pmprop2, dpmpaym_dbt paym, dpmrmprop_dbt pmrmprop, dfininstr_dbt fin, dobjatcor_dbt kateg, dobjattr_dbt zn_kat,     dcorschem_dbt corsch     "+
            "where     pmprop1.t_transferdate >= to_date ( '"+ot4_data_begin+"', 'DD.MM.RRRR' )                             "+
            "      and pmprop1.t_transferdate <= to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' )                               "+
            "      and pmprop1.t_debetcredit = 0                                                                            "+
            "      and pmprop1.t_group = 1                                                                                  "+
            "      and pmprop2.t_debetcredit = 1                                                                            "+
            "      and ( ( pmprop2.t_codekind = 3 and pmprop2.t_bankcode = '"+{MFO_Bank}+"' )                               "+
            "           or ( pmprop2.t_codekind = 6 and pmprop2.t_bankcode = '"+prbb_swift+"' ) )                                 "+
            "      and pmprop1.t_paymentid = pmprop2.t_paymentid                                                            "+
            "      and paym.t_paymstatus = 32000                                                                            "+
            "      and paym.t_paymentid = pmprop1.t_paymentid                                                               "+
            "      and paym.t_paymentid = pmprop2.t_paymentid                                                               "+
            "      and paym.t_paymentid = pmrmprop.t_paymentid                                                              "+
            "      and paym.t_fiid > 0                                                                                      "+
            "      and  corsch.t_account like '30114%'                         "+
//            "      and substr(paym.t_payeraccount,1,5) in ('30110','30114')  "+                                                                
            "      and (   (substr(paym.t_receiveraccount,1,5) between '42301' and  '42306')  "+
            "           	 or substr(paym.t_receiveraccount,1,5) in ('40909','40817','40912'))    "+
            "			 and not(( paym.t_payeraccount like '423%' or paym.t_payeraccount like '40807%' or paym.t_payeraccount like '40817%' ) "+
            "			 and (paym.t_receiveraccount like '423%' or paym.t_receiveraccount like '40807%' or paym.t_receiveraccount like '40817%')) "+
            "      and paym.t_fiid = fin.t_fiid                                                                             "+
            "         and kateg.t_object(+)=lpad(pmprop1.t_paymentid,10,0) and kateg.t_objecttype(+)=501 and kateg.t_groupid(+)=117 and kateg.t_validtodate(+)>=to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' )       "+
//             "         and kateg.t_validfromdate(+)<=to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' ) "+
            "         and (kateg.t_validtodate=(select max(kateg1.t_validtodate) from dobjatcor_dbt kateg1 where kateg.t_object=kateg1.t_object and kateg1.t_objecttype=501 and kateg1.t_groupid=117) "+
            "         or kateg.t_validtodate is null) "+
            "         and zn_kat.t_objecttype(+)=501 and zn_kat.t_groupid(+)=117 and zn_kat.t_attrid(+)=kateg.t_attrid "+
            "         and corsch.t_number=abs(pmprop1.t_corschem) "+
            "         and corsch.t_fiid=pmprop1.t_payfiid "+ 
           "order by paym.t_fiid   ";

var sql2122="  select pmprop1.t_paymentid npp,  "+                                                                            
            "         '2.1.2.2' podrazdel,   "+                                                                                
            "         pmrmprop.t_number ndoc,   "+                                                                            
            "         pmrmprop.t_date ddoc,  "+                                                                              
            "         pmprop1.t_transferdate dzn,  "+                                                                        
            "         paym.t_baseamount summa,  "+                                                                            
            "         fin.t_fi_code valuta,  "+                                                                              
            "         pmrmprop.t_payername plat,   "+                                                                          
                  "       paym.t_payeraccount c4_plat, "+
            "         pmrmprop.t_payerbankname b_plat,   "+                                                                    
            "         pmrmprop.t_receivername polu4,  "+                                                                      
            "           paym.t_receiveraccount c4_polu4, "+
            "         pmrmprop.t_receiverbankname b_polu4,  "+                                                                
            "         pmrmprop.t_ground osnov, zn_kat.t_nameobject kat117 "+                                                                            
            "  from dpmprop_dbt pmprop1, dpmprop_dbt pmprop2, dpmpaym_dbt paym, dpmrmprop_dbt pmrmprop, dfininstr_dbt fin, dobjatcor_dbt kateg, dobjattr_dbt zn_kat,     dcorschem_dbt corsch   "+
            "  where     pmprop1.t_transferdate >= to_date ( '"+ot4_data_begin+"', 'DD.MM.RRRR' )  "+                                
            "        and pmprop1.t_transferdate <= to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' ) "+                                
            "        and pmprop1.t_debetcredit = 0 "+                                                                        
            "        and pmprop1.t_group = 1 "+                                                                              
            "        and pmprop2.t_debetcredit = 1 "+                                                                        
            "        and ( ( pmprop2.t_codekind = 3 and pmprop2.t_bankcode = '"+{MFO_Bank}+"' ) "+                                
            "             or ( pmprop2.t_codekind = 6 and pmprop2.t_bankcode = '"+prbb_swift+"' ) )   "+                            
            "        and pmprop1.t_paymentid = pmprop2.t_paymentid   "+                                                        
            "        and paym.t_paymstatus = 32000 "+                                                                        
            "        and paym.t_paymentid = pmprop1.t_paymentid   "+                                                          
            "        and paym.t_paymentid = pmprop2.t_paymentid   "+                                                          
            "        and paym.t_paymentid = pmrmprop.t_paymentid  "+                                                          
            "        and paym.t_fiid = 0  "+                                                                                  
            "      /*  and corsch.t_account like '30111%' */ "+
            "        and paym.t_payeraccount like '30111%'  "+                                                                
            "        and (   paym.t_receiveraccount like '42301%' "+                                                        
            "             or paym.t_receiveraccount like '42302%' "+                                                        
            "             or paym.t_receiveraccount like '42303%' "+                                                        
            "             or paym.t_receiveraccount like '42304%' "+                                                        
            "             or paym.t_receiveraccount like '42305%' "+                                                        
            "             or paym.t_receiveraccount like '42306%' "+                                                        
            "             or paym.t_receiveraccount like '40909%' "+                                                        
            "             or paym.t_receiveraccount like '40817%' )  "+                                                      
            "			 and not(( paym.t_payeraccount like '423%' or paym.t_payeraccount like '40807%' or paym.t_payeraccount like '40817%' ) "+
            "			 and (paym.t_receiveraccount like '423%' or paym.t_receiveraccount like '40807%' or paym.t_receiveraccount like '40817%')) "+
            "        and paym.t_fiid = fin.t_fiid  "+                                                                        
            "           and kateg.t_object(+)=lpad(pmprop1.t_paymentid,10,0) and kateg.t_objecttype(+)=501 and kateg.t_groupid(+)=117 and kateg.t_validtodate(+)>=to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' )       "+
//             "           and kateg.t_validfromdate(+)<=to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' ) "+
            "           and (kateg.t_validtodate=(select max(kateg1.t_validtodate) from dobjatcor_dbt kateg1 where kateg.t_object=kateg1.t_object and kateg1.t_objecttype=501 and kateg1.t_groupid=117) "+
            "           or kateg.t_validtodate is null) "+
            "           and zn_kat.t_objecttype(+)=501 and zn_kat.t_groupid(+)=117 and zn_kat.t_attrid(+)=kateg.t_attrid "+
            "         and corsch.t_number=abs(pmprop1.t_corschem) "+
            "         and corsch.t_fiid=pmprop1.t_payfiid ";
                                                                                                                                                                                

var sql2211="  select pmprop1.t_paymentid npp,  "+                                                                            
            "         '2.2.1.1' podrazdel,   "+                                                                                
            "         pmrmprop.t_number ndoc,   "+                                                                            
            "         pmrmprop.t_date ddoc,  "+                                                                              
            "         pmprop1.t_transferdate dzn,  "+                                                                        
            "         paym.t_baseamount summa,  "+                                                                            
            "         fin.t_fi_code valuta,  "+                                                                              
            "         pmrmprop.t_payername plat,   "+                                                                          
                  "       paym.t_payeraccount c4_plat, "+
            "         pmrmprop.t_payerbankname b_plat,   "+                                                                    
            "         pmrmprop.t_receivername polu4,  "+                                                                      
            "           paym.t_receiveraccount c4_polu4, "+
            "         pmrmprop.t_receiverbankname b_polu4,  "+                                                                
            "         pmrmprop.t_ground osnov, zn_kat.t_nameobject kat117 "+                                                                            
            "  from dpmprop_dbt pmprop1, dpmprop_dbt pmprop2, dpmpaym_dbt paym, dpmrmprop_dbt pmrmprop, dfininstr_dbt fin, dobjatcor_dbt kateg, dobjattr_dbt zn_kat,     dcorschem_dbt corsch   "+
            "  where     pmprop1.t_transferdate >= to_date ( '"+ot4_data_begin+"', 'DD.MM.RRRR' )  "+                                
            "        and pmprop1.t_transferdate <= to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' ) "+                                
            "        and pmprop1.t_debetcredit = 1 "+                                                                        
            "        and pmprop1.t_group = 1 "+                                                                              
            "        and pmprop2.t_debetcredit = 0 "+                                                                        
            "        and ( ( pmprop2.t_codekind = 3 and pmprop2.t_bankcode = '"+{MFO_Bank}+"' ) "+                                
            "             or ( pmprop2.t_codekind = 6 and pmprop2.t_bankcode = '"+prbb_swift+"' ) )   "+                            
            "        and pmprop1.t_paymentid = pmprop2.t_paymentid   "+                                                        
            "        and paym.t_paymstatus = 32000 "+                                                                        
            "        and paym.t_paymentid = pmprop1.t_paymentid   "+                                                          
            "        and paym.t_paymentid = pmprop2.t_paymentid   "+                                                          
            "        and paym.t_paymentid = pmrmprop.t_paymentid  "+                                                          
            "        and paym.t_fiid > 0  "+                                                                                  
            "        and ( paym.t_payeraccount like '42601%' or paym.t_payeraccount like '40913%' )   "+                      
            "			 and not(( paym.t_payeraccount like '423%' or paym.t_payeraccount like '40807%' or paym.t_payeraccount like '40817%' ) "+
            "			 and (paym.t_receiveraccount like '423%' or paym.t_receiveraccount like '40807%' or paym.t_receiveraccount like '40817%')) "+
            "        and (   corsch.t_account like '30114%' "+                                                        
            "             or corsch.t_account like '30220%' "+                                                        
            "             or corsch.t_account like '30110%' )  "+                                                      
            "        and paym.t_fiid = fin.t_fiid  "+                                                                        
            "           and kateg.t_object(+)=lpad(pmprop1.t_paymentid,10,0) and kateg.t_objecttype(+)=501 and kateg.t_groupid(+)=117 and kateg.t_validtodate(+)>=to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' )       "+
//             "           and kateg.t_validfromdate(+)<=to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' ) "+
            "           and (kateg.t_validtodate=(select max(kateg1.t_validtodate) from dobjatcor_dbt kateg1 where kateg.t_object=kateg1.t_object and kateg1.t_objecttype=501 and kateg1.t_groupid=117) "+
            "           or kateg.t_validtodate is null) "+
            "           and zn_kat.t_objecttype(+)=501 and zn_kat.t_groupid(+)=117 and zn_kat.t_attrid(+)=kateg.t_attrid "+
            "        and corsch.t_number=abs(pmprop1.t_corschem) "+
            "           and corsch.t_fiid=pmprop1.t_payfiid "+ 
            "  order by paym.t_fiid ";      


var sql2212="  select pmprop1.t_paymentid npp,  "+                                                                            
            "         '2.2.1.2' podrazdel,   "+                                                                                
            "         pmrmprop.t_number ndoc,   "+                                                                            
            "         pmrmprop.t_date ddoc,  "+                                                                              
            "         pmprop1.t_transferdate dzn,  "+                                                                        
            "         paym.t_baseamount summa,  "+                                                                            
            "         fin.t_fi_code valuta,  "+                                                                              
            "         pmrmprop.t_payername plat,   "+                                                                          
                  "       paym.t_payeraccount c4_plat, "+
            "         pmrmprop.t_payerbankname b_plat,   "+                                                                    
            "         pmrmprop.t_receivername polu4,  "+                                                                      
            "           paym.t_receiveraccount c4_polu4, "+
            "         pmrmprop.t_receiverbankname b_polu4,  "+                                                                
            "         pmrmprop.t_ground osnov, zn_kat.t_nameobject kat117 "+                                                                            
            "  from dpmprop_dbt pmprop1, dpmprop_dbt pmprop2, dpmpaym_dbt paym, dpmrmprop_dbt pmrmprop, dfininstr_dbt fin, dobjatcor_dbt kateg, dobjattr_dbt zn_kat,     dcorschem_dbt corsch   "+
            "  where     pmprop1.t_transferdate >= to_date ( '"+ot4_data_begin+"', 'DD.MM.RRRR' )  "+                                
            "        and pmprop1.t_transferdate <= to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' ) "+                                
            "        and pmprop1.t_debetcredit = 1 "+                                                                        
            "        and pmprop1.t_group = 1 "+                                                                              
            "        and pmprop2.t_debetcredit = 0 "+                                                                        
            "        and ( ( pmprop2.t_codekind = 3 and pmprop2.t_bankcode = '"+{MFO_Bank}+"' ) "+                                
            "             or ( pmprop2.t_codekind = 6 and pmprop2.t_bankcode = '"+prbb_swift+"' ) )   "+                            
            "        and pmprop1.t_paymentid = pmprop2.t_paymentid   "+                                                        
            "        and paym.t_paymstatus = 32000 "+                                                                        
            "        and paym.t_paymentid = pmprop1.t_paymentid   "+                                                          
            "        and paym.t_paymentid = pmprop2.t_paymentid   "+                                                          
            "        and paym.t_paymentid = pmrmprop.t_paymentid  "+                                                          
            "        and paym.t_fiid = 0  "+                                                                                  
            "        and (   paym.t_payeraccount like '426%'   "+                                                              
            "             or paym.t_payeraccount like '40913%' "+                                                            
            "             or paym.t_payeraccount like '40820%' )  "+                                                          
            "			 and not(( paym.t_payeraccount like '423%' or paym.t_payeraccount like '40807%' or paym.t_payeraccount like '40817%' ) "+
            "			 and (paym.t_receiveraccount like '423%' or paym.t_receiveraccount like '40807%' or paym.t_receiveraccount like '40817%')) "+
            "        and corsch.t_account like '30111%'  "+                                                            
            "        and paym.t_fiid = fin.t_fiid  "+
            "           and kateg.t_object(+)=lpad(pmprop1.t_paymentid,10,0) and kateg.t_objecttype(+)=501 and kateg.t_groupid(+)=117 and kateg.t_validtodate(+)>=to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' )       "+
//             "           and kateg.t_validfromdate(+)<=to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' ) "+
            "           and (kateg.t_validtodate=(select max(kateg1.t_validtodate) from dobjatcor_dbt kateg1 where kateg.t_object=kateg1.t_object and kateg1.t_objecttype=501 and kateg1.t_groupid=117) "+
            "           or kateg.t_validtodate is null) "+
            "           and zn_kat.t_objecttype(+)=501 and zn_kat.t_groupid(+)=117 and zn_kat.t_attrid(+)=kateg.t_attrid "+
            "          and corsch.t_number=abs(pmprop1.t_corschem) "+
            "          and corsch.t_fiid=pmprop1.t_payfiid ";

var sql2221="  select pmprop1.t_paymentid npp,  "+                                                                            
            "         '2.2.2.1' podrazdel,   "+                                                                                
            "         pmrmprop.t_number ndoc,   "+                                                                            
            "         pmrmprop.t_date ddoc,  "+                                                                              
            "         pmprop1.t_transferdate dzn,  "+                                                                        
            "         paym.t_baseamount summa,  "+                                                                            
            "         fin.t_fi_code valuta,  "+                                                                              
            "         pmrmprop.t_payername plat,   "+                                                                          
                  "       paym.t_payeraccount c4_plat, "+
            "         pmrmprop.t_payerbankname b_plat,   "+                                                                    
            "         pmrmprop.t_receivername polu4,  "+                                                                      
            "           paym.t_receiveraccount c4_polu4, "+
            "         pmrmprop.t_receiverbankname b_polu4,  "+                                                                
            "         pmrmprop.t_ground osnov, zn_kat.t_nameobject kat117 "+                                                                            
            "  from dpmprop_dbt pmprop1, dpmprop_dbt pmprop2, dpmpaym_dbt paym, dpmrmprop_dbt pmrmprop, dfininstr_dbt fin, dobjatcor_dbt kateg, dobjattr_dbt zn_kat,     dcorschem_dbt corsch   "+
            "  where     pmprop1.t_transferdate >= to_date ( '"+ot4_data_begin+"', 'DD.MM.RRRR' )  "+                                
            "        and pmprop1.t_transferdate <= to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' ) "+                                
            "        and pmprop1.t_debetcredit = 0 "+                                                                        
            "        and pmprop1.t_group = 1 "+                                                                              
            "        and pmprop2.t_debetcredit = 1 "+                                                                        
            "        and ( ( pmprop2.t_codekind = 3 and pmprop2.t_bankcode = '"+{MFO_Bank}+"' ) "+                                
            "             or ( pmprop2.t_codekind = 6 and pmprop2.t_bankcode = '"+prbb_swift+"' ) )   "+                            
            "        and pmprop1.t_paymentid = pmprop2.t_paymentid   "+                                                        
            "        and paym.t_paymstatus = 32000 "+                                                                        
            "        and paym.t_paymentid = pmprop1.t_paymentid   "+                                                          
            "        and paym.t_paymentid = pmprop2.t_paymentid   "+                                                          
            "        and paym.t_paymentid = pmrmprop.t_paymentid  "+                                                          
            "        and paym.t_fiid > 0  "+                                                                                  
            "        and ( corsch.t_account like '30114%' or corsch.t_account like '30110%' )   "+                      
            "        and (   paym.t_receiveraccount like '42601%' "+                                                        
            "             or paym.t_receiveraccount like '42602%' "+                                                        
            "             or paym.t_receiveraccount like '42603%' "+                                                        
            "             or paym.t_receiveraccount like '42604%' "+                                                        
            "             or paym.t_receiveraccount like '42605%' "+                                                        
            "             or paym.t_receiveraccount like '42606%' "+                                                        
            "             or paym.t_receiveraccount like '40909%' "+                                                        
            "             or paym.t_receiveraccount like '40910%' )  "+                                                      
            "			 and not(( paym.t_payeraccount like '423%' or paym.t_payeraccount like '40807%' or paym.t_payeraccount like '40817%' ) "+
            "			 and (paym.t_receiveraccount like '423%' or paym.t_receiveraccount like '40807%' or paym.t_receiveraccount like '40817%')) "+
            "        and paym.t_fiid = fin.t_fiid  "+                                                                        
            "           and kateg.t_object(+)=lpad(pmprop1.t_paymentid,10,0) and kateg.t_objecttype(+)=501 and kateg.t_groupid(+)=117 and kateg.t_validtodate(+)>=to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' )       "+
//             "           and kateg.t_validfromdate(+)<=to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' ) "+
            "           and (kateg.t_validtodate=(select max(kateg1.t_validtodate) from dobjatcor_dbt kateg1 where kateg.t_object=kateg1.t_object and kateg1.t_objecttype=501 and kateg1.t_groupid=117) "+
            "           or kateg.t_validtodate is null) "+
            "           and zn_kat.t_objecttype(+)=501 and zn_kat.t_groupid(+)=117 and zn_kat.t_attrid(+)=kateg.t_attrid "+
            "          and corsch.t_number=abs(pmprop1.t_corschem) "+
            "         and corsch.t_fiid=pmprop1.t_payfiid "+ 
            "  order by paym.t_fiid ";                                                                                      

var sql2222="  select pmprop1.t_paymentid npp,  "+                                                                            
            "         '2.2.2.2' podrazdel,   "+                                                                                
            "         pmrmprop.t_number ndoc,   "+                                                                            
            "         pmrmprop.t_date ddoc,  "+                                                                              
            "         pmprop1.t_transferdate dzn,  "+                                                                        
            "         paym.t_baseamount summa,  "+                                                                            
            "         fin.t_fi_code valuta,  "+                                                                              
            "         pmrmprop.t_payername plat,   "+                                                                          
                  "       paym.t_payeraccount c4_plat, "+
            "         pmrmprop.t_payerbankname b_plat,   "+                                                                    
            "         pmrmprop.t_receivername polu4,  "+                                                                      
            "           paym.t_receiveraccount c4_polu4, "+
            "         pmrmprop.t_receiverbankname b_polu4,  "+                                                                
            "         pmrmprop.t_ground osnov, zn_kat.t_nameobject kat117 "+                                                                            
            "  from dpmprop_dbt pmprop1, dpmprop_dbt pmprop2, dpmpaym_dbt paym, dpmrmprop_dbt pmrmprop, dfininstr_dbt fin, dobjatcor_dbt kateg, dobjattr_dbt zn_kat,     dcorschem_dbt corsch   "+
            "  where     pmprop1.t_transferdate >= to_date ( '"+ot4_data_begin+"', 'DD.MM.RRRR' )  "+                                
            "        and pmprop1.t_transferdate <= to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' ) "+                                
            "        and pmprop1.t_debetcredit = 0 "+                                                                        
            "        and pmprop1.t_group = 1 "+                                                                              
            "        and pmprop2.t_debetcredit = 1 "+                                                                        
            "        and ( ( pmprop2.t_codekind = 3 and pmprop2.t_bankcode = '"+{MFO_Bank}+"' ) "+                                
            "             or ( pmprop2.t_codekind = 6 and pmprop2.t_bankcode = '"+prbb_swift+"' ) )   "+                            
            "        and pmprop1.t_paymentid = pmprop2.t_paymentid   "+                                                        
            "        and paym.t_paymstatus = 32000 "+                                                                        
            "        and paym.t_paymentid = pmprop1.t_paymentid   "+                                                          
            "        and paym.t_paymentid = pmprop2.t_paymentid   "+                                                          
            "        and paym.t_paymentid = pmrmprop.t_paymentid  "+                                                          
            "        and paym.t_fiid = 0  "+                                                                                  
            "        and corsch.t_account like '30111%'  "+                                                                
            "        and (   paym.t_receiveraccount like '426%'   "+                                                          
            "             or paym.t_receiveraccount like '40910%' "+                                                        
            "             or paym.t_receiveraccount like '40820%' )  "+                                              
            "			 and not(( paym.t_payeraccount like '423%' or paym.t_payeraccount like '40807%' or paym.t_payeraccount like '40817%' ) "+
            "			 and (paym.t_receiveraccount like '423%' or paym.t_receiveraccount like '40807%' or paym.t_receiveraccount like '40817%')) "+
            "        and paym.t_fiid = fin.t_fiid  "+
            "           and kateg.t_object(+)=lpad(pmprop1.t_paymentid,10,0) and kateg.t_objecttype(+)=501 and kateg.t_groupid(+)=117 and kateg.t_validtodate(+)>=to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' )       "+
//             "           and kateg.t_validfromdate(+)<=to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' ) "+
            "           and (kateg.t_validtodate=(select max(kateg1.t_validtodate) from dobjatcor_dbt kateg1 where kateg.t_object=kateg1.t_object and kateg1.t_objecttype=501 and kateg1.t_groupid=117) "+
            "              or kateg.t_validtodate is null) "+
            "           and zn_kat.t_objecttype(+)=501 and zn_kat.t_groupid(+)=117 and zn_kat.t_attrid(+)=kateg.t_attrid "+
            "          and corsch.t_number=abs(pmprop1.t_corschem) "+
            "          and corsch.t_fiid=pmprop1.t_payfiid ";







var sql311="   select * "+                                                                                
           "   from ( select pmprop1.t_paymentid npp, "+                                                  
           "                 '3.1.1' podrazdel, "+                                                        
           "                 pmrmprop.t_number ndoc,  "+                                                    
           "                 pmrmprop.t_date ddoc, "+                                                      
           "                 pmprop1.t_transferdate dzn, "+                                                
           "                 paym.t_baseamount summa, "+                                                  
           "                 fin.t_fi_code valuta, "+                                                      
           "                 pmrmprop.t_payername plat,  "+                                                
                  "       paym.t_payeraccount c4_plat, "+
           "                 pmrmprop.t_payerbankname b_plat,  "+                                          
           "                 pmrmprop.t_receivername polu4, "+                                            
           "            paym.t_receiveraccount c4_polu4, "+
           "                 pmrmprop.t_receiverbankname b_polu4, "+                                      
           "                 pmrmprop.t_ground osnov, zn_kat.t_nameobject kat117 "+                                                    
           "          from dpmprop_dbt pmprop1, "+                                                        
           "               dpmprop_dbt pmprop2, "+                                                        
           "               dpmpaym_dbt paym, "+                                                            
           "               dpmrmprop_dbt pmrmprop, "+                                                      
           "               dfininstr_dbt fin, dobjatcor_dbt kateg, dobjattr_dbt zn_kat,     dcorschem_dbt corsch  "+                                                            
           "          where     pmprop1.t_transferdate >= to_date ( '"+ot4_data_begin+"', 'DD.MM.RRRR' ) "+        
           "                and pmprop1.t_transferdate <= to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' )   "+        
           "                and pmprop1.t_debetcredit = 0   "+                                              
           "                and pmprop1.t_group = 1   "+                                                    
           "                and pmprop2.t_debetcredit = 1   "+                                              
           "                and ( ( pmprop2.t_codekind = 3 and pmprop2.t_bankcode = '"+{MFO_Bank}+"' )   "+      
           "                     or ( pmprop2.t_codekind = 6 and pmprop2.t_bankcode = '"+prbb_swift+"' ) )  "+    
           "                and pmprop1.t_paymentid = pmprop2.t_paymentid  "+                              
           "                and paym.t_paymstatus = 32000   "+                                              
           "                and paym.t_paymentid = pmprop1.t_paymentid  "+                                  
           "                and paym.t_paymentid = pmprop2.t_paymentid  "+                                  
           "                and paym.t_paymentid = pmrmprop.t_paymentid "+                                
           "                and paym.t_fiid > 0 "+                                                        
           "                and ( paym.t_payeraccount like '426%' or paym.t_payeraccount like '40807%' ) "+
           "                and (   corsch.t_account like '30102%'   "+                            
           "                     or corsch.t_account like '30109%'   "+                            
           "                     or corsch.t_account like '30110%' ) "+                          
           "                and (   paym.t_receiveraccount like '42301%'   "+                                
           "                     or paym.t_receiveraccount like '42302%'   "+                                
           "                     or paym.t_receiveraccount like '42303%'   "+                                
           "                     or paym.t_receiveraccount like '42304%'   "+                                
           "                     or paym.t_receiveraccount like '42305%'   "+                                
           "                     or paym.t_receiveraccount like '42306%'   "+                                
           "                     or paym.t_receiveraccount like '40909%'   "+                                
           "                     or paym.t_receiveraccount like '40817%' ) "+                              
           "                and paym.t_fiid = fin.t_fiid "+                                                
             "                    and kateg.t_object(+)=lpad(pmprop1.t_paymentid,10,0) and kateg.t_objecttype(+)=501 and kateg.t_groupid(+)=117 and kateg.t_validtodate(+)>=to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' )       "+
//          "                       and kateg.t_validfromdate(+)<=to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' ) "+
         "                       and (kateg.t_validtodate=(select max(kateg1.t_validtodate) from dobjatcor_dbt kateg1 where kateg.t_object=kateg1.t_object and kateg1.t_objecttype=501 and kateg1.t_groupid=117) "+
          "                           or kateg.t_validtodate is null) "+
         "                       and zn_kat.t_objecttype(+)=501 and zn_kat.t_groupid(+)=117 and zn_kat.t_attrid(+)=kateg.t_attrid "+
          "                   and corsch.t_number=abs(pmprop1.t_corschem) "+
          "                  and corsch.t_fiid=pmprop1.t_payfiid "+ 
           "          union   "+                                                                            
           "          select pmprop1.t_paymentid npp, "+                                                  
           "                 '3.1.1' podrazdel, "+                                                        
           "                 pmrmprop.t_number ndoc,  "+                                                    
           "                 pmrmprop.t_date ddoc, "+                                                      
           "                 pmprop1.t_transferdate dzn, "+                                                
           "                 paym.t_baseamount summa, "+                                                  
           "                 fin.t_fi_code valuta, "+                                                      
           "                 pmrmprop.t_payername plat,  "+                                                
                  "       paym.t_payeraccount c4_plat, "+
           "                 pmrmprop.t_payerbankname b_plat,  "+                                          
           "                 pmrmprop.t_receivername polu4, "+                                            
           "            paym.t_receiveraccount c4_polu4, "+
           "                 pmrmprop.t_receiverbankname b_polu4, "+                                      
           "                 pmrmprop.t_ground osnov, zn_kat.t_nameobject kat117 "+                                                    
           "          from dpmprop_dbt pmprop1, "+                                                        
           "               dpmprop_dbt pmprop2, "+                                                        
           "               dpmpaym_dbt paym, "+                                                            
           "               dpmrmprop_dbt pmrmprop, "+                                                      
           "               dfininstr_dbt fin, dobjatcor_dbt kateg, dobjattr_dbt zn_kat,     dcorschem_dbt corsch  "+                                                            
           "          where     pmprop1.t_transferdate >= to_date ( '"+ot4_data_begin+"', 'DD.MM.RRRR' ) "+        
           "                and pmprop1.t_transferdate <= to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' )   "+        
           "                and pmprop1.t_debetcredit = 0   "+                                              
           "                and pmprop1.t_group = 2   "+                                                    
           "                and pmprop2.t_debetcredit = 1   "+                                              
           "                and pmprop2.t_group = 2   "+                                                    
           "                and pmprop1.t_paymentid = pmprop2.t_paymentid  "+                              
           "                and paym.t_paymstatus = 32000   "+                                              
           "                and paym.t_paymentid = pmprop1.t_paymentid  "+                                  
           "                and paym.t_paymentid = pmprop2.t_paymentid  "+                                  
           "                and paym.t_paymentid = pmrmprop.t_paymentid "+                                
           "                and paym.t_fiid > 0 "+                                                        
           "                and ( paym.t_payeraccount like '426%' or paym.t_payeraccount like '40807%' ) "+
           "                and (   paym.t_receiveraccount like '42301%'   "+                                
           "                     or paym.t_receiveraccount like '42302%'   "+                                
           "                     or paym.t_receiveraccount like '42303%'   "+                                
           "                     or paym.t_receiveraccount like '42304%'   "+                                
           "                     or paym.t_receiveraccount like '42305%'   "+                                
           "                     or paym.t_receiveraccount like '42306%'   "+                                
           "                     or paym.t_receiveraccount like '40909%'   "+                                
           "                     or paym.t_receiveraccount like '40817%' ) "+                              
           "                and paym.t_fiid = fin.t_fiid    "+                                              
            "                       and kateg.t_object(+)=lpad(pmprop1.t_paymentid,10,0) and kateg.t_objecttype(+)=501 and kateg.t_groupid(+)=117 and kateg.t_validtodate(+)>=to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' )       "+
//             "                       and kateg.t_validfromdate(+)<=to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' ) "+
            "                       and (kateg.t_validtodate=(select max(kateg1.t_validtodate) from dobjatcor_dbt kateg1 where kateg.t_object=kateg1.t_object and kateg1.t_objecttype=501 and kateg1.t_groupid=117) "+
            "                             or kateg.t_validtodate is null) "+
            "                       and zn_kat.t_objecttype(+)=501 and zn_kat.t_groupid(+)=117 and zn_kat.t_attrid(+)=kateg.t_attrid "+
           ")  order by valuta   ";                                                                          


var sql312="   select * "+                                                                            
           "   from ( select pmprop1.t_paymentid npp, "+                                              
           "                 '3.1.2' podrazdel, "+                                                    
           "                 pmrmprop.t_number ndoc,  "+                                                
           "                 pmrmprop.t_date ddoc, "+                                                  
           "                 pmprop1.t_transferdate dzn, "+                                            
           "                 paym.t_baseamount summa, "+                                              
           "                 fin.t_fi_code valuta, "+                                                  
           "                 pmrmprop.t_payername plat,  "+                                            
                  "       paym.t_payeraccount c4_plat, "+
           "                 pmrmprop.t_payerbankname b_plat,  "+                                      
           "                 pmrmprop.t_receivername polu4, "+                                        
           "            paym.t_receiveraccount c4_polu4, "+
           "                 pmrmprop.t_receiverbankname b_polu4, "+                                  
           "                 pmrmprop.t_ground osnov, zn_kat.t_nameobject kat117 "+                                                
           "          from dpmprop_dbt pmprop1, "+                                                    
           "               dpmprop_dbt pmprop2, "+                                                    
           "               dpmpaym_dbt paym, "+                                                        
           "               dpmrmprop_dbt pmrmprop, "+                                                  
           "               dfininstr_dbt fin, dobjatcor_dbt kateg, dobjattr_dbt zn_kat,     dcorschem_dbt corsch  "+                                                        
           "          where     pmprop1.t_transferdate >= to_date ( '"+ot4_data_begin+"', 'DD.MM.RRRR' ) "+    
           "                and pmprop1.t_transferdate <= to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' )   "+    
           "                and pmprop1.t_debetcredit = 0   "+                                          
           "                and pmprop1.t_group = 1   "+                                                
           "                and pmprop2.t_debetcredit = 1   "+                                          
           "                and ( ( pmprop2.t_codekind = 3 and pmprop2.t_bankcode = '"+{MFO_Bank}+"' )   "+  
           "                     or ( pmprop2.t_codekind = 6 and pmprop2.t_bankcode = '"+prbb_swift+"' ) )  "+
           "                and pmprop1.t_paymentid = pmprop2.t_paymentid  "+                          
           "                and paym.t_paymstatus = 32000   "+                                          
           "                and paym.t_paymentid = pmprop1.t_paymentid  "+                              
           "                and paym.t_paymentid = pmprop2.t_paymentid  "+                              
           "                and paym.t_paymentid = pmrmprop.t_paymentid "+                            
           "                and paym.t_fiid = 0 "+                                                    
           "                and (   paym.t_payeraccount like '426%'  "+                                
           "                     or paym.t_payeraccount like '40807%'   "+                              
           "                     or paym.t_payeraccount like '40820%' ) "+                            
           "                and (   corsch.t_account like '30102%'   "+                        
           "                     or corsch.t_account like '30109%'   "+                        
           "                     or corsch.t_account like '30110%' ) "+                      
           "                and (   paym.t_receiveraccount like '42301%'   "+                            
           "                     or paym.t_receiveraccount like '42302%'   "+                            
           "                     or paym.t_receiveraccount like '42303%'   "+                            
           "                     or paym.t_receiveraccount like '42304%'   "+                            
           "                     or paym.t_receiveraccount like '42305%'   "+                            
           "                     or paym.t_receiveraccount like '42306%'   "+                            
           "                     or paym.t_receiveraccount like '409%'  "+                              
           "                     or paym.t_receiveraccount like '40817%' ) "+                          
           "                and paym.t_fiid = fin.t_fiid "+                                            
            "                       and kateg.t_object(+)=lpad(pmprop1.t_paymentid,10,0) and kateg.t_objecttype(+)=501 and kateg.t_groupid(+)=117 and kateg.t_validtodate(+)>=to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' )       "+
//             "                       and kateg.t_validfromdate(+)<=to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' ) "+
            "                       and (kateg.t_validtodate=(select max(kateg1.t_validtodate) from dobjatcor_dbt kateg1 where kateg.t_object=kateg1.t_object and kateg1.t_objecttype=501 and kateg1.t_groupid=117) "+
            "                             or kateg.t_validtodate is null) "+
            "                       and zn_kat.t_objecttype(+)=501 and zn_kat.t_groupid(+)=117 and zn_kat.t_attrid(+)=kateg.t_attrid "+
            "                       and corsch.t_number=abs(pmprop1.t_corschem) "+
            "                       and corsch.t_fiid=pmprop1.t_payfiid "+ 
           "          union   "+                                                                        
           "          select pmprop1.t_paymentid npp, "+                                              
           "                 '3.1.2' podrazdel, "+                                                    
           "                 pmrmprop.t_number ndoc,  "+                                                
           "                 pmrmprop.t_date ddoc, "+                                                  
           "                 pmprop1.t_transferdate dzn, "+                                            
           "                 paym.t_baseamount summa, "+                                              
           "                 fin.t_fi_code valuta, "+                                                  
           "                 pmrmprop.t_payername plat,  "+                                            
                  "       paym.t_payeraccount c4_plat, "+
           "                 pmrmprop.t_payerbankname b_plat,  "+                                      
           "                 pmrmprop.t_receivername polu4, "+                                        
           "            paym.t_receiveraccount c4_polu4, "+
           "                 pmrmprop.t_receiverbankname b_polu4, "+                                  
           "                 pmrmprop.t_ground osnov, zn_kat.t_nameobject kat117 "+                                                
           "          from dpmprop_dbt pmprop1, "+                                                    
           "               dpmprop_dbt pmprop2, "+                                                    
           "               dpmpaym_dbt paym, "+                                                        
           "               dpmrmprop_dbt pmrmprop, "+                                                  
           "               dfininstr_dbt fin, dobjatcor_dbt kateg, dobjattr_dbt zn_kat,     dcorschem_dbt corsch  "+                                                        
           "          where     pmprop1.t_transferdate >= to_date ( '"+ot4_data_begin+"', 'DD.MM.RRRR' ) "+    
           "                and pmprop1.t_transferdate <= to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' )   "+    
           "                and pmprop1.t_debetcredit = 0   "+                                          
           "                and pmprop1.t_group = 2   "+                                                
           "                and pmprop2.t_debetcredit = 1   "+                                          
           "                and pmprop2.t_group = 2   "+                                                
           "                and pmprop1.t_paymentid = pmprop2.t_paymentid  "+                          
           "                and paym.t_paymstatus = 32000   "+                                          
           "                and paym.t_paymentid = pmprop1.t_paymentid  "+                              
           "                and paym.t_paymentid = pmprop2.t_paymentid  "+                              
           "                and paym.t_paymentid = pmrmprop.t_paymentid "+                            
           "                and paym.t_fiid = 0 "+                                                    
           "                and (   paym.t_payeraccount like '426%'  "+                                
           "                     or paym.t_payeraccount like '40807%'   "+                              
           "                     or paym.t_payeraccount like '40820%' ) "+                            
           "                and (   paym.t_receiveraccount like '42301%'   "+                            
           "                     or paym.t_receiveraccount like '42302%'   "+                            
           "                     or paym.t_receiveraccount like '42303%'   "+                            
           "                     or paym.t_receiveraccount like '42304%'   "+                            
           "                     or paym.t_receiveraccount like '42305%'   "+                            
           "                     or paym.t_receiveraccount like '42306%'   "+                            
           "                     or paym.t_receiveraccount like '409%'  "+                              
           "                     or paym.t_receiveraccount like '40817%' ) "+                          
           "                and paym.t_fiid = fin.t_fiid    "+
            "                       and kateg.t_object(+)=lpad(pmprop1.t_paymentid,10,0) and kateg.t_objecttype(+)=501 and kateg.t_groupid(+)=117 and kateg.t_validtodate(+)>=to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' )       "+
//             "                       and kateg.t_validfromdate(+)<=to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' ) "+
            "                       and (kateg.t_validtodate=(select max(kateg1.t_validtodate) from dobjatcor_dbt kateg1 where kateg.t_object=kateg1.t_object and kateg1.t_objecttype=501 and kateg1.t_groupid=117) "+
            "                             or kateg.t_validtodate is null) "+
            "                       and zn_kat.t_objecttype(+)=501 and zn_kat.t_groupid(+)=117 and zn_kat.t_attrid(+)=kateg.t_attrid  )";



var sql321="   select * "+                                                                            
           "   from ( select pmprop1.t_paymentid npp, "+                                              
           "                 '3.2.1' podrazdel, "+                                                    
           "                 pmrmprop.t_number ndoc,  "+                                                
           "                 pmrmprop.t_date ddoc, "+                                                  
           "                 pmprop1.t_transferdate dzn, "+                                            
           "                 paym.t_baseamount summa, "+                                              
           "                 fin.t_fi_code valuta, "+                                                  
           "                 pmrmprop.t_payername plat,  "+                                            
                  "       paym.t_payeraccount c4_plat, "+
           "                 pmrmprop.t_payerbankname b_plat,  "+                                      
           "                 pmrmprop.t_receivername polu4, "+                                        
           "            paym.t_receiveraccount c4_polu4, "+
           "                 pmrmprop.t_receiverbankname b_polu4, "+                                  
           "                 pmrmprop.t_ground osnov, zn_kat.t_nameobject kat117 "+                                                
           "          from dpmprop_dbt pmprop1, "+                                                    
           "               dpmprop_dbt pmprop2, "+                                                    
           "               dpmpaym_dbt paym, "+                                                        
           "               dpmrmprop_dbt pmrmprop, "+                                                  
           "               dfininstr_dbt fin, dobjatcor_dbt kateg, dobjattr_dbt zn_kat,     dcorschem_dbt corsch  "+                                                        
           "          where     pmprop1.t_transferdate >= to_date ( '"+ot4_data_begin+"', 'DD.MM.RRRR' ) "+    
           "                and pmprop1.t_transferdate <= to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' )   "+    
           "                and pmprop1.t_debetcredit = 1   "+                                          
           "                and pmprop1.t_group = 1   "+                                                
           "                and pmprop2.t_debetcredit = 0   "+                                          
           "                and ( ( pmprop2.t_codekind = 3 and pmprop2.t_bankcode = '"+{MFO_Bank}+"' )   "+  
           "                     or ( pmprop2.t_codekind = 6 and pmprop2.t_bankcode = '"+prbb_swift+"' ) )  "+
           "                and pmprop1.t_paymentid = pmprop2.t_paymentid  "+                          
           "                and paym.t_paymstatus = 32000   "+                                          
           "                and paym.t_paymentid = pmprop1.t_paymentid  "+                              
           "                and paym.t_paymentid = pmprop2.t_paymentid  "+                              
           "                and paym.t_paymentid = pmrmprop.t_paymentid "+                            
           "                and paym.t_fiid > 0 "+                                                    
           "                and paym.t_payeraccount like '42301%' "+                                  
           "                and (   corsch.t_account like '30102%'   "+                        
           "                     or corsch.t_account like '30109%'   "+                        
           "                     or corsch.t_account like '30110%' ) "+                      
           "                and (   paym.t_receiveraccount like '42601%'   "+                            
           "                     or paym.t_receiveraccount like '42602%'   "+                            
           "                     or paym.t_receiveraccount like '42603%'   "+                            
           "                     or paym.t_receiveraccount like '42604%'   "+                            
           "                     or paym.t_receiveraccount like '42605%'   "+                            
           "                     or paym.t_receiveraccount like '42606%'   "+                            
           "                     or paym.t_receiveraccount like '40807%'   "+                            
           "                     or paym.t_receiveraccount like '40820%' ) "+                          
           "                and paym.t_fiid = fin.t_fiid "+                                            
            "                       and kateg.t_object(+)=lpad(pmprop1.t_paymentid,10,0) and kateg.t_objecttype(+)=501 and kateg.t_groupid(+)=117 and kateg.t_validtodate(+)>=to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' )       "+
//             "                       and kateg.t_validfromdate(+)<=to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' ) "+
            "                       and (kateg.t_validtodate=(select max(kateg1.t_validtodate) from dobjatcor_dbt kateg1 where kateg.t_object=kateg1.t_object and kateg1.t_objecttype=501 and kateg1.t_groupid=117) "+
            "                             or kateg.t_validtodate is null) "+
            "                       and zn_kat.t_objecttype(+)=501 and zn_kat.t_groupid(+)=117 and zn_kat.t_attrid(+)=kateg.t_attrid "+
            "                    and corsch.t_number=abs(pmprop1.t_corschem) "+
            "                       and corsch.t_fiid=pmprop1.t_payfiid "+ 
           "          union   "+                                                                        
           "          select pmprop1.t_paymentid npp, "+                                              
           "                 '3.2.1' podrazdel, "+                                                    
           "                 pmrmprop.t_number ndoc,  "+                                                
           "                 pmrmprop.t_date ddoc, "+                                                  
           "                 pmprop1.t_transferdate dzn, "+                                            
           "                 paym.t_baseamount summa, "+                                              
           "                 fin.t_fi_code valuta, "+                                                  
           "                 pmrmprop.t_payername plat,  "+                                            
                  "       paym.t_payeraccount c4_plat, "+
           "                 pmrmprop.t_payerbankname b_plat,  "+                                      
           "                 pmrmprop.t_receivername polu4, "+                                        
           "            paym.t_receiveraccount c4_polu4, "+
           "                 pmrmprop.t_receiverbankname b_polu4, "+                                  
           "                 pmrmprop.t_ground osnov, zn_kat.t_nameobject kat117 "+                                                
           "          from dpmprop_dbt pmprop1, "+                                                    
           "               dpmprop_dbt pmprop2, "+                                                    
           "               dpmpaym_dbt paym, "+                                                        
           "               dpmrmprop_dbt pmrmprop, "+                                                  
           "               dfininstr_dbt fin, dobjatcor_dbt kateg, dobjattr_dbt zn_kat,     dcorschem_dbt corsch  "+                                                        
           "          where     pmprop1.t_transferdate >= to_date ( '"+ot4_data_begin+"', 'DD.MM.RRRR' ) "+    
           "                and pmprop1.t_transferdate <= to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' )   "+    
           "                and pmprop1.t_debetcredit = 1   "+                                          
           "                and pmprop1.t_group = 2   "+                                                
           "                and pmprop2.t_debetcredit = 0   "+                                          
           "                and pmprop2.t_group = 2   "+                                                
           "                and pmprop1.t_paymentid = pmprop2.t_paymentid  "+                          
           "                and paym.t_paymstatus = 32000   "+                                          
           "                and paym.t_paymentid = pmprop1.t_paymentid  "+                              
           "                and paym.t_paymentid = pmprop2.t_paymentid  "+                              
           "                and paym.t_paymentid = pmrmprop.t_paymentid "+                            
           "                and paym.t_fiid > 0 "+                                                    
           "                and paym.t_payeraccount like '42301%' "+                                  
           "                and (   paym.t_receiveraccount like '42601%'   "+                            
           "                     or paym.t_receiveraccount like '42602%'   "+                            
           "                     or paym.t_receiveraccount like '42603%'   "+                            
           "                     or paym.t_receiveraccount like '42604%'   "+                            
           "                     or paym.t_receiveraccount like '42605%'   "+                            
           "                     or paym.t_receiveraccount like '42606%'   "+                            
           "                     or paym.t_receiveraccount like '40807%'   "+                            
           "                     or paym.t_receiveraccount like '40820%' ) "+                          
           "                and paym.t_fiid = fin.t_fiid    "+
            "                       and kateg.t_object(+)=lpad(pmprop1.t_paymentid,10,0) and kateg.t_objecttype(+)=501 and kateg.t_groupid(+)=117 and kateg.t_validtodate(+)>=to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' )       "+
//             "                       and kateg.t_validfromdate(+)<=to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' ) "+
            "                       and (kateg.t_validtodate=(select max(kateg1.t_validtodate) from dobjatcor_dbt kateg1 where kateg.t_object=kateg1.t_object and kateg1.t_objecttype=501 and kateg1.t_groupid=117) "+
            "                          or kateg.t_validtodate is null) "+
            "                       and zn_kat.t_objecttype(+)=501 and zn_kat.t_groupid(+)=117 and zn_kat.t_attrid(+)=kateg.t_attrid "+
           ")  order by valuta   ";

var sql322="   select * "+                                                                            
           "   from ( select pmprop1.t_paymentid npp, "+                                              
           "                 '3.2.2' podrazdel, "+                                                    
           "                 pmrmprop.t_number ndoc,  "+                                                
           "                 pmrmprop.t_date ddoc, "+                                                  
           "                 pmprop1.t_transferdate dzn, "+                                            
           "                 paym.t_baseamount summa, "+                                              
           "                 fin.t_fi_code valuta, "+                                                  
           "                 pmrmprop.t_payername plat,  "+                                            
                  "       paym.t_payeraccount c4_plat, "+
           "                 pmrmprop.t_payerbankname b_plat,  "+                                      
           "                 pmrmprop.t_receivername polu4, "+                                        
           "            paym.t_receiveraccount c4_polu4, "+
           "                 pmrmprop.t_receiverbankname b_polu4, "+                                  
           "                 pmrmprop.t_ground osnov, zn_kat.t_nameobject kat117 "+                                                
           "          from dpmprop_dbt pmprop1, "+                                                    
           "               dpmprop_dbt pmprop2, "+                                                    
           "               dpmpaym_dbt paym, "+                                                        
           "               dpmrmprop_dbt pmrmprop, "+                                                  
           "               dfininstr_dbt fin, dobjatcor_dbt kateg, dobjattr_dbt zn_kat,     dcorschem_dbt corsch  "+                                                        
           "          where     pmprop1.t_transferdate >= to_date ( '"+ot4_data_begin+"', 'DD.MM.RRRR' ) "+    
           "                and pmprop1.t_transferdate <= to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' )   "+    
           "                and pmprop1.t_debetcredit = 1   "+                                          
           "                and pmprop1.t_group = 1   "+                                                
           "                and pmprop2.t_debetcredit = 0   "+                                          
           "                and ( ( pmprop2.t_codekind = 3 and pmprop2.t_bankcode = '"+{MFO_Bank}+"' )   "+  
           "                     or ( pmprop2.t_codekind = 6 and pmprop2.t_bankcode = '"+prbb_swift+"' ) )  "+
           "                and pmprop1.t_paymentid = pmprop2.t_paymentid  "+                          
           "                and paym.t_paymstatus = 32000   "+                                          
           "                and paym.t_paymentid = pmprop1.t_paymentid  "+                              
           "                and paym.t_paymentid = pmprop2.t_paymentid  "+                              
           "                and paym.t_paymentid = pmrmprop.t_paymentid "+                            
           "                and paym.t_fiid = 0 "+                                                    
           "                and paym.t_payeraccount like '42301%' "+                                  
           "                and (   corsch.t_account like '30102%'   "+                        
           "                     or corsch.t_account like '30109%'   "+                        
           "                     or corsch.t_account like '30110%' ) "+                      
           "                and (   paym.t_receiveraccount like '42601%'   "+                            
           "                     or paym.t_receiveraccount like '42602%'   "+                            
           "                     or paym.t_receiveraccount like '42603%'   "+                            
           "                     or paym.t_receiveraccount like '42604%'   "+                            
           "                     or paym.t_receiveraccount like '42605%'   "+                            
           "                     or paym.t_receiveraccount like '42606%'   "+                            
           "                     or paym.t_receiveraccount like '40807%'   "+                            
           "                     or paym.t_receiveraccount like '40820%' ) "+                          
           "                and paym.t_fiid = fin.t_fiid "+                                            
            "                       and kateg.t_object(+)=lpad(pmprop1.t_paymentid,10,0) and kateg.t_objecttype(+)=501 and kateg.t_groupid(+)=117 and kateg.t_validtodate(+)>=to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' )       "+
//             "                       and kateg.t_validfromdate(+)<=to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' ) "+
            "                       and (kateg.t_validtodate=(select max(kateg1.t_validtodate) from dobjatcor_dbt kateg1 where kateg.t_object=kateg1.t_object and kateg1.t_objecttype=501 and kateg1.t_groupid=117) "+
            "                             or kateg.t_validtodate is null) "+
            "                       and zn_kat.t_objecttype(+)=501 and zn_kat.t_groupid(+)=117 and zn_kat.t_attrid(+)=kateg.t_attrid "+
            "                    and corsch.t_number=abs(pmprop1.t_corschem) "+
            "                       and corsch.t_fiid=pmprop1.t_payfiid "+ 
           "          union   "+                                                                        
           "          select pmprop1.t_paymentid npp, "+                                              
           "                 '3.2.2' podrazdel, "+                                                    
           "                 pmrmprop.t_number ndoc,  "+                                                
           "                 pmrmprop.t_date ddoc, "+                                                  
           "                 pmprop1.t_transferdate dzn, "+                                            
           "                 paym.t_baseamount summa, "+                                              
           "                 fin.t_fi_code valuta, "+                                                  
           "                 pmrmprop.t_payername plat,  "+                                            
                  "       paym.t_payeraccount c4_plat, "+
           "                 pmrmprop.t_payerbankname b_plat,  "+                                      
           "                 pmrmprop.t_receivername polu4, "+                                        
           "            paym.t_receiveraccount c4_polu4, "+
           "                 pmrmprop.t_receiverbankname b_polu4, "+                                  
           "                 pmrmprop.t_ground osnov, zn_kat.t_nameobject kat117 "+                                                
           "          from dpmprop_dbt pmprop1, "+                                                    
           "               dpmprop_dbt pmprop2, "+                                                    
           "               dpmpaym_dbt paym, "+                                                        
           "               dpmrmprop_dbt pmrmprop, "+                                                  
           "               dfininstr_dbt fin, dobjatcor_dbt kateg, dobjattr_dbt zn_kat,     dcorschem_dbt corsch  "+                                                        
           "          where     pmprop1.t_transferdate >= to_date ( '"+ot4_data_begin+"', 'DD.MM.RRRR' ) "+    
           "                and pmprop1.t_transferdate <= to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' )   "+    
           "                and pmprop1.t_debetcredit = 1   "+                                          
           "                and pmprop1.t_group = 2   "+                                                
           "                and pmprop2.t_debetcredit = 0   "+                                          
           "                and pmprop2.t_group = 2   "+                                                
           "                and pmprop1.t_paymentid = pmprop2.t_paymentid  "+                          
           "                and paym.t_paymstatus = 32000   "+                                          
           "                and paym.t_paymentid = pmprop1.t_paymentid  "+                              
           "                and paym.t_paymentid = pmprop2.t_paymentid  "+                              
           "                and paym.t_paymentid = pmrmprop.t_paymentid "+                            
           "                and paym.t_fiid = 0 "+                                                    
           "                and paym.t_payeraccount like '42301%' "+                                  
           "                and (   paym.t_receiveraccount like '42601%'   "+                            
           "                     or paym.t_receiveraccount like '42602%'   "+                            
           "                     or paym.t_receiveraccount like '42603%'   "+                            
           "                     or paym.t_receiveraccount like '42604%'   "+                            
           "                     or paym.t_receiveraccount like '42605%'   "+                            
           "                     or paym.t_receiveraccount like '42606%'   "+                            
           "                     or paym.t_receiveraccount like '40807%'   "+                            
           "                     or paym.t_receiveraccount like '40820%' ) "+                          
           "                and paym.t_fiid = fin.t_fiid    "+
            "                       and kateg.t_object(+)=lpad(pmprop1.t_paymentid,10,0) and kateg.t_objecttype(+)=501 and kateg.t_groupid(+)=117 and kateg.t_validtodate(+)>=to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' )       "+
//             "                       and kateg.t_validfromdate(+)<=to_date ( '"+ot4_data_end+"', 'DD.MM.RRRR' ) "+
            "                       and (kateg.t_validtodate=(select max(kateg1.t_validtodate) from dobjatcor_dbt kateg1 where kateg.t_object=kateg1.t_object and kateg1.t_objecttype=501 and kateg1.t_groupid=117) "+
            "                             or kateg.t_validtodate is null) "+
            "                       and zn_kat.t_objecttype(+)=501 and zn_kat.t_groupid(+)=117 and zn_kat.t_attrid(+)=kateg.t_attrid "+
           ")  order by valuta   ";



//msgbox(PTCK_BIC);
/*
obSheet.Range("a6").Value=PTCK_BIC;
obSheet.Range("a7").Value=TRANSP_SWIFT;
obSheet.Range("a8").Value=PTCK_BICPLUS;
obSheet.Range("a9").Value=PTCK_ALL;
obSheet.Range("a10").Value=PTCK_SWIFT;
obSheet.Range("a11").Value=LLCLASS_SWIFTMSGTYPE;
obSheet.Range("a12").Value={MFO_Bank};
*/
  
  
  //getstring(sql2121);
  out_sql(sql2111); message("   == Выведено: 1 подпункт из 8 =====");
//  debugbreak;
//  getstring(sql2111);
  out_sql(sql2112);message("   == Выведено: 2 подпункт из 8 =====");
  out_sql(sql2121);message("   == Выведено: 3 подпункт из 8 =====");
  debugbreak;
//  getstring       (sql2121);
  out_sql(sql2122);message("   == Выведено: 4 подпункт из 8 =====");
  out_sql(sql2211);message("   == Выведено: 5 подпункт из 8 =====");
  out_sql(sql2212);message("   == Выведено: 6 подпункт из 8 ====="); 
  out_sql(sql2221);message("   == Выведено: 7 подпункт из 8 ====="); 
  out_sql(sql2222); message("   == Выведено: 8 подпункт из 8 =====");
  
//  out_sql(sql311); message("   == Выведено: 9 подпункт из 12 =====");
//  out_sql(sql312); message("   == Выведено: 10 подпункт из 12 =====");
//  out_sql(sql321); message("   == Выведено: 11 подпункт из 12 =====");
//  out_sql(sql322);message("   == Выведено: 12 подпункт из 12 ====="); 
  format_select;
  ex.visible=true;

END;







MACRO EvMacro (dlg, cmd, id, key)

  if (cmd==DLG_INIT)
      message("~F2~ продолжить,  ~ESC~ выход");
     dlg.rec.Date_begin = {curdate};
     dlg.rec.Date_end = {curdate};
     UpdateFields(dlg); 
  end;

  if (cmd == DLG_REMFOCUS)
    if (FldName(dlg,id)=="date_begin")
       if ( dlg.rec.Date_begin > {curdate} )
          MsgBox("Дата начала больше даты текущего операционного дня"); 
          return CM_CANCEL;
       end;

    end;
    if (FldName(dlg,id)=="date_end")
       if ( dlg.rec.Date_end > {curdate} )
          MsgBox("Дата конца больше даты текущего операционного дня"); 
          return CM_CANCEL;
       end;
    end;
    UpdateFields(dlg); 
  end;    

  if (cmd==DLG_KEY)
    if (KEY==KEY_F9)
   return CM_ignore;
    end; //if F9

    if (KEY==KEY_ENTER)
   return CM_ignore;
    end; //if F9

    if (KEY==KEY_F3)
      return CM_ignore;
    end; //if F3

    if (KEY==KEY_F2)
      ot4_data_begin=dlg.rec.Date_begin;
      ot4_data_end=dlg.rec.Date_end;
      if ((ot4_data_begin>{curdate}) or (ot4_data_end>{curdate})) msgbox("значение даты больше текущего опердня"); return CM_ignore;
      else     rabota_time_begin=time();outputinexcel;return CM_SAVE;
      end;
    end; //if F2

    if (KEY==KEY_ESC)
      exit(1);
      return CM_CANCEL;
    end; //if esc

  end; //if DLG_KEY
END; //evmacro








if(rundialog(dlg,"evmacro")) 
  
     println();
      println("                                       ОТЧЕТ СФОРМИРОВАН В EXCEL");
     println();
      println("                                 для продолжения работы нажмите ESC");
      println("                                                                 ");
      println("                                                                   ");
      println("                              время формирования отчета:       ",Time()-rabota_time_begin);
   
end;



