/* ‘®áâ®ï­¨¥ «¨æ¥¢ëå áç¥â®¢                                        */
/*                                                                 */
/*                                                                 */
/*’¨å®¬¨à®¢ €.. 27.05.2009               ‚¥àá¨ï 1.0               */
/* Sokolov R-145922-3 ¬®¤¨ä¨ª æ¨ï - ¢ë¯ãáª ®âç¥â  ¢ Excel 04.02.13 */
/* 05.03.2014 GSP €¤ ¯â æ¨ï 2031                                   */
/* 17.06.2014 DPN I-00494920-2 €¤ ¯â¨à®¢ « ¯®¤ ¢á¥ ¡ ­ª¨           */
/* 02.07.2014 GSP R-375359-2   ¯â¨¬¨§ æ¨ï ¢ë¯®«­¥­¨ï ¨ ¨§¬¥­¥­¨¥  */
/*                             «®£¨ª¨ ¯® ®â¡®àã àã¡«¥¢ëå ®áâ âª®¢  */
/*                             ­  ¢ «îâ­ëå áç¥â å                  */
/* 10.01.2015 Teleshova ‚  à §¡¨¢ª  ¤®«¦­  ¡ëâì áâà®£®©        */
/* 13.01.2015 Chesnokov D.S.   ¨á¯à ¢¨« §  ‘ è¥© ¯® R-526825       */
/* 15.01.2015 DPN I-00544627-2 …á«¨ áâ®¨â £ «ª  "¢ë¢®¤¨âì ¯®ªàëâ¨ï"*/
/*                             -¢¥¢¥¤ãâáï ®áâ âª¨ ¢ àã¡.íª¢        */

import rsbdataset, globals, ª «¥­¤ àì;
var sql, i, pos, sum, fl3, inter, m, /*ints,*/ rest= " ", restf = " ", first, second, data, clos;
var  symbol, symb, balacc, reportdate, flag1, flag3, flag4, flagstr, dprt_v;
var g, val_p, val_a, j, saldo_p, saldo_a, branch, repbal, saldo_aall, saldo_pall, all, branchname, s, maxs;
//Sokolov R-145922-3 
import oralib, bankinter, rsexts, rmcmptl, RSD, "xlc.mac", "getperiodforrep.mac";
import "lib_fg.mac"; //Teleshova 10.01.2015
private var otchet_excel, ob, obSheet, ex, b, e, x, y;
private var all_local_puth:string;
private var fullstr_prn, ch_n; //fullstroka name , áç¥âç¨ª áâà®ª ¢­¨§ã ¯® ¢ «îâ¥

array menu_vibor;
FILE rep_ac() txt write;
private var str : string, m_path, tempFileName, tempFileNameBezPuti;
private var dd:date, tt:time, ii:integer;
//end R-145922-3
array arr;
const  KEY_F1      =315;
const  KEY_F2      =316;
const  KEY_F3      =317;
const KEY_ESC      = 27;
const KEY_SPACE    = 32;
const KEY_ENTER    = 13;

const TEXTDIR_REESTR = "BANK_INI\\™ˆ… €€Œ…’›\\„ˆ…Š’ˆˆ\\TEXTDIR";

record Department ("dp_dep.dbt");
var Fulloutputl, outl, outputl="account.lbr";                    

GetRegistryValue("BANK_INI\\™ˆ… €€Œ…’›\\„ˆ…Š’ˆˆ\\LBRDIR",2,outl);
Fulloutputl = FindPath(outputl, outl);
var dlg = TRecHandler("accbyday", fulloutputl, TRUE); 
GetTxtFileName("AccountbyDay");

/* ©¤¥¬ ¨¬ï ¯® ª®¤ã*/
private macro GetClientNameID(id)
var  sl=" select dep.t_name from  ddp_dep_dbt dep where dep.t_code="+id;
var  DataS=TRsbDataSet(sl);
  if( DataS.moveNext())
    return DataS.name;
  else
    msgbox("‘ã¡ê¥ªâ ­¥ ­ ©¤¥­ ¢ party.dbt");
    return 0;
  end;
END;

private macro strprnv(strarr)
var st=1;
private var strfull_arr;
 while (st<asize(strarr))
  [³      ³                         ³#####################################³                     ³                       ³             ³          ³]
  (strarr(st));
   st=st+1;
 end;
end;


private macro strprn(strarr)
var st=1;
private var stroka_arr;
 while (st<asize(strarr))
  [³                    ³#####################################³                     ³                       ³             ³          ³]
  (strarr(st));
   st=st+1;
 end;
end;



/* ©¤¥¬ ¨¬ï ¯® Partyid*/
private macro GetClientName(id)
//var  sl=string(" select t_name from dparty_dbt t where t.t_PartyID=",id);
//17.06.2014 DPN I-00494920-2
var sl = " SELECT pt.t_name FROM ddp_dep_dbt dep, dparty_dbt pt " +
         " WHERE dep.t_code = " + id + " and PT.T_PARTYID = DEP.T_PARTYID";
var  DataS=TRsbDataSet(sl);
  if( DataS.moveNext())
    return DataS.name;
  else
    if (id !=0)
       msgbox("‘ã¡ê¥ªâ ­¥ ­ ©¤¥­ ¢ party.dbt");
       return 0;
    else
      return "€ €Š à®¡¨§­¥á¡ ­ª";
    end;
  end;
END;

// **************************** Sokolov R-145922-3

private macro Clear(str)        //
   str = STRSUBST(STRSUBST(STRSUBST(str, ";", ","),strfor(13),""),strfor(10), "");
   // ­ ¤® ¢ëª¨­ãâì á¨¬¢®«ë 10 ¨ 13 ¨§ áâà®ª¨,   â ª¦¥ ¢á¥ ; â.ª. íâ® à §¤¥«¨â¥«ì ¢ .csv ä ©« å
   return str;
END;

private macro chekReestrRead(m_name:string, m_status:integer, m_err:integer)  //
	if ((m_status == V_UNDEF) or (m_err != 0))
    	msgbox("è¨¡ª  ¯®«ãç¥­¨ï §­ ç¥­¨ï ­ áâà®©ª¨ à¥¥áâà  " + m_name + " \n à®æ¥¤ãà  GetRegistryValue ¢¥à­ã«  ª®¤ ®è¨¡ª¨ "+m_err);
   		exit(0);
	end;
end;

private macro dayString(m_reestrName:string):string  //
   var m_errCode:integer = NULL;
   var m_statusGetRegistry :integer = NULL;
   var m_zna4enie:string  = NULL;
   if (m_reestrName == "")
      msgbox("à¨ çâ¥­¨¨ à¥¥áâà  ­¥ § ¤ ­  áâà®ª  à¥¥áâà ");
      exit(0)
   end;
   m_statusGetRegistry=GetRegistryValue(m_reestrName, V_STRING, m_zna4enie, m_errCode);
   chekReestrRead(m_reestrName, m_statusGetRegistry, m_errCode);
   return(m_zna4enie);
end;

private macro createUniqueFile()      //£¥­¥à æ¨ï ã­¨¢¥àá «ì­®£® ¨¬¥­¨ ä ©« 
	private var ff:string = "AccByDay_"+{oper}+"_"+date+"_"+time;
	private var file_ext:string = ".txt";
	tempFileName = dayString(TEXTDIR_REESTR);
	tempFileName = tempFileName + "\\" + ff;
	tempFileNameBezPuti = ff;
	tempFileName = StrSubst ( tempFileName, ".", "_" );
	tempFileName = StrSubst ( tempFileName, ":", "_" );
	tempFileName = StrSubst ( tempFileName, " ", "_" );
	tempFileName = tempFileName + file_ext;
	tempFileNameBezPuti = StrSubst ( tempFileNameBezPuti, ".", "_" );
	tempFileNameBezPuti = StrSubst ( tempFileNameBezPuti, ":", "_" );
	tempFileNameBezPuti = StrSubst ( tempFileNameBezPuti, " ", "_" );
	tempFileNameBezPuti = tempFileNameBezPuti + file_ext;
	if (substr(tempFileName,1,2) == "__")
		tempFileName=".."+substr(tempFileName,3)
	end;
end;

private macro copyToMe()     //ª®¯¨àã¥¬ ä ©« ¢à¥¬¥­­ëå ¤ ­­ëå á ‘ ­  â¥à¬¨­ « ¢® ¢à¥¬¥­­ãî ¯ ¯ªã(ª ªãî ¨¬¥­­® § ¢¨á¨â ®â «®ª. ­ áâà.)
   private var m_path: string = "";
   m_path = "$" + tempFileNameBezPuti;
   if (not CopyFile(tempFileNameBezPuti, m_path, TRUE))
     println ("… ‘Œƒ áª®¯¨à®¢ âì ä ©« á á¥à¢¥à  ¯à¨«®¦¥­¨© ­  â¥à¬¨­ «. ¨áå®¤­ë© ä ©«: "+tempFileNameBezPuti+" ä ©« ­ §­ ç¥­¨ï: " + m_path);
   else 
      println ("“‘…˜ áª®¯¨à®¢ ­ ä ©« á á¥à¢¥à  ¯à¨«®¦¥­¨© ­  â¥à¬¨­ «. ¨áå®¤­ë© ä ©«: "+tempFileNameBezPuti+" ä ©« ­ §­ ç¥­¨ï: " + m_path);
      if (not removeFile(tempFileName))
         println("¥ á¬®£ ã¤ «¨âì ä ©« "+tempFileName+" á á¥à¢¥à  ¯à¨«®¦¥­¨©. ­¨ç¥£® áâ è­®£®, ¯à®¤®«¦ ¥¬ à ¡®âã.");
      else
         println("ã¤ «¥­ ä ©« "+tempFileName+" á á¥à¢¥à  ¯à¨«®¦¥­¨©.");
      end;
   end;
end;


// ************************** Sokolov R-145922-3 end

private macro outall();
    repbal=balacc;
    balacc=strsubst(balacc,"*","");
    symb="";

     i=0;
    while (i<strlen(symbol))
        i=i+1;
        if (substr(symbol,i,1)=="A");
          symb=symb+"or acc.t_usertypeaccount like '%€%'";
        elif (substr(symbol,i,1)=="D");
          symb=symb+"or acc.t_usertypeaccount like '%D%'";
        elif (substr(symbol,i,1)=="F");
          symb=symb+"or acc.t_usertypeaccount like '%F%'";
        elif (substr(symbol,i,1)=="G");
          symb=symb+"or acc.t_usertypeaccount like '%G%'";
        elif (substr(symbol,i,1)=="I");
          symb=symb+"or acc.t_usertypeaccount like '%I%'";
        elif (substr(symbol,i,1)=="L");
          symb=symb+"or acc.t_usertypeaccount like '%L%'";
        elif (substr(symbol,i,1)=="N");
          symb=symb+"or acc.t_usertypeaccount like '%N%'";
        elif (substr(symbol,i,1)=="R");
          symb=symb+"or acc.t_usertypeaccount like '%R%'";
        elif (substr(symbol,i,1)=="Q");
          symb=symb+"or acc.t_usertypeaccount like '%Q%'";
        elif (substr(symbol,i,1)=="S");
          symb=symb+"or acc.t_usertypeaccount like '%S%'";
        elif (substr(symbol,i,1)=="U");
          symb=symb+"or acc.t_usertypeaccount like '%U%'";
        elif (substr(symbol,i,1)=="Z");
          symb=symb+"or acc.t_usertypeaccount like '%Z%'";
        elif (substr(symbol,i,1)=="");
          symb=symb+"or acc.t_usertypeaccount like '%%'";
        elif (substr(symbol,i,1)=="ƒ");
          symb=symb+"or acc.t_usertypeaccount like '%ƒ%'";
        elif (substr(symbol,i,1)=="„");
          symb=symb+"or acc.t_usertypeaccount like '%„%'";
        elif (substr(symbol,i,1)=="…");
          symb=symb+"or acc.t_usertypeaccount like '%…%'";
        elif (substr(symbol,i,1)=="ğ");
          symb=symb+"or acc.t_usertypeaccount like '%ğ%'";
        elif (substr(symbol,i,1)=="†");
          symb=symb+"or acc.t_usertypeaccount like '%†%'";
        elif (substr(symbol,i,1)=="‡");
          symb=symb+"or acc.t_usertypeaccount like '%‡%'";
        elif (substr(symbol,i,1)=="‰");
          symb=symb+"or acc.t_usertypeaccount like '%‰%'";
        elif (substr(symbol,i,1)=="Š");
          symb=symb+"or acc.t_usertypeaccount like '%Š%'";
        elif (substr(symbol,i,1)=="‹");
          symb=symb+"or acc.t_usertypeaccount like '%‹%'";
        elif (substr(symbol,i,1)=="Œ");
          symb=symb+"or acc.t_usertypeaccount like '%Œ%'";
        elif (substr(symbol,i,1)=="");
          symb=symb+"or acc.t_usertypeaccount like '%%'";
        elif (substr(symbol,i,1)=="");
          symb=symb+"or acc.t_usertypeaccount like '%%'";
        elif (substr(symbol,i,1)=="");
          symb=symb+"or acc.t_usertypeaccount like '%%'";
        elif (substr(symbol,i,1)=="’");
          symb=symb+"or acc.t_usertypeaccount like '%’%'";
        elif (substr(symbol,i,1)=="“");
          symb=symb+"or acc.t_usertypeaccount like '%“%'";
        elif (substr(symbol,i,1)=="”");
          symb=symb+"or acc.t_usertypeaccount like '%”%'";
        elif (substr(symbol,i,1)=="•");
          symb=symb+"or acc.t_usertypeaccount like '%•%'";
        elif (substr(symbol,i,1)=="–");
          symb=symb+"or acc.t_usertypeaccount like '%–%'";
        elif (substr(symbol,i,1)=="—");
          symb=symb+"or acc.t_usertypeaccount like '%—%'";
        elif (substr(symbol,i,1)=="˜");
          symb=symb+"or acc.t_usertypeaccount like '%˜%'";
        elif (substr(symbol,i,1)=="™");
          symb=symb+"or acc.t_usertypeaccount like '%™%'";
        elif (substr(symbol,i,1)=="›");
          symb=symb+"or acc.t_usertypeaccount like '%›%'";
        elif (substr(symbol,i,1)=="š");
          symb=symb+"or acc.t_usertypeaccount like '%š%'";
        elif (substr(symbol,i,1)=="œ");
          symb=symb+"or acc.t_usertypeaccount like '%œ%'";
        elif (substr(symbol,i,1)=="");
          symb=symb+"or acc.t_usertypeaccount like '%%'";
        elif (substr(symbol,i,1)=="Ÿ");
          symb=symb+"or acc.t_usertypeaccount like '%Ÿ%'";
        else

        end;
    end;

    if (strlen (symb)>0)
      symb=string("AND (",substr(symb,3),")");
    end;

    if (strlen(balacc)>0)
        inter="";
        i=0;
        pos=1;
        while (pos>0)
            m=strlen(balacc);
            while (i<m)
                i=i+1;
                if ((substr(balacc,i,1)!=0) and (substr(balacc,i,1)!=1) and (substr(balacc,i,1)!=2) and (substr(balacc,i,1)!=3)
                  and (substr(balacc,i,1)!=4) and (substr(balacc,i,1)!=5) and (substr(balacc,i,1)!=6) and (substr(balacc,i,1)!=7)
                  and (substr(balacc,i,1)!=8) and (substr(balacc,i,1)!=9))
                  pos =i;
                  if (pos!=1)
                     if (strlen(inter)<1)
                       inter = inter+" (acc.t_balance like '"+substr(balacc,1,pos-1)+"%'"; 
                     else
                       inter=inter+"  or acc.t_balance like '"+substr(balacc,1,pos-1)+"%'";
                     end;
                  end;
                  balacc=substr(balacc, pos+1);
                  i=m+1;
                end;
            end;
            if (i==m)
              pos=0;
            end;
            i=0;
        end;
        if (strlen(inter)>0)
            inter = inter +"  or acc.t_balance like '"+substr(balacc,1)+"%'";; 
        else
            inter = " (acc.t_balance like '"+substr(balacc,1)+"%'"; 
        end;
        inter=inter+")";
     end;
     if (not flag3)
         fl3 = " AND acc.t_type_account NOT LIKE ('%U%') "+
               " AND acc.t_type_account NOT LIKE ('%%') "+
               " AND acc.t_type_account NOT LIKE ('%%')";
     else
         fl3="";
     end;
// 15.01.2015 DPN I-00544627-2
     if (flag1)
        rest = " rsb_account.restac (acc.t_account,acc.t_code_currency, TO_DATE ('"+reportdate+"', 'DD-MM-YYYY'), acc.t_chapter, NULL,0)";
        if (not flag4)
            restf= " AND "+rest+" !=0 ";
        end;
        if(not flag3) 
            restf = restf + "AND substr(acc.t_account,6,3) = '810' ";
        end;
     else
         //Teleshova 10.01.2015
         //if(_bank.is_PRBB)
         if(flag3) // 15.01.2015 DPN I-00544627-2
             rest = "rsb_account.restac (acc.t_account,acc.t_code_currency, TO_DATE ('"+reportdate+"', 'DD-MM-YYYY'), acc.t_chapter, NULL,0)";
         else
             rest = "rsb_account.restac (acc.t_account,acc.t_code_currency, TO_DATE ('"+reportdate+"', 'DD-MM-YYYY'), acc.t_chapter, NULL)";
         end;
         if (not flag4)
            restf="AND "+rest+" !=0 ";
         end;
         restf = restf + " AND acc.t_code_currency <> 0 ";
     end;
     initprogress(-1, "†¤¨â¥, ®â¡¨à îâáï áç¥â ", "†¤¨â¥, ®â¡¨à îâáï áç¥â ");
     useprogress(-1);
     sql = " select /*+FULL (acc)*/ count(*) as cnt "+
           " FROM daccount_dbt acc,  dfininstr_dbt inst "+
           " WHERE  "+inter+
     branch+ fl3+
           " AND inst.t_fiid=acc.t_code_currency "+symb+
           " AND (acc.t_open_close = chr(0) OR acc.t_close_date > TO_DATE ('"+reportdate+"', 'DD-MM-YYYY')) "+
           " AND acc.t_open_date<=TO_DATE ('"+reportdate+"', 'DD-MM-YYYY') " + // ’ƒ ‚ ’‡ …’!!!  ’€Š €‚ˆ‹œ!!!
     restf; 
     first=trsbdataset(sql);
     first.movenext();
     maxs=first.cnt;
     debugbreak;
     sql = " SELECT /*+FULL (acc)*/ inst.t_fi_code , acc.t_balance, acc.t_account, acc.t_nameaccount, "+
             rest+
           "  AS rest, acc.T_KIND_ACCOUNT, "+
           "  acc.t_open_date, acc.t_close_date, acc.t_code_currency "+
           " FROM daccount_dbt acc, dfininstr_dbt inst "+
           " WHERE  "+ inter+ branch+fl3+
           " AND inst.t_fiid=acc.t_code_currency "+symb+
           " AND (acc.t_open_close = chr(0) OR acc.t_close_date > TO_DATE ('"+reportdate+"', 'DD-MM-YYYY')) "+
           " AND acc.t_open_date<=TO_DATE ('"+reportdate+"', 'DD-MM-YYYY') " + // ’ƒ ‚ ’‡ …’!!!  ’€Š €‚ˆ‹œ!!!
             restf+                
           " ORDER BY acc.t_balance, acc.t_code_currency ";
         //getstring(sql);
    first=trsbdataset(sql);
    second=trsbdataset(sql);
    debugbreak;
    remprogress(-1);
    initprogress(int(maxs),"†¤¨â¥,, ¯à®¨§¢®¤¨âáï ®¡à ¡®âª  áç¥â®¢","†¤¨â¥,, ¯à®¨§¢®¤¨âáï ®¡à ¡®âª  áç¥â®¢");
    val_p=0;
    val_a=0;
    j=0;
    saldo_p=0;
    saldo_a=0;
    i=0;
    saldo_pall=0;
    saldo_aall=0;
    all=0;
    s=0;
    if (second.movenext())
    else return 0;
    end;
    s=s+1;
    useprogress(s);
    debugbreak;
     if (flag1)
    [                               ‘®áâ®ï­¨¥ «¨æ¥¢ëå áç¥â®¢ ¯® ¯®¤à §¤¥«¥­¨î ############################
                                                 ­  ¡ « ­á®¢®¬ áç¥â¥ #####, §  ##########

    ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄ¿
    ³  ‹¨æ¥¢®© áç¥â      ³     ¨¬¥­®¢ ­¨¥ áç¥â                ³     ‘ «ì¤® €        ³      ‘ «ì¤®          ³   âªàëâ    ³  ‡ ªàëâ  ³]
    (branchname, second.balance, date(reportdate));
    else
    [                               ‘®áâ®ï­¨¥ «¨æ¥¢ëå áç¥â®¢ ¯® ¯®¤à §¤¥«¥­¨î ############################
                                                 ­  ¡ « ­á®¢®¬ áç¥â¥ #####, §  ##########

    ÚÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄ¿
    ³ ‚ «. ³       ‹¨æ¥¢®© áç¥â      ³     ¨¬¥­®¢ ­¨¥ áç¥â                ³     ‘ «ì¤® €        ³      ‘ «ì¤®          ³   âªàëâ    ³  ‡ ªàëâ  ³]
    (branchname, second.balance, date(reportdate));
    end;   
       while (second.movenext())
        s=s+1;
        useprogress(s);
         if (first.movenext())
         end;
         asize(arr,0);
        strsplit(string(first.nameaccount), arr, 37);
           if (first.close_date=="");
            clos="00.00.0000";
           else
            clos=date(first.close_date);
           end;

         if (flag1)
          /*“‹ˆ*/
          if(first.balance==second.balance)

           if ((first.kind_account == "") and (first.rest > 0))
          [ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄ´                       
           ³####################³#####################################³                     ³#######################³#############³##########³]
           (first.account, arr(0), money(first.rest):a, date(first.open_date), string(clos));
           saldo_p=saldo_p+first.rest;
           saldo_pall=saldo_pall+first.rest;
           strprn(arr);
           else
            [ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄ´                       
             ³####################³#####################################³#####################³                       ³#############³##########³]
           (first.account, arr(0), money(first.rest):a, date(first.open_date), string(clos));
           saldo_a=saldo_a+first.rest;
           saldo_aall=saldo_aall+first.rest;
           strprn(arr);
           end;
            i=i+1;
            all=all+1;
           else
           if ((first.kind_account == "") and (first.rest > 0))
          [ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄ´                       
           ³####################³#####################################³                     ³#######################³#############³##########³]
           (first.account, arr(0), money(first.rest):a, date(first.open_date), string(clos));
           saldo_p=saldo_p+first.rest;
           saldo_pall=saldo_pall+first.rest;
           strprn(arr);
           else
           [ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄ´                       
            ³####################³#####################################³#####################³                       ³#############³##########³]
           (first.account, arr(0), money(first.rest):a, date(first.open_date), string(clos));
           saldo_a=saldo_a+first.rest;
           saldo_aall=saldo_aall+first.rest;
           strprn(arr);
           end;
          i=i+1;
            all=all+1;
          [ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄ´                       
           ³ˆâ®£® ¯® ‘ #####: ª®«¨ç¥áâ¢® áç¥â®¢ #####                ³#####################³#######################³                        ³]
           ( first.balance, int(i), money(saldo_a):a,money(saldo_p):a);

          saldo_p=0;
          saldo_a=0;
          i=0;
    [ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
   
                                        ‘®áâ®ï­¨¥ «¨æ¥¢ëå áç¥â®¢ ¯® ¯®¤à §¤¥«¥­¨î ############################
                                                 ­  ¡ « ­á®¢®¬ áç¥â¥ #####, §  ##########

    ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄ¿
    ³  ‹¨æ¥¢®© áç¥â      ³     ¨¬¥­®¢ ­¨¥ áç¥â                ³     ‘ «ì¤® €        ³      ‘ «ì¤®          ³   âªàëâ    ³  ‡ ªàëâ  ³]
    (branchname, second.balance, date(reportdate));

          end;
     
         else
          /*‚€‹’€*/
            if(first.balance==second.balance)
             if (first.code_currency==second.code_currency)
           if (first.kind_account == "") 
            if (not flagstr)
           [ÃÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄ´];                       
            else
           [ÃÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄ´];                       
            end;
             flagstr=0;
           [³######³#########################³#####################################³                     ³#######################³#############³##########³]
           (first.fi_code, first.account, arr(0), money(first.rest):a, date(first.open_date), string(clos));
           saldo_p=saldo_p+first.rest;
           saldo_pall=saldo_pall+first.rest;
           strprnv(arr);
              val_p=val_p+first.rest;
           else
            if (not flagstr)
           [ÃÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄ´];                       
            else
           [ÃÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄ´];                       
            end;
             flagstr=0;
           [³######³#########################³#####################################³#####################³                       ³#############³##########³]
           (first.fi_code, first.account, arr(0), money(first.rest):a, date(first.open_date), string(clos));
           saldo_a=saldo_a+first.rest;
           saldo_aall=saldo_aall+first.rest;
              val_a=val_a+first.rest;
           strprnv(arr);
           end;
              i=i+1;
            all=all+1;
              j=j+1;
              else
        /*ˆâ®£ ¯® ¢ «îâ¥*/
           if (first.kind_account == "") 
            if (not flagstr)
           [ÃÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄ´];                       
            else
           [ÃÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄ´];                       
            end;
             flagstr=0;
            [³######³#########################³#####################################³                     ³#######################³#############³##########³]
           (first.fi_code, first.account, arr(0), money(first.rest):a, date(first.open_date), string(clos));
           saldo_p=saldo_p+first.rest;
           saldo_pall=saldo_pall+first.rest;
              val_p=val_p+first.rest;
           strprnv(arr);
           else
            if (not flagstr)
           [ÃÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄ´];                       
            else
           [ÃÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄ´];                       
            end;
             flagstr=0;
            [³######³#########################³#####################################³#####################³                       ³#############³##########³]
           (first.fi_code, first.account, arr(0), money(first.rest):a, date(first.open_date), string(clos));
           saldo_a=saldo_a+first.rest;
           saldo_aall=saldo_aall+first.rest;
              val_a=val_a+first.rest;
           strprnv(arr);
           end;
              i=i+1;
            all=all+1;
              j=j+1;
           [ÃÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄ´                       
            ³ˆâ®£® ¢ ¢ «îâ¥ ###: ª®«¨ç¥áâ¢® áç¥â®¢ #####                           ³#####################³#######################³                        ³]
         (first.fi_code, j, money(val_a):a, money(val_p):a);
                val_p=0;
               val_a=0;
               j=0;
               flagstr=1;
               end;
              else
              [############]
              (second.kind_account);
           if (first.kind_account == "")
            if (not flagstr)
           [ÃÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄ´];                       
            else
           [ÃÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄ´];                       
            end;
             flagstr=0;
            [³######³#########################³#####################################³                     ³#######################³#############³##########³]
           (first.fi_code, first.account, arr(0), money(first.rest):a, date(first.open_date), string(clos));
           saldo_p=saldo_p+first.rest;
           saldo_pall=saldo_pall+first.rest;
              val_p=val_p+first.rest;
           strprnv(arr);
           else
            if (not flagstr)
           [ÃÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄ´];                       
            else
           [ÃÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄ´];                       
            end;
             flagstr=0;
            [³######³#########################³#####################################³#####################³                       ³#############³##########³]
           (first.fi_code, first.account, arr(0), money(first.rest):a, date(first.open_date), string(clos));
           saldo_a=saldo_a+first.rest;
           saldo_aall=saldo_aall+first.rest;
              val_a=val_a+first.rest;
           strprnv(arr);
           end;
               i=i+1;
            all=all+1;
               j=j+1;
           [ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´                       
            ³ˆâ®£® ¯® ‘  #####: ª®«¨ç¥áâ¢® áç¥â®¢ #####                           ³#####################³#######################³                        ³]
         (first.balance, i, money(saldo_a):a, money(saldo_p):a);
               val_p=0;
               val_a=0;
               j=0;
             saldo_p=0;
            saldo_a=0;
            i=0;
            flagstr=1;
    [ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ];


    [                               ‘®áâ®ï­¨¥ «¨æ¥¢ëå áç¥â®¢ ¯® ¯®¤à §¤¥«¥­¨î ############################
                                                 ­  ¡ « ­á®¢®¬ áç¥â¥ #####, §  ##########

    ÚÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄ¿
    ³ ‚ «. ³       ‹¨æ¥¢®© áç¥â      ³     ¨¬¥­®¢ ­¨¥ áç¥â                ³     ‘ «ì¤® €        ³      ‘ «ì¤®          ³   âªàëâ    ³  ‡ ªàëâ  ³]
    (branchname, second.balance, date(reportdate));
 
           end;
       end;
     end;
     remprogress(s);
     initprogress(-1,"†¤¨â¥, à áç¨âë¢ îâáï ¨â®£¨","†¤¨â¥, à áç¨âë¢ îâáï ¨â®£¨");
     useprogress(-1);
     /*‡ ¢¥àè¥­¨¥ ®¡à ¡®âª¨*/
    debugbreak;
     if (first.movenext())
     end;
         asize(arr,0);
        strsplit(string(first.nameaccount), arr, 37);
           if (first.close_date=="");
            clos="00.00.0000";
           else
            clos=date(first.close_date);
           end;

     if (flag1)
           if ((first.kind_account == "")and (first.rest > 0))
           [ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄ´                       
            ³####################³#####################################³                     ³#######################³#############³##########³]
           (first.account, arr(0), money(first.rest):a, date(first.open_date), string(clos));
           saldo_p=saldo_p+first.rest;
           saldo_pall=saldo_pall+first.rest;
           strprn(arr);
           else
            [ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄ´                       
             ³####################³#####################################³#####################³                       ³#############³##########³]
           (first.account, arr(0), money(first.rest):a, date(first.open_date), string(clos));
           saldo_a=saldo_a+first.rest;
           saldo_aall=saldo_aall+first.rest;
           strprn(arr);
           end;
        i=i+1;
        all=all+1;
            [ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄ´                       
             ³ˆâ®£® ¯® ‘ #####: ª®«¨ç¥áâ¢® áç¥â®¢ #####                ³#####################³#######################³                        ³]
           ( first.balance, int(i), money(saldo_a):a,money(saldo_p):a);

          saldo_p=0;
          saldo_a=0;
          i=0;
    [ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ];
    saldo_p=0;
    saldo_a=0;
    i=0;
    /*sql = " SELECT   SUM ( "+
             rest+
           ")  AS sum, count(*) as cnt, "+
           "  acc.t_balance "+
        " FROM daccount"+ints+"_dbt acc, daccblnc_dbt bln, dfininstr_dbt inst "+
       " WHERE  acc.t_account = bln.t_account "+
        inter+
        branch+
         fl3+
        " AND inst.t_fiid=acc.t_code_currency "+
        " AND (acc.t_open_close != '‡' OR acc.t_close_date > '"+reportdate+"') "+
        restf+                
       " group BY acc.t_balance ";
        data=trsbdataset(sql);*/
    [                   ‘®áâ®ï­¨¥ «¨æ¥¢ëå áç¥â®¢ ¯® á¯¨áªã áç¥â®¢ §  ##########

    ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
    ³     « ­á®¢ë¥ áç¥â    ³     ‘ «ì¤® €        ³      ‘ «ì¤®          ³    Š®«¨ç¥áâ¢® áç¥â®¢   ³
    ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
    ³ˆâ®£® ¯® á¯¨áªã áç¥â®¢:³                     ³                       ³                        ³
    ³#######################³#####################³#######################³########################³
    ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ]
    (reportdate, repbal, money(saldo_aall):a,money(saldo_pall):a,int(all));                       

    /*   while (data.movenext())
 
       [³####################³#####################³#######################³########################³]
       (money(data.sum), int(data.cnt), data.balance);  
       end;*/
     else
    /*‚€‹’€*/
           if (first.kind_account == "")
            if (not flagstr)
           [ÃÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄ´];                       
            else
           [ÃÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄ´];                       
            end;
             flagstr=0;
            [³######³#########################³#####################################³                     ³#######################³#############³##########³]
           (first.fi_code, first.account, arr(0), money(first.rest):a, date(first.open_date), string(clos));
           saldo_p=saldo_p+first.rest;
           saldo_pall=saldo_pall+first.rest;
              val_p=val_p+first.rest;
           strprnv(arr);
           else
            if (not flagstr)
           [ÃÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄ´];                       
            else
           [ÃÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄ´];                       
            end;
             flagstr=0;
            [³######³#########################³#####################################³#####################³                       ³#############³##########³]
           (first.fi_code, first.account, arr(0), money(first.rest):a, date(first.open_date), string(clos));
           saldo_a=saldo_a+first.rest;
           saldo_aall=saldo_aall+first.rest;
              val_a=val_a+first.rest;
           strprnv(arr);
           end;
        i=i+1;
            all=all+1;
        j=j+1;
           [ÃÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄ´                       
            ³ˆâ®£® ¢ ¢ «îâ¥ ###: ª®«¨ç¥áâ¢® áç¥â®¢ #####                           ³#####################³#######################³                        ³]
         (first.fi_code, j, money(val_a):a, money(val_p):a);
           [ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´                       
            ³ˆâ®£® ¯® ‘  #####: ª®«¨ç¥áâ¢® áç¥â®¢ #####                           ³#####################³#######################³                        ³]
         (first.balance, i, money(saldo_a):a, money(saldo_p):a);
        val_p=0;
        val_a=0;
        j=0;
      saldo_p=0;
      saldo_a=0;
      i=0;
    [ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ];

    sql = " SELECT   SUM ( "+rest+
          ")  AS sum, count(*) as cnt, "+
           "  acc.t_balance, inst.t_fi_code "+
          " FROM daccount_dbt acc, daccblnc_dbt bln, dfininstr_dbt inst "+
          " WHERE  acc.t_account = bln.t_account and"+
          inter+branch+fl3+
          " AND inst.t_fiid=acc.t_code_currency "+
          " AND (acc.t_open_close = chr(0) OR acc.t_close_date > TO_DATE ('"+reportdate+"', 'DD-MM-YYYY')) "+
          restf+                
          " group BY acc.t_balance, inst.t_fi_code ";
    data=trsbdataset(sql);
    [                   ‘®áâ®ï­¨¥ «¨æ¥¢ëå áç¥â®¢ ¯® á¯¨áªã áç¥â®¢ §  ##########

    ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
    ³     « ­á®¢ë¥ áç¥â    ³‚ «îâ ³     ‘ «ì¤® €        ³      ‘ «ì¤®          ³    Š®«¨ç¥áâ¢® áç¥â®¢   ³
    ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
    ³ˆâ®£® ¯® á¯¨áªã áç¥â®¢:³      ³                     ³                       ³                        ³]
    (reportdate);                       
    flagstr=0;
     while (data.movenext())
       if (data.sum<0)
          if (flagstr)
             [ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´];
          end;
          [³#######################³######³#####################³                       ³########################³]
          (int(data.balance), int(data.fi_code), money(data.sum):a, int(data.cnt));
       else
          if (flagstr)
          [ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´];
          end;
          [³#######################³######³                     ³#######################³########################³]
          (int(data.balance), int(data.fi_code), money(data.sum):a, int(data.cnt));
       end;
       flagstr=1;
     end;
     if (flagstr)
       [ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´];
     end;
    [³ˆâ®£® ¯® á¯¨áªã áç¥â®¢: ########################                            ³########################³
     ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ]
    (repbal, int(all));
     end;
      remprogress(-1);
end;

//Sokolov R-145922-3 ¢ë¯¨áª  ¢ Excel ®â¤¥«ì­®© ¬ ªà®äã­ªæ¨¥©
private macro outall_excel();
 //debugbreak;
   createUniqueFile();
   open (rep_ac, tempFileName);
// *********************************************************************************************************************************************
   repbal=balacc;
   balacc=strsubst(balacc,"*","");
   symb="";

   i=0;
   while (i<strlen(symbol))
       i=i+1;
       if (substr(symbol,i,1)=="A");
         symb=symb+"or acc.t_usertypeaccount like '%€%'";
       elif (substr(symbol,i,1)=="D");
         symb=symb+"or acc.t_usertypeaccount like '%D%'";
       elif (substr(symbol,i,1)=="F");
         symb=symb+"or acc.t_usertypeaccount like '%F%'";
       elif (substr(symbol,i,1)=="G");
         symb=symb+"or acc.t_usertypeaccount like '%G%'";
       elif (substr(symbol,i,1)=="I");
         symb=symb+"or acc.t_usertypeaccount like '%I%'";
       elif (substr(symbol,i,1)=="L");
         symb=symb+"or acc.t_usertypeaccount like '%L%'";
       elif (substr(symbol,i,1)=="N");
         symb=symb+"or acc.t_usertypeaccount like '%N%'";
       elif (substr(symbol,i,1)=="R");
         symb=symb+"or acc.t_usertypeaccount like '%R%'";
       elif (substr(symbol,i,1)=="Q");
         symb=symb+"or acc.t_usertypeaccount like '%Q%'";
       elif (substr(symbol,i,1)=="S");
         symb=symb+"or acc.t_usertypeaccount like '%S%'";
       elif (substr(symbol,i,1)=="U");
         symb=symb+"or acc.t_usertypeaccount like '%U%'";
       elif (substr(symbol,i,1)=="Z");
         symb=symb+"or acc.t_usertypeaccount like '%Z%'";
       elif (substr(symbol,i,1)=="");
         symb=symb+"or acc.t_usertypeaccount like '%%'";
       elif (substr(symbol,i,1)=="ƒ");
         symb=symb+"or acc.t_usertypeaccount like '%ƒ%'";
       elif (substr(symbol,i,1)=="„");
         symb=symb+"or acc.t_usertypeaccount like '%„%'";
       elif (substr(symbol,i,1)=="…");
         symb=symb+"or acc.t_usertypeaccount like '%…%'";
       elif (substr(symbol,i,1)=="ğ");
         symb=symb+"or acc.t_usertypeaccount like '%ğ%'";
       elif (substr(symbol,i,1)=="†");
         symb=symb+"or acc.t_usertypeaccount like '%†%'";
       elif (substr(symbol,i,1)=="‡");
         symb=symb+"or acc.t_usertypeaccount like '%‡%'";
       elif (substr(symbol,i,1)=="‰");
         symb=symb+"or acc.t_usertypeaccount like '%‰%'";
       elif (substr(symbol,i,1)=="Š");
         symb=symb+"or acc.t_usertypeaccount like '%Š%'";
       elif (substr(symbol,i,1)=="‹");
         symb=symb+"or acc.t_usertypeaccount like '%‹%'";
       elif (substr(symbol,i,1)=="Œ");
         symb=symb+"or acc.t_usertypeaccount like '%Œ%'";
       elif (substr(symbol,i,1)=="");
         symb=symb+"or acc.t_usertypeaccount like '%%'";
       elif (substr(symbol,i,1)=="");
         symb=symb+"or acc.t_usertypeaccount like '%%'";
       elif (substr(symbol,i,1)=="");
         symb=symb+"or acc.t_usertypeaccount like '%%'";
       elif (substr(symbol,i,1)=="’");
         symb=symb+"or acc.t_usertypeaccount like '%’%'";
       elif (substr(symbol,i,1)=="“");
         symb=symb+"or acc.t_usertypeaccount like '%“%'";
       elif (substr(symbol,i,1)=="”");
         symb=symb+"or acc.t_usertypeaccount like '%”%'";
       elif (substr(symbol,i,1)=="•");
         symb=symb+"or acc.t_usertypeaccount like '%•%'";
       elif (substr(symbol,i,1)=="–");
         symb=symb+"or acc.t_usertypeaccount like '%–%'";
       elif (substr(symbol,i,1)=="—");
         symb=symb+"or acc.t_usertypeaccount like '%—%'";
       elif (substr(symbol,i,1)=="˜");
         symb=symb+"or acc.t_usertypeaccount like '%˜%'";
       elif (substr(symbol,i,1)=="™");
         symb=symb+"or acc.t_usertypeaccount like '%™%'";
       elif (substr(symbol,i,1)=="›");
         symb=symb+"or acc.t_usertypeaccount like '%›%'";
       elif (substr(symbol,i,1)=="š");
         symb=symb+"or acc.t_usertypeaccount like '%š%'";
       elif (substr(symbol,i,1)=="œ");
         symb=symb+"or acc.t_usertypeaccount like '%œ%'";
       elif (substr(symbol,i,1)=="");
         symb=symb+"or acc.t_usertypeaccount like '%%'";
       elif (substr(symbol,i,1)=="Ÿ");
         symb=symb+"or acc.t_usertypeaccount like '%Ÿ%'";
       else

       end;
    end;

    if (strlen (symb)>0)
        symb=string("AND (",substr(symb,3),")");
    end;

if (strlen(balacc)>0)
  inter="";
  i=0;
  pos=1;
  while (pos>0)
   m=strlen(balacc);
    while (i<m)
    i=i+1;
     if ((substr(balacc,i,1)!=0) and (substr(balacc,i,1)!=1) and (substr(balacc,i,1)!=2) and (substr(balacc,i,1)!=3)
        and (substr(balacc,i,1)!=4) and (substr(balacc,i,1)!=5) and (substr(balacc,i,1)!=6) and (substr(balacc,i,1)!=7)
        and (substr(balacc,i,1)!=8) and (substr(balacc,i,1)!=9))
        pos =i;
         if (pos!=1)
           if (strlen(inter)<1)
            inter = inter+" (acc.t_balance like '"+substr(balacc,1,pos-1)+"%'"; 
           else
            inter=inter+"  or acc.t_balance like '"+substr(balacc,1,pos-1)+"%'";
           end;
         end;
        balacc=substr(balacc, pos+1);
        i=m+1;
     end;
    end;
    if (i==m)
    pos=0;
    end;
    i=0;
   end;
   if (strlen(inter)>0)
    inter = inter +"  or acc.t_balance like '"+substr(balacc,1)+"%'";; 
   else
    inter = " (acc.t_balance like '"+substr(balacc,1)+"%'"; 
   end;
    inter=inter+")";
 end;
 if (not flag3)
   fl3 = "     AND acc.t_type_account NOT LIKE ('%U%') "+
         " AND acc.t_type_account NOT LIKE ('%%') "+
         " AND acc.t_type_account NOT LIKE ('%%')";
 else
   fl3="";
 end;
// 15.01.2015 DPN I-00544627-2
     if (flag1)
        rest = " rsb_account.restac (acc.t_account,acc.t_code_currency, TO_DATE ('"+reportdate+"', 'DD-MM-YYYY'), acc.t_chapter, NULL,0)";
        if (not flag4)
            restf= " AND "+rest+" !=0 ";
        end;
        if(not flag3) 
            restf = restf + "AND substr(acc.t_account,6,3) = '810' ";
        end;
     else
         //Teleshova 10.01.2015
         //if(_bank.is_PRBB)
         if(flag3) // 15.01.2015 DPN I-00544627-2
             rest = "rsb_account.restac (acc.t_account,acc.t_code_currency, TO_DATE ('"+reportdate+"', 'DD-MM-YYYY'), acc.t_chapter, NULL,0)";
         else
             rest = "rsb_account.restac (acc.t_account,acc.t_code_currency, TO_DATE ('"+reportdate+"', 'DD-MM-YYYY'), acc.t_chapter, NULL)";
         end;
         if (not flag4)
            restf="AND "+rest+" !=0 ";
         end;
         restf = restf + " AND acc.t_code_currency <> 0 ";
     end;
initprogress(-1, "†¤¨â¥, ®â¡¨à îâáï áç¥â ", "†¤¨â¥, ®â¡¨à îâáï áç¥â ");
useprogress(-1);
sql = " select count(*) as cnt "+
    " FROM daccount_dbt acc,  dfininstr_dbt inst "+
   " WHERE  "+inter+
    branch+
     fl3+
    " AND inst.t_fiid=acc.t_code_currency "+symb+
    " AND (acc.t_open_close = chr(0) OR acc.t_close_date > TO_DATE ('"+reportdate+"', 'DD-MM-YYYY')) "+
    " AND acc.t_open_date<=TO_DATE ('"+reportdate+"', 'DD-MM-YYYY') " + // ’ƒ ‚ ’‡ …’!!!  ’€Š €‚ˆ‹œ!!!
    restf; 
first=trsbdataset(sql);
first.movenext();
maxs=first.cnt;
debugbreak;
sql = " SELECT   inst.t_fi_code , acc.t_balance, acc.t_account, acc.t_nameaccount, "+
         rest+
       "  AS rest, acc.T_KIND_ACCOUNT, "+
       "  acc.t_open_date, acc.t_close_date, acc.t_code_currency "+
    " FROM daccount_dbt acc, dfininstr_dbt inst "+
   " WHERE  "+ inter+
    branch+
     fl3+
    " AND inst.t_fiid=acc.t_code_currency "+symb+
    " AND (acc.t_open_close = chr(0) OR acc.t_close_date > TO_DATE ('"+reportdate+"', 'DD-MM-YYYY')) "+
    " AND acc.t_open_date<=TO_DATE ('"+reportdate+"', 'DD-MM-YYYY') " + // ’ƒ ‚ ’‡ …’!!!  ’€Š €‚ˆ‹œ!!!
    restf+                
" ORDER BY acc.t_balance, acc.t_code_currency ";
//getstring(sql);
first=trsbdataset(sql);
second=trsbdataset(sql);
remprogress(-1);
initprogress(int(maxs),"†¤¨â¥,, ¯à®¨§¢®¤¨âáï ®¡à ¡®âª  áç¥â®¢","†¤¨â¥,, ¯à®¨§¢®¤¨âáï ®¡à ¡®âª  áç¥â®¢");
val_p=0;
val_a=0;
j=0;
saldo_p=0;
saldo_a=0;
i=0;
saldo_pall=0;
saldo_aall=0;
all=0;
s=0;
 if (second.movenext())
 else return 0;
end;
s=s+1;
useprogress(s);
 if (flag1)
 debugbreak;
 str = "‘®áâ®ï­¨¥ «¨æ¥¢ëå áç¥â®¢ ¯® ¯®¤à §¤¥«¥­¨î " + branchname;
   rep_ac.str = ToAnsi (str, true);
   insert (rep_ac);
 str = "­  ¡ « ­á®¢®¬ áç¥â¥ " + second.balance + " §  " + date(reportdate);
   rep_ac.str = ToAnsi (str, true);
   insert (rep_ac);
   str = "‹¨æ¥¢®© áç¥â " + ";" " ¨¬¥­®¢ ­¨¥ áç¥â  " + ";" + "‘ «ì¤® € " + ";" + "‘ «ì¤® " + ";" + "âªàëâ" + ";" + "‡ ªàëâ";
   rep_ac.str = ToAnsi (str, true);
   insert (rep_ac);

else
str = "‘®áâ®ï­¨¥ «¨æ¥¢ëå áç¥â®¢ ¯® ¯®¤à §¤¥«¥­¨î " + branchname;
   rep_ac.str = ToAnsi (str, true);
   insert (rep_ac);
 str = "­  ¡ « ­á®¢®¬ áç¥â¥ " + second.balance + " §  " + date(reportdate);
   rep_ac.str = ToAnsi (str, true);
   insert (rep_ac);
 
str = "‚ «." + ";" + "‹¨æ¥¢®© áç¥â " + ";" " ¨¬¥­®¢ ­¨¥ áç¥â  " + ";" + "‘ «ì¤® € " + ";" + "‘ «ì¤® " + ";" + "âªàëâ" + ";" + "‡ ªàëâ";
   rep_ac.str = ToAnsi (str, true);
   insert (rep_ac);

end;   
   while (second.movenext())
    s=s+1;
    useprogress(s);
     if (first.movenext())
     end;
     asize(arr,0);
    strsplit(string(first.nameaccount), arr, 37);
       if (first.close_date=="");
        clos="00.00.0000";
       else
        clos=date(first.close_date);
       end;
       
     if (flag1)
      /*“‹ˆ*/
      if(first.balance==second.balance)
       if ((first.kind_account == "") and (first.rest > 0))
         str =  first.account + ";" + first.nameaccount + ";" + ";" + money(first.rest) + ";" + date(first.open_date) + ";" + string(clos);
         rep_ac.str = ToAnsi (str, true);
         insert (rep_ac);
     
       saldo_p=saldo_p+first.rest;
       saldo_pall=saldo_pall+first.rest;
      
       
       else
        str = first.account + ";" + first.nameaccount + ";" + money(first.rest) + ";" + " " + ";" + date(first.open_date) + ";" + string(clos);
        rep_ac.str = ToAnsi (str, true);
        insert (rep_ac);
         
       saldo_a=saldo_a+first.rest;
       saldo_aall=saldo_aall+first.rest;
      
       end;
        i=i+1;
        all=all+1;
       else
       if ((first.kind_account == "") and (first.rest > 0))
       str = first.account + ";" + first.nameaccount + ";"  + ";" + money(first.rest) + ";" + date(first.open_date) + ";" + string(clos);
       rep_ac.str = ToAnsi (str, true);
       insert (rep_ac);
      
       saldo_p=saldo_p+first.rest;
       saldo_pall=saldo_pall+first.rest;
       
       else
       str = first.account + ";" + first.nameaccount + ";" + money(first.rest) + ";" + ";" + date(first.open_date) + ";" + string(clos);
       rep_ac.str = ToAnsi (str, true);
       insert (rep_ac);
       
       saldo_a=saldo_a+first.rest;
       saldo_aall=saldo_aall+first.rest;
       
       end;
      i=i+1;
        all=all+1;
        str = "ˆâ®£® ¯® ‘ " +  first.balance + ";" + "Š®«¨ç¥áâ¢® áç¥â®¢ "  +  int(i) + ";" +  money(saldo_a) + ";" + money(saldo_p);
        rep_ac.str = ToAnsi (str, true);
        insert (rep_ac);
      

      saldo_p=0;
      saldo_a=0;
      i=0;
      str = "‘®áâ®ï­¨¥ «¨æ¥¢ëå áç¥â®¢ ¯® ¯®¤à §¤¥«¥­¨î" + branchname;
      rep_ac.str = ToAnsi (str, true);
      insert (rep_ac);
      str = "­  ¡ « ­á®¢®¬ áç¥â¥ " + second.balance + ";" + "§  " + date(reportdate);
      rep_ac.str = ToAnsi (str, true);
      insert (rep_ac);


      end;
     
     else
      /*‚€‹’€*/
        if(first.balance==second.balance)
         if (first.code_currency==second.code_currency)
       if (first.kind_account == "") 
                
        str = first.fi_code + ";" + first.account + ";" + first.nameaccount + ";" + ";" +  money(first.rest) + ";" +  date(first.open_date) + ";" + string(clos);
        rep_ac.str = ToAnsi (str, true);
        insert (rep_ac);
         flagstr=0;
       
       saldo_p=saldo_p+first.rest;
       saldo_pall=saldo_pall+first.rest;
       
          val_p=val_p+first.rest;
       else
        
        str = first.fi_code + ";" + first.account + ";" + first.nameaccount + ";" + money(first.rest) + ";" + ";" + date(first.open_date) + ";" + string(clos);
        rep_ac.str = ToAnsi (str, true);
        insert (rep_ac);
         flagstr=0;
       
       saldo_a=saldo_a+first.rest;
       saldo_aall=saldo_aall+first.rest;
          val_a=val_a+first.rest;
       end;
          i=i+1;
        all=all+1;
          j=j+1;
          else
    /*ˆâ®£ ¯® ¢ «îâ¥*/
       if (first.kind_account == "") 
        
         flagstr=0;
         str = first.fi_code + ";" + first.account + ";" + first.nameaccount + ";" + ";" +  money(first.rest) + ";" +  date(first.open_date) + ";" + string(clos);
         rep_ac.str = ToAnsi (str, true);
         insert (rep_ac);
        
       saldo_p=saldo_p+first.rest;
       saldo_pall=saldo_pall+first.rest;
          val_p=val_p+first.rest;
       
       else
       
         flagstr=0;
         str = first.fi_code + ";" + first.account + ";" + first.nameaccount + ";" + money(first.rest) + ";" + ";" +  date(first.open_date) + ";" + string(clos);
         rep_ac.str = ToAnsi (str, true);
         insert (rep_ac);
        
       saldo_a=saldo_a+first.rest;
       saldo_aall=saldo_aall+first.rest;
          val_a=val_a+first.rest;
       
       end;
          i=i+1;
        all=all+1;
          j=j+1;
          str = "ˆâ®£® ¢ ¢ «îâ¥ "  + first.fi_code + ": " + ";" + "ª®«¨ç¥áâ¢® áç¥â®¢ " + j + ";" + ";" + money(val_a) + ";" + money(val_p);
          rep_ac.str = ToAnsi (str, true);
          insert (rep_ac);
           val_p=0;
           val_a=0;
           j=0;
           flagstr=1;
           end;
          else
          debugbreak; //stop
          str = second.kind_account;
          rep_ac.str = ToAnsi (str, true);
          insert (rep_ac);
          
       if (first.kind_account == "")
        
         flagstr=0;
         str = first.fi_code + ";" + first.account + ";" + first.nameaccount + ";" + ";" + money(first.rest) + ";" + date(first.open_date) + ";" + string(clos);
         rep_ac.str = ToAnsi (str, true);
         insert (rep_ac);
        
       saldo_p=saldo_p+first.rest;
       saldo_pall=saldo_pall+first.rest;
          val_p=val_p+first.rest;
       
       else
       
         flagstr=0;
         str = first.fi_code + ";" +  first.account + ";" + first.nameaccount + ";" +  money(first.rest) + ";" + ";" + date(first.open_date) + ";" + string(clos);
         rep_ac.str = ToAnsi (str, true);
         insert (rep_ac);
        
       saldo_a=saldo_a+first.rest;
       saldo_aall=saldo_aall+first.rest;
          val_a=val_a+first.rest;
       
       end;
           i=i+1;
        all=all+1;
           j=j+1;
           str = "ˆâ®£® ¯® ‘ "  + first.balance + ";" + "ª®«¨ç¥áâ¢® áç¥â®¢: " + i + ";" + ";" + money(saldo_a) + ";" + money(saldo_p);
           rep_ac.str = ToAnsi (str, true);
           insert (rep_ac);
           val_p=0;
           val_a=0;
           j=0;
         saldo_p=0;
        saldo_a=0;
        i=0;
        flagstr=1;

debugbreak;
       str = "‘®áâ®ï­¨¥ «¨æ¥¢ëå áç¥â®¢ ¯® ¯®¤à §¤¥«¥­¨î " + branchname;
       rep_ac.str = ToAnsi (str, true);
       insert (rep_ac);
       str = "­  ¡ « ­á®¢®¬ áç¥â¥ " + second.balance + ", " + "§  " + date(reportdate);
       rep_ac.str = ToAnsi (str, true);
       insert (rep_ac);



 
       end;
   end;
 end;
 remprogress(s);
 initprogress(-1,"†¤¨â¥, à áç¨âë¢ îâáï ¨â®£¨","†¤¨â¥, à áç¨âë¢ îâáï ¨â®£¨");
 useprogress(-1);
 /*‡ ¢¥àè¥­¨¥ ®¡à ¡®âª¨*/
debugbreak;
 if (first.movenext())
 end;
     asize(arr,0);
    strsplit(string(first.nameaccount), arr, 37);
       if (first.close_date=="");
        clos="00.00.0000";
       else
        clos=date(first.close_date);
       end;

 if (flag1)
       if ((first.kind_account == "")and (first.rest > 0))
       str = first.account + ";" + first.nameaccount + ";" + ";" + money(first.rest) + ";" + date(first.open_date) + ";" +  string(clos);
       rep_ac.str = ToAnsi (str, true);
       insert (rep_ac);
       
       saldo_p=saldo_p+first.rest;
       saldo_pall=saldo_pall+first.rest;
       
       else
        str = first.account + ";" + first.nameaccount + ";" + money(first.rest) + ";" + ";" + date(first.open_date) + ";" +  string(clos);
        rep_ac.str = ToAnsi (str, true);
        insert (rep_ac);
        
       saldo_a=saldo_a+first.rest;
       saldo_aall=saldo_aall+first.rest;
       
       end;
    i=i+1;
    all=all+1;
        str = "ˆ’ƒ ¯® ‘ "  + first.balance + ":" + ";" + "Š‹ˆ—…‘’‚ ‘—…’‚: " + int(i) + ";" + money(saldo_a) + ";" + money(saldo_p);
        rep_ac.str = ToAnsi (str, true);
        insert (rep_ac);
        
      saldo_p=0;
      saldo_a=0;
      i=0;
[ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ];
saldo_p=0;
saldo_a=0;
i=0;

str = " ";
rep_ac.str = ToAnsi (str, true);
insert (rep_ac);
str = "‘®áâ®ï­¨¥ «¨æ¥¢ëå áç¥â®¢ ¯® á¯¨áªã áç¥â®¢ §  " + reportdate;
 rep_ac.str = ToAnsi (str, true);
 insert (rep_ac);
 str = " « ­á®¢ë¥ áç¥â " + ";" + "‘ «ì¤® €" + ";" + "‘ «ì¤® " + ";" + "Š®«¨ç¥áâ¢® áç¥â®¢";
 rep_ac.str = ToAnsi (str, true);
 insert (rep_ac);
 str = "ˆâ®£® ¯® á¯¨áªã áç¥â®¢: ";
 rep_ac.str = ToAnsi (str, true);
 insert (rep_ac);
 str = repbal + ";" + money(saldo_aall) + ";" + money(saldo_pall) + ";" + int(all);
 rep_ac.str = ToAnsi (str, true);
 insert (rep_ac);


 else
/*‚€‹’€*/
       if (first.kind_account == "")
         flagstr=0;
         str = first.fi_code + ";" + first.account + ";" + first.nameaccount +";" + ";" + money(first.rest) + ";" + date(first.open_date) + ";" + string(clos);
         rep_ac.str = ToAnsi (str, true);
         insert (rep_ac);
        
       saldo_p=saldo_p+first.rest;
       saldo_pall=saldo_pall+first.rest;
          val_p=val_p+first.rest;
       
       else
        
         flagstr=0;
         str = first.fi_code + ";" +  first.account + ";" + first.nameaccount + ";" + money(first.rest) + ";" + ";" + date(first.open_date)+ ";" + string(clos);
         rep_ac.str = ToAnsi (str, true);
         insert (rep_ac);
        
       saldo_a=saldo_a+first.rest;
       saldo_aall=saldo_aall+first.rest;
          val_a=val_a+first.rest;
       
       end;
    i=i+1;
        all=all+1;
    j=j+1;
        str = "ˆâ®£® ¢ ¢ «îâ¥ " + first.fi_code + ";" + "ª®«¨ç¥áâ¢® áç¥â®¢ " + j + ";" + ";" + money(val_a) + ";" + money(val_p);
        rep_ac.str = ToAnsi (str, true);
        insert (rep_ac);
        str = "ˆâ®£® ¯® ‘ " + first.balance + ";" + " ª®«¨ç¥áâ¢® áç¥â®¢ " + j + ";" + ";" + money(saldo_a) + ";" + money(saldo_p);
        rep_ac.str = ToAnsi (str, true);
        insert (rep_ac);
       
    val_p=0;
    val_a=0;
    j=0;
  saldo_p=0;
  saldo_a=0;
  i=0;
[ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ];

sql = " SELECT   SUM ( "+
         rest+
       ")  AS sum, count(*) as cnt, "+
       "  acc.t_balance, inst.t_fi_code "+
    " FROM daccount_dbt acc, daccblnc_dbt bln, dfininstr_dbt inst "+
   " WHERE  acc.t_account = bln.t_account and"+
    inter+
    branch+
     fl3+
    " AND inst.t_fiid=acc.t_code_currency "+
    " AND (acc.t_open_close = chr(0) OR acc.t_close_date > TO_DATE ('"+reportdate+"', 'DD-MM-YYYY')) "+
    restf+                
" group BY acc.t_balance, inst.t_fi_code ";
data=trsbdataset(sql);
str = " ";
rep_ac.str = ToAnsi (str, true);
insert (rep_ac);
str = "‘®áâ®ï­¨¥ «¨æ¥¢ëå áç¥â®¢ ¯® á¯¨áªã áç¥â®¢ §  " + reportdate;
rep_ac.str = ToAnsi (str, true);
insert (rep_ac);
str = " « ­á®¢ë¥ áç¥â  " + ";" + "‚ «îâ  " + ";" + "‘ «ì¤® €" + ";" + "‘ «ì¤® " + ";" + "Š®«¨ç¥áâ¢® áç¥â®¢";
rep_ac.str = ToAnsi (str, true);
insert (rep_ac);
str = "ˆâ®£® ¯® á¯¨áªã áç¥â®¢: ";
rep_ac.str = ToAnsi (str, true);
insert (rep_ac);

                     
flagstr=0;
ch_n = 0;
 while (data.movenext())
 ch_n = ch_n + 1;
   if (data.sum<0)
   debugbreak;
      
      str = int(data.balance) + ";" + int(data.fi_code) + ";" + money(data.sum) + ";"+ ";" + int(data.cnt);
      rep_ac.str = ToAnsi (str, true);
      insert (rep_ac);
      
   else
      
      str = int(data.balance) + ";" + int(data.fi_code) + ";" + ";" + money(data.sum) + ";" + int(data.cnt);
      rep_ac.str = ToAnsi (str, true);
      insert (rep_ac);
      
   end;
   flagstr=1;
 end;
 
 str = "ˆâ®£® ¯® á¯¨áªã áç¥â®¢: " + repbal + ";" + ";" + ";" + ";" + int(all);
 rep_ac.str = ToAnsi (str, true);
 insert (rep_ac);

 end;
  remprogress(-1);

   b = 3;
   if (flag1)
    e = int(all) + 4;
    else
    e = int(all) + ch_n + 2;
   end;
   close(rep_ac);
   copyToMe();
   ob = CreateObject ("rsax","TRsAxServer","RsAxServer",false);
   ex = ob.CreateComObject ("Excel.Application");
   if (not(GetFileInfo("$"+tempFileNameBezPuti,@dd,@tt,@ii,@all_local_puth))); //all_local_puth- â® çâ® ­ ¤®. ¯®«­ë© ¯ãâì  ¡á®«îâ­ë© «®ª «ì­ë©
      msgbox("­¥ ¬®£ã ­ ©â¨ ­  «®ª «ì­®¬ ¤¨áª¥ ä ©« "+tempFileNameBezPuti+"          \n ®áâ ­ ¢«¨¢ îáì");
    exit(0);
   end;
  all_local_puth = SUBSTR(all_local_puth, 2);
   
   var aw=tarray;
   var w1=tarray;
   var w2=tarray;
   var w3=tarray;
   var w4=tarray;
   var w5=tarray;
   var w6=tarray;
   var w7=tarray;
   var w8=tarray;
   var w9=tarray;

   w1(0)=1; w1(1)=2; //ä®à¬ â áâ®«¡æ  - â¥ªáâ
   w2(0)=2; w2(1)=2; //ä®à¬ â áâ®«¡æ  - General
   w3(0)=3; w3(1)=2;//ä®à¬ â áâ®«¡æ  - General
   w4(0)=4; w4(1)=1;//ä®à¬ â áâ®«¡æ  - General
   w5(0)=5; w5(1)=2;//ä®à¬ â áâ®«¡æ  - General
   w6(0)=6; w6(1)=2;//ä®à¬ â áâ®«¡æ  - General
   w7(0)=7; w7(1)=1;//ä®à¬ â áâ®«¡æ  - General
   w8(0)=8; w8(1)=1;//ä®à¬ â áâ®«¡æ  - â¥ªáâ
   w9(0)=9; w9(1)=1;//ä®à¬ â áâ®«¡æ  - 
   
   aw(0)=w1;
   aw(1)=w2;
   aw(2)=w3;
   aw(3)=w4;
   aw(4)=w5;
   aw(5)=w6;
   aw(6)=w7;
   aw(7)=w8;
   aw(8)=w8;

	aw.MarshalByVal =true; // à ¡®â ¥â â®«ìª® â ª. ¯¥à¥¤ ç  ¯® §­ ç¥­¨î ç¥à¥§ @aw ¢ë§ë¢ ¥â ®è¨¡ªã
	w1.MarshalByVal =true;
	w2.MarshalByVal =true;
	w3.MarshalByVal =true;
	w4.MarshalByVal =true;
	w5.MarshalByVal =true;
	w6.MarshalByVal =true;
	w7.MarshalByVal =true;
	w8.MarshalByVal =true;
   w9.MarshalByVal =true;
   
    ex.Workbooks.opentext(all_local_puth,1251,1,1,-4142,false,false,true,false,false,false,";",aw,1,"."," ",true,true);
   //var format_str:string = "# ##0" + ex.International(3) + "00";
   private var m_range:string="a"+b+":h"+e; //¢ë¤¥«¨âì £à ­¨æë ïç¥¥ª
   private var m_range_niz;
   obSheet = ex.Sheets(1);
   ex.Sheets(1).Range("A:A").ColumnWidth=24;
   ex.Sheets(1).Range("B:B").ColumnWidth=36;
   ex.Sheets(1).Range("C:C").ColumnWidth=23;
   ex.Sheets(1).Range("D:D").ColumnWidth=23;
   ex.Sheets(1).Range("E:E").ColumnWidth=23;
   ex.Sheets(1).Range("F:F").ColumnWidth=22;
   ex.Sheets(1).Range("G:G").ColumnWidth=20;
   ex.Sheets(1).Range("1:1").RowHeight=25;
   ex.Sheets(1).Range("2:2").RowHeight=25;
   ex.Sheets(1).Rows("3:3").RowHeight=35;
   ex.Sheets(1).Range("A1:E1").MergeCells=true;
   ex.Sheets(1).Range("A2:E2").MergeCells=true;
   ex.Sheets(1).Range("A:G").WrapText=True;
   ex.Sheets(1).Rows("1:2").VerticalAlignment = 2;
   ex.Sheets(1).Rows("3:3").VerticalAlignment = 2;
   ex.Sheets(1).Range("A:G").HorizontalAlignment = 3;
   if (flag1)
       ex.Sheets(1).Range("A3:F3").interior.color = 4035000;
       m_range = "a"+b+":f"+e; // ¯¥à¥¤¥« âì
       x = e + 3;
       
       m_range_niz = "a" + x + ":d" + (x + 2);
       obSheet.Range(m_range_niz).Borders.Weight = 2;
   else
       x = e + 2;
       y = x + 3;
       m_range = "a" + b + ":g" + (e + 2);
       debugbreak;
       ch_n = y + ch_n + 2;
       m_range_niz = "a" + y + ":e" + ch_n;
       obSheet.Range(m_range_niz).Borders.Weight = 2;
       ex.Sheets(1).Range("A3:G3").interior.color = 4035000;
   end;
   ex.Sheets(1).Range("A:G").Font.Name = "Arial";
   ex.Sheets(1).Range("A:G").Font.Size = 10;
   
   
   private var m_cells:string; //®¡ê¥¤¨­¥­¨¥ ïç¥¥ª
   if (flag1)
   x = e + 2;
   y = x + 1;
   m_cells = "a" +x+ ":b" +x;
    ex.Sheets(1).Range(m_cells).MergeCells = true;
    else
     
   end;
   //ex.Sheets(1).Range("D:G").NumberFormat = format_str;
  //if (flag1)
   
   //
   obSheet.Range(m_range).Borders.Weight = 2;
  //end;
 
   ex.Visible = true;
 end; //end R-145922-3  
 /*¡à ¡®âç¨ª ¤¨ «®£®¢®© ¯ ­¥«¨ ¢¢®¤  ¨áå®¤­ëå ¤ ­­ëå ¤«ï ¯¥ç â¨*/
MACRO Event (dlg, cmd, id, key) 

   var const_mess = "~F2~ à®¤®«¦¨âì ~ESC~ ‚ëå®¤ ";
   var const_mess2 = "~F2~ à®¤®«¦¨âì ~SPACE~ ~ESC~ ‚ëå®¤ ";
   array symbolname;
   symbolname(0)="A Š áá ";
   symbolname(1)="D Š áá  ŠŠ ‡ à¥ç¥­áª¨©";
   symbolname(2)="F Š áá  ŠŠ ¥à¬áª¨© 1";
   symbolname(3)="G Š áá  ŠŠ ˆàªãâáª¨© 1";
   symbolname(4)="I Š áá  ŠŠ ¥à¬áª¨© 2";
   symbolname(5)="L Š áá  ŠŠ „¢®àï­áª¨©";
   symbolname(6)="N Š áá  ŠŠ ˆàªãâáª¨© 2";
   symbolname(7)="R Š áá  ŠŠ ƒ £ à¨­áª¨©";
   symbolname(8)="Q Š áá  ŠŠ ‘¥­­®©";
   symbolname(9)="S Š áá  ŠŠ ¥à¥§­¨ª¨ 1";
   symbolname(10)="U Š áá  ŠŠ ¥à¥§­¨ª¨ 2";
   symbolname(11)="Z Š áá  ŠŠ ”àã­§¥­áª¨©";
   symbolname(12)=" ãå£ «â¥à¨ï";
   symbolname(13)="ƒ ¥§¥à¢";
   symbolname(14)="„ Œ¥¦¡ ­ª";
   symbolname(15)="… Š áá  –Œ’";
   symbolname(16)="ğ ˆ­â¥à­¥â ¡ ­ª";
   symbolname(17)="† ‚Š“";
   symbolname(18)="‡ „¥¯®§¨âë îà.«¨æ";
   symbolname(19)="‰ Š áá  ’¢¥àáª®©";
   symbolname(20)="Š Š";
   symbolname(21)="‹ ƒŒ";
   symbolname(22)="Œ Š áá  ‘ ¤®¢®-Šã¤à¨­áª¨©";
   symbolname(23)=" ®§­¨ç­ë¥ ä¨­ ­á. “á«ã£¨";
   symbolname(24)=" „¥¯®§¨âë ä¨§.«¨æ";
   symbolname(25)=" ‚¥ªá¥«ì­ë© á¥ªâ®à";
   symbolname(26)="’ Š-ª ®ä¨á ’ã«ìáª¨©";
   symbolname(27)="“ „ '–¥­âà «ì­ë©'";
   symbolname(28)="”  Š áá  ¥âà®¢áª¨©";
   symbolname(29)="• Š áá  „/® '€¢â®§ ¢®¤áª¨©'";
   symbolname(30)="– –¥­­ë¥ ¡ã¬ £¨";
   symbolname(31)="— Š áá  ŠŠ ’î¬¥­áª¨© 1";
   symbolname(32)="˜ Š áá  ŠŠ „§¥à¦¨­áª¨©";
   symbolname(33)="™ ¥â®à£®¢ë¥ ®¯¥à æ  ";
   symbolname(34)="› Š áá  ŠŠ Šà á­® à¬¥©áª¨©";
   symbolname(35)="š Š‚Š“ 4";
   symbolname(36)="œ Š áá  ’®«áâ®¢áª¨©";
   symbolname(37)=" Š‚Š“ ü 1 (ã¤®¢ª¨­ )";
   symbolname(38)="Ÿ Š áá  ®¢®¤ ­¨«®¢áª¨©";

   /*¥à¢®­ ç «ì­ ï ¨­¨æ¨ «¨§ æ¨ï ¯®«¥©*/
   if(cmd == DLG_INIT)
      dprt_v = 0;
      dlg.rec.F1  = "X";
      dlg.rec.F2  = "";
      dlg.rec.F3  = "";
      dlg.rec.F4  = "";
      dlg.rec.balacc="";
      dlg.rec.reportDate = {curDate};
      dlg.rec.Symbol = "";
      dlg.rec.Branch = getclientnameid({operdprt});
      dlg.rec.branchname = GetClientName({operdprt});
      UpdateFields(dlg); 
   end;
   
   /*“áâ ­®¢ª  ¯®¤áª §®ª ¢ áâà®ª¥ á®áâ®ï­¨ï*/
   if (cmd==DLG_SETFOCUS)
     if ((FldName(dlg,id)=="F1") or (FldName(dlg,id)=="F2") or (FldName(dlg,id)=="F3") or (FldName(dlg,id)=="F4"))
       message(const_mess2);
     elif (FldName(dlg,id)=="ReportDate")
       message(" ~F3~ ‚ë¡®à ¤ âë ¨§ ª «¥­¤ àï "+const_mess);
     elif (FldName(dlg,id)=="Branch")
       message(" ~F3~ ‚ë¡®à ä¨«¨ «  "+const_mess);
     elif (FldName(dlg,id)=="Balacc")
       message(const_mess);
    end;
   end;
   
   if (cmd == DLG_REMFOCUS)
     /*à®¢¥àª  ª®àà¥ªâ­®áâ¨ ¤ â ®âç¥â */
     if (FldName(dlg,id) == "ReportDate")
       if ( dlg.rec.reportDate > {curdate} )
         MsgBox("„ â  ­ ç «  ¯¥à¨®¤  ­¥ ¬®¦¥â ¡ëâì ¡®«ìè¥ ¤ âë â¥ªãé¥£® ®¯¥à æ¨®­­®£® ¤­ï");
        return CM_CANCEL;
       end;
     end;
      UpdateFields(dlg); 
   end;

   if (cmd == DLG_KEY)
     /*‚ëå®¤ ¨§ ¤¨ «®£®¢®£® ®ª­  ä®à¬¨à®¢ ­¨ï ®âç¥â */
     if (KEY == KEY_ESC)
       return exit(1);//CM_CANCEL;
     /*‚ë¡®à ¤ ­­ëå ¨§ á¯¨áª */
     elif ( KEY == KEY_F3)
        /*‚ë¡®à ¤ âë ¨§ ª «¥­¤ àï*/
        if (FldName(dlg,id) == "ReportDate")
          dlg.rec.reportdate = GetDateByCalendar ({curDate});
        end;
        if (FldName(dlg,id) == "Branch")
           if (ListDepartment (Department))
              dlg.rec.branch = Department.name;
              dprt_v = department.code;
              dlg.rec.branchname = GetClientName(Department.code); //17.06.2014 DPN I-00494920-2
              message(" ~F3~ ‘¯¨á®ª ¯®¤à §¤¥«¥­¨© "+const_mess);
              UpdateFields(dlg);
           end;
        end;

        if (FldName(dlg,id) == "Symbol")
            g=menu(symbolname,"‘¨¬¢®« ®âç¥â­®áâ¨ áç¥â ");
            if (g==0)  
              dlg.rec.symbol = string(dlg.rec.symbol,"A");
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);
            elif (g==1)  
              dlg.rec.symbol = string(dlg.rec.symbol,"D");
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);
            elif (g==2)  
              dlg.rec.symbol = string(dlg.rec.symbol,"F");
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);
            elif (g==3)  
              dlg.rec.symbol = string(dlg.rec.symbol,"G");
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);
            elif (g==4)  
              dlg.rec.symbol = string(dlg.rec.symbol,"I");
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);
            elif (g==5)  
              dlg.rec.symbol = string(dlg.rec.symbol,"L");
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);
            elif (g==6)  
              dlg.rec.symbol = string(dlg.rec.symbol,"N");
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);
            elif (g==7)  
              dlg.rec.symbol = string(dlg.rec.symbol,"R");
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);
            elif (g==8)  
              dlg.rec.symbol = string(dlg.rec.symbol,"Q");
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);
            elif (g==9)  
              dlg.rec.symbol = string(dlg.rec.symbol,"S");
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);
            elif (g==10)  
              dlg.rec.symbol = string(dlg.rec.symbol,"U");
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);
            elif (g==11)  
              dlg.rec.symbol = string(dlg.rec.symbol,"Z");
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);
            elif (g==12)  
              dlg.rec.symbol = string(dlg.rec.symbol,"");
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);
            elif (g==13)  
              dlg.rec.symbol = string(dlg.rec.symbol,"ƒ");
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);
            elif (g==14)  
              dlg.rec.symbol = string(dlg.rec.symbol,"„");
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);
            elif (g==15)  
              dlg.rec.symbol = string(dlg.rec.symbol,"…");
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);
            elif (g==16)  
              dlg.rec.symbol = string(dlg.rec.symbol,"ğ");
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);
            elif (g==17)  
              dlg.rec.symbol = string(dlg.rec.symbol,"†");
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);
            elif (g==18)  
              dlg.rec.symbol = string(dlg.rec.symbol,"‡");
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);
            elif (g==19)  
              dlg.rec.symbol = string(dlg.rec.symbol,"‰");
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);
            elif (g==20)  
              dlg.rec.symbol = string(dlg.rec.symbol,"Š");
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);
            elif (g==21)  
              dlg.rec.symbol = string(dlg.rec.symbol,"‹");
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);
            elif (g==22)  
              dlg.rec.symbol = string(dlg.rec.symbol,"Œ");
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);
            elif (g==23)  
              dlg.rec.symbol = string(dlg.rec.symbol,"");
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);
            elif (g==24)  
              dlg.rec.symbol = string(dlg.rec.symbol,"");
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);
            elif (g==25)  
              dlg.rec.symbol = string(dlg.rec.symbol,"");
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);
            elif (g==26)  
              dlg.rec.symbol = string(dlg.rec.symbol,"’");
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);
            elif (g==27)  
              dlg.rec.symbol = string(dlg.rec.symbol,"“");
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);
            elif (g==28)  
              dlg.rec.symbol = string(dlg.rec.symbol,"”");
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);
            elif (g==29)  
              dlg.rec.symbol = string(dlg.rec.symbol,"•");
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);
            elif (g==30)  
              dlg.rec.symbol = string(dlg.rec.symbol,"–");
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);
            elif (g==31)  
              dlg.rec.symbol = string(dlg.rec.symbol,"—");
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);
            elif (g==32)  
              dlg.rec.symbol = string(dlg.rec.symbol,"˜");
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);
            elif (g==33)  
              dlg.rec.symbol = string(dlg.rec.symbol,"™");
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);
            elif (g==34)  
              dlg.rec.symbol = string(dlg.rec.symbol,"›");
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);
            elif (g==35)  
              dlg.rec.symbol = string(dlg.rec.symbol,"š");
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);
            elif (g==36)  
              dlg.rec.symbol = string(dlg.rec.symbol,"œ");
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);
            elif (g==37)  
              dlg.rec.symbol = string(dlg.rec.symbol,"");
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);
            elif (g==38)  
              dlg.rec.symbol = string(dlg.rec.symbol,"Ÿ");
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);
            else
              message(" ~F3~ ‘¯¨á®ª â¨¯®¢ á¨¬¢®«®¢ áç¥â®¢ "+const_mess);
              UpdateFields(dlg);

            end;
        end;

        
     elif (KEY == KEY_SPACE)
          /*‘¡à®á ãáâ ­®¢®ª ¢ ¯®«¥ ®ä¨á ¡ ­ª */
           if (FldName(dlg,id) == "F1") 
            if (dlg.rec.f1=="")
            dlg.rec.f1="X";
            dlg.rec.f2="";
            UpdateFields(dlg);
            else
            dlg.rec.f1="";
            dlg.rec.f2="X";
             UpdateFields(dlg);
            end;
           elif (FldName(dlg,id) == "Allb") 
            if (dlg.rec.allb=="")
            dlg.rec.allb="X";
            UpdateFields(dlg);
            else
            dlg.rec.allb="";
            UpdateFields(dlg);
            end;
           elif (FldName(dlg,id) == "Symbol")
              dlg.rec.symbol = "";
           elif (FldName(dlg,id) == "F2")
            if (dlg.rec.f2=="")
            dlg.rec.f2="X";
            dlg.rec.f1="";
            UpdateFields(dlg);
            else
            dlg.rec.f2="";
            dlg.rec.f1="X";
            UpdateFields(dlg);
            end;
           elif (FldName(dlg,id) == "f3") 
            if (dlg.rec.f3=="")
            dlg.rec.f3="X";
            UpdateFields(dlg);
            else
            dlg.rec.f3="";
             UpdateFields(dlg);
            end;
           elif (FldName(dlg,id) == "f4")
            if (dlg.rec.f4=="")
            dlg.rec.f4="X";
            UpdateFields(dlg);
            else
            dlg.rec.f4="";
            UpdateFields(dlg);
            end;
           end;

     elif (( KEY == KEY_F2 ) or ( KEY == KEY_ENTER ))        //à®¢¥àª¨ ¯à¨ ¢¢®¤¥
         //Sokolov  ¢ë¯ãáª ¢ ä®à¬ â¥ Excel R-145922-3
          menu_vibor (0) = "¡ëç­ë© ä®à¬ â";
          menu_vibor (1) = "Excel";
          otchet_excel = Menu (menu_vibor, "‚ë¡¥à¨â¥ ¢ à¨ ­â ä®à¬ â  ¢ë¯¨áª¨");
          //end
         if ( dlg.rec.Reportdate > {curdate} )
                MsgBox("„ â  ­ ç «  ¯¥à¨®¤  ­¥ ¬®¦¥â ¡ëâì ¡®«ìè¥ ¤ âë â¥ªãé¥£® ®¯¥à æ¨®­­®£® ¤­ï");
                return CM_IGNORE;
         end;
        reportDate  = dlg.rec.reportdate;
        flag1=dlg.rec.f1;
        flag3=dlg.rec.f3;
        symbol=dlg.rec.symbol;
        flag4=dlg.rec.f4;
        if (Department.nodetype==1)
//          branch = " AND acc.t_department = "+department.code;
          branch = " AND acc.t_branch = "+dprt_v;
        elif (dprt_v==0)
          branch="";
        else
          branch = " AND acc.t_branch = "+dprt_v;
        end;
        balacc=dlg.rec.balacc;
        branchname=dlg.rec.branchname;
        if ( dlg.rec.allb == "X")
          branch = "";
        branchname="‚¥áì ¡ ­ª";
//          branch = " AND acc.t_department = "+department.code;
        end;
         if (strlen(balacc)>3)    
           Return CM_SAVE;
        else msgbox("¥¢¥à­® ¢¢¥¤¥­ ¡ « ­á®¢ë©");
           Return CM_IGNORE;
        end;
         if ((reportdate < {curDate}))    
           Return CM_SAVE;
        elif (gettrue(true,"„ â  à ¢­  â¥ªãé¥¬ã ®¯à¥à æ¨®­­®¬ã ¤­î. à®¤®«¦¨âì?"))
           Return CM_SAVE;
        end;
      else
           Return CM_IGNORE;
     end;
   end;     
END;

//private macro total


if (RunDialog(dlg, "Event"))                  
if (flag1=="X")
   flag1=1;
   else
   flag1=0;
end;
if (flag3=="X")
   flag3=1;
   else
   flag3=0;
end;
if (flag4=="X")
   flag4=1;
   else
   flag4=0;
end;
//Sokolov R-145922-3
if (otchet_excel == 0)
 outall();
else
 outall_excel();
end;//end R-145922-3
setoutput(null,true);
end;


END;


