import BankInter, RSD, globals;

var zapros,  zapros2, zapros3 , zapros4 :RSDRecordset;
var SQLQuery, SQLQuery_2, SQLQuery_3 , SQLQuery_4:string  = "";
var counter  :integer = 0, query, all: integer = 0;
var Arm;

getint(Arm,"‡ ¤ ©â¥ ­®¬¥à €Œ ");
// Tikh ¤«ï ¢á¥å  à¬
if (arm == 0)
SQLQuery = " SELECT DISTINCT (t_role) AS arm "+
           " FROM dperson_lnk_dbt "+
       " ORDER BY arm";
else
SQLQuery = " SELECT distinct(t_role) AS arm "+
           " FROM dperson_lnk_dbt "+
           " WHERE T_role = "+arm;
end;
QUERY = RSDRecordset(SQLQuery); /*à¥§ã«ìâ â § ¯à®á */
while (query.movenext())
counter = 0;
//-------------

SQLQuery = " select t_user, t_role "
            +" from dperson_lnk_dbt "
            +" where t_role = " + query.value(0)
            +" order by t_user";

zapros = RSDRecordset(SQLQuery); /*à¥§ã«ìâ â § ¯à®á */

 [
   ##########

   ‘¯¨á®ª ¯à¨¢ï§ª¨ á®âàã¤­¨ª®¢ ª â¨¯®¢®¬ã €Œ

   ###### 
   ÚÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
   ³ ®¬¥à ³                   “§¥«                      ³            §¢ ­¨¥ ¬¥­î               ³   ®¬¥à    ³            ”.ˆ..            ³
   ³ ¬¥­î  ³                    ’‘                       ³                                       ³¯®«ì§®¢ â¥«ï³        ®¯¥à æ¨®­¨áâ          ³
   ÃÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´]({CurDate}, query.value(0) );

while (zapros.moveNext)

SQLQuery_2 =" select pers.t_name, pers.t_oper, pers.t_codedepart , part.t_name "
            +" from dperson_dbt pers, dparty_dbt part ,DDP_DEP_DBT dep"
            +"  where pers.t_oper =  "+ zapros.value(0) 
            +"  and pers.t_UserClosed <> 'X' "
            +"  and pers.t_userblocked <> 'X' "
            +"  AND NOT pers.t_name LIKE '%RSTYLE%' "
            +"  AND pers.t_lastconnectdate >= to_date('01.01.2012','dd.mm.yyyy') "
            +"  AND pers.t_datecreateoper <= to_date('31.03.2012','dd.mm.yyyy') "
            +"  and dep.t_code =  pers.t_codedepart "
            +"  and dep.t_partyid = part.t_partyid ";
//             +" order by t_oper";
zapros2 = RSDRecordset(SQLQuery_2);
if (zapros2.moveNext)
counter = counter + 1;
// Tikh ¡é¨© áç¥âç¨ª
all = all+1;

//zapros2.moveNext;

SQLQuery_3 =" select t_name, t_menuid "
            +" from dmenutpl_dbt"
       +" where t_menuid = "+ zapros.value(1)+";";       
zapros3 = RSDRecordset(SQLQuery_3);
zapros3.moveNext;
/*
// § ¯à®á ã§«  ¯® ¢­ãâà¥­¥© ’‘
SQLQuery_4 =" select t_code1, t_code2 "
            +" from dop_otdel_dbt"
       +" where t_oper = "+ zapros.value(0)+";";         
zapros4 = RSDRecordset(SQLQuery_4);

   if (zapros4.moveNext)
[      ³#######³###-### ³ ######################################³##########  ³ #############################³] 
        (zapros.value(1):c, zapros4.value(0), zapros4.value(1):l, zapros3.value(0), zapros.value(0):r, zapros2.value(0));
   else
[      ³#######³¥“ª § ­³ ######################################³##########  ³ #############################³] 
        (zapros.value(1):c,  zapros3.value(0), zapros.value(0):r, zapros2.value(0));
   end;
*/
// ã§«ë ¯® ¤¨áâà¨¡ãâ¨¢­®© ’‘
[ ³#######³#############################################³ ######################################³##########  ³ #############################³] 
        (zapros.value(1):c, zapros2.value(3):r, zapros3.value(0), zapros.value(0):r, zapros2.value(0));

end;
end;

[ ÀÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ];
          
[ ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
  ³‚á¥£® á®âàã¤­¨ª®¢ ¯®¤ª«îç¥­® ª €Œ: #######                                                         ³ 
  ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ](Counter:l);
end;
// Tikh ¡é¨© áç¥âç¨ª
if (all != counter)
[ ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
  ³‚á¥£® á®âàã¤­¨ª®¢ ¯®¤ª«îç¥­® ª €Œ ¯® ¢á¥¬ ¬¥­î: #######                                            ³ 
  ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ](all:l);
end;

    