/*                                                   *
 * Удаление записей в таблице обмена СМС оповещениями*
 *                                                   */
Import BankInter, PTInter, rsd, "globals.mac";
  macro deleteSMS() 

  var cmd : RsdCommand;
  var sqlstr;
    sqlstr = " DECLARE " 
             " table_not_found EXCEPTION;" 
             " PRAGMA EXCEPTION_INIT( table_not_found, -00942 ); "
             " BEGIN " 
             "   EXECUTE IMMEDIATE 'delete from usr_vpaym_dbt where eventdate < (sysdate - 14)'; " 
             " EXCEPTION " 
             "   WHEN table_not_found THEN NULL; " 
             " END; ";

  cmd = RsdCommand(sqlstr);
  cmd.execute();
  end;