/*
Тихомиров А.Н.

Коды ОКАТО подразделений
*/
import rsd, globals;

var rsd = rsdrecordset(rsdcommand(" select * from (SELECT dep.t_name as dep, party.t_name as name, party.t_partyid "+
"  FROM ddp_dep_dbt dep, dparty_dbt party  "+
" WHERE dep.t_partyid = party.t_partyid "+
"   and dep.t_status = 2 ) tab1 left join  "+
"   (select atc.t_object, atr.t_numinlist from dobjatcor_dbt atc, dobjattr_dbt atr "+
"   where    atc.t_objecttype = 3 "+
"   AND atc.t_groupid = 12 "+
"   and atr.t_groupid = atc.t_groupid "+
"   and atc.T_VALIDTODATE > to_date ('"+{curdate}+"','DD-MM-YYYY') "+
"   and atc.T_VALIDFROMDATE <= to_date ('"+{curdate}+"','DD-MM-YYYY') "+
"   and atc.T_ATTRID = atr.T_ATTRID "+
"   ) tab2 "+
"   on lpad(tab1.t_partyid, 10, '0') = tab2.t_object "+
"   order by dep "));
[Окато подразделений ПРББ


Подразделение     Наименование                              Код ОКАТО];


while (rsd.movenext())

[#########   ###############################################  ###############]
(rsd.value(0):c, rsd.value(1):c, rsd.value(4):z:r);


end;

end;