/************************************************************************
Макрос отчета отражающий информацию по операциям, проведенным операционистами ВК
Исполнитель: Телешова Александра 18.11.2011 По заявке С-6353
Изменен: TAM 25.11.2011 Добавлена дополнительная проверка на блоки с операциями ВК
Изменен: TAM 25.11.2011 Добавлены колонки № паспорта сделки и код ВО в отчет
************************************************************************/
import RsbDataSet, BankInter, PTInter, globals, календарь; 
import rcw, RSD, rsexts;
import "KeyCodes.mac";
import "VBAconst.mac";

var begin_date, end_date, oper_id, oper_name, dep_id, dep_number, dep_name, che = 3, i, i_old, ex, ob,FullOutPut, obBook, obSheet; //, output = "vk_operation_rep.xlt";
//var exel_begin_stroka:integer=6;
//var exelstroka:integer=exel_begin_stroka;
var strok_end:integer=1, strok_begin:integer=0; // кол-во строк в файле данных
var _i=0, bal2="", bal="";
private var dd:date, tt:time, ii:integer, ss:string;  // это переменные для использования FileInfo
//che = 3;
var tempFileName:string = "", tempFileNameBezPuti:string ="";
//виды отчетов:краткий\полный
var full_report:bool = true;
//виды отчетов:оперы\офисы
var oper_report:bool = true;

//debugbreak;
record oper (person);

const TEXTDIR_REESTR = "BANK_INI\\ОБЩИЕ ПАРАМЕТРЫ\\ДИРЕКТОРИИ\\TEXTDIR";

var Fulloutputlbr, outlbr, outputlbr="vk_operation_rep.lbr";                    
GetRegistryValue("BANK_INI\\ОБЩИЕ ПАРАМЕТРЫ\\ДИРЕКТОРИИ\\LBRDIR",2,outlbr);
Fulloutputlbr = FindPath(outputlbr, outlbr);
if (not Fulloutputlbr)
    msgbox("Не найдена LBR");
    exit();
end;

var dlg = TRecHandler("v2.2", fulloutputlbr, TRUE); 

/****************************************************вспомогательные функции (begin)****************************************/
//Получение настройки реестра
macro chekReestrRead(m_name:string, m_status:integer, m_err:integer)
    if ((m_status == V_UNDEF) or (m_err != 0))
        msgbox("Ошибка получения значения настройки реестра " + m_name + " \n Процедура GetRegistryValue вернула код ошибки "+m_err);
        exit(0);
    end;
end;

macro dayString(m_reestrName:string):string
    private var m_errCode           :integer = NULL;
    private var m_statusGetRegistry :integer = NULL;
    private var m_zna4enie          :string  = NULL;
    if (m_reestrName == "")
        msgbox("При чтении реестра не задана строка реестра");
        exit(0)
    end;
    m_statusGetRegistry=GetRegistryValue(m_reestrName, V_STRING, m_zna4enie, m_errCode);
    chekReestrRead(m_reestrName, m_statusGetRegistry, m_errCode);
    return(m_zna4enie);
end;

//создание заголовка файла с данными
macro createUniqueFile()
    private var ff:string = "vk_opr__"+{oper}+"_"+date+"_"+time;
    private var file_ext:string = ".txt";
    tempFileName = dayString(TEXTDIR_REESTR);
    tempFileName = tempFileName + "\\" + ff;
    tempFileNameBezPuti = ff;
    tempFileName = StrSubst ( tempFileName, ".", "_" );
    tempFileName = StrSubst ( tempFileName, ":", "_" );
    tempFileName = StrSubst ( tempFileName, " ", "_" );
    tempFileName = tempFileName + file_ext;
    tempFileNameBezPuti = StrSubst ( tempFileNameBezPuti, ".", "_" );
    tempFileNameBezPuti = StrSubst ( tempFileNameBezPuti, ":", "_" );
    tempFileNameBezPuti = StrSubst ( tempFileNameBezPuti, " ", "_" );
    tempFileNameBezPuti = tempFileNameBezPuti + file_ext;
    if (substr(tempFileName,1,2) == "__")
        tempFileName=".."+substr(tempFileName,3)
    end;
end;

//копирование файла на терминал
macro copyToMe()
    private var m_path: string = "";
    m_path = "$" + tempFileNameBezPuti;
    if (not CopyFile(tempFileNameBezPuti, m_path, TRUE))
        println ("Не удалось скопировать файл с Cервера Приложений на терминал. Исходный файл: "+tempFileNameBezPuti+" Файл назначения: " + m_path);
    else 
        println ("Успешно скопирован файл с Сервера Приложений на терминал. Исходный файл: "+tempFileNameBezPuti+" Фаил назначения: " + m_path);
        if (not removeFile(tempFileName))
            println("Не удалось удалить фаил с Сервера Приложений "+tempFileName+". Продолжаем работу.");
        else
            println("Удален файл "+tempFileName+" с Сервера Приложений.");
        end;
    end;
end;

//Получение наименования субъекта по его идентификатору
macro GetPartyName(party_id)
    if(party_id == -1)
            return "Региональные офисы";
    end;
    var cmd, data;
    cmd = RsdCommand("select t_name from dparty_dbt where t_partyid = ?");
    cmd.AddParam("party", RSDBP_IN, party_id);
    cmd.execute;
    data = RsdRecordset(cmd);
    if (data.movenext())
        return data.value(0);
    else 
        return " ";
    end;
end;

//Получение РС-Кода клиента
macro GetPartyRSCode(party_id)
    var cmd, data;
    cmd = RsdCommand("SELECT code.t_code FROM dobjcode_dbt code WHERE code.t_objecttype = 3 AND code.t_codekind = 20 AND     code.t_objectid = ?");
    cmd.AddParam("party", RSDBP_IN, party_id);
    cmd.execute;
    data =  RsdRecordset(cmd);
    if (data.movenext())
        return data.value(0);
    else 
        return " ";
    end;
end;

//Получение номера документа по идентификатору платежа
macro GetDocNumber (pm_id, pm_fiid)
    var cmd, data, arh;
    if(pm_fiid !=0 )
        arh = "darhdoc$_dbt";
    else 
        arh = "darhdoc_dbt";
    end;
    cmd = RsdCommand("select t_numb_document from " + arh + " arh, dpmdocs_dbt doc where doc.t_paymentid = ? and doc.t_applicationkey = arh.t_applicationkey ");
    cmd.AddParam("pm", RSDBP_IN, pm_id);
    cmd.execute;
    data = RsdRecordset(cmd);
    if (data.movenext())
        return data.value(0);
    else 
        return " ";
    end;
end;

//ФИО опера по идентификатору
macro GetOperName(id)
    var cmd, data;
    cmd = RsdCommand("select t_name from dperson_dbt where t_oper = ?");
    cmd.AddParam("oper", RSDBP_IN, id);
    cmd.execute;
    data = RsdRecordset(cmd);
    if (data.movenext())
        return data.value(0);
    else 
        return " ";
    end;
end;

macro GetOperItog(id)
    var cmd, data;
    cmd = RsdCommand(" SELECT COUNT (t_oper) FROM vk_operations_tmp where t_oper = ?");
    cmd.AddParam("id", RSDBP_IN, id);
    cmd.execute;
    data = RsdRecordset(cmd);
    if (data.movenext())
        return string(data.value(0));
    else 
        return " ";
    end;
end;

//ФИО опера по идентификатору
macro GetISOCur(id)
    var cmd, data;
    cmd = RsdCommand(" select t_fi_code from dfininstr_dbt where t_fiid =  ?");
    cmd.AddParam("id", RSDBP_IN, id);
    cmd.execute;
    data = RsdRecordset(cmd);
    if (data.movenext())
        return data.value(0);
    else 
        return id;
    end;
end;

macro GetPaymTypeOperation(pm_id)
    var cmd, data;
    cmd = RsdCommand(" select t_passportnumber, t_blockid, T_PAYERACCOUNT, T_RECEIVERACCOUNT, t_fiid from vk_operations_tmp where t_paymentid = ?");
    cmd.AddParam("id", RSDBP_IN, pm_id);
    cmd.execute;
    data = RsdRecordset(cmd);
    if (data.movenext())
        if (data.value(0) != "X")
            return "ОПС";
        else
            if(((data.value(1) == 11001117) or (data.value(1) == 11000133 )) and (data.value(4) == 0))
                return "РубЗ";
            else 
                if(((data.value(1) == 11000117) and 
                        (  (SubStr(data.value(2),1,3) == "423") 
                        or (SubStr(data.value(2),1,3) == "426") 
                        or (SubStr(data.value(2),1,5) == "40817") 
                        or (SubStr(data.value(2),1,5) == "40820") 
                        or (SubStr(data.value(2),1,5) == "40912") 
                        or (SubStr(data.value(2),1,5) == "40913" ))) 
                    or (((data.value(1) == 11001117) or (data.value(1) == 11000133) or (data.value(1) == 11001777)) and 
                        (  (SubStr(data.value(3),1,3) == "423") 
                        or (SubStr(data.value(3),1,3) == "426") 
                        or (SubStr(data.value(3),1,5) == "40817")
                        or (SubStr(data.value(3),1,5) == "40820")
                        or (SubStr(data.value(2),1,5) == "40912")
                        or (SubStr(data.value(2),1,5) == "40913" ))))
                        return "ОФЛР\Н";
                elif(((data.value(1) == 11000117) and (SubStr(data.value(2),1,5) == "40807"))
                    or (((data.value(1) == 11001117) or (data.value(1) == 11000133) or (data.value(1) == 11001777)) and (SubStr(data.value(3),1,5) == "40807")))
                        return "ОНЮЛ";
                else
                        return "ОбПС";
                end;
            end;
        
        end;
    end;
end;

//форматирование вывода в экселе
macro format_osv(b:integer, e:integer)
    debugbreak;
    private var m_range:string;
    if(oper_report == true)
        if(full_report == true)
            m_range = "a"+b+":q"+e;
        else
            m_range = "a"+b+":h"+e;
        end;
    else
        m_range = "a"+b+":h"+e;
    end;
    obSheet.range(m_range).Borders(xlEdgeLeft).LineStyle = xlContinuous;
    obSheet.range(m_range).Borders(xlDiagonalDown).LineStyle = xlNone;           
    obSheet.range(m_range).Borders(xlDiagonalUp).LineStyle = xlNone;             
    obSheet.range(m_range).Borders(xlEdgeLeft).LineStyle = xlContinuous;         
    obSheet.range(m_range).Borders(xlEdgeLeft).Weight = xlThin;                  
    obSheet.range(m_range).Borders(xlEdgeLeft).ColorIndex = xlAutomatic;         
    obSheet.range(m_range).Borders(xlEdgeTop).LineStyle = xlContinuous;          
    obSheet.range(m_range).Borders(xlEdgeTop).Weight = xlThin;                   
    obSheet.range(m_range).Borders(xlEdgeTop).ColorIndex = xlAutomatic;          
    obSheet.range(m_range).Borders(xlEdgeBottom).LineStyle = xlContinuous;       
    obSheet.range(m_range).Borders(xlEdgeBottom).Weight = xlThin;                
    obSheet.range(m_range).Borders(xlEdgeBottom).ColorIndex = xlAutomatic;       
    obSheet.range(m_range).Borders(xlEdgeRight).LineStyle = xlContinuous;        
    obSheet.range(m_range).Borders(xlEdgeRight).Weight = xlThin;                 
    obSheet.range(m_range).Borders(xlEdgeRight).ColorIndex = xlAutomatic;        
    obSheet.range(m_range).Borders(xlInsideVertical).LineStyle = xlContinuous;   
    obSheet.range(m_range).Borders(xlInsideVertical).Weight = xlThin;            
    obSheet.range(m_range).Borders(xlInsideVertical).ColorIndex = xlAutomatic;   
    obSheet.range(m_range).Borders(xlInsideHorizontal).LineStyle = xlContinuous; 
    obSheet.range(m_range).Borders(xlInsideHorizontal).Weight = xlThin;          
    obSheet.range(m_range).Borders(xlInsideHorizontal).ColorIndex = xlAutomatic; 
end;

//заполнение временной таблицы данными по операциям ВК
macro FillTmpTable()
    begaction(2000, "Заполнение временной таблицы...", false);
    message("Заполнение временной таблицы...");
   var sqlString, cmd; 
   //данные по операциям валютных контролеров
    sqlString = " INSERT INTO vk_operations_tmp " +
            " SELECT   step.t_oper, paym.t_paymentid, step.t_fact_date, paym.t_fiid, " +
            " paym.t_amount, paym.t_payfiid, paym.t_payamount, nvl(val.t_code,'X'), nvl(co.t_passportnumber,'X'), paym.t_payer, " +
            " paym.t_payeraccount, paym.t_payerbankid, paym.t_receiver, " +
            " paym.t_receiveraccount, paym.t_receiverbankid, step.t_blockid, 0 " +
            " FROM doprstep_dbt step, " +
            "      doproper_dbt opr, " +
            "      dpmpaym_dbt paym, " +
            "      dperson_dbt pers, " +
            "      dpmco_dbt co, " +
            "      dllvalues_dbt val " +
            " WHERE step.t_fact_date BETWEEN TO_DATE ('" + begin_date + "', 'dd.mm.yyyy') " +
                                   " AND TO_DATE ('" + end_date + "', 'dd.mm.yyyy') "
                        " AND (   (step.t_blockid = 11000117) " +
                                " OR (step.t_blockid = 11000118) " +
                                " OR (step.t_blockid = 11001117) " +
                                " OR (step.t_blockid = 11001777) " +
                                " OR (step.t_blockid = 11000133 AND step.t_number_step = 20) ) " +
                        " AND step.t_isexecute = 'X' " +
                        " AND step.t_id_operation = opr.t_id_operation " +
                        " AND opr.t_documentid = LPAD (paym.t_paymentid, 34, '0') " +
                        " AND paym.t_paymentid = co.t_paymentid(+) " +
                        " AND val.t_element(+) = co.t_vo_code " +
                        " AND val.t_list(+) = 1805 " + 
                        " AND step.t_oper = pers.t_oper " +
            " ORDER BY step.t_oper, step.t_fact_date ";
    cmd =  RsdCommand( sqlString );
    cmd.execute();
    //при ошибках в номере паспорта
    cmd = RsdCommand(" update vk_operations_tmp tmp  set tmp.T_PASSPORTNUMBER = 'X' where length(tmp.t_passportnumber) < 20");
    cmd.execute();
    //обновляем подразделения для списаний
    sqlString = " UPDATE vk_operations_tmp tmp " +
                " SET tmp.t_branch = " +
                    " nvl((SELECT t_partyid " +
                    " FROM ddp_dep_dbt " +
                    " WHERE t_code = (SELECT acnt.t_branch " +
                                     " FROM daccount_dbt acnt " + 
                                     " WHERE acnt.t_account = tmp.t_payeraccount)),0) " +
                " WHERE tmp.t_payerbankid = 3045 ";
    cmd = RsdCommand(sqlString);
    cmd.execute();
    //обновляем подразделения для зачислений
    sqlString = " UPDATE vk_operations_tmp tmp " +
                " SET tmp.t_branch = " +
                    " nvl((SELECT t_partyid " +
                        " FROM ddp_dep_dbt " +
                        " WHERE t_code = (SELECT acnt.t_branch " +
                                         " FROM daccount_dbt acnt " +
                                         " WHERE acnt.t_account = tmp.t_receiveraccount)),0) " +
                " WHERE tmp.t_receiverbankid = 3045 "; 
    cmd = RsdCommand(sqlString);
    cmd.execute();
    endaction();
end;
/****************************************************вспомогательные функции (end)****************************************/

                                                                                       
/****************************************************обработка диалоговой панели(begin)****************************************/
//Макрос обработки диалоговой панели
MACRO Event (dlg, cmd, id, key)
    //debugbreak;
    var res;
    array gname; //вид отчета
    gname(0)="Полный отчет";
    gname(1)="Краткий отчет";
    array department_number, department_id,department_name;//офисы
    //номера офисов
    department_number(0) = "001";
    department_number(1) = "002";
    department_number(2) = "006";
    department_number(3) = "011";
    department_number(4) = "012";
    department_number(5) = "013";
    department_number(6) = "000"; //региональные
    //айди субъектов
    department_id(0) = 13;
    department_id(1) = 15;
    department_id(2) = 19;
    department_id(3) = 66;
    department_id(4) = 179;
    department_id(5) = 662066;
    department_id(6) = -1;
    //Наименовнаие отделения
    department_name(0) = "Д\о Центральный";
    department_name(1) = "Д\о Автозаводский";
    department_name(2) = "Д\о Новоданиловский";
    department_name(3) = "Д\о Новодмитровский";
    department_name(4) = "Д\о Авилон-Плаза";
    department_name(5) = "Д\о Новинский";
    department_name(6) = "Региональные Д\о";
    
    var const_mess = " ~F3~ Выбор значений из списка ~F2~ Продолжить ~ESC~ Выход ";

    /*Инициализация панели*/
    if(cmd == DLG_INIT)
        //по всем операм полный отчет
        dlg.rec.begindate = {curdate};
        dlg.rec.enddate = {curdate};
        dlg.rec.oper_choice = "";
        dlg.rec.branch_choice = "";
        DisableFields(dlg,3);
        DisableFields(dlg,2);
        //DisableFields(dlg,7);
        dlg.rec.oper = "";
        dlg.rec.branch = "";
        dlg.rec.opername = "";
        dlg.rec.branchname = "";
        dlg.rec.short_report = "";
        UpdateFields(dlg); 
    end;
        
    /*Установка подсказок в строке состояния*/
    if (cmd==DLG_SETFOCUS)
        if (FldName(dlg,id)=="BeginDate")
            message(" ~F3~ Выбор даты из календаря "+const_mess);
        elif (FldName(dlg,id)=="EndDate")
            message(" ~F3~ Выбор даты из календаря "+const_mess);
        elif (FldName(dlg,id)=="oper")
            message(" ~F3~ Выбор операциониста "+const_mess);
        else
            message(const_mess);
        end;     
    end;
        
    if (cmd == DLG_REMFOCUS)
        /*Проверка корректности дат отчета*/
        UpdateFields(dlg); 
    end;
    
    if (cmd == DLG_KEY)
        /*Выход из окна формирования отчета*/
        if (KEY == KEY_ESC)
            return CM_CANCEL;
        
        /*Выбор данных из списка*/
        elif ( KEY == KEY_F3)
            if (FldName(dlg,id) == "BeginDate")
                dlg.rec.begindate = GetDateByCalendar ({curDate});
                message(" ~F3~ Выбор даты "+const_mess);
                UpdateFields(dlg);
            end;
                
            if (FldName(dlg,id) == "EndDate")
                dlg.rec.enddate = GetDateByCalendar ({curDate});
                message(" ~F3~ Выбор даты "+const_mess);
                UpdateFields(dlg);
            end;
                
            if (FldName(dlg,id) == "oper")
                if (Listoper (oper))
                    dlg.rec.oper = oper.oper;
                    dlg.rec.opername = oper.name;
                    message(" ~F3~ Выбор операциониста "+const_mess);
                    UpdateFields(dlg);
                end;
            end;
                
            if(FldName(dlg,id) == "branch")
                res = menu(department_name,"Офисы",10,35);
                if (res == 0)
                    dlg.rec.branch = department_number(0);
                    dlg.rec.branchname = department_name(0);
                elif (res == 1)
                    dlg.rec.branch = department_number(1);
                    dlg.rec.branchname = department_name(1);
                elif (res == 2)
                    dlg.rec.branch = department_number(2);
                    dlg.rec.branchname = department_name(2);
                elif (res == 3)
                    dlg.rec.branch = department_number(3);
                    dlg.rec.branchname = department_name(3);
                elif (res == 4)
                    dlg.rec.branch = department_number(4);
                    dlg.rec.branchname = department_name(4);
                elif (res == 5)
                    dlg.rec.branch = department_number(5);
                    dlg.rec.branchname = department_name(5);
                elif (res == 6)
                    dlg.rec.branch = department_number(6);
                    dlg.rec.branchname = department_name(6);
                end;
                UpdateFields(dlg);
                //заполним глобальные перемеенные для отчета
                dep_id = department_id(res);
                dep_name = department_name(res);
                dep_number = department_number(res);
            end;

            if (FldName(dlg,id) == "short_report")
                res = menu(gname,"Вид отчета",10,35);
                if (res == 0)
                    dlg.rec.short_report = "Полный";
                    UpdateFields(dlg);
                elif (res == 1)
                    dlg.rec.short_report = "Краткий";
                    UpdateFields(dlg);
                else 
                        message(const_mess);
                        UpdateFields(dlg);
                end;
            end;
        
        //установка вида отчета
        elif (KEY == KEY_SPACE)
            if( FldName(dlg,id) == "oper_choice")
                dlg.rec.oper_choice = "X";
                dlg.rec.branch_choice = "";
                dlg.rec.branchname = "";
                DisableFields(dlg,8);
                DisableFields(dlg,2);
                EnableFields(dlg,3);
                UpdateFields(dlg);
            elif (FldName(dlg,id) == "branch_choice")
                dlg.rec.branch_choice = "X";
                dlg.rec.oper_choice = "";
                dlg.rec.opername = "";
                DisableFields(dlg,3);
                DisableFields(dlg,6);
                EnableFields(dlg,2);
                UpdateFields(dlg);
            else
                message(const_mess);
                UpdateFields(dlg);
            end;
        /*Проверки при вводе*/	
        elif (( KEY == KEY_F2 ) or (KEY == KEY_ENTER))         
            if ( dlg.rec.begindate > {curDate} )
                MsgBox("Дата начала периода должна быть не больше текущей даты");
                return CM_IGNORE;
            end;
            
            if ( dlg.rec.begindate > dlg.rec.enddate )
                MsgBox("Дата начала периода должна быть не больше конечной даты");
                return CM_IGNORE;
            end;
            
            if(dlg.rec.short_report == "")
                MsgBox("Не задан вид отчета: краткий или полный!");
                return CM_IGNORE;
            end;
            begin_date  = dlg.rec.beginDate;
            end_date  = dlg.rec.endDate;
            
            //оперы\офисы
            if (dlg.rec.oper_choice == "X")
                oper_report = true;
            elif (dlg.rec.branch_choice == "X")
                oper_report = false;
            else
                msgbox("Выберите вид отчета: по офисам или операционистам!");
            end;
            
            //полный\краткий
            if(dlg.rec.short_report == "Полный")
                full_report = true;
            elif (dlg.rec.short_report == "Краткий")
                full_report = false;
            else
                msgbox("Выберите вид отчета: краткий или полный!");
                return CM_IGNORE;
            end;
            
            if(dlg.rec.oper == "")
                oper_id = 0;
            else
                oper_id = dlg.rec.oper;
            end;
            
            if(dlg.rec.branch == "")
                dep_id = dep_name = dep_number = 0;
            end;
            
            return CM_SAVE;
        end;
    else
        return CM_IGNORE;
    end;
END;
/****************************************************обработка диалоговой панели(end)****************************************/

/******************************************* Полный отчет по операционистам ВК (begin) **********************************************/
macro WriteHeadForFullOper()
    private var m_range:string="A"+(che+1)+":Q"+(che+1);
    obSheet.Cells(1,1).Value= "Отчет по операциям валютных контролеров";
    obSheet.Cells(2,1).Value= "За период с " + begin_date + " по " + end_date;
    if (oper_id == 0)
        obSheet.Cells(3,1).Value = "По всем операционистам ";
    else
        obSheet.Cells(3,1).Value = "По операционисту: " + GetOperName(oper_id) + "       Всего:    " + GetOperItog(oper_id);
    end;
   
    obSheet.Cells(che + 1,1).Value = "№";
    obSheet.Cells(che + 1,2).Value = "ИД платежа";
    obSheet.Cells(che + 1,3).Value = "Дата";
    obSheet.Cells(che + 1,4).Value = "С\З";
    obSheet.Cells(che + 1,5).Value = "Валюта счета";
    obSheet.Cells(che + 1,6).Value = "Сумма в валюте счета";
    obSheet.Cells(che + 1,7).Value = "Валюта платежа";
    obSheet.Cells(che + 1,8).Value = "Сумма в валюте платежа";
    obSheet.Cells(che + 1,9).Value = "Код ВО";
    obSheet.Cells(che + 1,10).Value = "№ паспорта";
    obSheet.Cells(che + 1,11).Value = "Тип операции";
    obSheet.Cells(che + 1,12).Value = "Наименование клиента ПРББ";
    obSheet.Cells(che + 1,13).Value = "RS-код";
    obSheet.Cells(che + 1,14).Value = "Счет плательщика";
    obSheet.Cells(che + 1,15).Value = "Банк плательщика";
    obSheet.Cells(che + 1,16).Value = "Счет получателя";
    obSheet.Cells(che + 1,17).Value = "Банк получателя";
    
    obSheet.Range(m_range).Borders.Weight=2;
    obSheet.Range(m_range).interior.color=4035000;
    obSheet.Range(m_range).HorizontalAlignment = xlCenter;
    obSheet.Range(m_range).font.Name = "Calibri";
    obSheet.Range(m_range).font.FontStyle = "bold";
    obSheet.Range(m_range).font.Size = 12;
    obSheet.Columns("A:A").ColumnWidth = 20;
    obSheet.Columns("B:Q").EntireColumn.AutoFit;
end;

macro WriteBodyFullOper(data)
    var first= true;
    //переменные данных в отчет
    var j = 1, bank_id, operid, oper_name, paym_id, paym_date, operation, debet_fiid, debet_amount, paym_fiid, paym_amount, paym_vo_code, paym_passport_number, paym_type, client_name, client_code, payer_account, payer_bank, reciever_account, reciever_bank, current_oper_id = 0, f_opr_changed = false;
    i = che + 2;
    i_old = i;
    InitProgress(-1, "Отобранные операции выводятся в файл. Период операций с " + begin_date + " по " + end_date);
    createUniqueFile();
    FILE aa () txt write;
    open(aa, tempFileName);
    aa.str = " ";
    insert(aa);
    var first_row:bool = true;
    while(data.movenext)
        if( (oper_id == 0) and (current_oper_id != data.value(0)))
            //выводим наименование операциониста
            operid = string(data.value(0));
            oper_name = GetOperName(data.value(0));
            aa.str = oper_name + "|" + operid + "|" + "Всего операций:" + "|" + GetOperItog(operid);
            aa.str = toansi(aa.str, true);
            insert(aa);
            strok_end = strok_end +1;
            UseProgress(_i=_i + 1);
        end;
        //Выводим инфу
        current_oper_id = data.value(0);
        paym_id = data.value(1);
        paym_date = date(data.value(2));
        debet_fiid = GetISOCur(data.value(3));
        debet_amount = data.value(4);
        paym_fiid = GetISOCur(data.value(5));
        paym_amount = data.value(6);
        if(data.value(7) != "X")
            paym_vo_code = data.value(7);
        else
            paym_vo_code = "";
        end;
        if(data.value(8) != "X")
            paym_passport_number = data.value(8);
        else
            paym_passport_number = "";
        end;
        paym_type = GetPaymTypeOperation(paym_id);
        payer_bank = GetPartyName(data.value(11));
        reciever_bank = GetPartyName(data.value(14));
        //Вид операции: 1 - зачисление 2 - списание
        //идентификатор нашего банка
        bank_id = {OurBank};
        if ( data.value(11) == data.value(14) ) //внутренний платеж
            operation = 2;
        else
            if ( data.value(11) == bank_id)
                operation = 2;
            elif ( data.value(14) == bank_id)
                operation = 1;
            end;
        end;
        if (operation == 1)
            client_name = GetPartyName(data.value(12));
            client_code = GetPartyRSCode(data.value(12));
        else
            client_name = GetPartyName(data.value(9));
            client_code = GetPartyRSCode(data.value(9));
        end;
        payer_account = data.value(10);
        reciever_account = data.value(13);
        
        aa.str = j + "|" + paym_id + "|" + paym_date + "|" + operation + "|" + debet_fiid + "|" + debet_amount + "|" + paym_fiid + "|" + paym_amount + "|" + string(paym_vo_code) + "|" + paym_passport_number + "|" + paym_type + "|" + client_name + "|" + client_code + "|" + payer_account + "|" + payer_bank + "|" + reciever_account + "|" + reciever_bank;
        aa.str = toansi(aa.str, true);
        insert(aa);
        strok_end = strok_end +1;
        UseProgress(_i=_i + 1);
        j = j +1;
    end;
    close(aa);
    RemProgress();
end;

macro FullReportForOper()
    debugbreak;
    var data,sqlString,cmd;
    //msgbox("Полный отчет по операционистами");
    begaction(2000, "Выполнение запроса к БД...", false);
    message("Выполнение запроса к БД...");
    //выьираем всё что есть в vk_operations_tmp
    if(oper_id == 0)
        sqlString = " select * from vk_operations_tmp ";
    else
        sqlString = " select * from vk_operations_tmp where t_oper = " + oper_id;
    end;
    cmd = RSDCommand( sqlString );
    data = RsdRecordset( cmd );
    endaction();
    WriteBodyFullOper(data);
    message("Файл с данными пересылается на терминал!!!");
    copyToMe();
    message("Запускается  EXCEL");
    ob = CreateObject ("rsax","TRsAxServer","RsAxServer",IsStandAlone());
    ex = ob.CreateComObject ("Excel.Application", True);
    ex.ReferenceStyle = -4150; //R1C1
    ex.visible=false;
    if (not(GetFileInfo("$"+tempFileNameBezPuti,@dd,@tt,@ii,@ss))); //ss - 
       msgbox("Не удалось найти на локальном диске файл "+tempFileNameBezPuti+"   \n останавливаюсь");
       exit(0);
    end;
    ss = substr(ss,2); 
    var aw=tarray;
    
    var w1=tarray;  var w2=tarray;  var w3=tarray;  var w4=tarray;
    var w5=tarray;  var w6=tarray;  var w7=tarray;  var w8=tarray;
    var w9=tarray;  var w10=tarray;  var w11=tarray;  var w12=tarray;
    var w13=tarray;  var w14=tarray;  var w15=tarray;  var w16=tarray; var w17=tarray;
    //Формат: 1 - общий, 2 - текст
    w1(0)=1; w1(1)=1;       w2(0)=2; w2(1)=1;       w3(0)=3; w3(1)=1;       w4(0)=4; w4(1)=2; //дата
    w5(0)=5; w5(1)=1;       w6(0)=6; w6(1)=1;       w7(0)=7; w7(1)=1;/*сумма*/       w8(0)=8; w8(1)=1;
    w9(0)=9; w9(1)=2;       w10(0)=10; w10(1)=2;    w11(0)=11; w11(1)=2;    w12(0)=12; w12(1)=2;
    w13(0)=13; w13(1)=2;    w14(0)=14; w14(1)=2;    w15(0)=15; w15(1)=2;    w16(0)=16; w16(1)=2;  w17(0)=17; w17(1)=2;
    
    aw(0)=w1;       aw(1)=w2;       aw(2)=w3;       aw(3)=w4;
    aw(4)=w5;       aw(5)=w6;       aw(6)=w7;       aw(7)=w8;
    aw(8)=w9;       aw(9)=w10;      aw(10)=w11;     aw(11)=w12;
    aw(12)=w13;     aw(13)=w14;     aw(14)=w15;     aw(15)=w16; aw(16)=w17;
    
    aw.MarshalByVal =true; 
    w1.MarshalByVal =true;      w2.MarshalByVal =true;      w3.MarshalByVal =true;      w4.MarshalByVal =true;
    w5.MarshalByVal =true;      w6.MarshalByVal =true;      w7.MarshalByVal =true;      w8.MarshalByVal =true;
    w9.MarshalByVal =true;      w10.MarshalByVal =true;     w11.MarshalByVal =true;     w12.MarshalByVal =true;
    w13.MarshalByVal =true;     w14.MarshalByVal =true;     w15.MarshalByVal =true;     w16.MarshalByVal =true; 
    w17.MarshalByVal =true;
    
    begaction(2000, "Файл данных загружается в EXCEL", false);
    message("Файл данных загружается в EXCEL");
    
    obBook = ex.Workbooks.opentext(ss,1251,1,1,2,false,false,false,false,false,true,"|",aw,1,"."," ",true,true);
    endaction;
    strok_begin = 2;
    obSheet=ex.Sheets(1);
    ex.Sheets(1).Rows("1:1").Insert(-4121); strok_begin = strok_begin +1; strok_end = strok_end +1;
    ex.Sheets(1).Rows("1:1").Insert(-4121); strok_begin = strok_begin +1; strok_end = strok_end +1;
    ex.Sheets(1).Rows("1:1").Insert(-4121); strok_begin = strok_begin +1; strok_end = strok_end +1;
    
    begaction(2000,"Данные загружены в EXCEL, производится форматирвоание...", false);
    message("Данные загружены в EXCEL, производится форматирвоание...");
    
    WriteHeadForFullOper();
    format_osv(strok_begin, strok_end);
    endaction;
    println;
    println("Отчет сформирован. Для продолжения нажмите ESC ");
    ex.visible=true;
end;
/******************************************* Полный отчет пооперационистам ВК (end) **********************************************/

/******************************************* Краткий отчет по операционистам ВК (begin) **********************************************/
macro WriteHeadForShortOper()
    private var m_range:string="A"+(che+1)+":H"+(che+1);
    obSheet.Cells(1,1).Value= "Краткий отчет по операциям валютных контролеров";
    obSheet.Cells(2,1).Value= "За период с " + begin_date + " по " + end_date;
    
    obSheet.Cells(che + 1,1).Value= "ФИО операциониста ВК";
    obSheet.Cells(che + 1,2).Value= "Код операциониста ВК";
    obSheet.Cells(che + 1,3).Value= "Итого";
    obSheet.Cells(che + 1,4).Value= "ОПС";
    obSheet.Cells(che + 1,5).Value= "ОбПС";
    obSheet.Cells(che + 1,6).Value= "РубЗ";
    obSheet.Cells(che + 1,7).Value= "ОФЛР/Н";
    obSheet.Cells(che + 1,8).Value= "ОНЮЛ";
    
    obSheet.Range(m_range).Borders.Weight=2;
    obSheet.Range(m_range).interior.color=4035000;
    obSheet.Range(m_range).HorizontalAlignment = xlCenter;
    obSheet.Range(m_range).font.Name = "Calibri";
    obSheet.Range(m_range).font.FontStyle = "bold";
    obSheet.Range(m_range).font.Size = 12;
    obSheet.Columns("A:A").ColumnWidth = 20;
    var format_str:string = "# ##0" + ex.International(3) + "00";
    obSheet.Columns("B:H").EntireColumn.AutoFit;
end;

macro WriteBodyShortOper(data)
    //переменные данных в отчет
    var oper_name, operid, itog, cnt_ops, cnt_obps, cnt_rub_zach, cnt_ofl, cnt_oner, itog_all = 0, cnt_ops_all = 0, cnt_obps_all = 0, cnt_rub_zach_all = 0, cnt_ofl_all = 0, cnt_oner_all = 0;
    i = che + 2;
    i_old = i;
    InitProgress(-1, "Отобранные операции выводятся в файл. Период операций с " + begin_date + " по " + end_date);
    createUniqueFile();
    FILE aa () txt write;
    open(aa, tempFileName);
    aa.str = " ";
    insert(aa);
    var first_row:bool = true;
    while(data.movenext)
        //Выводим инфу
        if(oper_id == 0)
            oper_name = GetOperName(data.value(0));
            operid = data.value(0);
        else
            oper_name = GetOperName(oper_id);
            operid = oper_id;
        end;
        itog = data.value(1);
        cnt_ops = data.value(2);
        cnt_rub_zach = data.value(4);
        cnt_ofl = data.value(5);
        cnt_oner = data.value(6);
        cnt_obps = data.value(3) - cnt_rub_zach - cnt_ofl - cnt_oner;
        //итого
        itog_all = itog_all + itog;
        cnt_ops_all = cnt_ops_all + cnt_ops;
        cnt_obps_all = cnt_obps_all + cnt_obps;
        cnt_rub_zach_all = cnt_rub_zach_all + cnt_rub_zach;
        cnt_ofl_all = cnt_ofl_all + cnt_ofl;
        cnt_oner_all = cnt_oner_all + cnt_oner;
        //
        aa.str = oper_name + "|" + operid + "|" + itog + "|" + cnt_ops + "|" + cnt_obps + "|" + cnt_rub_zach + "|" + cnt_ofl + "|" + cnt_oner;
        aa.str = toansi(aa.str, true);
        insert(aa);
        strok_end = strok_end +1;
        UseProgress(_i=_i + 1);
    end;
    aa.str = "Итого: " + "|" + " " + "|" + itog_all + "|" + cnt_ops_all + "|" + cnt_obps_all + "|" + cnt_rub_zach_all + "|" + cnt_ofl_all + "|" + cnt_oner_all;
    aa.str = toansi(aa.str, true);
    insert(aa);
    strok_end = strok_end +1;
    close(aa);
    RemProgress();
end;

macro ShortReportForOper()
    debugbreak;
    var data,sqlString,cmd;
    begaction(2000, "Выполнение запроса к БД...", false);
    message("Выполнение запроса к БД...");
    if (oper_id == 0)
    sqlString = " SELECT   oper, SUM (cnt), SUM (pasp), SUM (npasp), SUM (rubz), SUM (ofl), SUM (oner) " +
                " FROM (SELECT   t_oper AS oper, COUNT (t_oper) AS cnt, 0 AS pasp, 0 AS npasp, 0 AS rubz, 0 AS ofl, 0 AS oner " +
                            " FROM vk_operations_tmp " +
                            " GROUP BY t_oper " +
                        " UNION " +
                        " SELECT   t_oper AS oper, 0 AS cnt, COUNT (*) AS pasp, 0 AS npasp, 0 AS rubz, 0 AS ofl, 0 AS oner " + 
                            " FROM vk_operations_tmp " + 
                            " WHERE t_passportnumber != 'X' " +
                            " GROUP BY t_oper " +
                        " UNION " +
                        " SELECT   t_oper AS oper, 0 AS cnt, 0 AS pasp, COUNT (*) AS npasp, 0 AS rubz, 0 AS ofl, 0 AS oner " +
                            " FROM vk_operations_tmp " +
                            " WHERE t_passportnumber = 'X' " +
                            " GROUP BY t_oper " +
                        " UNION " +
                        " SELECT   t_oper AS oper, 0 AS cnt, 0 AS pasp, 0 AS npasp, COUNT (*) AS rubz, 0 AS ofl, 0 AS oner " +
                            " FROM vk_operations_tmp tmp " + 
                            " WHERE (tmp.t_blockid = 11001117 OR tmp.t_blockid = 11000133) " +
                            " AND tmp.t_fiid = 0 " +
                            " GROUP BY t_oper " +
                        " UNION " +
                        " SELECT   t_oper AS oper, 0 AS cnt, 0 AS pasp, 0 AS npasp, 0 AS rubz, COUNT (*) AS ofl, 0 AS oner " +
                            " FROM vk_operations_tmp tmp " +
                            " WHERE ( tmp.t_blockid = 11000117 " +
                                    " AND (   tmp.t_payeraccount LIKE '423%' " +
                                    " OR tmp.t_payeraccount LIKE '40817%' " +
                                    " OR tmp.t_payeraccount LIKE '426%' " +
                                    " OR tmp.t_payeraccount LIKE '40820%' " +
                                    " OR tmp.t_payeraccount LIKE '40912%' " +
                                    " OR tmp.t_payeraccount LIKE '40913%' ) ) " +
                                " OR ( ( tmp.t_blockid = 11001117 OR tmp.t_blockid = 11000133 OR tmp.t_blockid = 11001777 ) " +
                                    " AND (   tmp.t_receiveraccount LIKE '423%' " +
                                    " OR tmp.t_receiveraccount LIKE '40817%' " +
                                    " OR tmp.t_receiveraccount LIKE '426%' " +
                                    " OR tmp.t_receiveraccount LIKE '40820%' " +
                                    " OR tmp.t_receiveraccount LIKE '40912%' " +
                                    " OR tmp.t_receiveraccount LIKE '40913%' ) ) " +
                            " GROUP BY t_oper " +
                        " UNION " +
                        " SELECT   t_oper AS oper, 0 AS cnt, 0 AS pasp, 0 AS npasp, 0 AS rubz, 0 AS ofl, COUNT (*) AS oner " +
                            " FROM vk_operations_tmp tmp " +
                            " WHERE (    tmp.t_blockid = 11000117 " +
                                " AND tmp.t_payeraccount LIKE '40807%' ) " +
                                " OR (    (   tmp.t_blockid = 11001117 OR tmp.t_blockid = 11000133 OR tmp.t_blockid = 11001777 ) " +
                                " AND tmp.t_receiveraccount LIKE '40807%' ) " +
                        " GROUP BY t_oper) " + 
                " GROUP BY oper ";
    else
        sqlString = " SELECT 0, SUM (cnt), SUM (pasp), SUM (npasp), SUM (rubz), SUM (ofl), SUM (oner) " +
                    " FROM (SELECT COUNT (t_oper) AS cnt, 0 AS pasp, 0 AS npasp, 0 AS rubz, 0 AS ofl, 0 AS oner " +
                                " FROM vk_operations_tmp " +
                                " WHERE t_oper = ? " +
                                " UNION " +
                            " SELECT 0 AS cnt, COUNT (*) AS pasp, 0 AS npasp, 0 AS rubz, 0 AS ofl, 0 AS oner " + 
                                " FROM vk_operations_tmp " +
                                " WHERE t_passportnumber != 'X' AND t_oper = ? " +
                            " UNION " +
                            " SELECT 0 AS cnt, 0 AS pasp, COUNT (*) AS npasp, 0 AS rubz, 0 AS ofl, 0 AS oner " +
                                " FROM vk_operations_tmp " +
                                " WHERE t_passportnumber = 'X' AND t_oper = ? " +
                            " UNION " +
                            " SELECT 0 AS cnt, 0 AS pasp, 0 AS npasp, COUNT (*) AS rubz, 0 AS ofl, 0 AS oner " +
                                " FROM vk_operations_tmp tmp " +
                                " WHERE (tmp.t_blockid = 11001117 OR tmp.t_blockid = 11000133) " +
                                " AND tmp.t_fiid = 0 " +
                                " AND t_oper = ? " +
                            " UNION " +
                            " SELECT 0 AS cnt, 0 AS pasp, 0 AS npasp, 0 AS rubz, COUNT (*) AS ofl, 0 AS oner " +
                                " FROM vk_operations_tmp tmp " +
                                " WHERE t_oper = ? " +
                                " AND (   (    tmp.t_blockid = 11000117 " + 
                                " AND (   tmp.t_payeraccount LIKE '423%' " +
                                " OR tmp.t_payeraccount LIKE '40817%' " +
                                " OR tmp.t_payeraccount LIKE '426%' " +
                                " OR tmp.t_payeraccount LIKE '40820%' " +
                                " OR tmp.t_payeraccount LIKE '40912%' " +
                                " OR tmp.t_payeraccount LIKE '40913%' ) ) " +
                                " OR (    (   tmp.t_blockid = 11001117 " +
                                " OR tmp.t_blockid = 11000133 " +
                                " OR tmp.t_blockid = 11001777 ) " +
                                " AND (   tmp.t_receiveraccount LIKE '423%' " +
                                " OR tmp.t_receiveraccount LIKE '40817%' " +
                                " OR tmp.t_receiveraccount LIKE '426%' " 
                                " OR tmp.t_receiveraccount LIKE '40820%' " +
                                " OR tmp.t_receiveraccount LIKE '40912%' " +
                                " OR tmp.t_receiveraccount LIKE '40913%' ) ) ) " +
                            " UNION " +
                            " SELECT 0 AS cnt, 0 AS pasp, 0 AS npasp, 0 AS rubz, 0 AS ofl, COUNT (*) AS oner " +
                                " FROM vk_operations_tmp tmp " +
                                " WHERE t_oper = ? " +
                                " AND (   (    tmp.t_blockid = 11000117 " +
                                " AND tmp.t_payeraccount LIKE '40807%' ) " +
                                " OR (    (   tmp.t_blockid = 11001117 " +
                                " OR tmp.t_blockid = 11000133 " +
                                " OR tmp.t_blockid = 11001777 ) " +
                                " AND tmp.t_receiveraccount LIKE '40807%' ) ) ) ";
    end;
    cmd = RSDCommand( sqlString );
    if(oper_id != 0)
        cmd.AddParam("party1", RSDBP_IN, oper_id);
        cmd.AddParam("party2", RSDBP_IN, oper_id);
        cmd.AddParam("party3", RSDBP_IN, oper_id);
        cmd.AddParam("party4", RSDBP_IN, oper_id);
        cmd.AddParam("party5", RSDBP_IN, oper_id);
        cmd.AddParam("party6", RSDBP_IN, oper_id);
    end;
    data = RsdRecordset( cmd );
    endaction();
    WriteBodyShortOper(data);
    message("Файл с данными пересылается на терминал!!!");
    copyToMe();
    message("Запускается  EXCEL");
    ob = CreateObject ("rsax","TRsAxServer","RsAxServer",IsStandAlone());
    ex = ob.CreateComObject ("Excel.Application", True);
    ex.ReferenceStyle = -4150; //R1C1
    ex.visible=false;
    if (not(GetFileInfo("$"+tempFileNameBezPuti,@dd,@tt,@ii,@ss))); //ss - 
       msgbox("Не удалось найти на локальном диске файл "+tempFileNameBezPuti+"   \n останавливаюсь");
       exit(0);
    end;
    ss = substr(ss,2); 
    var aw=tarray;
    
    var w1=tarray;  var w2=tarray;  var w3=tarray;  var w4=tarray;
    var w5=tarray;  var w6=tarray;  var w7=tarray;  var w8=tarray;
    //Формат: 1 - общий, 2 - текст
    w1(0)=1; w1(1)=1;       w2(0)=2; w2(1)=1;       w3(0)=3; w3(1)=1;       w4(0)=4; w4(1)=1;
    w5(0)=5; w5(1)=1;       w6(0)=6; w6(1)=1;       w7(0)=7; w7(1)=1;       w8(0)=8; w8(1)=1;
    
    aw(0)=w1;       aw(1)=w2;       aw(2)=w3;       aw(3)=w4;
    aw(4)=w5;       aw(5)=w6;       aw(6)=w7;       aw(7)=w8;
     
    aw.MarshalByVal =true; 
    w1.MarshalByVal =true;      w2.MarshalByVal =true;      w3.MarshalByVal =true;      w4.MarshalByVal =true;
    w5.MarshalByVal =true;      w6.MarshalByVal =true;      w7.MarshalByVal =true;      w8.MarshalByVal =true;
    
    begaction(2000, "Файл данных загружается в EXCEL", false);
    message("Файл данных загружается в EXCEL");
    
    obBook = ex.Workbooks.opentext(ss,1251,1,1,2,false,false,false,false,false,true,"|",aw,1,"."," ",true,true);
    endaction;
    strok_begin = 2;
    obSheet=ex.Sheets(1);
    ex.Sheets(1).Rows("1:1").Insert(-4121); strok_begin = strok_begin +1; strok_end = strok_end +1;
    ex.Sheets(1).Rows("1:1").Insert(-4121); strok_begin = strok_begin +1; strok_end = strok_end +1;
    ex.Sheets(1).Rows("1:1").Insert(-4121); strok_begin = strok_begin +1; strok_end = strok_end +1;
    
    begaction(2000,"Данные загружены в EXCEL, производится форматирвоание...", false);
    message("Данные загружены в EXCEL, производится форматирвоание...");
    
    WriteHeadForShortOper();
    format_osv(strok_begin, strok_end);
    endaction;
    println;
    println("Отчет сформирован. Для продолжения нажмите ESC ");
    ex.visible=true;
end;

/******************************************* Краткий отчет по операционистам ВК (end) **********************************************/

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Вспомогательная функция джля отчета по офисам
macro GetInfoForBranch( branch_id)
    var sqlString, cmd, data;
    sqlString = " SELECT   oper, SUM (cnt), SUM (pasp), SUM (npasp), SUM (rubz), SUM (ofl), SUM (oner) " +
                " FROM (SELECT   t_oper AS oper, COUNT (t_oper) AS cnt, 0 AS pasp, 0 AS npasp, 0 AS rubz, 0 AS ofl, 0 AS oner " +
                            " FROM vk_operations_tmp ";
        if(branch_id == -1)
            sqlString = sqlString + " WHERE t_branch NOT IN (13, 15, 19, 66, 179, 662066) ";
        else
            sqlString = sqlString + " WHERE t_branch = ? ";
        end;
    sqlString = sqlString +
                        " GROUP BY t_oper " +
                        " UNION " +
                        " SELECT   t_oper AS oper, 0 AS cnt, COUNT (*) AS pasp, 0 AS npasp, 0 AS rubz, 0 AS ofl, 0 AS oner " +
                            " FROM vk_operations_tmp " +
                            " WHERE t_passportnumber != 'X' AND ";
        if(branch_id == -1)
            sqlString = sqlString + " t_branch NOT IN (13, 15, 19, 66, 179, 662066) ";
        else
            sqlString = sqlString + " t_branch = ? ";
        end;
    sqlString = sqlString + 
                            " GROUP BY t_oper " +
                        " UNION " +
                        " SELECT   t_oper AS oper, 0 AS cnt, 0 AS pasp, COUNT (*) AS npasp, 0 AS rubz, 0 AS ofl, 0 AS oner " +
                            " FROM vk_operations_tmp " +
                            " WHERE t_passportnumber = 'X' AND ";
        if(branch_id == -1)
            sqlString = sqlString + " t_branch NOT IN (13, 15, 19, 66, 179, 662066) ";
        else
            sqlString = sqlString + " t_branch = ? ";
        end;
    sqlString = sqlString + 
                            " GROUP BY t_oper " +
                        " UNION " +
                        " SELECT   t_oper AS oper, 0 AS cnt, 0 AS pasp, 0 AS npasp, COUNT (*) AS rubz, 0 AS ofl, 0 AS oner " +
                            " FROM vk_operations_tmp tmp " +
                            " WHERE (tmp.t_blockid = 11001117 OR tmp.t_blockid = 11000133) " +
                            " AND tmp.t_fiid = 0  AND" ;
        if(branch_id == -1)
            sqlString = sqlString + " t_branch NOT IN (13, 15, 19, 66, 179, 662066) ";
        else
            sqlString = sqlString + " t_branch = ? ";
        end;
    sqlString = sqlString + 
                            " GROUP BY t_oper " +
                        " UNION " +
                        " SELECT   t_oper AS oper, 0 AS cnt, 0 AS pasp, 0 AS npasp, 0 AS rubz, COUNT (*) AS ofl, 0 AS oner " +
                            " FROM vk_operations_tmp tmp " ;
        if(branch_id == -1)
            sqlString = sqlString + " WHERE  t_branch NOT IN (13, 15, 19, 66, 179, 662066) ";
        else
            sqlString = sqlString + " WHERE t_branch = ? ";
        end;
    sqlString = sqlString +
                               " AND ( ( tmp.t_blockid = 11000117 " +
                                        " AND (   tmp.t_payeraccount LIKE '423%' " +
                                        " OR tmp.t_payeraccount LIKE '40817%' " +
                                        " OR tmp.t_payeraccount LIKE '426%' " +
                                        " OR tmp.t_payeraccount LIKE '40820%' " +
                                        " OR tmp.t_payeraccount LIKE '40912%' " +
                                        " OR tmp.t_payeraccount LIKE '40913%' ) ) " +
                                " OR ( ( tmp.t_blockid = 11001117 OR tmp.t_blockid = 11000133 OR tmp.t_blockid = 11001777 ) " +
                                        " AND (   tmp.t_receiveraccount LIKE '423%' " +
                                        " OR tmp.t_receiveraccount LIKE '40817%' " +
                                        " OR tmp.t_receiveraccount LIKE '426%' " +
                                        " OR tmp.t_receiveraccount LIKE '40820%' " +
                                        " OR tmp.t_receiveraccount LIKE '40912%' " + 
                                        " OR tmp.t_receiveraccount LIKE '40913%' ) ) ) " +
                            " GROUP BY t_oper " +
                        " UNION " +
                        " SELECT   t_oper AS oper, 0 AS cnt, 0 AS pasp, 0 AS npasp, 0 AS rubz, 0 AS ofl, COUNT (*) AS oner " +
                            " FROM vk_operations_tmp tmp ";
    if(branch_id == -1)
            sqlString = sqlString + " WHERE  t_branch NOT IN (13, 15, 19, 66, 179, 662066) ";
        else
            sqlString = sqlString + " WHERE t_branch = ? ";
        end;
    sqlString = sqlString +
                           " AND ( ( tmp.t_blockid = 11000117 AND tmp.t_payeraccount LIKE '40807%' ) " +
                                        " OR ( ( tmp.t_blockid = 11001117 OR tmp.t_blockid = 11000133 OR tmp.t_blockid = 11001777 ) " +
                                                " AND tmp.t_receiveraccount LIKE '40807%' ) ) " +
                            " GROUP BY t_oper) " +
                " GROUP BY oper " ;
    cmd = RSDCommand( sqlString );
    if(branch_id != -1)
        cmd.AddParam("party1", RSDBP_IN, branch_id);
        cmd.AddParam("party2", RSDBP_IN, branch_id);
        cmd.AddParam("party3", RSDBP_IN, branch_id);
        cmd.AddParam("party4", RSDBP_IN, branch_id);
        cmd.AddParam("party5", RSDBP_IN, branch_id);
        cmd.AddParam("party6", RSDBP_IN, branch_id);
    end;
    cmd.execute;
    data = RsdRecordset( cmd );
    return data;
end;
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

/******************************************* Полный отчет по офисам (begin) ********************************************************/
macro WriteHeadForFullDepartment()
     private var m_range:string="A"+(che+1)+":H"+(che+1);
    obSheet.Cells(1,1).Value= "Полный отчет по операциям валютных контролеров в разрезе офисов";
    obSheet.Cells(2,1).Value= "За период с " + begin_date + " по " + end_date;
    if ( dep_id == 0)
        obSheet.Cells(3,1).Value = "По всем офисам ";
    else
        obSheet.Cells(3,1).Value = "По офису: " + GetPartyName(dep_id);
    end;
    
    obSheet.Cells(che + 1,1).Value= "ФИО операциониста ВК";
    obSheet.Cells(che + 1,2).Value= "Код операциониста ВК";
    obSheet.Cells(che + 1,3).Value= "Итого";
    obSheet.Cells(che + 1,4).Value= "ОПС";
    obSheet.Cells(che + 1,5).Value= "ОбПС";
    obSheet.Cells(che + 1,6).Value= "РубЗ";
    obSheet.Cells(che + 1,7).Value= "ОФЛР/Н";
    obSheet.Cells(che + 1,8).Value= "ОНЮЛ";
    
    obSheet.Range(m_range).Borders.Weight=2;
    obSheet.Range(m_range).interior.color=4035000;
    obSheet.Range(m_range).HorizontalAlignment = xlCenter;
    obSheet.Range(m_range).font.Name = "Calibri";
    obSheet.Range(m_range).font.FontStyle = "bold";
    obSheet.Range(m_range).font.Size = 12;
    obSheet.Columns("A:A").ColumnWidth = 20;
    var format_str:string = "# ##0" + ex.International(3) + "00";
    obSheet.Columns("B:H").EntireColumn.AutoFit;
end;

macro WriteBodyFullDepartment(aa, data, close)
    //переменные данных в отчет
    var close_aa = close;
    var oper_name, operid, itog, cnt_ops, cnt_obps, cnt_rub_zach, cnt_ofl, cnt_oner, itog_all = 0, cnt_ops_all = 0, cnt_obps_all = 0, cnt_rub_zach_all = 0, cnt_ofl_all = 0, cnt_oner_all = 0;
    i = che + 2;
    i_old = i;
    InitProgress(-1, "Отобранные операции выводятся в файл. Период операций с " + begin_date + " по " + end_date);
    var first_row:bool = true;
    while(data.movenext)
        //Выводим инфу
        oper_name = GetOperName(data.value(0));
        operid = data.value(0);
        itog = data.value(1);
        cnt_ops = data.value(2);
        cnt_rub_zach = data.value(4);
        cnt_ofl = data.value(5);
        cnt_oner = data.value(6);
        cnt_obps = data.value(3) - cnt_rub_zach - cnt_ofl - cnt_oner;
        aa.str = oper_name + "|" + operid + "|" + itog + "|" + cnt_ops + "|" + cnt_obps + "|" + cnt_rub_zach + "|" + cnt_ofl + "|" + cnt_oner;
        aa.str = toansi(aa.str, true);
        insert(aa);
        strok_end = strok_end +1;
        UseProgress(_i=_i + 1);
        //сводные данные
        itog_all = itog_all + itog;
        cnt_ops_all = cnt_ops_all + cnt_ops;
        cnt_obps_all = cnt_obps_all + cnt_obps;
        cnt_rub_zach_all = cnt_rub_zach_all + cnt_rub_zach;
        cnt_ofl_all = cnt_ofl_all + cnt_ofl;
        cnt_oner_all = cnt_oner_all + cnt_oner;
    end;
    //Итого
    dep_name = "Итого: ";
    aa.str = dep_name + "|" + " " + "|" + itog_all + "|" + cnt_ops_all + "|" + cnt_obps_all + "|" + cnt_rub_zach_all + "|" + cnt_ofl_all + "|" + cnt_oner_all;
    aa.str = toansi(aa.str, true);
    insert(aa);
    strok_end = strok_end +1;
    if(close_aa == true)
        close(aa);
    end;
    RemProgress();
end;

macro FullReportForDepartment(xx, department, all)
    debugbreak;
    var data, sqlString, cmd, i = 0;
    begaction(2000, "Выполнение запроса к БД...", false);
    message("Выполнение запроса к БД...");
    data = GetInfoForBranch(department);
    endaction();
    dep_id = department;
    if (all = 1)
        WriteBodyFullDepartment(xx, data, false);
    else
        WriteBodyFullDepartment(xx, data, true);
    end;
end;

macro FullReportForDepartments()
    debugbreak;
    var shab = "Наименование офиса";
    createUniqueFile();
    FILE aa () txt write;
    open(aa, tempFileName);
    aa.str = " ";
    insert(aa);
    strok_end = strok_end +1;
    if( dep_id != 0)
       FullReportForDepartment(aa, dep_id, 0);
    else 
        //наименование офиса
        aa.str = shab + "|" + GetPartyName(15);
        aa.str = toansi(aa.str, true);
        insert(aa);
        strok_end = strok_end +1;
        FullReportForDepartment(aa, 15, 1);
        /*****************************************/
        aa.str = shab + "|" + GetPartyName(19);
        aa.str = toansi(aa.str, true);
        insert(aa);
        strok_end = strok_end +1;
        FullReportForDepartment(aa, 19, 1);
        /*****************************************/
        aa.str = shab + "|" + GetPartyName(66);
        aa.str = toansi(aa.str, true);
        insert(aa);
        strok_end = strok_end +1;
        FullReportForDepartment(aa, 66, 1);
        /*****************************************/
        aa.str = shab + "|" + GetPartyName(179);
        aa.str = toansi(aa.str, true);
        insert(aa);
        strok_end = strok_end +1;
        FullReportForDepartment(aa, 179, 1);
        /*****************************************/
        aa.str = shab + "|" + GetPartyName(662066);
        aa.str = toansi(aa.str, true);
        insert(aa);
        FullReportForDepartment(aa, 662066, 1);
        /*****************************************/
        aa.str = shab + "|" + GetPartyName(-1);
        aa.str = toansi(aa.str, true);
        insert(aa);
        strok_end = strok_end +1;
        FullReportForDepartment(aa, -1, 1);
        /*****************************************/
        dep_id = 0;
    end;
    close(aa);
    message("Файл с данными пересылается на терминал!!!");
    copyToMe();
    message("Запускается  EXCEL");
    ob = CreateObject ("rsax","TRsAxServer","RsAxServer",IsStandAlone());
    ex = ob.CreateComObject ("Excel.Application", True);
    ex.ReferenceStyle = -4150; //R1C1
    ex.visible=false;
    if (not(GetFileInfo("$"+tempFileNameBezPuti,@dd,@tt,@ii,@ss))); //ss - 
       msgbox("Не удалось найти на локальном диске файл "+tempFileNameBezPuti+"   \n останавливаюсь");
       exit(0);
    end;
    ss = substr(ss,2); 
    var aw=tarray;
    
    var w1=tarray;  var w2=tarray;  var w3=tarray;  var w4=tarray;
    var w5=tarray;  var w6=tarray;  var w7=tarray;
    
    //Формат: 1 - общий, 2 - текст
    w1(0)=1; w1(1)=1;       w2(0)=2; w2(1)=1;       w3(0)=3; w3(1)=1;       w4(0)=4; w4(1)=1;
    w5(0)=5; w5(1)=1;       w6(0)=6; w6(1)=1;       w7(0)=7; w7(1)=1;
    
    aw(0)=w1;       aw(1)=w2;       aw(2)=w3;       aw(3)=w4;
    aw(4)=w5;       aw(5)=w6;       aw(6)=w7;       
    
    aw.MarshalByVal =true; 
    w1.MarshalByVal =true;      w2.MarshalByVal =true;      w3.MarshalByVal =true;      w4.MarshalByVal =true;
    w5.MarshalByVal =true;      w6.MarshalByVal =true;      w7.MarshalByVal =true;      
    
    begaction(2000, "Файл данных загружается в EXCEL", false);
    message("Файл данных загружается в EXCEL");
    
    obBook = ex.Workbooks.opentext(ss,1251,1,1,2,false,false,false,false,false,true,"|",aw,1,"."," ",true,true);
    endaction;
    strok_begin = 2;
    obSheet=ex.Sheets(1);
    ex.Sheets(1).Rows("1:1").Insert(-4121); strok_begin = strok_begin +1; strok_end = strok_end +1;
    ex.Sheets(1).Rows("1:1").Insert(-4121); strok_begin = strok_begin +1; strok_end = strok_end +1;
    ex.Sheets(1).Rows("1:1").Insert(-4121); strok_begin = strok_begin +1; strok_end = strok_end +1;
    
    begaction(2000,"Данные загружены в EXCEL, производится форматирвоание...", false);
    message("Данные загружены в EXCEL, производится форматирвоание...");
    
    WriteHeadForFullDepartment();
    format_osv(strok_begin, strok_end);
    endaction;
    println;
    println("Отчет сформирован. Для продолжения нажмите ESC ");
    ex.visible=true; 
    
end;
/******************************************* Полный отчет по офисам (end) **********************************************************/


/******************************************* Краткий отчет по офисам (begin) **********************************************************/
macro WriteHeadForShortDepartment()
     private var m_range:string="A"+(che+1)+":H"+(che+1);
    obSheet.Cells(1,1).Value= "Краткий отчет по операциям валютных контролеров в разрезе офисов";
    obSheet.Cells(2,1).Value= "За период с " + begin_date + " по " + end_date;
       
    obSheet.Cells(che + 1,1).Value= "Наименование офиса";
    obSheet.Cells(che + 1,2).Value= "Код офиса";
    obSheet.Cells(che + 1,3).Value= "Итого";
    obSheet.Cells(che + 1,4).Value= "ОПС";
    obSheet.Cells(che + 1,5).Value= "ОбПС";
    obSheet.Cells(che + 1,6).Value= "РубЗ";
    obSheet.Cells(che + 1,7).Value= "ОФЛР/Н";
    obSheet.Cells(che + 1,8).Value= "ОНЮЛ";
    
    obSheet.Range(m_range).Borders.Weight=2;
    obSheet.Range(m_range).interior.color=4035000;
    obSheet.Range(m_range).HorizontalAlignment = xlCenter;
    obSheet.Range(m_range).font.Name = "Calibri";
    obSheet.Range(m_range).font.FontStyle = "bold";
    obSheet.Range(m_range).font.Size = 12;
    obSheet.Columns("A:A").ColumnWidth = 20;
    var format_str:string = "# ##0" + ex.International(3) + "00";
    obSheet.Columns("B:H").EntireColumn.AutoFit;
end;

macro WriteBodyShortDepartment(data)
    //переменные данных в отчет
    var dep_name, depid, itog , cnt_ops , cnt_obps , cnt_rub_zach , cnt_ofl , cnt_oner , itog_reg = 0 , cnt_ops_reg = 0 , cnt_obps_reg = 0, cnt_rub_zach_reg = 0, cnt_ofl_reg = 0, cnt_oner_reg = 0, itog_all = 0 , cnt_ops_all = 0, cnt_obps_all = 0, cnt_rub_zach_all = 0, cnt_ofl_all = 0, cnt_oner_all = 0;
    i = che + 2;
    i_old = i;
    InitProgress(-1, "Отобранные операции выводятся в файл. Период операций с " + begin_date + " по " + end_date);
    createUniqueFile();
    FILE aa () txt write;
    open(aa, tempFileName);
    aa.str = " ";
    insert(aa);
    var first_row:bool = true;
    if(dep_id == 0)
        while(data.movenext)
            if ((data.value(0) == 13) or (data.value(0) == 15)  or (data.value(0) == 19)
            or (data.value(0) == 66)  or (data.value(0) == 179) or (data.value(0) == 662066))
                //Выводим инфу
                dep_name = GetPartyName(data.value(0));
                depid = data.value(0);
                itog = data.value(1);
                cnt_ops = data.value(2);
                cnt_rub_zach = data.value(4);
                cnt_ofl = data.value(5);
                cnt_oner = data.value(6);
                cnt_obps = data.value(3) - cnt_rub_zach - cnt_ofl - cnt_oner;
                aa.str = dep_name + "|" + depid + "|" + itog + "|" + cnt_ops + "|" + cnt_obps + "|" + cnt_rub_zach + "|" + cnt_ofl + "|" + cnt_oner;
                aa.str = toansi(aa.str, true);
                insert(aa);
                strok_end = strok_end +1;
                //сводные данные
                itog_all = itog_all + itog;
                cnt_ops_all = cnt_ops_all + cnt_ops;
                cnt_obps_all = cnt_obps_all + cnt_obps;
                cnt_rub_zach_all = cnt_rub_zach_all + cnt_rub_zach;
                cnt_ofl_all = cnt_ofl_all + cnt_ofl;
                cnt_oner_all = cnt_oner_all + cnt_oner;
                UseProgress(_i=_i + 1);
            else
                itog_reg = itog_reg + data.value(1);
                cnt_ops_reg = cnt_ops_reg + data.value(2);
                cnt_rub_zach_reg = cnt_rub_zach_reg + data.value(4);
                cnt_ofl_reg = cnt_ofl_reg + data.value(5);
                cnt_oner_reg = cnt_oner_reg + data.value(6);
                cnt_obps_reg = cnt_obps_reg + data.value(3) - data.value(4) - data.value(5) - data.value(6);
                UseProgress(_i=_i + 1);
            end;
        end;
        //сводные данные
        itog_all = itog_all + itog_reg;
        cnt_ops_all = cnt_ops_all + cnt_ops_reg;
        cnt_obps_all = cnt_obps_all + cnt_obps_reg;
        cnt_rub_zach_all = cnt_rub_zach_all + cnt_rub_zach_reg;
        cnt_ofl_all = cnt_ofl_all + cnt_ofl_reg;
        cnt_oner_all = cnt_oner_all + cnt_oner_reg;
        //выводим по региональным
        dep_name = GetPartyName(-1);
        dep_id = " ";
        aa.str = dep_name + "|" + depid + "|" + itog_reg + "|" + cnt_ops_reg + "|" + cnt_obps_reg + "|" + cnt_rub_zach_reg + "|" + cnt_ofl_reg + "|" + cnt_oner_reg;
        aa.str = toansi(aa.str, true);
        insert(aa);
        strok_end = strok_end +1;
        //Итого
        dep_name = "Итого: ";
        aa.str = dep_name + "|" + " " + "|" + itog_all + "|" + cnt_ops_all + "|" + cnt_obps_all + "|" + cnt_rub_zach_all + "|" + cnt_ofl_all + "|" + cnt_oner_all;
        aa.str = toansi(aa.str, true);
        insert(aa);
        strok_end = strok_end +1;
        //региональные 
        close(aa);
        RemProgress();
    else
        while(data.movenext)
            dep_name = GetPartyName(dep_id);
            depid = dep_id;
            itog = data.value(0);
            cnt_ops = data.value(1);
            cnt_rub_zach = data.value(3);
            cnt_ofl = data.value(4);
            cnt_oner = data.value(5);
            cnt_obps = data.value(2) - cnt_rub_zach - cnt_ofl - cnt_oner;
            aa.str = dep_name + "|" + depid + "|" + itog + "|" + cnt_ops + "|" + cnt_obps + "|" + cnt_rub_zach + "|" + cnt_ofl + "|" + cnt_oner;
            aa.str = toansi(aa.str, true);
            insert(aa);
            strok_end = strok_end +1;
            UseProgress(_i=_i + 1);
        end;
        //Итого
        dep_name = "Итого: ";
        aa.str = dep_name + "|" +" " + "|" + itog + "|" + cnt_ops + "|" + cnt_obps + "|" + cnt_rub_zach + "|" + cnt_ofl + "|" + cnt_oner;
        aa.str = toansi(aa.str, true);
        insert(aa);
        strok_end = strok_end +1;
        //региональные 
        close(aa);
        RemProgress();
    end;
end;

macro ShortReportForDepartment()
    debugbreak;
    var data, sqlString, cmd, i = 0;
    //msgbox("Полный отчет по операционистами");
    begaction(2000, "Выполнение запроса к БД...", false);
    message("Выполнение запроса к БД...");
    //выьираем всё что есть в vk_operations_tmp
    if( dep_id == 0)
        sqlString = " SELECT   branch, SUM (cnt), SUM (pasp), SUM (npasp), SUM (rubz), SUM (ofl), SUM (oner) " +
                " FROM (SELECT   t_branch AS branch, COUNT (t_branch) AS cnt, 0 AS pasp, 0 AS npasp, 0 AS rubz, 0 AS ofl, 0 AS oner " +
                            " FROM vk_operations_tmp " +
                            " GROUP BY t_branch " +
                        " UNION " +
                        " SELECT   t_branch AS branch, 0 AS cnt, COUNT (*) AS pasp, 0 AS npasp, 0 AS rubz, 0 AS ofl, 0 AS oner " +
                            " FROM vk_operations_tmp " +
                            " WHERE t_passportnumber != 'X' " +
                            " GROUP BY t_branch " +
                        " UNION " +
                        " SELECT   t_branch AS branch, 0 AS cnt, 0 AS pasp, COUNT(*) AS npasp, 0 AS rubz, 0 AS ofl, 0 AS oner " +
                            " FROM vk_operations_tmp " +
                            " WHERE t_passportnumber = 'X' " +
                            " GROUP BY t_branch " +
                        " UNION " +
                        " SELECT   t_branch AS branch, 0 AS cnt, 0 AS pasp, 0 AS npasp, COUNT (*) AS rubz, 0 AS ofl, 0 AS oner " +
                            " FROM vk_operations_tmp tmp " +
                            " WHERE (tmp.t_blockid = 11001117 OR tmp.t_blockid = 11000133) " +
                            " AND tmp.t_fiid = 0 " +
                            " GROUP BY t_branch " +
                        " UNION " +
                        " SELECT   t_branch AS branch, 0 AS cnt, 0 AS pasp, 0 AS npasp, 0 AS rubz, COUNT (*) AS ofl, 0 AS oner " +
                            " FROM vk_operations_tmp tmp " +
                            " WHERE ( tmp.t_blockid = 11000117 " +
                                        " AND ( tmp.t_payeraccount LIKE '423%' " +
                                            " OR tmp.t_payeraccount LIKE '40817%' " +
                                            " OR tmp.t_payeraccount LIKE '426%' " +
                                            " OR tmp.t_payeraccount LIKE '40820%' " +
                                            " OR tmp.t_payeraccount LIKE '40912%' " +
                                            " OR tmp.t_payeraccount LIKE '40913%' ) ) " +
                                    " OR ( ( tmp.t_blockid = 11001117 OR tmp.t_blockid = 11000133 OR tmp.t_blockid = 11001777 ) " +
                                        " AND (   tmp.t_receiveraccount LIKE '423%' " +
                                            " OR tmp.t_receiveraccount LIKE '40817%' " +
                                            " OR tmp.t_receiveraccount LIKE '426%' " +
                                            " OR tmp.t_receiveraccount LIKE '40820%' " +
                                            " OR tmp.t_receiveraccount LIKE '40912%'  " +
                                            " OR tmp.t_receiveraccount LIKE '40913%' ) ) " +
                            " GROUP BY t_branch " +
                        " UNION " +
                        " SELECT   t_branch AS branch, 0 AS cnt, 0 AS pasp, 0 AS npasp, 0 AS rubz, 0 AS ofl, COUNT (*) AS oner " + 
                            " FROM vk_operations_tmp tmp " +
                            " WHERE ( tmp.t_blockid = 11000117 AND tmp.t_payeraccount LIKE '40807%' ) " +
                               " OR ( ( tmp.t_blockid = 11001117 OR tmp.t_blockid = 11000133 OR tmp.t_blockid = 11001777 ) " +
                                    " AND tmp.t_receiveraccount LIKE '40807%' ) " +
                            " GROUP BY t_branch) " +
                " GROUP BY branch ";
    else
        sqlString = " SELECT SUM (cnt), SUM (pasp), SUM (npasp), SUM (rubz), SUM (ofl), SUM (oner) " +
                    " FROM (SELECT COUNT (t_branch) AS cnt, 0 AS pasp, 0 AS npasp, 0 AS rubz, 0 AS ofl, 0 AS oner " +
                           " FROM vk_operations_tmp ";
            if(dep_id != -1)
                sqlString = sqlString + " WHERE t_branch = ? ";
            else
                sqlString = sqlString + " WHERE  t_branch NOT IN (13, 15, 19, 66, 179, 662066) ";
            end;
        sqlString = sqlString +
                            " UNION " +
                            " SELECT 0 AS cnt, COUNT (*) AS pasp, 0 AS npasp, 0 AS rubz, 0 AS ofl, 0 AS oner " +
                                " FROM vk_operations_tmp " +
                                " WHERE t_passportnumber != 'X' AND ";
            if(dep_id != -1)
                sqlString = sqlString + " t_branch = ? ";
            else
                sqlString = sqlString + " t_branch NOT IN (13, 15, 19, 66, 179, 662066) ";
            end;
        sqlString = sqlString +
                            " UNION " +
                            " SELECT 0 AS cnt, 0 AS pasp, COUNT (*) AS npasp, 0 AS rubz, 0 AS ofl, 0 AS oner " +
                                " FROM vk_operations_tmp " +
                                " WHERE t_passportnumber = 'X' AND ";
            if(dep_id != -1)
                sqlString = sqlString + " t_branch = ? ";
            else
                sqlString = sqlString + " t_branch NOT IN (13, 15, 19, 66, 179, 662066) ";
            end;
        sqlString = sqlString +
                            " UNION " +
                            " SELECT 0 AS cnt, 0 AS pasp, 0 AS npasp, COUNT (*) AS rubz, 0 AS ofl, 0 AS oner " +
                                " FROM vk_operations_tmp tmp " +
                                " WHERE (tmp.t_blockid = 11001117 OR tmp.t_blockid = 11000133) " +
                                " AND tmp.t_fiid = 0 ";
            if(dep_id != -1)
                sqlString = sqlString + " AND t_branch = ? ";
            else
                sqlString = sqlString + " AND t_branch NOT IN (13, 15, 19, 66, 179, 662066) ";
            end;
        sqlString = sqlString +
                            " UNION " +
                            " SELECT 0 AS cnt, 0 AS pasp, 0 AS npasp, 0 AS rubz, COUNT (*) AS ofl, 0 AS oner " +
                                " FROM vk_operations_tmp tmp ";
            if(dep_id != -1)
                sqlString = sqlString + " WHERE t_branch = ? ";
            else
                sqlString = sqlString + " WHERE t_branch NOT IN (13, 15, 19, 66, 179, 662066) ";
            end;
        sqlString = sqlString +
                                " AND (   (    tmp.t_blockid = 11000117 " +
                                " AND (   tmp.t_payeraccount LIKE '423%' " +
                                " OR tmp.t_payeraccount LIKE '40817%' " +
                                " OR tmp.t_payeraccount LIKE '426%' " +
                                " OR tmp.t_payeraccount LIKE '40820%' " +
                                " OR tmp.t_payeraccount LIKE '40912%' " +
                                " OR tmp.t_payeraccount LIKE '40913%' ) ) " +
                                " OR (    (   tmp.t_blockid = 11001117 " +
                                " OR tmp.t_blockid = 11000133 " +
                                " OR tmp.t_blockid = 11001777 ) " +
                                " AND (   tmp.t_receiveraccount LIKE '423%' " +
                                " OR tmp.t_receiveraccount LIKE '40817%' " +
                                " OR tmp.t_receiveraccount LIKE '426%' " +
                                " OR tmp.t_receiveraccount LIKE '40820%' " +
                                " OR tmp.t_receiveraccount LIKE '40912%' " +
                                " OR tmp.t_receiveraccount LIKE '40913%' ) ) ) " +
                            " UNION " +
                            " SELECT 0 AS cnt, 0 AS pasp, 0 AS npasp, 0 AS rubz, 0 AS ofl, COUNT (*) AS oner " +
                                " FROM vk_operations_tmp tmp ";
            if(dep_id != -1)
                sqlString = sqlString + " WHERE t_branch = ? ";
            else
                sqlString = sqlString + " WHERE t_branch NOT IN (13, 15, 19, 66, 179, 662066) ";
            end;
        sqlString = sqlString +
                                " AND (   (    tmp.t_blockid = 11000117 " +
                                " AND tmp.t_payeraccount LIKE '40807%' ) " +
                                " OR (    (   tmp.t_blockid = 11001117 " +
                                " OR tmp.t_blockid = 11000133 " +
                                " OR tmp.t_blockid = 11001777 ) " +
                                " AND tmp.t_receiveraccount LIKE '40807%' ) ) ) ";
    end;
    cmd = RSDCommand( sqlString );
    if((dep_id != -1) and (dep_id != 0))
        cmd.AddParam("party1", RSDBP_IN, dep_id);
        cmd.AddParam("party2", RSDBP_IN, dep_id);
        cmd.AddParam("party3", RSDBP_IN, dep_id);
        cmd.AddParam("party4", RSDBP_IN, dep_id);
        cmd.AddParam("party5", RSDBP_IN, dep_id);
        cmd.AddParam("party6", RSDBP_IN, dep_id);
    end;
    data = RsdRecordset( cmd );
    endaction();
    WriteBodyShortDepartment(data);
    message("Файл с данными пересылается на терминал!!!");
    copyToMe();
    message("Запускается  EXCEL");
    ob = CreateObject ("rsax","TRsAxServer","RsAxServer",IsStandAlone());
    ex = ob.CreateComObject ("Excel.Application", True);
    ex.ReferenceStyle = -4150; //R1C1
    ex.visible=false;
    if (not(GetFileInfo("$"+tempFileNameBezPuti,@dd,@tt,@ii,@ss))); //ss - 
       msgbox("Не удалось найти на локальном диске файл "+tempFileNameBezPuti+"   \n останавливаюсь");
       exit(0);
    end;
    ss = substr(ss,2); 
    var aw=tarray;
    
    var w1=tarray;  var w2=tarray;  var w3=tarray;  var w4=tarray;
    var w5=tarray;  var w6=tarray;  var w7=tarray;
    
    //Формат: 1 - общий, 2 - текст
    w1(0)=1; w1(1)=1;       w2(0)=2; w2(1)=1;       w3(0)=3; w3(1)=1;       w4(0)=4; w4(1)=1;
    w5(0)=5; w5(1)=1;       w6(0)=6; w6(1)=1;       w7(0)=7; w7(1)=1;
    
    aw(0)=w1;       aw(1)=w2;       aw(2)=w3;       aw(3)=w4;
    aw(4)=w5;       aw(5)=w6;       aw(6)=w7;       
    
    aw.MarshalByVal =true; 
    w1.MarshalByVal =true;      w2.MarshalByVal =true;      w3.MarshalByVal =true;      w4.MarshalByVal =true;
    w5.MarshalByVal =true;      w6.MarshalByVal =true;      w7.MarshalByVal =true;      
    
    begaction(2000, "Файл данных загружается в EXCEL", false);
    message("Файл данных загружается в EXCEL");
    
    obBook = ex.Workbooks.opentext(ss,1251,1,1,2,false,false,false,false,false,true,"|",aw,1,"."," ",true,true);
    endaction;
    strok_begin = 2;
    obSheet=ex.Sheets(1);
    ex.Sheets(1).Rows("1:1").Insert(-4121); strok_begin = strok_begin +1; strok_end = strok_end +1;
    ex.Sheets(1).Rows("1:1").Insert(-4121); strok_begin = strok_begin +1; strok_end = strok_end +1;
    ex.Sheets(1).Rows("1:1").Insert(-4121); strok_begin = strok_begin +1; strok_end = strok_end +1;
    
    begaction(2000,"Данные загружены в EXCEL, производится форматирвоание...", false);
    message("Данные загружены в EXCEL, производится форматирвоание...");
    
    WriteHeadForShortDepartment();
    format_osv(strok_begin, strok_end);
    endaction;
    println;
    println("Отчет сформирован. Для продолжения нажмите ESC ");
    ex.visible=true; 
    
end;
/******************************************* Краткий отчет по офисам (end) **********************************************************/



/*Точка входа в макрос */
if (RunDialog(dlg, "Event"))
     debugbreak;                                                                
    //очищаем вспомогательную таблицу vk_operations_tmp
    var cmd = RsdCommand("TRUNCATE TABLE vk_operations_tmp");
    cmd.execute();
    //заполняем таблицу всеми операциями ВК  за указанный период
    FillTmpTable();
    if(oper_report == true)
        if(full_report == true)
            FullReportForOper();
        else
            ShortReportForOper();
        end;
    else
        if(full_report == true)
            FullReportForDepartments();
        else
            ShortReportForDepartment();
        end;
    end;
end;