//Gurin S. 22.04.2015 I-00563524-2
Import RSD, Календарь, globals,rsbdataset,treport;

 var ds, sql;
 var sum_rub;
 var i:integer=0;
 var tek_cod,pred_cod;
 var table1=ctablereport();
   	table1.addcolumn("N",5,AL_RIGHT);
   	table1.addcolumn("код клиента",8,AL_RIGHT);
   	table1.addcolumn("наименование счета",50,AL_RIGHT);
   	table1.addcolumn("счет ",25,AL_LEFT);
   	table1.addcolumn("опер",8,AL_LEFT);
   	table1.addcolumn("рублевые остатки",10,AL_right);
   	table1.addcolumn("валютные остатки",10,AL_right);
   	      table1.printhead("остатки на 1е января 2011 года");

 var d;
 DateSplit({curdate}, null, null, d);
 d = Date(1,1,d);

 sql = " SELECT  SUBSTR (cod.t_code, 7) AS code, acc.t_account c4et, acc.t_nameaccount name_acc, acc.t_oper op, " + 
       "			rsb_account.resta (acc.t_account, TO_DATE ('" + d + "', 'DD.MM.YYYY'), acc.t_chapter, 0) rest_rub, 0 rest_val " +
       "   FROM  daccount_dbt acc, dobjcode_dbt cod " +
       "  WHERE  acc.t_usertypeaccount LIKE '%Y%' " +
       "	  AND acc.t_type_account NOT LIKE '%П%' " +
       "	  AND acc.t_type_account NOT LIKE '%Н%' " +
       "	  AND acc.t_type_account NOT LIKE '%U%' " +
       "	  AND acc.t_chapter = 1 " +
       "	  AND cod.t_objectid = acc.t_client " +
       "	  AND cod.t_codekind = 1 " +
       "	  AND t_objecttype = 3 " +
       "	  AND cod.t_state = 0 " +
       "ORDER BY code, c4et " ;


 ds=trsbdataset(sql);
 sum_rub = 0.0;
 pred_cod = 0;
 tek_cod = 0;
 while (ds.movenext)
    tek_cod=ds.value("code");
    i=i+1;
    if ((tek_cod != pred_cod) and (i>1)) table1.printseparator; end;
    table1.printStringTransferByWord(i,ds.value("code"),ds.value("name_acc"),ds.value("c4et"),ds.value("op"),ds.value("rest_rub"),ds.value("rest_val"));
    sum_rub=sum_rub+ds.value("rest_rub");
    pred_cod=tek_cod;
 end;

 table1.printbottom("всего счетов:"+i+" сумма рублевая "+sum_rub:a);