/*Поступление платежей на счета                              */
/*                                                           */
/*                                                           */
/*Тихомиров А.Н. 05.10.2009                    Версия 1.0    */


import globals, RSD,rcw, rslx, Календарь, rsbdataset, ptinter, bankinter;
var typeflag, maskflag, accmaskDt, accmaskCrd, fl, acctypeDt, acctypeCrd, inter, ruleflag, attr, statinz, statusflag,  datebegin, dateend, i, m, g, k, ib, sum, cnt, val;
var out, output = "outdoc.xls", fulloutput, ex, ob, obBook, obsheet, typedtflag, typecrdflag, typedttext, typecrdtext, maskcrdflag, maskdtflag, string1, string2, fl1, cnt1;

var cmd, rsd, ruletext, oper, operin;
array stat, type, rule;

const  KEY_F1      =315;
const  KEY_F2      =316;
const  KEY_F3      =317;
const KEY_ESC      = 27;
const KEY_SPACE    = 32;
const KEY_ENTER    = 13;


private macro code1(id)
var cmd, rsd;
if (id>0)
cmd = rsdcommand(" select codedt.t_code from  dobjcode_dbt codedt "+
 " where codedt.t_codekind = 1 "+
 "  AND codedt.t_objecttype = 3 "+
 "  AND codedt.t_objectid = LPAD (?, 9, '0') ");
cmd.addparam("ID", RSDBP_IN, id);
cmd.execute();
rsd = rsdrecordset(cmd);
else
return "Отсутствует код 1";
end;
if (rsd.movenext())
 return rsd.value(0);
 else
 return "Отсутствует код 1";
end;
END;


private macro Outall()
var acctab="", accin="", acctype="", atrtab="", atrin="", statout1="", statout2="", statin="", stattab = "",sql, rsd;
    if (IsStandAlone()) // Двухзвенка
                 if ((ValType(ex)!=V_UNDEF) and (ex.Visible==False))
                   ex = ActiveX("Excel.Application",NULL,false); 
                 else
                   ex = ActiveX("Excel.Application",NULL,true);
                   
                 end;
  
      else // Трехзвенка
               ob = CreateObject ("rsax","TRsAxServer","RsAxServer",false);
               ex = ob.CreateComObject ("Excel.Application",true);

     end; 
GetRegistryValue("BANK_INI\\ОБЩИЕ ПАРАМЕТРЫ\\ДИРЕКТОРИИ\\USERTEMPLSDIR",2,out);
Fulloutput = FindPath(output, out);                    
               
obBook = ex.Workbooks.open(fulloutput); 
obSheet = obBook.ActiveSheet(); 




/*   statout1 = "Status, ";
   statout2 = " val.t_name Status, ";

   stattab =  " doprcurst_dbt cur, "+
           " doprstval_dbt val, ";

   statin = " AND cur.t_id_operation = opr.t_id_operation "+
         " AND cur.t_statuskindid = 291 "+
         " AND val.t_numvalue in (1,2,4,5) "+
         " AND cur.t_statuskindid = val.t_statuskindid "+
         " AND cur.t_numvalue = val.t_numvalue ";*/


   statout1 = "Status, stat1, ";
   statout2 = " val.t_name Status, val1.t_name Stat1,";

   stattab =  " doprcurst_dbt cur, doprcurst_dbt cur1,"+
           " doprstval_dbt val, doprstval_dbt val1,";

   statin = " AND cur.t_id_operation = opr.t_id_operation "+
         " AND cur.t_statuskindid = 291 "+
         " AND val.t_numvalue in (2,4,5) "+
         " AND cur.t_statuskindid = val.t_statuskindid "+
         " AND cur.t_numvalue = val.t_numvalue "+

         " AND cur1.t_id_operation = opr.t_id_operation "+
         " AND cur1.t_statuskindid = 292 "+
         " AND cur1.t_statuskindid = val1.t_statuskindid "+
         " AND cur1.t_numvalue = val1.t_numvalue ";


sql = "select count(1) as cnt "+
 " FROM dpmpaym_dbt pm, "+
    "   doproper_dbt opr, "+
    "   dpmrmprop_dbt rm, "+
        stattab+
    "   dpmprop_dbt prop, "+
    "   dfininstr_dbt inst, "+
    "   doprstep_dbt step, "+
    "   doprblock_dbt bl, "+
    "   doprkdoc_dbt doc "+
 " WHERE opr.t_documentid = LPAD (TO_CHAR (pm.t_paymentid), 34, '0') "+
    " AND opr.t_dockind = pm.t_dockind  "+
    " AND pm.t_paymentid = rm.t_paymentid "+
    " AND prop.T_TRANSFERDATE <= to_date('"+datebegin+"','DD-MM-YYYY') "+
    " AND prop.t_paymentid = pm.t_paymentid "+
    " AND prop.t_issender = CHR (0) "+
    " AND pm.t_basefiid=0 "+
    " AND prop.t_group = 1 "+
      statin+operin+
    " AND doc.t_dockind = pm.t_dockind "+
    " AND inst.t_fiid = pm.t_basefiid "+
    " AND step.t_id_operation = opr.t_id_operation "+
    " AND step.t_isexecute = 'R'"+
//    " AND step.t_countnum = (select max(st.t_countnum) from doprstep_dbt st where st.t_id_operation = step.t_id_operation) "+
    " AND doc.t_dockind = pm.t_dockind "
    " AND bl.t_blockid = step.t_blockid ";
rsd = trsbdataset(sql);
if(rsd.movenext())
initprogress(int(rsd.cnt));
end;


sql = "select bl.t_name, count(1) as cnt, sum(pm.t_amount) as sum "+
 " FROM dpmpaym_dbt pm, "+
    "   doproper_dbt opr, "+
    "   dpmrmprop_dbt rm, "+
        stattab+
    "   dpmprop_dbt prop, "+
    "   dfininstr_dbt inst, "+
    "   doprstep_dbt step, "+
    "   doprblock_dbt bl, "+
    "   doprkdoc_dbt doc "+
 " WHERE opr.t_documentid = LPAD (TO_CHAR (pm.t_paymentid), 34, '0') "+
    " AND opr.t_dockind = pm.t_dockind  "+
    " AND pm.t_paymentid = rm.t_paymentid "+
    " AND prop.T_TRANSFERDATE <= to_date('"+datebegin+"','DD-MM-YYYY') "+
    " AND prop.t_paymentid = pm.t_paymentid "+
    " AND prop.t_issender = CHR (0) "+
    " AND pm.t_basefiid=0 "+
    " AND prop.t_group = 1 "+
      statin+operin+
    " AND doc.t_dockind = pm.t_dockind "+
    " AND inst.t_fiid = pm.t_basefiid "+
    " AND step.t_id_operation = opr.t_id_operation "+
//    " AND step.t_countnum = (select max(st.t_countnum) from doprstep_dbt st where st.t_id_operation = step.t_id_operation) "+
    " AND step.t_isexecute = 'R'"+
    " AND bl.t_blockid = step.t_blockid "
    " group by bl.t_name"+
    " order by bl.t_name"; 
i = 4;
   rsd = trsbdataset(sql);
  while (rsd.movenext())
   obSheet.Range("C"+(i)+":E"+(i)).mergecells=true;
   obSheet.Range("C"+i).Value=rsd.name;
   obSheet.Range("F"+i).Value=rsd.cnt;
   obSheet.Range("G"+i).Value=rsd.sum;i = i+1;
  end;
     i = i+1;
     ib = i;

      obSheet.Range("A"+4).Value=string1;
      obSheet.Range("A"+5).Value=string2;
      obSheet.Range("E"+ib+":F64999").numberformat = "@";
      obSheet.Range("F"+ib+":G64999").numberformat = "@";
      obSheet.Range("A"+ib+":A64999").wraptext=true;
      obSheet.Range("B"+ib+":B64999").wraptext=true;
      obSheet.Range("C"+ib+":C64999").wraptext=true;
      obSheet.Range("D"+ib+":D64999").wraptext=true;
      obSheet.Range("E"+ib+":E64999").wraptext=true;
      obSheet.Range("F"+ib+":F64999").wraptext=true;
      obSheet.Range("G"+ib+":G64999").wraptext=true;
      obSheet.Range("H"+ib+":H64999").wraptext=true;
      obSheet.Range("I"+ib+":I64999").wraptext=true;
      obSheet.Range("J"+ib+":J64999").wraptext=true;
      obSheet.Range("K"+ib+":K64999").wraptext=true;
      obSheet.Range("L"+ib+":L64999").wraptext=true;
      obSheet.Range("M"+ib+":M64999").wraptext=true;
       debugbreak;
      obsheet.pagesetup.zoom=55;
      obSheet.Range("A1").ColumnWidth=5;
      obSheet.Range("B1").ColumnWidth=25;
      obSheet.Range("C1").ColumnWidth=15;
      obSheet.Range("D1").ColumnWidth=10;
      obSheet.Range("E1").ColumnWidth=25;
      obSheet.Range("F1").ColumnWidth=25;
      obSheet.Range("G1").ColumnWidth=15;
      obSheet.Range("H1").ColumnWidth=30;
      obSheet.Range("I1").ColumnWidth=10;
      obSheet.Range("J1").ColumnWidth=25;
      obSheet.Range("K1").ColumnWidth=30;
      obSheet.Range("L1").ColumnWidth=10;

      obSheet.Range("A"+ib).Value="№ п/п";
      obSheet.Range("B"+ib).Value="Плательщик";
      obSheet.Range("C"+ib).Value="Документ";
      obSheet.Range("D"+ib).Value="Дата";
      obSheet.Range("E"+ib).Value="Счет плательщика";
      obSheet.Range("F"+ib).Value="Счет получателя";
      obSheet.Range("G"+ib).Value="Сумма";
      obSheet.Range("H"+ib).Value="Назначение платежа";
      obSheet.Range("I"+ib).Value="Статус документооборота";
      obSheet.Range("J"+ib).Value="Шаг операции";
      obSheet.Range("K"+ib).Value="Рабочая область";
      obSheet.Range("L"+ib).Value="ID платежа";

sql = "select rownum, t_payer, t_payername, docname, T_TRANSFERDATE, "+statout1+
      " t_payeraccount, t_receiveraccount, t_amount, t_ccy, t_ground, "+
      " namestep, t_paymentid, Dockind from (select  t_payer, t_payername, docname, T_TRANSFERDATE, "+statout1+
      " t_payeraccount, t_receiveraccount, t_amount, t_ccy, t_ground, "+
      " namestep, t_paymentid, DECODE (case,  "+
    " 'ББ_15_16_70_400_430_440', 'ББ   (15-мультики, 16, 27 -платежки ББ, 70-мемеорики, 400,430,440 -кассовые ББ)', "+
    " 'РКО_230_231_233'        , 'РКО  (230, 231, 233 - Заявления на открытие/закрытие счетов)', "+
    " 'РКО_201_202_410_420'        , 'РКО  (201, 202 - РДД, 410,420 - Кассовые РКО-шные документы)', "+
    " 'РКО_51'                 , 'РКО  (51 - периодическая комиссия)', "+
    " 'ББ_59'                  , 'ББ   (59 - требования на оплату периодических комиссий)', "+
    " 'АРМП_320_322'        , 'АРМП (Ответные платежки)', "+
    " 'ПРОЧЕЕ'                 , 'Остальные экземпляры операций' "+
   " ) Dockind  from ( "+
   " SELECT rm.t_payername, pm.t_payer, prop.T_TRANSFERDATE, "+
    "   pm.t_payeraccount, pm.t_receiveraccount, pm.t_amount, inst.t_ccy, rm.t_ground, "+
    "   bl.t_name namestep, doc.t_name as docname, pm.t_paymentid, pm.t_basefiid,     "+statout2+
    "     case  "+
    "        when pm.t_dockind in (15, 16, 70, 400, 430, 440, 27) then 'ББ_15_16_70_400_430_440' "+
    "        when pm.t_dockind in (230, 231, 233)             then 'РКО_230_231_233' "+
    "        when pm.t_dockind in (201, 202, 410, 420)             then 'РКО_201_202_410_420' "+
    "        when pm.t_dockind in (51)                        then 'РКО_51' "+
    "        when pm.t_dockind in (59)                        then 'ББ_59' "+
    "        when pm.t_dockind in (320, 322)              then 'АРМП_320_322' "+
    "        else 'Остальное'  "+
    "     end case "+
 " FROM dpmpaym_dbt pm, "+
    "   doproper_dbt opr, "+
    "   dpmrmprop_dbt rm, "+
        stattab+
    "   dpmprop_dbt prop, "+
    "   dfininstr_dbt inst, "+
    "   doprstep_dbt step, "+
    "   doprblock_dbt bl, "+
    "   doprkdoc_dbt doc "+
 " WHERE opr.t_documentid = LPAD (TO_CHAR (pm.t_paymentid), 34, '0') "+
    " AND opr.t_dockind = pm.t_dockind  "+
    " AND pm.t_paymentid = rm.t_paymentid "+
    " AND prop.T_TRANSFERDATE <= to_date('"+datebegin+"','DD-MM-YYYY') "+
    " AND prop.t_paymentid = pm.t_paymentid "+
    " AND prop.t_issender = CHR (0) "+
    " AND prop.t_group = 1 "+
    " AND pm.t_basefiid=0 "+
      statin+operin+
    " AND inst.t_fiid = pm.t_basefiid "+
    " AND doc.t_dockind = pm.t_dockind "+
    " AND step.t_id_operation = opr.t_id_operation "+
//    " AND step.t_countnum = (select max(st.t_countnum) from doprstep_dbt st where st.t_id_operation = step.t_id_operation) "+
    " AND step.t_isexecute = 'R'"+
    " AND bl.t_blockid = step.t_blockid) "+
    " order by namestep, t_basefiid, t_amount) ";

rsd = trsbdataset(sql);

obSheet.Range("A"+2).Value="Отчет о исходящих в рублях платежей";
obSheet.Range("A"+3).Value="На дату "+datebegin;

 k=0;
sum = 0;
cnt = 0;
cnt1 = 0;
while (rsd.movenext())
if (k ==0)
fl1 = rsd.namestep;
val = rsd.ccy;
end;
if ((k > 0) and (rsd.ccy != val))
obSheet.Range("A"+(i+1)+":L"+(i+1)).mergecells=true;
obSheet.Range("A"+(i+1)).Value=string("Итого документов ",cnt,"на сумму ",sum);
val = rsd.ccy;
sum = 0;
cnt = 0;
   i = i+1;
   k = k+1;
end;

if ((k > 0) and (rsd.namestep != fl1))
obSheet.Range("A"+(i+1)+":L"+(i+1)).mergecells=true;
obSheet.Range("A"+(i+1)).Value=string("Итого документов ",cnt);
fl1 = rsd.namestep;
cnt1 = 0;
   i = i+1;
   k = k+1;
end;

useprogress(int(k));
   sum = sum + rsd.t_amount;
   cnt = cnt + 1;
   cnt1 = cnt1 + 1;
   i = i+1;
   k = k+1;
   obSheet.Range("A"+i).Value=rsd.rownum;
//   obSheet.Range("B"+i).Value=code1(rsd.payer);
   obSheet.Range("B"+i).Value=rsd.payername;
   obSheet.Range("C"+i).Value=rsd.docname;
   obSheet.Range("D"+i).Value=rsd.TRANSFERDATE;
   obSheet.Range("E"+i).Value=rsd.payeraccount;
   obSheet.Range("F"+i).Value=rsd.receiveraccount;
   obSheet.Range("G"+i).Value=rsd.amount;
   obSheet.Range("H"+i).Value=rsd.ground;
//   obSheet.Range("I"+i).Value=rsd.status;
   obSheet.Range("I"+i).Value=rsd.stat1;
   obSheet.Range("J"+i).Value=rsd.namestep;
   obSheet.Range("K"+i).Value=rsd.dockind;
   obSheet.Range("L"+i).Value=rsd.paymentid;
   if (i>64499)
      obSheet.Range("A"+4).Value=string1;
      obSheet.Range("A"+5).Value=string2;
      obSheet.Range("E"+ib+":F64999").numberformat = "@";
      obSheet.Range("F"+ib+":G64999").numberformat = "@";
      obSheet.Range("A"+ib+":A64999").wraptext=true;
      obSheet.Range("B"+ib+":B64999").wraptext=true;
      obSheet.Range("C"+ib+":C64999").wraptext=true;
      obSheet.Range("D"+ib+":D64999").wraptext=true;
      obSheet.Range("E"+ib+":E64999").wraptext=true;
      obSheet.Range("F"+ib+":F64999").wraptext=true;
      obSheet.Range("G"+ib+":G64999").wraptext=true;
      obSheet.Range("H"+ib+":H64999").wraptext=true;
      obSheet.Range("I"+ib+":I64999").wraptext=true;
      obSheet.Range("J"+ib+":J64999").wraptext=true;
      obSheet.Range("K"+ib+":K64999").wraptext=true;
      obSheet.Range("L"+ib+":L64999").wraptext=true;
      obSheet.Range("M"+ib+":M64999").wraptext=true;

      obSheet.Range("A1").ColumnWidth=5;
      obSheet.Range("B1").ColumnWidth=25;
      obSheet.Range("C1").ColumnWidth=15;
      obSheet.Range("D1").ColumnWidth=10;
      obSheet.Range("E1").ColumnWidth=25;
      obSheet.Range("F1").ColumnWidth=25;
      obSheet.Range("G1").ColumnWidth=15;
      obSheet.Range("H1").ColumnWidth=30;
      obSheet.Range("I1").ColumnWidth=10;
      obSheet.Range("J1").ColumnWidth=25;
      obSheet.Range("K1").ColumnWidth=30;
      obSheet.Range("L1").ColumnWidth=10;

      obsheet.pagesetup.zoom=67;
      obSheet.Range("A"+ib).Value="№ п/п";
      obSheet.Range("B"+ib).Value="Плательщик";
      obSheet.Range("C"+ib).Value="Документ";
      obSheet.Range("D"+ib).Value="Дата";
      obSheet.Range("E"+ib).Value="Счет плательщика";
      obSheet.Range("F"+ib).Value="Счет получателя";
      obSheet.Range("G"+ib).Value="Сумма";
      obSheet.Range("H"+ib).Value="Назначение платежа";
      obSheet.Range("I"+ib).Value="Статус документооборота";
      obSheet.Range("J"+ib).Value="Шаг операции";
      obSheet.Range("K"+ib).Value="Рабочая область";
      obSheet.Range("L"+ib).Value="ID платежа";

   end;
end;
obSheet.Range("A"+(i+1)+":L"+(i+1)).mergecells=true;
obSheet.Range("A"+(i+1)).Value=string("Итого документов ",cnt,"на сумму ",sum);i=i+1;
obSheet.Range("A"+ib+":L"+(i)).Borders.Weight=2;
obSheet.Range("A"+ib+":L"+ib).interior.color=4035000;
Ex.visible = true;       
end;

/*Точка входа*/
datebegin = {curdate};
if (getdate(datebegin, "Выберите дату отчета"))
if (getint(oper, "Задайте операциониста (0 или ESC для всех)"))
  if (oper>0)
  operin = " AND pm.t_oper = "+oper;
  OutAll;
  else
  operin = "";
  OutAll;
  end;
else
  operin = "";
  OutAll;
end;
end;
