/* Реестр внешних исходящих платежей                                    							*/
/*                                                                     							*/
/*                                                                         							*/
/* Тихомиров А.Н.		02.04.2009			Версия 1.1								*/
/* Агеев С.В.			25.01.2012			Добавил возможность выпуска отчёта по всем (указать 0)		*/


import "cb_sql", globals, календарь, bankinter;
var opr,dir, datebegin, dateend, cmd, i, k, payername;

const  KEY_F1      =315;
const  KEY_F2      =316;
const  KEY_ALT_F2  =361;
const  KEY_F3      =317;
const KEY_ESC      = 27;
const KEY_SPACE    = 32;
const KEY_ENTER    = 13;

/* EVG 12.01.2011 */
const  KEY_F9      =323;

record oper ("person");
var Fulloutputl, outl, outputl="outpaym.lbr";                    

GetRegistryValue("BANK_INI\\ОБЩИЕ ПАРАМЕТРЫ\\ДИРЕКТОРИИ\\LBRDIR",2,outl);
Fulloutputl = FindPath(outputl, outl);
var dlg = TRecHandler("outpaym", fulloutputl, TRUE); 

//var out, fulloutput, output = "\\outpaym.txt";
var fulloutput = GetTxtFileName("outpaym");

private macro bicb(id)
var  sl= "select obj.t_code from dobjcode_dbt obj where "+
 "obj.t_objectid="+id+" and obj.t_codekind=3 ";
var  DataS=TRsbDataSet(sl);

  if( DataS.moveNext())
    return DataS.code;
  else
    msgbox("Субъект не найден в party.dbt");
    return 0;
  end;
END;

private macro GetNameoper(id)
if (id != 0)
	var  sl="select t_name from dperson_dbt where t_oper="+id ;
	
	var  DataS=TRsbDataSet(sl);
	
	if( DataS.moveNext())
		return DataS.name;
	else
		msgbox("Субъект не найден в party.dbt");
		return 0;
	end;
else
	return "Все";
end;

END;


private macro opernum(opr)
// Любой разделитель
var inter="";
var i=0;
var pos=1, m, sq, dataset;
 while (pos>0)
   m=strlen(opr);
    while (i<m)
      i=i+1;
      if ((substr(opr,i,1)!=0) and (substr(opr,i,1)!=1) and (substr(opr,i,1)!=2) and (substr(opr,i,1)!=3)
         and (substr(opr,i,1)!=4) and (substr(opr,i,1)!=5) and (substr(opr,i,1)!=6) and (substr(opr,i,1)!=7)
         and (substr(opr,i,1)!=8) and (substr(opr,i,1)!=9))
        pos =i;
	 if (opr != 0)
	      	if (pos!=1)
       	 	sq = "select count (*) as cnt from dperson_dbt where t_oper="+substr(opr,1,pos-1);
        		dataset=trsbdataset(sq);
	         	if (dataset.movenext())
	       	     	if (dataset.cnt==0)
              	 		msgbox ("Заданного значения "+substr(opr,1,pos-1)+"нет в справочнике");
               			return false
	       	     	end;
       	   	end;
       	end;
	 end;
       opr=substr(opr, pos+1);
       i=m+1;
       end;
     end;
     if (i==m)
       pos=0;
     end;
     i=0;
 end;
 
if (opr != 0)
	sq = "select count (*) as cnt from dperson_dbt where t_oper="+substr(opr,1);
	dataset=trsbdataset(sq);
	if (dataset.movenext())
		if (dataset.cnt==0)
			msgbox ("Заданного значения "+substr(opr,1,pos-1)+"нет в справочнике");
			return false
		end; 
	end;
end;
return true;
end;


private macro printopernum(opr)
// Любой разделитель
var fl=0;
var inter="";
var i=0;
var pos=1, m, sq, dataset;
 while (pos>0)
   m=strlen(opr);
    while (i<m)
      i=i+1;
        if ((substr(opr,i,1)!=0) and (substr(opr,i,1)!=1) and (substr(opr,i,1)!=2) and (substr(opr,i,1)!=3)
           and (substr(opr,i,1)!=4) and (substr(opr,i,1)!=5) and (substr(opr,i,1)!=6) and (substr(opr,i,1)!=7)
           and (substr(opr,i,1)!=8) and (substr(opr,i,1)!=9))
            pos =i;
              if (pos!=1)
                   if (fl==0)
                      fl = 1;
                        [              Отв. исполнитель   ________________________##################### ]
                         (GetNameoper(substr(opr,1,pos-1)));
                    else
                        [                                 ________________________##################### ]
                        (GetNameoper(substr(opr,1,pos-1)));
                    end;
               end;
             opr=substr(opr, pos+1);
             i=m+1;
          end;
     end;
     if (i==m)
       pos=0;
     end;
     i=0;
 end;
 if (fl==0)
  [              Отв. исполнитель   ________________________##################### ]
  (GetNameoper(opr));
 else
  [                                 ________________________##################### ]
  (GetNameoper(opr));
 end;
return true;
end;



private macro outall
var oprp=opr;
// Любой разделитель
var inter="";
var i=0;
var pos=1, m, sq, dataset;
 while (pos>0)
   m=strlen(opr);
     while (i<m)
       i=i+1;
         if ((substr(opr,i,1)!=0) and (substr(opr,i,1)!=1) and (substr(opr,i,1)!=2) and (substr(opr,i,1)!=3)
            and (substr(opr,i,1)!=4) and (substr(opr,i,1)!=5) and (substr(opr,i,1)!=6) and (substr(opr,i,1)!=7)
            and (substr(opr,i,1)!=8) and (substr(opr,i,1)!=9))
           pos =i;
             if (pos!=1)
                if (strlen(inter)<1)
                   inter = inter+" AND dpmpaym_dbt.t_oper in("+substr(opr,1,pos-1); 
                else
                   inter=inter+","+substr(opr,1,pos-1);
                end;
             end;
             opr=substr(opr, pos+1);
             i=m+1;
          end;
      end;
      if (i==m)
        pos=0;
      end;
      i=0;
 end;
 if (strlen(inter)>0)
   inter = inter+","+substr(opr,1); 
 else
   inter = " AND dpmpaym_dbt.t_oper in("+substr(opr,1);
 end;
 inter=inter+")";

	if (opr == 0)
		inter = "";
	end;

var sql = " SELECT dpmrmprop_dbt.t_number, dpmprop_dbt.t_transferdate as valuedate, "+
"       dpmpaym_dbt.t_payeraccount, dpmpaym_dbt.t_receiveraccount, "+
"       dpmpaym_dbt.t_amount, dpmrmprop_dbt.t_ground, dpmrmprop_dbt.t_receivername, dpmrmprop_dbt.t_payername, "+
"       dpmpaym_dbt.t_payerbankid, dpmpaym_dbt.t_receiverbankid "+
"  FROM dpmpaym_dbt, dpmprop_dbt, dpmrmprop_dbt "+
" WHERE dpmprop_dbt.t_group = 1 "+
"   AND dpmprop_dbt.t_issender = CHR (0) "+
"   AND dpmpaym_dbt.t_paymentid = dpmprop_dbt.t_paymentid "+
//"   AND dpmpaym_dbt.t_valuedate BETWEEN TO_DATE ('"+datebegin+"', 'DD-MM-YYYY') AND TO_DATE ('"+dateend+"', 'DD-MM-YYYY') "+
"   AND dpmprop_dbt.t_transferdate BETWEEN TO_DATE ('"+datebegin+"', 'DD-MM-YYYY') AND TO_DATE ('"+dateend+"', 'DD-MM-YYYY') "+
"   AND dpmpaym_dbt.t_fiid = 0 "+
    inter+
"   AND dpmpaym_dbt.t_paymentid = dpmrmprop_dbt.t_paymentid "+
"   AND dpmpaym_dbt.t_paymstatus > 0"+
"   AND dpmrmprop_dbt.t_shifroper = '01' "+
"   AND dpmpaym_dbt.t_futurepayeraccount = dpmpaym_dbt.t_futurereceiveraccount "+
"   order by dpmpaym_dbt.t_amount";
dataset=trsbdataset(sql);
var n=0;
var amount_all=0;

//GetRegistryValue("BANK_INI\\ОБЩИЕ ПАРАМЕТРЫ\\ДИРЕКТОРИИ\\TEXTDIR",2,out);
//fulloutput=out+output;
//setoutput(fulloutput,false);
payername = "ОАО АКБ "+strfor(34)+"ПРОБИЗНЕСБАНК"+strfor(34);


[                                                   Реестр внешних платежей по операциям на межбанковском рынке

                                                                 за период с ########## по ##########

┌─────┬──────────┬─────────────────────────────────────────────┬───────────────────────────────────────────────────────┬──────────────┬────────────────────────────────────┐
│  №  │   Дата   │                Плательщик                   │                        Получатель                     │     Сумма    │           Назначение платежа       │
│док. │документа ├─────────────────────┬───────────────────────┼──────────┬────────────────────┬───────────────────────┤              │                                    │
│     │          │        Счет         │     Наименование      │    Бик   │        Счет        │      Наименование     │              │                                    │]
(date(datebegin), date(dateend));


 while (dataset.movenext())
  n=n+1;
  amount_all=amount_all+dataset.amount;
[├─────┼──────────┼─────────────────────┼───────────────────────┼──────────┼────────────────────┼───────────────────────┼──────────────┼────────────────────────────────────┤
│#####│##########│#####################│#######################│##########│####################│#######################│##############│####################################│]
(dataset.number:c, date(dataset.valuedate), dataset.payeraccount,substr(payername,1,30),bicb(dataset.receiverbankid),dataset.receiveraccount,substr(dataset.receivername,1,30),dataset.amount,substr(dataset.ground,1,45));
i=0;
if (strlen(dataset.ground)>45)
 i=int(strlen(dataset.ground)/45);
end;
//  if (int(strlen(dataset.payername)/30)>i)
//   i=int(strlen(dataset.payername)/30);
  if (int(strlen(payername)/30)>i)
   i=int(strlen(payername)/30);
  end;
  if (int(strlen(dataset.receivername)/30)>i)
   i=int(strlen(dataset.receivername)/30);
  end;
k=0;
 while (k<i)
 k=k+1;
[│     │          │                     │#######################│          │                    │#######################│              │####################################│]
//(substr(dataset.payername, (k*30+1),30),substr(dataset.receivername, (k*30+1),30), substr(dataset.ground, (k*45),45));
(substr(payername, (k*30+1),30),substr(dataset.receivername, (k*30+1),30), substr(dataset.ground, (k*45),45));
end;

end;

[└─────┴──────────┴─────────────────────┴───────────────────────┴──────────┴────────────────────┴───────────────────────┴──────────────┴────────────────────────────────────┘

             Количество документво:    ##########
             На сумму:   ########################
             
             
             Начальник УУ и КФО   ________________________#####################]
(n, amount_all, (GetNameoper(dir)));
             
printopernum(oprp);

[ 

                ______________________
                
      М.П.

                ______________________

               
                
             Документ подготовлен ________________________#####################   ]
((GetNameoper({oper})));


END;


 /*Обработчик диалоговой панели ввода исходных данных для печати*/
MACRO Event (dlg, cmd, id, key) 

   var const_mess = "~F2~ Продолжить ~ESC~ Выход ";
   var const_mess2 = "~F2~ Продолжить ~SPACE~ ~ESC~ Выход ";
   var data, sql;
   /*Первоначальная инициализация полей*/
   if(cmd == DLG_INIT)
      dlg.rec.DateBegin = {curDate}-1;
      dlg.rec.DateEnd = {curDate};
      data=trsbdataset(string("select * from outpaym_dbt where t_oper=",{oper}));
      if (data.movenext())
      dlg.rec.opernum = data.opernum;
      dlg.rec.dirnum = data.dirnum;
      dlg.rec.dirname = getnameoper(data.dirnum);
      else
      dlg.rec.opernum = "";
      dlg.rec.dirnum = "";
      dlg.rec.dirname = "";
      end;
      UpdateFields(dlg); 
   end;
   
   /*Установка подсказок в строке состояния*/
   if (cmd==DLG_SETFOCUS)
     if  (FldName(dlg,id)=="DateBegin")
       message(" ~F3~ Выбор даты из календаря "+const_mess);
     elif (FldName(dlg,id)=="DateEnd")
       message(" ~F3~ Выбор даты из календаря "+const_mess);
     elif (FldName(dlg,id)=="OperNum")
       message(" ~F3~ Выбор операциониста ALT+F2 Запустить с сохранением"+const_mess);
     elif (FldName(dlg,id) == "DirNum")
              message(" ~F3~ Выбор операциониста ALT+F2 Запустить с сохранением"+const_mess);
    end;
   end;
   if (cmd == DLG_REMFOCUS)
     /*Проверка корректности дат отчета*/
     if (FldName(dlg,id) == "DateBegin")
       if ( dlg.rec.DateBegin > {curdate} )
         MsgBox("Дата начала периода не может быть больше даты текущего операционного дня");
        return CM_CANCEL;
       elif ( dlg.rec.DateBegin > dlg.rec.DateEnd )
         MsgBox("Дата начала периода не может быть больше даты окончания периода");
        return CM_CANCEL;
       end;
     end;
     if (FldName(dlg,id) == "DateEnd")
       if ( dlg.rec.DateEnd > {curdate} )
         MsgBox("Дата не может быть больше даты текущего операционного дня");
        return CM_CANCEL;
       elif ( dlg.rec.DateBegin > dlg.rec.DateEnd )
         MsgBox("Дата окончания периода не может быть меньше даты начала периода");
        return CM_CANCEL;
       end;
    end;
    if (FldName(dlg,id) == "OperNum")
     if (strlen(dlg.rec.opernum)>0)
     	if (dlg.rec.opernum!=0)
     		if (not opernum(dlg.rec.opernum))
        		return CM_CANCEL;
     		end
     	end;
     end;
    end;
      UpdateFields(dlg); 
   end;

   if (cmd == DLG_KEY)
     /*Выход из диалогового окна формирования отчета*/
     if (KEY == KEY_ESC)
       return exit(1);//CM_CANCEL;
     /*Выбор данных из списка*/
     elif ( KEY == KEY_F3)
        /*Выбор даты из календаря*/
        if (FldName(dlg,id) == "DateBegin")
          dlg.rec.datebegin = GetDateByCalendar ({curDate});
        end;
        if (FldName(dlg,id) == "DateEnd")
          dlg.rec.dateend = GetDateByCalendar ({curDate});
        end;
        if (FldName(dlg,id) == "OperNum")
           if (Listoper (oper))
              dlg.rec.opernum = oper.oper;
              message(" ~F3~ Выбор операциониста ALT+F2 Запустить с сохранением"+const_mess);
              UpdateFields(dlg);
          end;
        end;
       if (FldName(dlg,id) == "DirNum")
           if (Listoper (oper))
              dlg.rec.dirnum = oper.oper;
              dlg.rec.dirname = oper.name;
              message(" ~F3~ Выбор операциониста ALT+F2 Запустить с сохранением"+const_mess);
              UpdateFields(dlg);
          end;
        end;

        
     elif (( KEY == KEY_F2 ) or (KEY == KEY_ENTER))         //Проверки при вводе
         if ( dlg.rec.DateBegin > {curdate} )
                MsgBox("Дата начала периода не может быть больше даты текущего операционного дня");
                return CM_IGNORE;
          elif ( dlg.rec.DateBegin > dlg.rec.DateEnd )
                MsgBox("Дата начала периода не может быть больше даты окончания периода");
                return CM_IGNORE;
         end;
          if ( dlg.rec.DateEnd > {curdate} )
                MsgBox("Дата не может быть больше даты текущего операционного дня");
                return CM_IGNORE;
          elif ( dlg.rec.DateBegin > dlg.rec.DateEnd )
                MsgBox("Дата окончания периода не может быть меньше даты начала периода");
                return CM_IGNORE;
          end;

        /* EVG 12/01/2011 Нужно пользователю хоть что-то сказать */
        if ( KEY == KEY_F2 )
           if ( dlg.rec.opernum == "" )
              msgbox ("Пожалуйста, укажите отв. исполнителя");
              return CM_IGNORE;
           elif ( dlg.rec.dirnum == "" )
              msgbox ("Пожалуйста, укажите начальника УУ и КФО");
              return CM_IGNORE;
           end;
        end;

        if ((dlg.rec.opernum!="") and (dlg.rec.dirnum!=""))
           if ((opernum(dlg.rec.opernum)) or (dlg.rec.opernum == 0))
              Datebegin  = dlg.rec.Datebegin;
              Dateend = dlg.rec.DateEnd;
              opr=dlg.rec.opernum;
              dir=dlg.rec.dirnum;
              Return CM_SAVE;
           end;
        else
           return CM_IGNORE;
        end;

           
   /* EVG 12.01.2011 Обработка F9 */
   elif (KEY == KEY_F9)
        return CM_IGNORE;

   elif (KEY == KEY_ALT_F2)
     if (opernum(dlg.rec.opernum))
        Datebegin  = dlg.rec.Datebegin;
        Dateend = dlg.rec.DateEnd;
       opr=dlg.rec.opernum;
       dir=dlg.rec.dirnum;
       data=trsbdataset(string("select * from outpaym_dbt where t_oper=",{oper}));
       if (data.movenext())
        sql =  "update outpaym_dbt set t_opernum='"+string(opr)+"', t_dirnum='"+string(dir)+"' where t_oper="+string({oper});
        cmd = RSDCommand( sql );
        cmd.Execute();
       else 
        sql = "insert into outpaym_dbt values ("+string({oper})+","+string(opr)+","+string(dir)+")";
        SQL_Execute(sql,"Присвоение значений", false);
       end;
        Return CM_SAVE;
     else
      return CM_IGNORE;
     end;
      return CM_IGNORE;
     end;
   end;
        
END;


/*Точка входа в макрос*/
/*Создаем таблицу, если таблицы нет*/
  var sql;
  sql = "DECLARE \n"
      +  " v_err EXCEPTION; \n"
      +  " PRAGMA EXCEPTION_INIT( v_err, -955 );\n"
      + "BEGIN EXECUTE IMMEDIATE 'CREATE TABLE outpaym_dbt"
      + " ( T_OPER NUMBER(5), " 
      + "   T_OPERNUM VARCHAR2(40), " 
      +   " T_DIRNUM VARCHAR2(40) )';\n " 
      + "EXCEPTION WHEN v_err THEN NULL; \n"
      + "END; \n";
  SQL_Execute(sql,"Создание таблицы отчета", false);

if (RunDialog(dlg, "Event"))                  
outall();
end;
END;