/*Поступление платежей на счета                              */
/*                                                           */
/*                                                           */
/*Тихомиров А.Н. 05.10.2009                    Версия 1.0    */


import globals, RSD,rcw, rslx, Календарь, rsbdataset, ptinter, bankinter, payminter;
var typeflag, maskflag, accmaskDt, accmaskCrd, fl, acctypeDt, acctypeCrd, inter, ruleflag, attr, statinz, statusflag,  datebegin, dateend, i, m, g, k, ib, sum, cnt, val;
var out, output = "outdoc.xls", fulloutput, ex, ob, obBook, obsheet, typedtflag, typecrdflag, typedttext, typecrdtext, maskcrdflag, maskdtflag, string1, string2, fl1, cnt1;

var cmd, rsd, ruletext, oper, operin, paymentobj, me;
array stat, type, rule, mn;

private macro Outall()
var acctab="", accin="", acctype="", atrtab="", atrin="", statout1="", statout2="", statin="", stattab = "",sql, rsd;
    if (IsStandAlone()) // Двухзвенка
                 if ((ValType(ex)!=V_UNDEF) and (ex.Visible==False))
                   ex = ActiveX("Excel.Application",NULL,false); 
                 else
                   ex = ActiveX("Excel.Application",NULL,true);
                   
                 end;
  
      else // Трехзвенка
               ob = CreateObject ("rsax","TRsAxServer","RsAxServer",false);
               ex = ob.CreateComObject ("Excel.Application",true);

     end; 
GetRegistryValue("BANK_INI\\ОБЩИЕ ПАРАМЕТРЫ\\ДИРЕКТОРИИ\\USERTEMPLSDIR",2,out);
Fulloutput = FindPath(output, out);                    
               
obBook = ex.Workbooks.open(fulloutput); 
obSheet = obBook.ActiveSheet(); 

mn(0) = "Платежи в ожидании шага 'Зачисление(инициатор-Фронт)'";
mn(1) = "Платежи с шагом 'Выгрузка во Фронт'";

me = menu(mn);

if   (me == -1)
exit(1);
elif (me == 0)
sql = "select count(1) as cnt   "+
" from dpmpaym_dbt pm, doproper_dbt opr, doprstep_dbt step where "+
" opr.T_DOCUMENTID = lpad(pm.t_paymentid, 34, '0') "+
" and opr.T_ID_OPERATION = step.T_ID_OPERATION "+
" and step.T_ISEXECUTE = 'R' "+
" and step.T_SYMBOL = 'n' "+
" and step.T_BLOCKID = 11000120 "+
" and opr.T_DOCKIND = pm.T_DOCKIND "+
" and pm.t_valuedate between to_date('10.10.2009','dd.mm.yyyy') and to_date('"+{curdate}+"','dd.mm.yyyy')  "+
" and pm.T_PAYMSTATUS < 32000 "; 
elif (me == 1)
sql = "select count(1) as cnt   "+
" from dpmpaym_dbt pm, doproper_dbt opr, doprstep_dbt step where "+
" opr.T_DOCUMENTID = lpad(pm.t_paymentid, 34, '0') "+
" and opr.T_ID_OPERATION = step.T_ID_OPERATION "+
" and step.T_SYMBOL = 'f' "+
" and step.T_BLOCKID = 11000120 "+
" and opr.T_DOCKIND = pm.T_DOCKIND "+
" and pm.t_valuedate between to_date('10.10.2009','dd.mm.yyyy') and to_date('"+{curdate}+"','dd.mm.yyyy')  "+
" and pm.T_PAYMSTATUS < 32000 "; 
end;



   rsd = trsbdataset(sql);
  if (rsd.movenext())
   initprogress(int(rsd.cnt));
  end;

i = 4;
     i = i+1;
     ib = i;

      obSheet.Range("A"+4).Value=string1;
      obSheet.Range("A"+5).Value=string2;
      obSheet.Range("H"+ib+":F64999").numberformat = "@";
      obSheet.Range("M"+ib+":G64999").numberformat = "@";
      obSheet.Range("A"+ib+":A64999").wraptext=true;
      obSheet.Range("B"+ib+":B64999").wraptext=true;
      obSheet.Range("C"+ib+":C64999").wraptext=true;
      obSheet.Range("D"+ib+":D64999").wraptext=true;
      obSheet.Range("E"+ib+":E64999").wraptext=true;
      obSheet.Range("F"+ib+":F64999").wraptext=true;
      obSheet.Range("G"+ib+":G64999").wraptext=true;
      obSheet.Range("H"+ib+":H64999").wraptext=true;
      obSheet.Range("I"+ib+":I64999").wraptext=true;
      obSheet.Range("J"+ib+":J64999").wraptext=true;
      obSheet.Range("K"+ib+":K64999").wraptext=true;
      obSheet.Range("L"+ib+":L64999").wraptext=true;
      obSheet.Range("M"+ib+":M64999").wraptext=true;
      obSheet.Range("N"+ib+":M64999").wraptext=true;
      obSheet.Range("O"+ib+":M64999").wraptext=true;
      obSheet.Range("P"+ib+":M64999").wraptext=true;
      obSheet.Range("Q"+ib+":M64999").wraptext=true;
      obSheet.Range("R"+ib+":M64999").wraptext=true;
      obSheet.Range("S"+ib+":M64999").wraptext=true;
      obSheet.Range("T"+ib+":M64999").wraptext=true;
      obSheet.Range("U"+ib+":M64999").wraptext=true;
      obSheet.Range("V"+ib+":M64999").wraptext=true;

       
       debugbreak;
      obsheet.pagesetup.zoom=55;
      obSheet.Range("A1").ColumnWidth=5;
      obSheet.Range("B1").ColumnWidth=5;
      obSheet.Range("C1").ColumnWidth=10;
      obSheet.Range("D1").ColumnWidth=10;
      obSheet.Range("E1").ColumnWidth=5;
      obSheet.Range("F1").ColumnWidth=20;
      obSheet.Range("G1").ColumnWidth=35;
      obSheet.Range("H1").ColumnWidth=20;
      obSheet.Range("I1").ColumnWidth=25;
      obSheet.Range("J1").ColumnWidth=10;
      obSheet.Range("K1").ColumnWidth=10;
      obSheet.Range("L1").ColumnWidth=25;
      obSheet.Range("M1").ColumnWidth=20;
      obSheet.Range("N1").ColumnWidth=35;
      obSheet.Range("O1").ColumnWidth=20;
      obSheet.Range("P1").ColumnWidth=10;
      obSheet.Range("Q1").ColumnWidth=5;
      obSheet.Range("R1").ColumnWidth=5;
      obSheet.Range("S1").ColumnWidth=2;
      obSheet.Range("T1").ColumnWidth=50;
      obSheet.Range("U1").ColumnWidth=10;
      obSheet.Range("V1").ColumnWidth=50;

      obSheet.Range("A"+ib).Value="№ п/п";
      obSheet.Range("B"+ib).Value="№ документа";
      obSheet.Range("C"+ib).Value="Дата";
      obSheet.Range("D"+ib).Value="Сумма";
      obSheet.Range("E"+ib).Value="Вид платежа";
      obSheet.Range("F"+ib).Value="ИНН/КПП плательщика";
      obSheet.Range("G"+ib).Value="Наименование плательщика";
      obSheet.Range("H"+ib).Value="Счет плательщика";
      obSheet.Range("I"+ib).Value="Банк плательщика";
      obSheet.Range("J"+ib).Value="БИК банка плательщика";
      obSheet.Range("K"+ib).Value="БИК банка получателя";
      obSheet.Range("L"+ib).Value="Банк получателя";
      obSheet.Range("M"+ib).Value="Счет получателя";
      obSheet.Range("N"+ib).Value="Наименование получателя";
      obSheet.Range("O"+ib).Value="ИНН/КПП получателя";
      obSheet.Range("P"+ib).Value="ДПП";
      obSheet.Range("Q"+ib).Value="Шифр операции";
      obSheet.Range("R"+ib).Value="Пачка";
      obSheet.Range("S"+ib).Value="Очередность";
      obSheet.Range("T"+ib).Value="Основание платежа";
      obSheet.Range("U"+ib).Value="PaymentID";
      obSheet.Range("V"+ib).Value="Рабочая область";

/*obSheet.Range("A"+2).Value="Платежи на шаги Зачисление (фронт инициатор)";*/
obSheet.Range("A"+2).Value=mn(me);


if   (me == -1)
exit(1);
elif (me == 0)
sql = "select rownum, t_paymentid, DECODE (case,  "+
" 'ББ_15_16_70_400_430_440', 'ББ   (15-мультики, 16 -платежки ББ, 70-мемеорики, 400,430,440 -кассовые ББ)',  "+
" 'РКО_230_231_233'        , 'РКО  (230, 231, 233 - Заявления на открытие/закрытие счетов)',  "+
" 'РКО_201_202_410_420'        , 'РКО  (201, 202 - РДД, 410,420 - Кассовые РКО-шные документы)',  "+
" 'РКО_51'                 , 'РКО  (51 - периодическая комиссия)',  "+
" 'ББ_59'                  , 'ББ   (59 - требования на оплату периодических комиссий)',  "+
" 'АРМП_320_322_27'        , 'АРМП (Ответные платежи)',  "+
" 'ПРОЧЕЕ'                 , 'Остальные экземпляры операций'  "+
" ) Dockind from ( "+
"select pm.t_paymentid,    "+
"     case   "+
"        when pm.t_dockind in (15, 16, 70, 400, 430, 440) then 'ББ_15_16_70_400_430_440'  "+
"        when pm.t_dockind in (230, 231, 233)             then 'РКО_230_231_233'  "+
"        when pm.t_dockind in (201, 202, 410, 420)             then 'РКО_201_202_410_420'  "+
"        when pm.t_dockind in (51)                        then 'РКО_51'  "+
"        when pm.t_dockind in (59)                        then 'ББ_59'  "+
"        when pm.t_dockind in (320, 322, 27)              then 'АРМП_320_322_27'  "+
"        else 'Остальное'   "+
"     end case   "+
" from dpmpaym_dbt pm, doproper_dbt opr, doprstep_dbt step where "+
" opr.T_DOCUMENTID = lpad(pm.t_paymentid, 34, '0') "+
" and opr.T_ID_OPERATION = step.T_ID_OPERATION "+
" and step.T_ISEXECUTE = 'R' "+
" and step.T_SYMBOL = 'n' "+
" and step.T_BLOCKID = 11000120 "+
" and opr.T_DOCKIND = pm.T_DOCKIND "+
" and pm.t_valuedate between to_date('10.10.2009','dd.mm.yyyy') and to_date('"+{curdate}+"','dd.mm.yyyy')  "+
" and pm.T_PAYMSTATUS < 32000 )";  
elif (me == 1)
sql = "select rownum, t_paymentid, DECODE (case,  "+
" 'ББ_15_16_70_400_430_440', 'ББ   (15-мультики, 16 -платежки ББ, 70-мемеорики, 400,430,440 -кассовые ББ)',  "+
" 'РКО_230_231_233'        , 'РКО  (230, 231, 233 - Заявления на открытие/закрытие счетов)',  "+
" 'РКО_201_202_410_420'        , 'РКО  (201, 202 - РДД, 410,420 - Кассовые РКО-шные документы)',  "+
" 'РКО_51'                 , 'РКО  (51 - периодическая комиссия)',  "+
" 'ББ_59'                  , 'ББ   (59 - требования на оплату периодических комиссий)',  "+
" 'АРМП_320_322_27'        , 'АРМП (Ответные платежи)',  "+
" 'ПРОЧЕЕ'                 , 'Остальные экземпляры операций'  "+
" ) Dockind from ( "+
"select pm.t_paymentid,    "+
"     case   "+
"        when pm.t_dockind in (15, 16, 70, 400, 430, 440) then 'ББ_15_16_70_400_430_440'  "+
"        when pm.t_dockind in (230, 231, 233)             then 'РКО_230_231_233'  "+
"        when pm.t_dockind in (201, 202, 410, 420)             then 'РКО_201_202_410_420'  "+
"        when pm.t_dockind in (51)                        then 'РКО_51'  "+
"        when pm.t_dockind in (59)                        then 'ББ_59'  "+
"        when pm.t_dockind in (320, 322, 27)              then 'АРМП_320_322_27'  "+
"        else 'Остальное'   "+
"     end case   "+
" from dpmpaym_dbt pm, doproper_dbt opr, doprstep_dbt step where "+
" opr.T_DOCUMENTID = lpad(pm.t_paymentid, 34, '0') "+
" and opr.T_ID_OPERATION = step.T_ID_OPERATION "+
" and step.T_SYMBOL = 'f' "+
" and step.T_BLOCKID = 11000120 "+
" and opr.T_DOCKIND = pm.T_DOCKIND "+
" and pm.t_valuedate between to_date('10.10.2009','dd.mm.yyyy') and to_date('"+{curdate}+"','dd.mm.yyyy')  "+
" and pm.T_PAYMSTATUS < 32000 )";  
end;


rsd = trsbdataset(sql);

 k=0;
sum = 0;
cnt = 0;
cnt1 = 0;

while (rsd.movenext())

paymentobj = rsbpayment(rsd.paymentid);
i = i+1;
  useprogress(int(i-4));
      obSheet.Range("A"+i).Value=rsd.rownum;
      obSheet.Range("B"+i).Value=paymentobj.number;
      obSheet.Range("C"+i).Value=paymentobj.valuedate;
      obSheet.Range("D"+i).Value=paymentobj.baseamount;
      obSheet.Range("E"+i).Value=paymentobj.paymentkind;
      obSheet.Range("F"+i).Value=paymentobj.payerINN;
      obSheet.Range("G"+i).Value=paymentobj.payername;
      obSheet.Range("H"+i).Value=paymentobj.payeraccount;
      obSheet.Range("I"+i).Value=paymentobj.payerbankname;
      obSheet.Range("J"+i).Value=paymentobj.payerbankcode;
      obSheet.Range("K"+i).Value=paymentobj.receiverbankcode;
      obSheet.Range("L"+i).Value=paymentobj.receiverbankname;
      obSheet.Range("M"+i).Value=paymentobj.receiveraccount;
      obSheet.Range("N"+i).Value=paymentobj.receivername;
      obSheet.Range("O"+i).Value=paymentobj.receiverINN;
      if (paymentobj.payerchargeoffdate == "00.00.0000")
      obSheet.Range("P"+i).Value=" ";
      else
      obSheet.Range("P"+i).Value=paymentobj.payerchargeoffdate;
      end;
      obSheet.Range("P"+i).Value=paymentobj.payerchargeoffdate;
      obSheet.Range("Q"+i).Value=paymentobj.shifroper;
      obSheet.Range("R"+i).Value=paymentobj.numberpack;
      obSheet.Range("S"+i).Value=paymentobj.priority;
      obSheet.Range("T"+i).Value=paymentobj.ground;
      obSheet.Range("U"+i).Value=rsd.paymentid;
      obSheet.Range("V"+i).Value=rsd.dockind;

end;
remprogress();
obSheet.Range("A"+ib+":V"+(i)).Borders.Weight=2;
obSheet.Range("A"+ib+":V"+ib).interior.color=4035000;
Ex.visible = true;       
end;

/*Точка входа*/



  OutAll;
