/*Протокол Квитовки исходящих платежей                                 */
/*                                                                     */
/*                                                                     */
/*Тихомиров А.Н. 09.06.2009                    Версия 1.0              */

import rsbdataset, payminter, globals;
var PaymentObj;
var sql, dataset, sumd, d, sumk, k, sumdm, dm, sumkm, km, reportdate, fl, amount, sum, arr, sql2, dataset2, i = 0, cnt;
reportdate = {curdate};
if (getdate(reportdate, "Введите дату отчета"))
else
return 0;
end;

sql = " select count(1) as cnt "+
      " from dwlpm_dbt, "+
      " dpmpaym_dbt, "+
      " dwlmeslnk_dbt, "+
      " dwlmes_dbt, "+
      " dpmrmprop_dbt, "+
      " dwlmesval_dbt, "+
      " dwlsess_dbt "+
      " WHERE dwlpm_dbt.t_paymentid = dpmpaym_dbt.t_paymentid "+
" AND dwlpm_dbt.t_wlpmnum = 0 "+
" AND dwlpm_dbt.t_direct = CHR (0) "+
" AND dwlmeslnk_dbt.t_objkind = 501 "+
" AND dwlmeslnk_dbt.t_objid = dwlpm_dbt.t_wlpmid "+
"  AND dwlsess_dbt.t_tpid = 9 "+
 " AND dpmpaym_dbt.t_paymstatus = 32000 "+
" AND dwlmes_dbt.t_mesid = dwlmeslnk_dbt.t_mesid "+
" AND dwlmesval_dbt.t_index = 1 "+
" AND dwlmesval_dbt.t_mesid = dwlmes_dbt.t_mesid "+
" AND dpmrmprop_dbt.t_paymentid = dpmpaym_dbt.t_paymentid "+
" AND dwlsess_dbt.t_sessionid = dwlmes_dbt.t_sessionid "+
" AND dwlmes_dbt.t_outsideabonentdate = TO_DATE ('"+reportdate+"', 'DD-MM-YYYY') ";

dataset = trsbdataset(sql);
if (dataset.movenext())
initprogress(int(dataset.cnt));
end;


sql = " select  substr(substr(t_value,instr(lower(t_value),'edno')+6),1,instr(substr(t_value,instr(lower(t_value),'edno')+6),'"+strfor(34)+"')-1) as edno, "+
      " substr(substr(t_value,instr(lower(t_value),'edauthor')+10),1,10) as edauthor, "+
      " substr(substr(t_value,instr(lower(t_value),'eddate')+8),1,10) as eddate, "+
      " dpmrmprop_dbt.t_number, dpmpaym_dbt.t_payeraccount, "+
      "  dpmpaym_dbt.t_receiveraccount, "+
      "  dpmpaym_dbt.t_amount, dpmpaym_dbt.t_paymentid "+
      " from dwlpm_dbt, "+
      " dpmpaym_dbt, "+
      " dwlmeslnk_dbt, "+
      " dwlmes_dbt, "+
      " dpmrmprop_dbt, "+
      " dwlmesval_dbt, "+
      " dwlsess_dbt "+
      " WHERE dwlpm_dbt.t_paymentid = dpmpaym_dbt.t_paymentid "+
" AND dwlpm_dbt.t_wlpmnum = 0 "+
" AND dwlpm_dbt.t_direct = CHR (0) "+
" AND dwlmeslnk_dbt.t_objkind = 501 "+
" AND dwlmeslnk_dbt.t_objid = dwlpm_dbt.t_wlpmid "+
"  AND dwlsess_dbt.t_tpid = 9 "+
" AND dpmpaym_dbt.t_paymstatus = 32000 "+
" AND dwlmes_dbt.t_mesid = dwlmeslnk_dbt.t_mesid "+
" AND dwlmesval_dbt.t_index = 1 "+
" AND dwlmesval_dbt.t_mesid = dwlmes_dbt.t_mesid "+
" AND dpmrmprop_dbt.t_paymentid = dpmpaym_dbt.t_paymentid "+
" AND dwlsess_dbt.t_sessionid = dwlmes_dbt.t_sessionid "+
" AND dwlmes_dbt.t_outsideabonentdate = TO_DATE ('"+reportdate+"', 'DD-MM-YYYY') ";

dataset = trsbdataset(sql);

[                                           ОТЧЕТ
               Квитовка  выписки  МЦИ   за   ##########/дата/
-------------------------------------------------------------------------------------------------------
  №№ док-та  :    Плательщик        :      Получатель      :     Проведено          :    Проведено 
             :        Счет          :         Счет         :       Банком           :       МЦИ
-------------------------------------------------------------------------------------------------------](reportdate);
arr = string("(");
sum = 0;
cnt = 0;
while (dataset.movenext())
i = i+1;
useprogress(int(i));
/*sql2 = " select * from (select substr(t_value,instr(lower(t_value),'eddate')+8,10) as eddate, "+
" substr(substr(t_value,instr(lower(t_value),'edrefid edno')+14),1,instr(substr(t_value,instr(lower(t_value),'edrefid edno')+14),'"+strfor(34)+"')-1) as edno, "+
" substr(substr(t_value,instr(lower(t_value),'sum=')+5),1,instr(substr(t_value,instr(lower(t_value),'sum=')+5),'"+strfor(34)+"')-1) as sm, "+
" substr(substr(t_value,instr(lower(t_value),'edrefid')),instr(lower(substr(t_value,instr(lower(t_value),'edrefid'))),'edauthor')+10, 10) as edauthor "+
"  from  dwlmes_dbt, dwlmesval_dbt where instr(lower(t_value),'ed206')>0 AND t_index = 1 "+
//" AND dwlmes_dbt.t_outsideabonentdate = TO_DATE ('"+reportdate+"', 'DD-MM-YYYY') "+
" AND dwlmesval_dbt.t_mesid = dwlmes_dbt.t_mesid ) ed206 where concat(ed206.edauthor,ed206.edno) = "+string(dataset.edauthor, dataset.edno);*/
sql2 = " select * from (select "+
" substr(t_value,instr(lower(t_value),'eddate')+8,10) as eddate, "+
" substr(substr(t_value,instr(lower(t_value),'edno=')+6),1,instr(substr(t_value,instr(lower(t_value),'edno=')+6),'"+strfor(34)+"')-1) as edno, "+
" substr(substr(t_value,instr(lower(t_value),'sum=')+5),1,instr(substr(t_value,instr(lower(t_value),'sum=')+5),'"+strfor(34)+"')-1) as sm, "+
" substr(substr(t_value,instr(lower(t_value),'edauthor=')+10),1,instr(substr(t_value,instr(lower(t_value),'edauthor=')+10),'"+strfor(34)+"')-1) as edauthor "+
"  from dwlmesval_dbt, dwlmes_dbt where dwlmes_dbt.t_rlsformid = 301 and dwlmesval_dbt.t_mesid = dwlmes_dbt.t_mesid "+
" and dwlmes_dbt.t_mesid in (select dwlmes_dbt.t_mesid from dwlmesval_dbt, dwlmes_dbt where dwlmes_dbt.t_rlsformid = 301 "+
" and dwlmesval_dbt.t_mesid = dwlmes_dbt.t_mesid and dwlmesval_dbt.t_index = 1 "+
"  and substr(t_value,instr(lower(t_value),'eddate')+8,10) = '"+dataset.eddate+"') and dwlmesval_dbt.t_index>1 )"+
" ed206 where concat(ed206.edauthor,ed206.edno) = "+string(dataset.edauthor, dataset.edno);
dataset2 = trsbdataset(sql2);
if (dataset2.movenext())
arr = string(arr,dataset.edauthor, dataset.edno,", ");
else
[############:######################:######################:########################:####################]
       (dataset.number:z, dataset.payeraccount:c:z, dataset.receiveraccount:c:z, dataset.amount:c:z, " ");
       sum = sum + dataset.amount;
       cnt = cnt+1;
end;

end;
[ИТОГО ПЛАТЕЖЕЙ  :########################:####################]
       (money(sum), int(cnt));

/*if (strlen(arr)>5)
arr = string(arr,")");
/*sql2 = " select * from (select "+
" substr(t_value,instr(lower(t_value),'eddate')+8,10) as eddate, "+
" substr(substr(t_value,instr(lower(t_value),'edno=')+6),1,instr(substr(t_value,instr(lower(t_value),'edno=')+6),'"+strfor(34)+"')-1) as edno, "+
" substr(substr(t_value,instr(lower(t_value),'sum=')+5),1,instr(substr(t_value,instr(lower(t_value),'sum=')+5),'"+strfor(34)+"')-1) as sm, "+
" substr(substr(t_value,instr(lower(t_value),'edauthor=')+10),1,instr(substr(t_value,instr(lower(t_value),'edauthor=')+10),'"+strfor(34)+"')-1) as edauthor "+
"  from dwlmesval_dbt, dwlmes_dbt where dwlmes_dbt.t_rlsformid = 301 and dwlmesval_dbt.t_mesid = dwlmes_dbt.t_mesid "+
" and dwlmes_dbt.t_sysdate = '"+(date(reportdate)+1)+"' and dwlmesval_dbt.t_index>1 )"+
" ed206 where concat(ed206.edauthor,ed206.edno) = "+arr;*/
sql2 = " select * from (select "+
" substr(t_value,instr(lower(t_value),'eddate')+8,10) as eddate, "+
" substr(substr(t_value,instr(lower(t_value),'edno=')+6),1,instr(substr(t_value,instr(lower(t_value),'edno=')+6),'"+strfor(34)+"')-1) as edno, "+
" substr(substr(t_value,instr(lower(t_value),'sum=')+5),1,instr(substr(t_value,instr(lower(t_value),'sum=')+5),'"+strfor(34)+"')-1) as sm, "+
" substr(substr(t_value,instr(lower(t_value),'edauthor=')+10),1,instr(substr(t_value,instr(lower(t_value),'edauthor=')+10),'"+strfor(34)+"')-1) as edauthor "+
"  from dwlmesval_dbt, dwlmes_dbt where dwlmes_dbt.t_rlsformid = 301 and dwlmesval_dbt.t_mesid = dwlmes_dbt.t_mesid "+
" and dwlmes_dbt.t_mesid in (select dwlmes_dbt.t_mesid from dwlmesval_dbt, dwlmes_dbt where dwlmes_dbt.t_rlsformid = 301 "+
" and dwlmesval_dbt.t_mesid = dwlmes_dbt.t_mesid and dwlmesval_dbt.t_index = 1 "+
"  and substr(t_value,instr(lower(t_value),'eddate')+8,10) = '"+dataset.eddate+"') and dwlmesval_dbt.t_index>1 )"+
" ed206 where concat(ed206.edauthor,ed206.edno) not in "+arr;
msgbox(sql2);
dataset2 = trsbdataset(sql2);
while (dataset2.movenext())
sql = " select  substr(substr(t_value,instr(lower(t_value),'edno')+6),1,instr(substr(t_value,instr(lower(t_value),'edno')+6),'"+strfor(34)+"')-1) as edno, "+
      " substr(substr(t_value,instr(lower(t_value),'edauthor')+10),1,10) as edauthor, "+
      " dpmrmprop_dbt.t_number, dpmpaym_dbt.t_payeraccount, "+
      "  dpmpaym_dbt.t_receiveraccount, "+
      "  dpmpaym_dbt.t_amount, dpmpaym_dbt.t_paymentid "+
      " from dwlpm_dbt, "+
      " dpmpaym_dbt, "+
      " dwlmeslnk_dbt, "+
      " dwlmes_dbt, "+
      " dpmrmprop_dbt, "+
      " dwlmesval_dbt, "+
      " dwlsess_dbt "+
      " WHERE dwlpm_dbt.t_paymentid = dpmpaym_dbt.t_paymentid "+
" AND dwlpm_dbt.t_wlpmnum = 0 "+
" AND dwlpm_dbt.t_direct = CHR (0) "+
" AND dwlmeslnk_dbt.t_objkind = 501 "+
" AND dwlmeslnk_dbt.t_objid = dwlpm_dbt.t_wlpmid "+
" AND dwlmes_dbt.t_mesid = dwlmeslnk_dbt.t_mesid "+
" AND dwlmesval_dbt.t_index = 1 "+
" AND dwlmesval_dbt.t_mesid = dwlmes_dbt.t_mesid "+
" AND dpmrmprop_dbt.t_paymentid = dpmpaym_dbt.t_paymentid "+
" AND dwlsess_dbt.t_sessionid = dwlmes_dbt.t_sessionid "+
" AND dwlmes_dbt.t_outsideabonentdate = TO_DATE ('"+reportdate+"', 'DD-MM-YYYY')) paym"+
" AND concat(paym.edauthor,paym.edno) = "+string(dataset2.edauthor,dataset2.edno);
dataset = trsbdataset(sql);
if (dataset.movenext())
[############:######################:######################:########################:####################]
       (dataset.number:z, dataset.payeraccount:c:z, dataset.receiveraccount:c:z, " ", dataset.amount:c:z, " ");
end;
end;
END;

  
  
  
  
 select  substr(substr(t_value,instr(lower(t_value),'edno')+6),1,instr(substr(t_value,instr(lower(t_value),'edno')+6),'+strfor(34)+')-1) as edno, 
 substr(substr(t_value,instr(lower(t_value),'edauthor')+10),1,10) as edauthor, 
 substr(substr(t_value,instr(lower(t_value),'eddate')+8),1,10) as eddate, 
 dpmrmprop_dbt.t_number, dpmpaym_dbt.t_payeraccount, 
  dpmpaym_dbt.t_receiveraccount, 
  dpmpaym_dbt.t_amount, darhdoc_dbt.t_sum, dpmpaym_dbt.t_paymentid , darhdoc_dbt.t_date_carry, darhdoc_dbt.T_ACCOUNT_PAYER, darhdoc_dbt.T_ACCOUNT_RECEIVER
 from dwlpm_dbt, 
 dpmpaym_dbt, 
 dwlmeslnk_dbt, 
 dwlmes_dbt, 
 dpmrmprop_dbt, 
 dwlmesval_dbt, 
 darhdoc_dbt,
 dpmdocs_dbt,
 dwlsess_dbt 
 WHERE dwlpm_dbt.t_paymentid = dpmpaym_dbt.t_paymentid 
 AND dwlpm_dbt.t_wlpmnum = 0 
 AND dwlpm_dbt.t_direct = CHR (0) 
 AND dwlmeslnk_dbt.t_objkind = 501 
 AND dwlmeslnk_dbt.t_objid = dwlpm_dbt.t_wlpmid 
  AND dwlsess_dbt.t_tpid = 9 
 --AND dpmpaym_dbt.t_paymstatus = 32000 
 AND dwlmes_dbt.t_mesid = dwlmeslnk_dbt.t_mesid 
 AND dwlmesval_dbt.t_index = 1 
 AND dwlmesval_dbt.t_mesid = dwlmes_dbt.t_mesid 
 AND dpmrmprop_dbt.t_paymentid = dpmpaym_dbt.t_paymentid 
 AND dwlsess_dbt.t_sessionid = dwlmes_dbt.t_sessionid 
 AND dwlmes_dbt.t_outsideabonentdate = TO_DATE ('19.10.2009', 'DD-MM-YYYY') 
 AND  dpmdocs_dbt.t_paymentid =  dpmpaym_dbt.t_paymentid
 AND  dpmdocs_dbt.t_applicationkey = darhdoc_dbt.T_APPLICATIONKEY
 AND  darhdoc_dbt.t_date_carry != TO_DATE ('19.10.2009', 'DD-MM-YYYY');
 
 
 
 
select sum( darhdoc_dbt.t_sum) 
 from dwlpm_dbt, 
 dpmpaym_dbt, 
 dwlmeslnk_dbt, 
 dwlmes_dbt, 
 dpmrmprop_dbt, 
 dwlmesval_dbt, 
 darhdoc_dbt,
 dpmdocs_dbt,
 dwlsess_dbt 
 WHERE dwlpm_dbt.t_paymentid = dpmpaym_dbt.t_paymentid 
 AND dwlpm_dbt.t_wlpmnum = 0 
 AND dwlpm_dbt.t_direct = CHR (0) 
 AND dwlmeslnk_dbt.t_objkind = 501 
 AND dwlmeslnk_dbt.t_objid = dwlpm_dbt.t_wlpmid 
  AND dwlsess_dbt.t_tpid = 9 
 --AND dpmpaym_dbt.t_paymstatus = 32000 
 AND dwlmes_dbt.t_mesid = dwlmeslnk_dbt.t_mesid 
 AND dwlmesval_dbt.t_index = 1 
 AND dwlmesval_dbt.t_mesid = dwlmes_dbt.t_mesid 
 AND dpmrmprop_dbt.t_paymentid = dpmpaym_dbt.t_paymentid 
 AND dwlsess_dbt.t_sessionid = dwlmes_dbt.t_sessionid 
 AND dwlmes_dbt.t_outsideabonentdate = TO_DATE ('19.10.2009', 'DD-MM-YYYY') 
 AND  dpmdocs_dbt.t_paymentid =  dpmpaym_dbt.t_paymentid
 AND  dpmdocs_dbt.t_applicationkey = darhdoc_dbt.T_APPLICATIONKEY
 AND  darhdoc_dbt.t_date_carry != TO_DATE ('19.10.2009', 'DD-MM-YYYY')  
  
  */         