/************************************************************************/
/*          Автоматизированная банковская система RS-Bank v6.0          */
/*                                                                      */
/*               Copyright (c) R-Style Ukraine                          */
/*                                                                      */
/*  Имя файла        : Repforprobis.mac                                 */
/*                                                                      */
/*  Описание         : макрос выбора параметров запроса для отчета      */
/*                                                                      */
/*  Программист      : Новиков С. С.                                    */
/*                                                                      */
/*  Создан           : 24.07.2008                                       */
/*                                                                      */
/*  Изменен          : 28.07.2008 Ойкин В.А.(voikin)                    */
/*                                                                      */
/*  Изменен          : 03.09.2008  Новиков С.С.                         */
/************************************************************************/

import globals;
import oralib;
import "KeyCodes.mac";
import rcw,RSD;
import PTInter,cb_sql;
import "Rep_DocDay.mac";


        
private var script = "",
            MenuChoise1,
            MenuChoise2;
        var NameRep,
            RepFileName;
        var rsrec:object,
            cmd,
            officeN, depN,
            rselect = "";
                    
    array repform;
    array reptype;
record Department ("dp_dep.dbt");
record Person     ("person.dbt");
record office(ptoffice);
record superior(ptoffice);
record dlg(docday1,"RSU.lbr") dialog;

const cn = RsdConnection("DSN=rsbob;USER ID=prbb2920;PASSWORD=prbb2920");

  macro EvProc (rsrec, cmd, id, key)
      if(( cmd == DLG_KEY ) and ( key == 13 ))
        return CM_SELECT;
      end;
  end;

  macro HandleEvent (dlg, cmd, id, key)
    var OrgDate:date = {curdate} + 1;
    var NoChangeDate:bool = false;

    if(cmd == DLG_INIT)
      PartyID = {OurBank};
      dlg.NumDepart = ""/*GetOurDepNum(string({NumDprt}))*/;   //voikin добавил возможность выбора отчета по всему банку
      dlg.NameDepart = "Банк"/*GetDepNameByID(GetDepartID(dlg.NumDepart))*/;
      dlg.NumDep = "";
      dlg.Dep = "По всем отделам" ;       
      dlg.Oper = "";
      dlg.NameOper = "Все операциониcты";
      dlg.Head = "";
      dlg.Date = {curdate};        
      UpdateFields(Dlg);
    end;
    if (cmd==DLG_SETFOCUS)
      if (
        (FldName(dlg,id)=="NumDepart") or
        (FldName(dlg,id)=="Oper"))
         message(" ~F3~ Справочник "+const_message);
      else
        message(const_message);
      end;
      officeN = dlg.NumDepart;
      depN = dlg.NumDep;
    end;

    if ((cmd == DLG_REMFOCUS))
      if (FldName(dlg,id)=="NumDepart")
        if (false)//(GetDepartID(dlg.NumDepart) == "" ) and (dlg.NumDepart != "")) //voikin добавил возможность выбора отчета по всему банку
          msgbox("Подразделение "+dlg.NumDepart+" не найдено ");
          UpdateFields(dlg);
          return CM_CANCEL;
        elif (officeN != dlg.NumDepart) 
          dlg.NumDep = "";
          dlg.Dep = "По всем отделам" ;       
          dlg.Oper = "";
          dlg.NameOper = "Все операциониcты";
          dlg.Head = "";
          UpdateFields(dlg);
        end; 
      elif (FldName(dlg,id)=="NumDep")
        if ((GetOfficeName(dlg.NumDep) == "") and (dlg.NumDep != "")) //voikin добавил возможность выбора отчета по всему банку
          msgbox("Отдел "+dlg.NumDep+" не найден ");
          UpdateFields(dlg);
          return CM_CANCEL;
        elif (depN != dlg.NumDep)
          dlg.Oper = "";
          dlg.NameOper = "Все операциониcты";
          if (depN != "")
            dlg.Head = "";
          end;
        else
          if (dlg.NumDep == "")
            dlg.Head = "";
            dlg.Dep = "По всем отделам";
          else
            dlg.Dep = GetOfficeName(dlg.NumDep);
          end;
          UpdateFields(dlg);
        end;
        officeN = dlg.NumDepart;
        depN = dlg.NumDep;
      elif (FldName(dlg,id)=="Date")
        if ( dlg.Date > {curdate} )
          MsgBox("Дата больше даты текущего операционного дня"); 
          return CM_CANCEL;
        end;
      
      elif (FldName(dlg,id)=="Oper")
        if ((GetOperName(dlg.Oper) == "") and (dlg.Oper != "") )
          msgbox("Операционист "+dlg.Oper+" не найден ");
          UpdateFields(dlg);
          return CM_CANCEL;
        else
          if (dlg.Oper == "")
             dlg.NameOper = "Все операционисты";
          else  
             dlg.NameOper = GetOperName(dlg.Oper);
          end;
          UpdateFields(dlg); 
        end;
      end;
      if (dlg.NumDepart == "")
        dlg.NameDepart = "Банк";
      else
        dlg.NameDepart = GetDepNameByID(GetDepartID(dlg.NumDepart));
      end;
      if (dlg.NumDep == "")
        dlg.Dep = "По всем отделам";
      end;
      UpdateFields(dlg); 
    end;


    if (cmd==DLG_KEY)
      if (KEY==KEY_ESC)
        if (GetTrue(TRUE,"Вы действительно хотите выйти?"))
          exit(1);
          return  CM_CANCEL;
        else
          return  CM_IGNORE;    
        end;
     
      elif (KEY==KEY_ENTER)
       if (FldName(dlg,id) == "Account")
          setfocus(dlg,0);
          return CM_Ignore;
       end;
      
      elif (KEY==KEY_F9)
        return CM_Ignore;          
      elif (KEY==KEY_F3)

        if (FldName(dlg,id) == "reptype")
          RepType(0)  = "Баланс -> Рубли -> Внутренние мемориальные";    
          RepType(1)  = "Баланс -> Рубли -> Внутрибанковские платежные"; 
          RepType(2)  = "Баланс -> Рубли -> Внутриклиентские";           
          RepType(3)  = "Баланс -> Рубли -> Ностро";                     
          RepType(4)  = "Баланс -> Валюта -> Внутренние мемориальные";   
          RepType(5)  = "Баланс -> Валюта -> Внутрибанковские платежные";
          RepType(6)  = "Баланс -> Валюта -> Внутриклиентские";          
          RepType(7)  = "Баланс -> Валюта -> Ностро";                    
          RepType(8)  = "Баланс -> Валюта -> Документы конвертации" ;    
          RepType(9)  = "Внебаланс -> Рубли";                            
          RepType(10) = "Внебаланс -> Валюта";                           
          RepType(11) = "Срочные операции -> Рубли";                     
          RepType(12) = "Срочные операции -> Валюта";                    
      
          MenuChoise1 = Menu(reptype, "Меню");
          if (MenuChoise1 >= 0)
            dlg.RepType = reptype(MenuChoise1);
            UpdateFields(dlg); 
          end;
   
        elif (FldName(dlg,id) == "repform")
          repform(0) = "Сводный реестр мем.ордеров";
          repform(1) = "Контрольная ведомость";
          repform(2) = "Реестр операций";
          
          MenuChoise2 = Menu(repform, "Меню");
          if (MenuChoise2 >= 0)
            dlg.RepForm = RepForm(MenuChoise2);
            UpdateFields(dlg); 
          end;
  
        elif (FldName(dlg,id) == "NumDepart")
          if (ListDepartment (Department))
            dlg.NumDepart = Department.Name;
            dlg.NameDepart = GetDepNameByID(Department.PartyID);
            PartyID = Department.PartyID;
            UpdateFields(dlg);
          end;
        elif (FldName(dlg,id) == "Oper")
          if (dlg.NumDep != "")  
            rselect = "select v.t_oper, v.t_name " +   
                      "from dperson_dbt v inner join " +
                      "    (dofficer_dbt d inner join " +
                      "     dptoffice_dbt m" +
                      "       on m.t_officecode = '"+ trim(dlg.NumDep) +"' and"+
                      "          d.t_partyid = m.t_partyid and" + 
                      "          d.t_officeid = m.t_officeid)" + 
                      "      on v.t_partyid = d.t_personid";
          elif ((dlg.NumDep == "") and (dlg.NumDepart != ""))
            rselect = "select v.t_oper, v.t_name " +   
                      "from dperson_dbt v inner join " +
                      "     dofficer_dbt d " +
                      "     on d.t_partyid  = '"+ PartyID +"' " +
                      "     and v.t_partyid = d.t_personid";
          end;
            cmd = RSDCommand(cn, rselect);
            rsrec = RSDRecordset( cmd, RSDVAL_CLIENT, RSDVAL_STATIC );
            if (RunScroll(rsrec, 0, 0, "Опера", @EvProc, "Список операционистов", "~Enter~ выбор сотрудника ~Esc~ выход", true))
              dlg.oper = rsrec.value (0);
              dlg.NameOper = rsrec.value (1);
              UpdateFields(dlg);
              OperSelect = dlg.oper;
            end;
        elif (FldName(dlg,id) == "NumDep")
          if (dlg.numdepart != "")
            if (ListOrgStructure(PartyID,OrgDate,office,superior,0,NoChangeDate))  
              dlg.NumDep = office.Officecode;
              dlg.Dep = GetOfficeName(dlg.NumDep);
              dlg.Head = GetChiefNameDep(office.Officecode);
              UpdateFields(dlg);
              OrgRegStruct = dlg.NumDep; 
              OrgRegStructName = GetDep1Name(dlg.NumDep);
            end;
          else
            msgbox("Вы не выбрали банк."); 
          end;
        end;
      
      elif (KEY==KEY_F2)

        if ((dlg.Date > {curDate}) or ( dlg.repform == "") or (dlg.reptype == ""))
          MsgBox("Не все поля корректны!");
          return CM_Ignore;
        end;

        if (dlg.NumDepart!="")
          CodDep = GetOurDepCode(dlg.NumDepart);
        else
          CodDep = Null;
        end;
        RepTypeS = RepType(MenuChoise1);
        RepFormS = RepForm(MenuChoise2);
        NumDepart = dlg.NumDepart;
        NameDepart = dlg.NameDepart;
        NumDep = dlg.NumDep;
        Dep = dlg.Dep;
        Oper = dlg.Oper;
        NameOper = dlg.NameOper;
        DateDocum = dlg.Date;
        return CM_SAVE;
/*!!!*/
      /**************************************************************************************************/
      end; /* end cmd==DLG_KEY*/
    end;
  end;
 

  if (RunDialog(dlg,"HandleEvent"))
    if (RepFormS == "Сводный реестр мем.ордеров")        
      if (RepTypes == "Баланс -> Рубли -> Внутренние мемориальные")    
        RepFileName = "..\\txtfile\\DocDay801." + UserNumber();
        NameRep = "Баланс\\Рубли\\Внутренние мемориальные";
        if(NumDepart == "")
            Report8(RepFileName,"09","6",NameRep,"and (substr(arh.t_account_payer, 1, 5) not in ('30110', '30114', '30115', '47417') or substr(arh.t_account_receiver, 1, 5) not in ('30110', '30114', '30115', '47417')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ",1);
        else
            Report11(RepFileName,"09","6",NameRep,"and (substr(arh.t_account_payer, 1, 5) not in ('30110', '30114', '30115', '47417') or substr(arh.t_account_receiver, 1, 5) not in ('30110', '30114', '30115', '47417')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ",1);
        end;  
      elif (RepTypes == "Баланс -> Рубли -> Внутрибанковские платежные")
        RepFileName = "..\\txtfile\\DocDay802." + UserNumber();
        NameRep = "Баланс\\Рубли\\Внутрибанковские платежные";
        if(NumDepart == "")
            Report8(RepFileName,"02","6",NameRep,"and (substr(arh.t_account_payer, 1, 5) not in ('30110', '30114', '30115') or substr(arh.t_account_receiver, 1, 5) not in ('30110', '30114', '30115')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ",1);
        else
            Report11(RepFileName,"02","6",NameRep,"and (substr(arh.t_account_payer, 1, 5) not in ('30110', '30114', '30115') or substr(arh.t_account_receiver, 1, 5) not in ('30110', '30114', '30115')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ",1);
        end;
      elif (RepTypes == "Баланс -> Рубли -> Внутриклиентские")           
        RepFileName = "..\\txtfile\\DocDay803." + UserNumber();
        NameRep = "Баланс\\Рубли\\Внутриклиентские";
        if(NumDepart == "")
           Report8(RepFileName,"01","6",NameRep,"and (substr(arh.t_account_payer, 1, 5) not in ('30110', '30114', '30115', '30208') or substr(arh.t_account_receiver, 1, 5) not in ('30110', '30114', '30115', '30208')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ",1);
        else
           Report11(RepFileName,"01","6",NameRep,"and (substr(arh.t_account_payer, 1, 5) not in ('30110', '30114', '30115', '30208') or substr(arh.t_account_receiver, 1, 5) not in ('30110', '30114', '30115', '30208')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ",1);
        end;
      elif (RepTypes == "Баланс -> Рубли -> Ностро")
        RepFileName = "..\\txtfile\\DocDay804." + UserNumber();
        NameRep = "Баланс\\Рубли\\НОСТРО";
        if(NumDepart == "")
           Report8(RepFileName,"(09,13)","1",NameRep,"and (substr(arh.t_account_payer, 1, 5) in ('30110', '30114', '30115', '30213') or substr(arh.t_account_receiver, 1, 5) in ('30110', '30114', '30115', '30213')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ",1);
        else
           Report11(RepFileName,"(09,13)","1",NameRep,"and (substr(arh.t_account_payer, 1, 5) in ('30110', '30114', '30115', '30213') or substr(arh.t_account_receiver, 1, 5) in ('30110', '30114', '30115', '30213')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ",1);
        end;
                           
      elif (RepTypes == "Баланс -> Валюта -> Внутренние мемориальные")
        RepFileName = "..\\txtfile\\DocDay901." + UserNumber();
        NameRep = "Баланс\\Валюта\\Внутренние мемориальные";
        if(NumDepart == "")
           Report9(RepFileName,"09","6",NameRep,"and (substr(arh.t_account_payer, 1, 5) not in ('30110', '30114', '30115', '47417') or substr(arh.t_account_receiver, 1, 5) not in ('30110', '30114', '30115', '47417')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ",1);
        else
           Report12(RepFileName,"09","6",NameRep,"and (substr(arh.t_account_payer, 1, 5) not in ('30110', '30114', '30115', '47417') or substr(arh.t_account_receiver, 1, 5) not in ('30110', '30114', '30115', '47417')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ",1);
        end; 
      elif (RepTypes == "Баланс -> Валюта -> Внутрибанковские платежные")
        RepFileName = "..\\txtfile\\DocDay902." + UserNumber();
        NameRep = "Баланс\\Валюта\\Внутрибанковские платежные";
        if(NumDepart == "")
            Report9(RepFileName,"02","6",NameRep,"and (substr(arh.t_account_payer, 1, 5) not in ('30110', '30114', '30115') or substr(arh.t_account_receiver, 1, 5) not in ('30110', '30114', '30115')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ",1);
        else
            Report12(RepFileName,"02","6",NameRep,"and (substr(arh.t_account_payer, 1, 5) not in ('30110', '30114', '30115') or substr(arh.t_account_receiver, 1, 5) not in ('30110', '30114', '30115')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ",1);
        end;
      elif (RepTypes == "Баланс -> Валюта -> Внутриклиентские")          
        RepFileName = "..\\txtfile\\DocDay903." + UserNumber();
        NameRep = "Баланс\\Валюта\\Внутриклиентские";
        if(NumDepart == "")
            Report9(RepFileName,"01","6",NameRep,"and (substr(arh.t_account_payer, 1, 5) not in ('30110', '30114', '30115', '30208') or substr(arh.t_account_receiver, 1, 5) not in ('30110', '30114', '30115', '30208')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ",1);
        else
            Report12(RepFileName,"01","6",NameRep,"and (substr(arh.t_account_payer, 1, 5) not in ('30110', '30114', '30115', '30208') or substr(arh.t_account_receiver, 1, 5) not in ('30110', '30114', '30115', '30208')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ",1);
        end;
      elif (RepTypes == "Баланс -> Валюта -> Ностро")                    
        RepFileName = "..\\txtfile\\DocDay904." + UserNumber();
        NameRep = "Баланс\\Валюта\\НОСТРО";
        if(NumDepart == "")
            Report9(RepFileName,"(09,13)","1",NameRep,"and (substr(arh.t_account_payer, 1, 5) in ('30110', '30114', '30115', '30213') or substr(arh.t_account_receiver, 1, 5) in ('30110', '30114', '30115', '30213')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ",1);
        else
            Report12(RepFileName,"(09,13)","1",NameRep,"and (substr(arh.t_account_payer, 1, 5) in ('30110', '30114', '30115', '30213') or substr(arh.t_account_receiver, 1, 5) in ('30110', '30114', '30115', '30213')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ",1);
        end;
      elif (RepTypes == "Баланс -> Валюта -> Документы конвертации")
        RepFileName = "..\\txtfile\\DocDay1013." + UserNumber();
        NameRep = "Балансовые\\Документы конвертации";
        if(NumDepart == "")
           Report10(RepFileName,NameRep);
        else
           Report13(RepFileName,NameRep);
        end;
      elif (RepTypes == "Внебаланс -> Рубли")
        RepFileName = "..\\txtfile\\DocDay805." + UserNumber();
        NameRep = "Внебаланс\\Рубли";
        if(NumDepart == "")
            Report8(RepFileName,"","",NameRep,"","",3);
        else
            Report11(RepFileName,"","",NameRep,"","",3);
        end; 
      elif (RepTypes == "Внебаланс -> Валюта")                  
        RepFileName = "..\\txtfile\\DocDay905." + UserNumber();
        NameRep = "Внебаланс\\Валюта";
        if(NumDepart == "")
            Report9(RepFileName,"","",NameRep,"","",3);
        else
            Report12(RepFileName,"","",NameRep,"","",3);
        end;
      elif (RepTypes == "Срочные операции -> Рубли")                     
        RepFileName = "..\\txtfile\\DocDay86." + UserNumber();
        NameRep = "Срочные операции\\Рубли";
        if(NumDepart == "")
            Report8(RepFileName,"","",NameRep,"","",4);
        else
            Report11(RepFileName,"","",NameRep,"","",4);
        end;
      elif (RepTypes == "Срочные операции -> Валюта")        
        RepFileName = "..\\txtfile\\DocDay906." + UserNumber();
        NameRep = "Срочные операции\\Валюта";
        if(NumDepart == "")
            Report9(RepFileName,"","",NameRep,"","",4);
        else
            Report12(RepFileName,"","",NameRep,"","",4);
        end;
      end;
    elif (RepFormS == "Контрольная ведомость")
      if (RepTypes == "Баланс -> Рубли -> Внутренние мемориальные")
        RepFileName = "..\\txtfile\\DocDay401." + UserNumber();
        NameRep = "Баланс\\Рубли\\Внутренние мемориальные";
        if(NumDepart == "")
          Report4(RepFileName,"09","6",NameRep,"and (substr(arh.t_account_payer, 1, 5) not in ('30110', '30114', '30115', '47417') or substr(arh.t_account_receiver, 1, 5) not in ('30110', '30114', '30115', '47417')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ",1);
        else
          Report6(RepFileName,"09","6",NameRep,"and (substr(arh.t_account_payer, 1, 5) not in ('30110', '30114', '30115', '47417') or substr(arh.t_account_receiver, 1, 5) not in ('30110', '30114', '30115', '47417')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ",1);
        end;   
      elif (RepTypes == "Баланс -> Рубли -> Внутрибанковские платежные") 
        RepFileName = "..\\txtfile\\DocDay402." + UserNumber();
        NameRep = "Баланс\\Рубли\\Внутрибанковские платежные";
        if(NumDepart == "")
            Report4(RepFileName,"02","6",NameRep,"and (substr(arh.t_account_payer, 1, 5) not in ('30110', '30114', '30115') or substr(arh.t_account_receiver, 1, 5) not in ('30110', '30114', '30115')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ",1);
        else
            Report6(RepFileName,"02","6",NameRep,"and (substr(arh.t_account_payer, 1, 5) not in ('30110', '30114', '30115') or substr(arh.t_account_receiver, 1, 5) not in ('30110', '30114', '30115')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ",1);
        end;
      elif (RepTypes == "Баланс -> Рубли -> Внутриклиентские")           
        RepFileName = "..\\txtfile\\DocDay403." + UserNumber();
        NameRep = "Баланс\\Рубли\\Внутриклиентские";
        if(NumDepart == "")
            Report4(RepFileName,"01","6",NameRep,"and (substr(arh.t_account_payer, 1, 5) not in ('30110', '30114', '30115', '30208') or substr(arh.t_account_receiver, 1, 5) not in ('30110', '30114', '30115', '30208')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ",1);
        else
            Report6(RepFileName,"01","6",NameRep,"and (substr(arh.t_account_payer, 1, 5) not in ('30110', '30114', '30115', '30208') or substr(arh.t_account_receiver, 1, 5) not in ('30110', '30114', '30115', '30208')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ",1);
        end;  
      elif (RepTypes == "Баланс -> Рубли -> Ностро")
        RepFileName = "..\\txtfile\\DocDay404." + UserNumber();
        NameRep = "Баланс\\Рубли\\НОСТРО";
        if(NumDepart == "")
            Report4(RepFileName,"(09,13)","1",NameRep,"and (substr(arh.t_account_payer, 1, 5) in ('30110', '30114', '30115', '30213') or substr(arh.t_account_receiver, 1, 5)  in ('30110', '30114', '30115','30213')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ",1);
        else
            Report6(RepFileName,"(09,13)","1",NameRep,"and (substr(arh.t_account_payer, 1, 5) in ('30110', '30114', '30115', '30213') or substr(arh.t_account_receiver, 1, 5)  in ('30110', '30114', '30115','30213')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ",1);
        end;                  
      elif (RepTypes == "Баланс -> Валюта -> Внутренние мемориальные")
        RepFileName = "..\\txtfile\\DocDay501." + UserNumber();
        NameRep = "Баланс\\Валюта\\Внутренние мемориальные";
        if(NumDepart == "")
            Report5(RepFileName,"09","6",NameRep,"and (substr(arh.t_account_payer, 1, 5) not in ('30110', '30114', '30115', '47417') or substr(arh.t_account_receiver, 1, 5) not in ('30110', '30114', '30115', '47417')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ",1);
        else
            Report7(RepFileName,"09","6",NameRep,"and (substr(arh.t_account_payer, 1, 5) not in ('30110', '30114', '30115', '47417') or substr(arh.t_account_receiver, 1, 5) not in ('30110', '30114', '30115', '47417')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ",1);
        end; 
      elif (RepTypes == "Баланс -> Валюта -> Внутрибанковские платежные")
        RepFileName = "..\\txtfile\\DocDay502." + UserNumber();
        NameRep = "Баланс\\Валюта\\Внутрибанковские платежные";
        if(NumDepart == "")
            Report5(RepFileName,"02","6",NameRep,"and (substr(arh.t_account_payer, 1, 5) not in ('30110', '30114', '30115') or substr(arh.t_account_receiver, 1, 5) not in ('30110', '30114', '30115')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ",1);
        else
            Report7(RepFileName,"02","6",NameRep,"and (substr(arh.t_account_payer, 1, 5) not in ('30110', '30114', '30115') or substr(arh.t_account_receiver, 1, 5) not in ('30110', '30114', '30115')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ",1);
        end;
      elif (RepTypes == "Баланс -> Валюта -> Внутриклиентские")          
        RepFileName = "..\\txtfile\\DocDay503." + UserNumber();
        NameRep = "Баланс\\Валюта\\Внутриклиентские";
        if(NumDepart == "")
            Report5(RepFileName,"01","6",NameRep,"and (substr(arh.t_account_payer, 1, 5) not in ('30110', '30114', '30115', '30208') or substr(arh.t_account_receiver, 1, 5) not in ('30110', '30114', '30115', '47417')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ",1);
        else
            Report7(RepFileName,"01","6",NameRep,"and (substr(arh.t_account_payer, 1, 5) not in ('30110', '30114', '30115', '30208') or substr(arh.t_account_receiver, 1, 5) not in ('30110', '30114', '30115', '47417')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ",1);
        end;  
      elif (RepTypes == "Баланс -> Валюта -> Ностро")                    
        RepFileName = "..\\txtfile\\DocDay504." + UserNumber();
        NameRep = "Баланс\\Валюта\\НОСТРО";
        if(NumDepart == "")
            Report5(RepFileName,"(09,13)","1",NameRep,"and (substr(arh.t_account_payer, 1, 5) in ('30110', '30114', '30115', '30213') or substr(arh.t_account_receiver, 1, 5)  in ('30110', '30114', '30115','30213')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ",1);
        else                     
            Report7(RepFileName,"(09,13)","1",NameRep,"and (substr(arh.t_account_payer, 1, 5) in ('30110', '30114', '30115', '30213') or substr(arh.t_account_receiver, 1, 5)  in ('30110', '30114', '30115','30213')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ",1);
        end;
      elif (RepTypes == "Баланс -> Валюта -> Документы конвертации")
        RepFileName = "..\\txtfile\\DocDay575." + UserNumber();
        NameRep = "Баланс\\Документы конвертации";
        if(NumDepart == "")
            Report14(RepFileName,NameRep);
        else
            Report15(RepFileName,NameRep);
        end;
      elif (RepTypes == "Внебаланс -> Рубли")
        RepFileName = "..\\txtfile\\DocDay405." + UserNumber();
        NameRep = "Внебаланс\\Рубли";
        if(NumDepart == "")
            Report4(RepFileName,"","",NameRep,"","",3);
        else
            Report6(RepFileName,"","",NameRep,"","",3);
        end;                         
      elif (RepTypes == "Внебаланс -> Валюта")                           
        RepFileName = "..\\txtfile\\DocDay506." + UserNumber();
        NameRep = "Внебаланс\\Валюта";
        if(NumDepart == "")
            Report5(RepFileName,"","",NameRep,"","",3);
        else
            Report7(RepFileName,"","",NameRep,"","",3);
        end;
      elif (RepTypes == "Срочные операции -> Рубли")          
        RepFileName = "..\\txtfile\\DocDay406." + UserNumber();
        NameRep = "Срочные операции\\Рубли";
        if(NumDepart == "")
            Report4(RepFileName,"","",NameRep,"","",4);
        else
            Report6(RepFileName,"","",NameRep,"","",4);
        end;
      elif (RepTypes == "Срочные операции -> Валюта")                    
        RepFileName = "..\\txtfile\\DocDay507." + UserNumber();
        NameRep = "Срочные операции\\Валюта";
        if(NumDepart == "")
            Report5(RepFileName,"","",NameRep,"","",4);
        else
            Report7(RepFileName,"","",NameRep,"","",4);
        end;
      end;
    elif (RepFormS == "Реестр операций")
      if (RepTypes == "Баланс -> Рубли -> Внутренние мемориальные")
          RepFileName = "..\\txtfile\\DocDay201." + UserNumber();
          NameRep = "Баланс\\Рубли\\Внутренние мемориальные";
          Report2(RepFileName,"09","6",NameRep,"and (substr(arh.t_account_payer, 1, 5) not in ('30110', '30114', '30115', '47417') or substr(arh.t_account_receiver, 1, 5) not in ('30110', '30114', '30115', '47417')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ",1);
      elif (RepTypes == "Баланс -> Рубли -> Внутрибанковские платежные")
          RepFileName = "..\\txtfile\\DocDay202." + UserNumber();
          NameRep = "Баланс\\Рубли\\Внутрибанковские платежные";
          Report2(RepFileName,"02","6",NameRep,"and (substr(arh.t_account_payer, 1, 5) not in ('30110', '30114', '30115') or substr(arh.t_account_receiver, 1, 5) not in ('30110', '30114', '30115')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ",1);
      elif (RepTypes == "Баланс -> Рубли -> Внутриклиентские")
          RepFileName = "..\\txtfile\\DocDay203." + UserNumber();
          NameRep = "Баланс\\Рубли\\Внутриклиентские";       
          Report2(RepFileName,"01","6",NameRep,"and (substr(arh.t_account_payer, 1, 5) not in ('30110', '30114', '30115', '30208') or substr(arh.t_account_receiver, 1, 5) not in ('30110', '30114', '30115', '30208')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ",1);
      elif (RepTypes == "Баланс -> Рубли -> Ностро")                     
          RepFileName = "..\\txtfile\\DocDay204." + UserNumber();
          NameRep = "Баланс\\Рубли\\НОСТРО";  
          Report2(RepFileName,"(09,13)","1",NameRep,"and (substr(arh.t_account_payer, 1, 5) in ('30110', '30114', '30115', '30213') or substr(arh.t_account_receiver, 1, 5)  in ('30110', '30114', '30115','30213')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ",1);
      elif (RepTypes == "Баланс -> Валюта -> Внутренние мемориальные")
          RepFileName = "..\\txtfile\\DocDay101." + UserNumber();
          NameRep = "Баланс\\Валюта\\Внутренние мемориальные";
          Report1(RepFileName,"09","6",NameRep,"and (substr(arh.t_account_payer, 1, 5) not in ('30110', '30114', '30115', '47417') or substr(arh.t_account_receiver, 1, 5) not in ('30110', '30114', '30115', '47417')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ", 1);
      elif (RepTypes == "Баланс -> Валюта -> Внутрибанковские платежные")
          RepFileName = "..\\txtfile\\DocDay102." + UserNumber();
          NameRep = "Баланс\\Валюта\\Внутрибанковские платежные";
          Report1(RepFileName,"02","6",NameRep,"and (substr(arh.t_account_payer, 1, 5) not in ('30110', '30114', '30115') or substr(arh.t_account_receiver, 1, 5) not in ('30110', '30114', '30115')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ",1);
      elif (RepTypes == "Баланс -> Валюта -> Внутриклиентские")          
          RepFileName = "..\\txtfile\\DocDay103." + UserNumber();
          NameRep = "Баланс\\Валюта\\Внутриклиентские";
          Report1(RepFileName,"01","6",NameRep,"and (substr(arh.t_account_payer, 1, 5) not in ('30110', '30114', '30115', '30208') or substr(arh.t_account_receiver, 1, 5) not in ('30110', '30114', '30115', '30208')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ",1);
      elif (RepTypes == "Баланс -> Валюта -> Ностро")                   
          RepFileName = "..\\txtfile\\DocDay104." + UserNumber();
          NameRep = "Баланс\\Валюта\\НОСТРО";
          Report1(RepFileName," ('09', '13')","1",NameRep,"and (substr(arh.t_account_payer, 1, 5) in ('30110', '30114', '30115', '30213') or substr(arh.t_account_receiver, 1, 5) in ('30110', '30114', '30115','30213')) ","and arh.t_account_payer not like 'ОВП%'and arh.t_account_receiver not like 'ОВП%' ",1);
      elif (RepTypes == "Баланс -> Валюта -> Документы конвертации")    
          RepFileName = "..\\txtfile\\DocDay301." + UserNumber();
          NameRep = "Балансовые\\Документы конвертации";
          Report3(RepFileName,NameRep);
      elif (RepTypes == "Внебаланс -> Рубли")
          RepFileName = "..\\txtfile\\DocDay205." + UserNumber();
          NameRep = "Внебаланс\\Рубли";                        
          Report2(RepFileName,"","",NameRep,"","",3);
      elif (RepTypes == "Внебаланс -> Валюта")                           
          RepFileName = "..\\txtfile\\DocDay105." + UserNumber();
          NameRep = "Внебаланс\\Валюта";
          Report1(RepFileName,"","",NameRep,"","",3);
      elif (RepTypes == "Срочные операции -> Рубли")                     
          RepFileName = "..\\txtfile\\DocDay206." + UserNumber();
          NameRep = "Срочные операции\\Рубли";    
          Report2(RepFileName,"","",NameRep,"","",4);
      elif (RepTypes == "Срочные операции -> Валюта")
          RepFileName = "..\\txtfile\\DocDay106." + UserNumber();
          NameRep = "Срочные операции\\Валюта";
          Report1(RepFileName,"","",NameRep,"","",4);
      end;
    end;
  end;



  
