/*                                                           */
/* Модифицировано: Коркин И.Н. 21.06.2010                    */
/* Доработана возможность запуска отчета из планировщика     */
/* и сохранение отчета                                       */
/*************************************************************/

//11.07.2012 vihrov C-12122 смена диапазонов кодов

import rsbdataset, globals, ptinter, ActX;

/* Коркин И.Н. По заявке I-013680 */
import "getperiodforrep.mac";
var period, interval, path1=""  , rep_file_name="", date_begin, date_end, namedep; 

 var ЧислоЛистов=1,      
      File_Name="";

 var Код_Ячейки="";
 var Номер_Строки  = 5,  /*с которой начинается заполнение данных*/
     лист = 1;


MACRO GetData(start, enddate)

var rs, str, str2, cnt=0;
var newcode, oldcode, isfirst = true, summ=$0;

 str = "SELECT oc.t_code, pt.t_shortname, pr.t_number, t.t_amount, t.t_i2placedate, pr.t_ground  " +
       "  FROM dpmpaym_dbt t, dpmrmprop_dbt pr, dobjcode_dbt oc, dparty_dbt pt " +
       " WHERE t.t_paymstatus = 2000 " +
       "   AND t.t_chapter = 1 " +
       "   AND t.t_fiid = 0 " +
       "   AND t.t_dockind = 201 " +
       "   AND pr.t_paymentid = t.t_paymentid " +
//Tikh По звонку пользователя
       "   AND t.t_i2placedate between TO_DATE ('"+start+"', 'dd.mm.yyyy') and TO_DATE ('"+enddate+"', 'dd.mm.yyyy')" +
//       "   AND t.t_i2placedate <= TO_DATE ('"+start+"', 'dd.mm.yyyy') " +
//       "   AND oc.t_codekind = 101 " +
       "   AND oc.t_codekind = 1 and oc.t_state=0 " +
       "   AND oc.t_objecttype = 3 " +
       "   AND oc.t_objectid = t.t_payer " +
       "   and PT.T_PARTYID = T.T_PAYER " +
       " order by oc.t_code, t.t_i2placedate, T.T_AMOUNT ";


  rs = trsbdataset(str);

  Запись_ячейка(1,"A2",string("По состоянию на " +start+ " включительно"));


  while (rs and rs.movenext)
    cnt = cnt+1;
    summ = summ + money(rs.t_amount);
debugbreak;
  Код_Ячейки ="A"+Номер_Строки;  Запись_ячейка(1,Код_Ячейки, substr(rs.t_code,7));
  Код_Ячейки ="B"+Номер_Строки;  Запись_ячейка(1,Код_Ячейки, rs.t_shortname);
  Код_Ячейки ="C"+Номер_Строки;  Запись_ячейка(1,Код_Ячейки, rs.t_number);
  Код_Ячейки ="D"+Номер_Строки;  Запись_ячейка(1,Код_Ячейки, rs.t_amount);
  Код_Ячейки ="E"+Номер_Строки;  Запись_ячейка(1,Код_Ячейки, date(rs.t_i2placedate));// ПолучитьКодСубъекта(rs.t_payer,1));
  Код_Ячейки ="F"+Номер_Строки;  Запись_ячейка(1,Код_Ячейки, rs.t_ground);

  Номер_Строки=Номер_Строки+1;
end;


//  (summ);

//  Код_Ячейки ="B"+Номер_Строки;  Запись_ячейка(1,Код_Ячейки, "Итого");
//  Код_Ячейки ="H"+Номер_Строки;  Запись_ячейка(1,Код_Ячейки, money(summ));

end;




 var startdate, enddate, promt, summ=$15000;
  startDate = {curdate} - 1;

     ОткрытиеТаблицы_Книги("rep_k2.xls");
     ИнициализацияЛистов(ЧислоЛистов);
  ws(1).Activate;/*можно писать в этот лист*/
  ob.Visible=false;


// if (GetCmdLineParm("Startdate",startdate))
/* Коркин И.Н. По заявке I-013680 */
if (((GetCmdLineParm("period", period)) and (GetCmdLineParm("interval", interval)) and (GetCmdLineParm("namedep",namedep)) and (GetCmdLineParm("path1", path1)) and (GetCmdLineParm("filename", rep_file_name))) or
	 ((GetCmdLineParm("interval", interval)) and (GetCmdLineParm("date_begin",date_begin)) and 
	  (GetCmdLineParm("date_end",date_end)) and (GetCmdLineParm("namedep",namedep))  and (GetCmdLineParm("path1", path1)) and (GetCmdLineParm("filename", rep_file_name))))
   date_begin = date(date_begin);
   date_end = date(date_end);
	getPeriod (period, interval, @date_begin, @date_end);
	GetData(date_begin, date_end);
else


//Tikh По звонку пользователя
  if ( not GetDate( startDate, "Введите дату периода начала помещения в К2 :" ) )
//  if ( not GetDate( startDate, "Введите дату отчета :" ) )
    exit(1);
  else
    if (startDate >= {curdate})
      msgbox("Значение даты "+string(startDate)+" введено неверно !!!");
      exit(1);
    end;

    if(startdate == date(0,0,0))
       startdate = "01.01.0001";
    end;
  end;
    GetData(startdate, {curdate});
end;

    

  //msgbox("Все! Теперь можете просмотреть полученный отчет в EXCEL","| Нажмите ESC");
  ob.Visible=true;

/* Коркин И.Н. Сохранение отчета. По заявке I-013680 */
if ((path1 != "") and (rep_file_name != ""))
	var mon12, day12, year12;
	DateSplit({curdate}, day12, mon12, year12);
	path1 =  path1 +"\\" + rep_file_name + day12 + mon12 + year12 + string(random(100)) + ".xls";
   wb.SaveAs(path1);
end;

  exit(1);