/*************************************************************************/
/*     Дополнение к автоматизированной банковской системе RS-Bank        */
/*                                                                       */
/*    Имя файла        : rep_debet30k2.mac                               */
/*                                                                       */
/*    Программист      : Котов С.С.                                      */
/*                                                                       */
/*    Создан           : 26.06.2014                                      */
/*                                                                       */
/*************************************************************************/

import Globals, cb_sql;

var date_={curdate};

private macro PrintTop(date_)
  [
    Суммы дебиторской задолженности ПЗО по срокам нахождения в картотеке

   ┌─────┬──────────────────────┬───────────────────┬───────────────────┐
   │Номер│        Номер         │Сумма задолженности│Сумма задолженности│
   │ п/п │        счета         │сроком больше 30 д.│сроком меньше 30 д.│](date(date_));
end;

private macro PrintMed
  [├─────┼──────────────────────┼───────────────────┼───────────────────┤];
end;

private macro PrintLine(n,param0,param1,param2)
  [│#####│######################│###################│###################│](n,param0:r,money(param1):r,money(param2):r);
end;

private macro PrintBottom
  [└─────┴──────────────────────┴───────────────────┴───────────────────┘];
end;

private macro GetData(date_)

 var n=1, before30=0, after30=0;

 var query:string =" select t_receiveraccount," + "\n" +
                   "        sum(case" + "\n" +
                   "              when t_i2placedate<"+GetSqlDate(date_)+"-30 then t_futurepayeramount" + "\n" +
                   "              else 0" + "\n" +
                   "            end) before30,       " + "\n" +
                   "        sum(case" + "\n" +
                   "              when t_i2placedate<"+GetSqlDate(date_)+"-30 then 0" + "\n" +
                   "              else t_futurepayeramount" + "\n" +
                   "            end) after30" + "\n" +
                   "   from dpmpaym_dbt t" + "\n" +
                   "  where t_paymstatus = 2000" + "\n" +
                   "    and substr(t_receiveraccount, 1, 5) in ('47423', '60301')" + "\n" +
                   "  group by t_receiveraccount" + "\n" +
                   "  order by t_receiveraccount";

 var rs =  trsbdataset(query);

 PrintTop;
 PrintMed;
 while ((rs)and(rs.moveNext()))
  if (rs and (ValType(rs.value(0)) != 26))
   PrintLine(n,rs.value(0),rs.value(1),rs.value(2));
   n = n + 1;
   before30 = before30 + rs.value(1);
   after30  = after30  + rs.value(2);
  end;
 end;
 PrintMed;
 PrintLine("Итого","",before30,after30);
 PrintBottom;
 return 0;
end;

// Пока без параметров, но заготовки оставил
//if ( getdate(date_, "Введите дату") )
 GetData(date_);
//end;

