/************************************************************************/
/*          Автоматизированная банковская система RS-Bank v6.0          */
/*                                                                      */
/*               Copyright (c) R-Style Ukraine                          */
/*                                                                      */
/*  Имя файла        : Repforprobis.mac                                 */
/*                                                                      */
/*  Описание         : макрос выбора параметров запроса для отчета      */
/*                                                                      */
/*  Программист      : Новиков С. С.                                    */
/*                                                                      */
/*  Создан           : 24.07.2008                                       */
/*                                                                      */
/*  Изменен          : 28.07.2008 Ойкин В.А.(voikin)                    */
/*                                                                      */
/*  Изменен          : 03.09.2008  Новиков С.С.                         */
/************************************************************************/


import globals;
//используется для выборки данных
import oralib;
//import reportsforms;
import "KeyCodes.mac";
var DateDocum,
    CodDep:integer,
    NumDepart:string = "",
    NameDepart:string = "",
    Oper:integer = 0,
    NameOper:string = "",
    Account:string = "";
var const_message=" ~F2~ Продолжить  ~ESC~ Выход ";
var NameRep;
record Department ("dp_dep.dbt");
record Person     ("person.dbt");
record dlg(docday1,"RSU.lbr") dialog;
//RunDialog(dlg,"HandleEvent");  
//println("|"+NumDepart+"|");
//exit(1);                     //voikin: этот макрос импортирую в свои и там уже вызываю диалог

/*Поиск имени по PartyID*/
macro GetNameByID(id)
private var rsc:object = Null, str="";

  str=string(" select t.* from dparty_dbt t where t.t_PartyID=",id);

  rsc=execSQLselect(str);

  if( rsc.moveNext())
    return rsc.value("T_Name");
  else
    msgbox("Клиент не найден в party");
    return 0;
  end;
end;


macro GetDepartName(NumDepartment:string):string
 var select:string = "";
 var rs:object;
 select = "SELECT t_partyid FROM ddp_dep_dbt "+
          "WHERE t_name = '"+NumDepartment+"' AND t_status = 2 ";
 rs = execSQLselect(select);
 while(rs.moveNext())
    return string(rs.Value(0));
 end;
 return "";
end;       


macro GetOurDepNum(NDep):string
 var select:string = "";
 var rs:object;
 select = "SELECT t_name FROM ddp_dep_dbt "+
          "WHERE t_code = "+NDep+" AND t_status = 2 ";
 rs = execSQLselect(select);
 while(rs.moveNext())
    return string(rs.Value(0));
 end;
 return "";
end;                                

macro GetOurDepCode(NDep):string
 var select:string = "";
 var rs:object;
 select = "SELECT t_code FROM ddp_dep_dbt "+
          "WHERE t_name = '"+NDep+"'";
 rs = execSQLselect(select);
 while(rs.moveNext())
    return string(rs.Value(0));
 end;
 return "";
end;                                

macro GetOperName(NumOper:integer):string
 var select:string = "";
 var rs:object;
 select = "SELECT t_name FROM dperson_dbt "+
          "WHERE t_oper = "+NumOper+"";
 rs = execSQLselect(select);
 while(rs.moveNext())
   return string (rs.Value(0));
 end;
 return "";  
end;


MACRO HandleEvent (dlg, cmd, id, key)

   if(cmd == DLG_INIT)
	//msgbox({NumDprt});
      dlg.NameRep = NameRep;	
      dlg.NumDepart = ""/*GetOurDepNum(string({NumDprt}))*/;   //voikin добавил возможность выбора отчета по всему банку
      dlg.NameDepart = "Банк"/*GetNameByID(GetDepartName(dlg.NumDepart))*/;
      dlg.Oper = 0;
      dlg.NameOper = "Все операциониcты";
      dlg.Date = {curdate};        
      UpdateFields(Dlg);
   end;
   if (cmd==DLG_SETFOCUS)
     if (
        (FldName(dlg,id)=="NumDepart") or
        (FldName(dlg,id)=="Oper"))
         message(" ~F3~ Справочник "+const_message);
     else
        message(const_message);
     end;
   end;

   if ((cmd == DLG_REMFOCUS))
     if (FldName(dlg,id)=="NumDepart")
       if ((GetDepartName(dlg.NumDepart) == "" ) and (dlg.NumDepart != "")) //voikin добавил возможность выбора отчета по всему банку
          msgbox("Подразделение "+dlg.NumDepart+" не найдено ");
          UpdateFields(dlg);
          return CM_CANCEL;
       else
          if (dlg.NumDepart == "")
             dlg.NameDepart = "Банк";
          else
             dlg.NameDepart = GetNameByID(GetDepartName(dlg.NumDepart));
          end;
          UpdateFields(dlg);
       end;
     /**03/09/2008 Новиков С.С. добавил проверку корректности ввода даты*************************************/
     elif (FldName(dlg,id)=="Date")
           if ( dlg.Date > {curdate} )
              MsgBox("Дата больше даты текущего операционного дня"); 
              return CM_CANCEL;
           end;
     /******************************************************************************************************/  
     elif (FldName(dlg,id)=="Oper")
       if ((GetOperName(dlg.Oper) == "") and (dlg.Oper != 0) )
          msgbox("Операционист "+dlg.Oper+" не найден ");
          UpdateFields(dlg);
          return CM_CANCEL;
       else
          if (dlg.Oper == 0)
             dlg.NameOper = "Все операционисты";
          else  
             dlg.NameOper = GetOperName(dlg.Oper);
          end;
          UpdateFields(dlg); 
       end;
     end;
     UpdateFields(dlg); 
   end; /* end cmd==DLG_SETFOCUS*/

   if (cmd==DLG_KEY)
      if (KEY==KEY_ESC)
         if (GetTrue(TRUE,"Вы действительно хотите выйти?"))
           return  CM_CANCEL;
         else
           return  CM_IGNORE;    
         end;
                 
      elif (KEY==KEY_F3)
         if (FldName(dlg,id) == "NumDepart")
          if (ListDepartment (Department))
             dlg.NumDepart = Department.Name;
             dlg.NameDepart = GetNameByID(Department.PartyID);
             UpdateFields(dlg);
          end;
         elif (FldName(dlg,id) == "Oper")
          if (ListOper(Person))
             dlg.Oper = Person.Oper;
             dlg.NameOper = Person.Name;
             UpdateFields(dlg); 
          end; 
         end; /*end KEY==KEY_F3*/
      
      elif (KEY==KEY_F2)
         if(dlg.NumDepart!="")
           CodDep = GetOurDepCode(dlg.NumDepart);  //voikin
         else
           CodDep = Null;
         end;
         NumDepart = dlg.NumDepart;
         NameDepart = dlg.NameDepart;
         Oper = dlg.Oper;
         NameOper = dlg.NameOper;
         DateDocum = dlg.Date;
         Account = dlg.Account;
      /**03/09/2008 Новиков С.С. добавил возможность выполнение только при корректных данных*************/   
         if (DateDocum <= {curDate})
           Return CM_SAVE;
         else
            MsgBox("Не все поля корректны!");
         end;
      /**************************************************************************************************/
      end; /* end cmd==DLG_KEY*/

   end;
// return CM_DEFAULT;   
END;


