/*+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

   ██████████    ██████████             ████████           ████   ████   ████   ████
   ████   ████   ████   ████           ███   ███           ████   ████   ████   ████
   ███████████   ███████████            ███████             ████ ████     ████ ████
   ████████      ████████             ████████ ███           ███ ███       ███ ███
   ████  ████    ████  ████          ████   █████            ███████       ███████
   ████   ████   ████   ████          █████████████           █████         █████

   RR Рахмедов Р.С. & Володина В.В.

   Имя файла : ReportComDiv.mac

   Создан    : VV 27.11.2013(C-24569)
   
   Доработан : RR 22.05.2014

   Описание  : Макрос формирования отчета об удержанных комиссиях в разрезе дат\доходных счетов\дивизионах\
              
   ChangeLog:
   
-----------------------------------------------------------------------------------------------------------------------------------------------------
   //RR 23.07.2014 Внесены правки в отбор по дивизионам
-----------------------------------------------------------------------------------------------------------------------------------------------------
   //RR 25.12.2014 Оптимизирую основной запрос
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*/

 import globals, oralib, BANKINTER, keycodes, rcw, RSD, PTInter, cb_sql, Календарь, VBAConst, "lib_lang.mac",OprInter,treport,payminter,LikePy;
 import "fg_Life_parm.mac" , "fastexcel.mac";
 
 private var fgBank = fg_life_subject({OurBank}); 
 private var script = "",
             excludeBankList = "",
             MenuChoise1,
             select_div,
             cmd_div,
             div_record,
             select_numc,
             cmd_numc,
             numc_record,
             select_acc,
             cmd_acc,
             acc_record,
             select_com,    //+1
             cmd_com,
             com_record,            
             param_div,    
             param_numc,    
             param_acc,
             param_com,  //+1   
             param_datab,   
             param_datae;  
         var contragentSelect,recordcount = 1;
         var ob,ex,obBook,pathfile,path,dataCount;
         var filen = "DIF.lbr";
         var depChoice="";
         var depChoice1="";
         var depChoice2="";
         var depChoice3="";      //+1
         var Div, NumC, Acc,Com, DataB, DataE, DivText, NumText, AccText, ComText;    //+1
         var RepArray = TArray();

 GetRegistryValue("BANK_INI\\ОБЩИЕ ПАРАМЕТРЫ\\ДИРЕКТОРИИ\\LBRDIR",2,path);

 pathfile = FindPath(filen,path);
 if (not pathfile)
   msgbox("Не найдена LBR");
   exit();
 end;

 var dlg = TRecHandler("DIF",pathfile,true);

 MACRO GetCommandText(Acc, DataB, DataE, Div, CText, FeeType)   //+1
 
  var  contragentSelect, ACCFILTER = "", DEFFFILTER = "";
  
  if (Acc != "")
    ACCFILTER = "                            AND ( PAYM.T_RECEIVERACCOUNT IN ("+Acc+") " +
                "                                  OR EXISTS " +
                "                                       (SELECT   1 " +
                "                                          FROM   dpmaddpi_dbt " +
                "                                         WHERE   t_paymentid = PAYM.T_PAYMENTID " +
                "                                                 AND t_account IN ("+Acc+")) " +
                "                                  OR EXISTS " +
                "                                       (SELECT   1 " +
                "                                          FROM   DOPROPER_DBT OPR, DOPRDOCS_DBT DOC, DACCTRN_DBT TRN " +
                "                                         WHERE       OPR.T_DOCUMENTID = LPAD (TO_CHAR (PAYM.T_PAYMENTID), 34, '0') " +
                "                                                 AND DOC.T_ID_OPERATION = OPR.T_ID_OPERATION " +
                "                                                 AND DOC.T_DOCKIND = 1 " +
                "                                                 AND TRN.T_ACCTRNID = DOC.T_ACCTRNID " +
                "                                                 AND TRN.T_CHAPTER = 1 " +
                "                                                 AND TRN.T_ACCOUNT_RECEIVER IN ("+Acc+"))) ";
  end;
  
  
  
  if ( FeeType == 1 )
    DEFFFILTER = "                            AND DEFF.T_DATEPERIODEND BETWEEN TO_DATE ('"+DataB+"','dd.mm.yyyy') " +
                 "                                                         AND TO_DATE ('"+DataE+"','dd.mm.yyyy') ";
  elif (   ( FeeType == 3 ) 
        or ( FeeType == 6 ) )
    DEFFFILTER = "                            AND DEFF.T_DATEFEE BETWEEN TO_DATE ('"+DataB+"','dd.mm.yyyy') " +
                 "                                                   AND TO_DATE ('"+DataE+"','dd.mm.yyyy') ";
  end;

  contragentSelect = " SELECT   COM.T_CODE, " +
                     "          REGEXP_REPLACE(COM.T_NAME, '[' || chr(10) || chr(11) || chr(13) ||':]+', '') T_NAME, " +
                     "          P.T_PAYERACCOUNT, " +
                     "          REGEXP_REPLACE(ACC.T_NAMEACCOUNT, '[' || chr(10) || chr(11) || chr(13) ||':]+', '') T_NAMEACCOUNT, " +
                     "          DECODE (CLIENTOS.T_SERVICEKIND,  1001, 'ДКБ', " +
                     "                                           1002, 'ДМСБ', " +
                     "                                           3,    ' ') DIV, " +
                     "          CASE " +
                     "             WHEN P.T_RECEIVERACCOUNT != CHR (1) " +
                     "             THEN " +
                     "                P.T_RECEIVERACCOUNT " +
                     "             ELSE " +
                     "                (SELECT   max(t_account) " +
                     "                   FROM   dpmaddpi_dbt " +
                     "                  WHERE   t_paymentid = P.T_PAYMENTID " +
                     "                    AND   SUBSTR (T_ACCOUNT, 1, 8) in ('47423810','70601810') ) " +
                     "          END " +
                     "             shit_dahodaff, " +
                     "          P.T_AMOUNT, " +
                     "          CASE " +
                     "             WHEN P.T_PAYMSTATUS = 32000 " +
                     "             THEN " +
                     "                CASE " +
                     "                   WHEN EXISTS " +
                     "                           (SELECT   1 " +
                     "                              FROM   DOPROPER_DBT OPR, DOPRSTEP_DBT STP " +
                     "                             WHERE   OPR.T_DOCUMENTID = LPAD (TO_CHAR (P.T_PAYMENTID),34,'0') " +
                     "                                     AND STP.T_ID_OPERATION = OPR.T_ID_OPERATION " +
                     "                                     AND STP.T_BLOCKID = 10000127 " +
                     "                                     AND STP.T_ISEXECUTE = CHR (88)) " +
                     "                   THEN " +
                     "                      0 " +
                     "                   ELSE " +
                     "                      P.T_AMOUNT - P.T_FUTUREPAYERAMOUNT " +
                     "                END " +
                     "             ELSE " +
                     "                P.T_AMOUNT - P.T_FUTUREPAYERAMOUNT " +
                     "          END " +
                     "             PAYED_SUM, " +
                     "       P.T_AMOUNT  " +
                     "       - CASE " +
                     "             WHEN P.T_PAYMSTATUS = 32000 " +
                     "             THEN " +
                     "                CASE " +
                     "                   WHEN EXISTS " +
                     "                           (SELECT   1 " +
                     "                              FROM   DOPROPER_DBT OPR, DOPRSTEP_DBT STP, DOPRBLOCK_DBT BLK " +
                     "                             WHERE   OPR.T_DOCUMENTID = LPAD (TO_CHAR (P.T_PAYMENTID),34,'0') " +
                     "                                     AND STP.T_ID_OPERATION = OPR.T_ID_OPERATION " +
                     //"                                     AND STP.T_BLOCKID = 10000127 " +
                     "                                     AND STP.T_ISEXECUTE = CHR (88) " +
                     "                                     AND STP.T_BLOCKID = BLK.T_BLOCKID " +
                     "                                     AND BLK.T_NAME = 'Возврат из картотеки') " +
                     "                   THEN " +
                     "                      0 " +
                     "                   ELSE " +
                     "                      P.T_AMOUNT - P.T_FUTUREPAYERAMOUNT " +
                     "                END " +
                     "             ELSE " +
                     "                P.T_AMOUNT - P.T_FUTUREPAYERAMOUNT " +
                     "          END " +
                     "             NOT_PAYED_SUM, " +
                     "          TO_CHAR(P.T_VALUEDATE,'DD.MM.YYYY') VALUEDATE, " +
                     "          P.T_PAYMENTID " +
                     "   FROM   DPMPAYM_DBT P, " +
                     "          DSFCOMISS_DBT COM, " +
                     "          DACCOUNT_DBT ACC, " +
                     "          DCLIENT_DBT CLIENTOS, " +
                     "         (SELECT   T_NUMBER, T_FEETYPE " +
                     "            FROM   DSFCOMISS_DBT " +
                     "           WHERE   T_NUMBER >= 1000 AND T_FEETYPE = "+FeeType+ " "+ CText+") " +
                     "          t " +
                     "  WHERE   P.T_PAYMENTID IN " +
                     "                (  SELECT   MIN (PAYM.T_PAYMENTID) " +
                     "                     FROM   DSFDEF_DBT DEFF, " +
                     "                            DPMPAYM_DBT PAYM " +
                     "                    WHERE       DEFF.T_COMMNUMBER = T.T_NUMBER " +
                     "                            AND DEFF.T_FEETYPE = T.T_FEETYPE " +
                     "                            AND PAYM.T_FEETYPE = T.T_FEETYPE " +
                     "                            AND DEFF.T_STATUS >= 30 " +
                     "                            AND DEFF.T_SUM != 0 " + DEFFFILTER +
                     "                            AND PAYM.T_DEFCOMID = DEFF.T_ID " +
                     "                            AND PAYM.T_PAYER = CLIENTOS.T_PARTYID " + ACCFILTER +
                     "                 GROUP BY   PAYM.T_DEFCOMID) " +
                     "          AND COM.T_NUMBER = T.T_NUMBER " +
                     "          AND COM.T_FEETYPE = T.T_FEETYPE " +
                     "          AND ACC.T_ACCOUNT = P.T_PAYERACCOUNT " +
                     "          AND ACC.T_CHAPTER = 1 " +
                     "          AND ACC.T_CLIENT = P.T_PAYER " +
                     "          AND CLIENTOS.T_PARTYID = P.T_PAYER " +
                     "          AND CLIENTOS.T_BRANCH = 0 " +
                     "          AND CLIENTOS.T_STARTDATE = (SELECT   MAX (T_STARTDATE) " +
                     "                                        FROM   DCLIENT_DBT " +
                     "                                       WHERE   T_PARTYID = P.T_PAYER " +
                     "                                         AND  (T_FINISHDATE >= TO_DATE ('"+{curdate}+"', 'dd.mm.yyyy') " +
                     "                                               OR T_FINISHDATE = TO_DATE ('01.01.0001', 'dd.mm.yyyy'))) " +
                     "          AND (   CLIENTOS.T_FINISHDATE >= to_date('"+{curdate}+"','dd.mm.yyyy') " +
                     "               OR CLIENTOS.T_FINISHDATE = to_date('01.01.0001','dd.mm.yyyy') ) " +
                     "          AND CLIENTOS.T_SERVICEKIND = (SELECT   MAX (T_SERVICEKIND) " +
                     "                                          FROM   DCLIENT_DBT " +
                     "                                         WHERE   T_PARTYID = P.T_PAYER " +
                     "                                           AND   T_SERVICEKIND IN ("+Div+") " +
                     "                                           AND  (T_FINISHDATE >= TO_DATE ('"+{curdate}+"', 'dd.mm.yyyy') " +
                     "                                                 OR T_FINISHDATE = TO_DATE ('01.01.0001', 'dd.mm.yyyy'))) ";
   return contragentSelect;
END;

 private macro cutTextCodeToStr(_str) /*приведеие данных из полей формы к sql строке для оператора IN*/
          var mas:Tarray=tarray();
          var i:integer = 0, i1 = 0;
          var CodeToStr = "",f;
              mas(mas.size) = ","; mas(mas.size) = ";"; /*список проверяемых символов, можно расширить */
              i = 0; i1 = 0;
          while (i1<mas.size)
             f = split(trim(_str),mas(i1));
             CodeToStr = "";
             while (i<f.size(f))
                CodeToStr = CodeToStr + "','" + trim(f(i)) ;
                i = i + 1;      
             end;
             _str = substr(CodeToStr,4);
             i = 0; i1 = i1+1;
          end;
          return(substr(CodeToStr,3)+"'");
 end;
 
 MACRO SetTypeColumns(aw:tarray); /*Создаем двумерный массив с форматами столбцов*/
            var w1  = tarray(true); w1(0)  = 1;  w1(1)  = 2; aw(0)  = w1; /* формат столбца - Text     */
            var w2  = tarray(true); w2(0)  = 2;  w2(1)  = 2; aw(1)  = w2; /* формат столбца - Text     */
            var w3  = tarray(true); w3(0)  = 3;  w3(1)  = 2; aw(2)  = w3; /* формат столбца - Text     */
            var w4  = tarray(true); w4(0)  = 4;  w4(1)  = 2; aw(3)  = w4; 
            var w5  = tarray(true); w5(0)  = 5;  w5(1)  = 2; aw(4)  = w5; 
            var w6  = tarray(true); w6(0)  = 6;  w6(1)  = 2; aw(5)  = w6;
            var w7  = tarray(true); w7(0)  = 7;  w7(1)  = 1; aw(6)  = w7; 
            var w8  = tarray(true); w8(0)  = 8;  w8(1)  = 1; aw(7)  = w8; 
            var w9  = tarray(true); w9(0)  = 9;  w9(1)  = 1; aw(8)  = w9;
            var w10 = tarray(true); w10(0) = 10; w10(1) = 2; aw(9)  = w10; 
         //   var w9=tarray(true); w9(0)=9; w9(1)=2; aw(8)=w9; /* формат столбца - Text     */
 END;/*macro*/

 MACRO splitTime()  /* перевод времени в формат ЧЧ_ММ_СС для вставки в имя файла */
  private var timesec = string(Time);
  private var splittimesec; 
     splittimesec = Substr(timesec,1,2)+"_"+substr(timesec,4,2)+"_"+substr(timesec,7,2);
     return splittimesec;
    
 END;

 MACRO ContragentsReport() /* Конструктор запроса, создание транспортного файла и открытие его Экселем */

   private var dd:date,      /*|                                            */
               tt:time,      /*|  это переменные для использования FileInfo */
               ii:integer,   /*|                                            */
               ss:string;    /*|                                            */
           var TimeSecond = splitTime();
           var NameTranspFile:string = "ReportComiss_"+TimeSecond;
           var SPNameTranspFile = GetTxtFileName(NameTranspFile);
               NameTranspFile = substr(SPNameTranspFile,12);     /* имя файла без пути */
           var ComArray = TArray();
           var i = 0;
           var dataContr;
               
   setOutput(SPNameTranspFile);
   RepArray(0) = dlg.rec.DataB;
   RepArray(1) = dlg.rec.DataE;
   RepArray(2) = dlg.rec.Com;
   RepArray(3) = dlg.rec.NumC;
   RepArray(4) = dlg.rec.Acc;
   RepArray(5) = dlg.rec.Div;
 
 if (dlg.rec.Div!="")
   DivText = "'"+dlg.rec.Div+"'";
 else  
   DivText = "'3','1001','1002'";  
 end;

debugbreak;

 if (dlg.rec.NumC!="")
   if(depChoice1) 
     if (index(dlg.rec.numc,",") == 0)
       ComArray(i) = dlg.rec.numc;
     else
       while (index(dlg.rec.numc,",") != 0)
         ComArray(i) = substr(dlg.rec.numc, 1, index(dlg.rec.numc,",")- 1);
         dlg.rec.numc = substr(dlg.rec.numc, index(dlg.rec.numc,",")+ 1);
         i = i + 1;
         if (index(dlg.rec.numc,",") == 0)
           ComArray(i) = dlg.rec.numc;
           i = i + 1;
         end;
       end;
     end;
   else
     ComArray(i) = "'"+dlg.rec.numc+"'";
   end;
 end;
 
 if (dlg.rec.Acc!="")
   if (StrLen(dlg.rec.Acc) > 20)
     AccText = dlg.rec.Acc;
   else
     AccText = "'"+dlg.rec.Acc+"'";
   end;
 else   
   AccText = "";
 end;
 
 i = 0;
 
//if(dlg.rec.Com)                //+1
//  if(depChoice3)
//  end;  
//end;

 if (ComArray.size == 0 )
   var rs = RSDRecordset("select t_code from dsfcomiss_dbt where t_number >= 1000 and t_feetype = " +dlg.rec.com);
   i = 0;
   while (rs and rs.movenext())
     ComArray(i) = "'"+rs.value(0)+"'";
     i = i + 1;
   end;
 end;
 
  i = 0;
  InitProgress(ComArray.size,"Ждите...","Идет обработка комиссий");
  while (i < ComArray.size)
   
    message("Обработка комиссии " + ComArray(i));
    
    contragentSelect = GetCommandText(AccText, dlg.rec.DataB, dlg.rec.DataE, DivText, "and t_code = "+ComArray(i)+"", dlg.rec.com);   //+1
    dataContr = TRsbDataSet(contragentSelect);
    debugbreak;
    
    if ( i == 0 )
      println("Код комиссии"             +"║"+
              "Наименование комиссии"    +"║"+
              "Счет плательщика"         +"║"+
              "Наименование плательщика" +"║"+
              "Дивизион"                 +"║"+
              "Счет дохода"              +"║"+
              "Сумма комиссии"           +"║"+
              "Оплаченная сумма"         +"║"+
              "Не оплачено"              +"║"+
              "Дата документа"           +"║" );          //+1
    end;
      
    dataCount = 2;
    InitProgress(-1,"","Выборка данных комиссии "+ComArray(i));
    while(dataContr.movenext())  /* заполнение транспортного файла */
       dataCount = dataCount+1;
       println(dataContr.code             + "║" +  
               dataContr.name             + "║" + 
               dataContr.payeraccount     + "║" + 
               dataContr.nameaccount      + "║" +
               dataContr.div              + "║" +
               dataContr.shit_dahodaff    + "║" +
               dataContr.amount           + "║" +
               dataContr.PAYED_SUM        + "║" +
               dataContr.NOT_PAYED_SUM    + "║" +
               dataContr.valuedate        + "║" );          //+1     
       recordcount = recordcount + 1;
       UseProgress(recordcount);
     end;/*while*/
     RemProgress();
       
   i = i + 1;
   UseProgress(i);
 end;
 RemProgress();
 
 setOutput(NULL,TRUE);
 CopyFile(NameTranspFile,"$c:\\rspar\\"+NameTranspFile, TRUE);                                      /* копирование транспортного файла на терминал */
 ob = CreateObject ("rsax","TRsAxServer","RsAxServer",IsStandAlone());                              /* создание объекта для работы с приложениями  */
 ex = ob.CreateComObject ("Excel.Application", true);                                               /* Active X, запуск Экселя                     */
                                                                                                    /*                                             */
 if(not(GetFileInfo("$c:\\rspar\\"+NameTranspFile,@dd,@tt,@ii,@ss)));                               /* проверка успешности копирования и наличия   */
    println("не мог найти на локальном диске файл "+NameTranspFile+"          \n останавливаюсь");  /* файла на терминале пользователя             */
    exit(0);
 end;
 
 ss = substr(ss,2);
 var aw=tarray(true); 
 SetTypeColumns(aw);
 obBook = ex.Workbooks.opentext (ss, 866, 1, 1,2,false,false,false,false,false,true,"║",aw,1,"."," ",true,false); /*  открытие транспортного файла       */
   
 END;/*macro ContragentsReport()*/

 Macro formatExcel()
     message("Форматирование книги Excel");
     
     private var i = 1; 
             var obSheet = ex.Sheets(1);
     while(recordcount >= i)                                        /* передается число строк в рекордсете           */
        obSheet.Range("A"+i+":K"+i).Interior.Color = 15395562;      /* в диапазоне с записанными данными заливаем    */
        i = i + 2;                                                  /* через одну строки светло серым                */
     end;
     obSheet.Range("A1:K1").HorizontalAlignment = -4108;//xlCenter; /* горизонтальное выравнивание                   */
     obSheet.Range("A1:K1").Interior.Color = 1;                     /* заливка ячейки, в данном случае черным цветом */
     obSheet.Range("A1:K1").Font.Colorindex = 2;                    /* цвет текста                                   */
     obSheet.Range("A1:K1").WrapText = true;
     obSheet.Range("A1:K1").Font.Bold = true;                       /* полужирный текст                              */
     ex.ActiveWindow.Selection.AutoFilter;                          /* установка автофильтра на активный лист        */
     obSheet.Range("A2").Select;                                    /* выбор ячейки и последующее                    */
     ex.ActiveWindow.FreezePanes = true;                            /* закрепление области                           */
     obSheet.Columns("A:A").ColumnWidth = 14.00;                    /* установление ширины колонок                   */
     obSheet.Columns("B:B").ColumnWidth = 32.00;                    /*                                               */
     obSheet.Columns("C:C").ColumnWidth = 22.00;                    /*                                               */
     obSheet.Columns("D:D").ColumnWidth = 32.00;                    /*                                               */
     obSheet.Columns("E:E").ColumnWidth = 12.00;                    /*                                               */
     obSheet.Columns("F:F").ColumnWidth = 22.00;                    /*                                               */
     obSheet.Columns("G:G").ColumnWidth = 12.00;                    /*                                               */
     obSheet.Columns("G:G").NumberFormat= "# ##0,00р.";
     obSheet.Columns("H:H").ColumnWidth = 12.00;                    /*                                               */
     obSheet.Columns("H:H").NumberFormat= "# ##0,00р.";
     obSheet.Columns("I:I").ColumnWidth = 12.00;                    /*                                               */
     obSheet.Columns("I:I").NumberFormat= "# ##0,00р.";
     obSheet.Columns("J:J").ColumnWidth = 12.00;                    /*                                               */
   
     obSheet.Range("A1:J"+recordcount).Borders.LineStyle = xlContinuous;  /* тип линии границы - сплошной            */
     obSheet.Range("A1:J"+recordcount).Borders.Weight = xlThin;           /* толщина линии                           */
     obSheet.Range("A1:J1").Borders.Colorindex = 2;                       /* свет линии рамки - белый                */
     obSheet.Rows("1:1").RowHeight = 30.00;                               /* установление высоты строки              */
   
    i=i+3;
    // ObSheet.Range("A"+i+":B"+i).Merge;	
    ObSheet.Cells(i, 1).Value = "Итого(кол-во):";
    ObSheet.Cells(i,2).Value =string(recordcount-1);
    ObSheet.Cells(i,3).Value = "Штук";
    i=i+1;
    // ObSheet.Range("A"+i+":B"+i).Merge;	
    ObSheet.Cells(i, 1).Value = "Общая сумма комиссий: ";
    ObSheet.Cells(i, 2).Value =  "=СУММ(G2:G"+(i-5)+")";
  
 i=i+1;
    // ObSheet.Range("A"+i+":B"+i).Merge;	
    ObSheet.Cells(i, 1).Value = "Оплачено: ";
    ObSheet.Cells(i, 2).Value =  "=СУММ(H2:H"+(i-6)+")";
  
 i=i+1;
    // ObSheet.Range("A"+i+":B"+i).Merge;	
    ObSheet.Cells(i, 1).Value = "Неоплачено: ";
    ObSheet.Cells(i, 2).Value =  "=СУММ(I2:I"+(i-7)+")";
  

     //	ObSheet.Cells(i, 2).Value = string(recordcount) + "шт";
     ex.visible = true;
 end;/*macro*/

 MACRO HandleEvent (dlg, cmd, id, key)
        //вспомогательное заполнение массива для построения скроллинга
     macro addCol (ar, ind, fld, head, width, rdonly)
         ar.value (ind * 6) = fld;
         ar.value (ind * 6 + 1) = head;
         ar.value (ind * 6 + 2) = width;
         ar.value (ind * 6 + 3 ) = 2;  // fldType
         ar.value (ind * 6 + 4 ) = -1; // decPoint
         ar.value (ind * 6 + 5 ) = 0;  // reserv
     end;
    
     macro EvProc (div_record, cmd_div, id, key)
        if(( cmd == DLG_KEY ) and ( KEY==KEY_Enter ))
           return CM_SELECT;
        end;
     end;
    
     macro EvProc1 (numc_record, cmd_numc, id, key)
        if(( cmd == DLG_KEY ) and ( KEY==KEY_Enter ))
           return CM_SELECT;
        end;
     end;
    
     macro EvProc2 (acc_record, cmd_acc, id, key)
        if(( cmd == DLG_KEY ) and ( KEY==KEY_Enter ))
           return CM_SELECT;
        end;
     end;

 //+1
     macro EvProc3 (com_record, cmd_com, id, key)
       if(( cmd == DLG_KEY ) and ( KEY==KEY_Enter ))
          return CM_SELECT;
       end;
     end;

     macro EventHandler (rs, cmd, id, key )
      if (cmd == DLG_INIT)
          if (not AddMultiAction (rs, 316)) 
              msgbox ("Не удалось выполнить AddMultiAction ()");
          end;
      end;
      if ((cmd == DLG_MSEL) and (key == 316)) // F2
          depChoice = depChoice+ "," + string (rs.value("T_SERVICEKIND"));
          return CM_MSEL_CONT_CLEAR;
      end;
      if(depChoice)
         if ((cmd == DLG_KEY) and ((key == 13) or (KEY==KEY_ESC)))
             return CM_SELECT;
          end;
      else 
          if ((cmd == DLG_KEY) and (key == 13))
             return CM_SELECT;
          end; 
      end;
         if (cmd == DLG_MSELEND)// and (key == 316)) // F2
             return CM_MSEL_STOP_CLEARALL;
         end;
      end;  
    
      macro EventHandler1 (rs, cmd, id, key )
        if (cmd == DLG_INIT)
            if (not AddMultiAction (rs, 316)) 
                msgbox ("Не удалось выполнить AddMultiAction ()");
            end;
        end;
        if ((cmd == DLG_MSEL) and (key == 316)) // F2
            depChoice1 = depChoice1+","+"'"+string (rs.value("T_CODE"))+"'";
            return CM_MSEL_CONT_CLEAR;
        end;
      if(depChoice1)
        if ((cmd == DLG_KEY) and ((key == 13) or (KEY==KEY_ESC)))
            return CM_SELECT;
         end;
     else 
         if ((cmd == DLG_KEY) and (key == 13))
            return CM_SELECT;
         end; 
     end;
        if (cmd == DLG_MSELEND)// and (key == 316)) // F2
            return CM_MSEL_STOP_CLEARALL;
        end;
       
       end; 
    
      macro EventHandler2 (rs, cmd, id, key )
        if (cmd == DLG_INIT)
            if (not AddMultiAction (rs, 316)) 
                msgbox ("Не удалось выполнить AddMultiAction ()");
            end;
        end;
        if ((cmd == DLG_MSEL) and (key == 316)) // F2
            depChoice2 =depChoice2+","+"'"+string (rs.value("T_ACCOUNT"))+"'";
            return CM_MSEL_CONT_CLEAR;
        end;
       if(depChoice2)
        if ((cmd == DLG_KEY) and ((key == 13) or (KEY==KEY_ESC)))
            return CM_SELECT;
         end;
     else 
         if ((cmd == DLG_KEY) and (key == 13))
            return CM_SELECT;
         end; 
     end;

        if (cmd == DLG_MSELEND)// and (key == 316)) // F2
            return CM_MSEL_STOP_CLEARALL;
        end;
     end;  

       

  if(cmd == DLG_INIT)
        message("~F2~ продолжить, ~F3~ справочник, ~ESC~ выход ");
         dlg.rec.DataB = {curDate};    
         dlg.rec.DataE = {curDate};
         dlg.rec.com   = 1; //По умолчанию периодические
       UpdateFields(dlg);
  end;
  /*
  if (cmd == DLG_REMFOCUS)
        if (FldName(dlg,id)=="DataB")
           if ( dlg.rec.DataB > {curdate} )
              MsgBox("Дата начала периода больше даты текущего операционного дня"); 
              return CM_CANCEL;
           end;
        end;
        if (FldName(dlg,id)=="DataE")
           if ( dlg.rec.DataE > {curdate} )
              MsgBox("Дата конца периода больше даты текущего операционного дня"); 
              return CM_CANCEL;
           end;
        end;
     
        UpdateFields(dlg); 
  end;*/

  if (cmd==DLG_KEY)
    if (KEY==KEY_ESC)
      return  exit(1);;
    elif (KEY==KEY_F1)
     msgbox("HELP YOURSELF");
      return CM_Ignore;   
        
    elif (KEY==KEY_F9)
      return CM_Ignore;  
        
    elif (KEY==KEY_F3)
      var col = TArray();
        
      if (FldName(dlg,id) == "DataB")
        dlg.rec.DataB = GetDateByCalendar ({curDate});
      end;
        
      if (FldName(dlg,id) == "DataE")
        dlg.rec.DataE = GetDateByCalendar ({curDate});
      end;
      
      if (FldName(dlg,id) == "Div")
        addCol(col, 0, "Номер", "Номер", 15, true);
        addCol(col, 1, "Наименование", "Наименование", 15, true);
        depChoice="";
        select_div = " SELECT   DISTINCT CL.T_SERVICEKIND, DECODE (CL.T_SERVICEKIND, 1001, 'ДКБ', 1002, 'ДМСБ') "+
                     "   FROM   dclient_dbt cl "+
                     "  WHERE   CL.T_SERVICEKIND in(1001, 1002) ";
        cmd_div = RSDCommand(select_div);
        div_record = RSDRecordset( cmd_div, RSDVAL_CLIENT, RSDVAL_STATIC );
         if (RunScroll(div_record,col,2,"Дивизион",@EventHandler,"Дивизионы","ВАЖНО! ~Enter~-выбора одного значения, ~F2~ -сохранить множественный выбор , ~Esc~-выход", true))
          if(depChoice)
            dlg.rec.Div= substr(depChoice,2);
           else
              dlg.rec.Div= div_record.value(0);
           end;  
          UpdateFields(dlg);
         end;
       end;     
       
      if (FldName(dlg,id) == "NumC")
        addCol(col, 0, "Номер", "Номер", 15, true);
        addCol(col, 1, "Код", "Код комиссии", 15, true);
        addCol(col, 2, "Наименование", "Наименование", 30, true);
        depChoice1="";

        if (dlg.rec.com == "")
          select_numc = " select t_number ,t_code ,t_name from dsfcomiss_dbt where t_number >= 1000 order by t_number ";
        else
          select_numc = " select t_number ,t_code ,t_name from dsfcomiss_dbt where t_number >= 1000 and t_feetype = "+dlg.rec.com+" order by t_number ";
        end;

        cmd_numc = RSDCommand(select_numc);
        numc_record = RSDRecordset( cmd_numc, RSDVAL_CLIENT, RSDVAL_STATIC );
               
        if (RunScroll(numc_record,col,3,"Комиссии",@EventHandler1,"Комиссии","~Enter~-выбора одного значения, ~Esc~-выход", true))
          if(depChoice1)                 
            dlg.rec.NumC=substr(depChoice1,2);
          else
            dlg.rec.NumC=numc_record.value(1);
          end; 
           UpdateFields(dlg);
        end;
       end;  

      if (FldName(dlg,id) == "Acc")
        depChoice2="";
        addCol(col,0, "Счет", "Счет", 23, true);
        addCol(col,1, "Наименование", "Наименование", 23, true);
        addCol(col,2, "Остаток", "Остаток", 23, true);       

        select_acc ="select AC.T_ACCOUNT, AC.T_NAMEACCOUNT,AC.T_R0 from daccount_dbt ac where AC.T_ACCOUNT like '70601810%' ";
        cmd_acc = RSDCommand(select_acc);
        acc_record = RSDRecordset( cmd_acc, RSDVAL_CLIENT, RSDVAL_STATIC );
               
        if (RunScroll(acc_record,col,1,"Счет",@EventHandler2,"Счета доходов","ВАЖНО! ~Enter~-выбора одного значения, ~F2~ -сохранить множественный выбор , ~Esc~-выход", true))
           if(depChoice2)
             dlg.rec.Acc= substr(depChoice2,2);                   
           else
              dlg.rec.Acc=acc_record.value(0);                   
           end; 
                                
           UpdateFields(dlg);
        end;
    end; 

   //+1
      if (FldName(dlg,id) == "Com")
        addCol(col, 0, "Номер", "Номер", 15, true);
        addCol(col, 1, "Наименование", "Наименование", 15, true);
        depChoice3="";
        select_com = "select t_inumberalg, t_sznamealg from   dnamealg_dbt where t_itypealg = 2375 ";
        cmd_com = RSDCommand(select_com);
        com_record = RSDRecordset( cmd_com, RSDVAL_CLIENT, RSDVAL_STATIC );
        if (RunScroll(com_record,col,2,"Тип взимания",@EventHandler,"Тип взимания","ВАЖНО! ~Enter~-выбора одного значения, ~F2~ -сохранить множественный выбор , ~Esc~-выход", true))
          if(depChoice3)
            dlg.rec.Com= substr(depChoice3,2);
          else
              dlg.rec.Com= com_record.value(0);
          end;  
          UpdateFields(dlg);
        end;
      end;     

   elif ( KEY == KEY_F2 )  
     Return CM_SAVE;
     DataB=dlg.rec.DataB;
     DataE=dlg.rec.DataE;
   elif (KEY==KEY_UP)
     Return 0 ;
   elif (KEY==KEY_DOWN)
    return 0;
   elif (KEY==KEY_LEFT)
     return 0;
   elif (KEY==KEY_RIGHT)
     return 0;
   elif (KEY==KEY_TAB)
     return 0;
   elif (KEY==KEY_ENTER)
     return 0;
   else
     Return CM_IGNORE;
   end;
  
  end; /* end cmd==DLG_KEY*/
 
 end;/*macro HandleEvent*/
 
/*****************************************************Точка Входа(Entry Point)**********************************************************************/
  if (RunDialog(dlg,"HandleEvent"))        
    ContragentsReport();
    formatExcel();
    println("Отчет сформирован по следующим параметрам:");
    println("Дата начала    : " + RepArray(0));
    println("Дата окончания : " + RepArray(1));
    println("Тип комиссий   : " + RepArray(2));
    println("Комиссии       : " + RepArray(3));
    println("Доходные счета : " + RepArray(4));
    println("Дивизионы      : " + RepArray(5));
  end;
/**************************************************************************************************************************************************/












