/****************************************************/
/* Таблица маршрутизации в эксель                   */
/* Коркин И.Н.                                      */
/* 17.12.2010                                       */
/* Реализовано по заявке I-074699.                  */
/****************************************************/

import rsexts, "VBAconst.mac";
import RsbDataSet, globals;

//Gurin S. 07.02.2014 Адаптация 2031
private const xlGeneral = 1,
              xlBottom = -4107,
              xlContext = -5002;


var 	exst, i, page, flag, ex, ob, out, f, countlist,
		output="tm.xls",
		fulloutput, obBook, obsheet;

var begindate, enddate, chapter, che;

macro calculate(chapter, begindate, enddate)
	var query, data;
   query = "select * from usr_route_parm";
   message("Расчет...");
   data = TRsbDataset(query);
   return data;
end;    
    
macro openExcel(output)
	var out;
   if (IsStandAlone()) // Двухзвенка
      if ((ValType(ex)!=V_UNDEF) and (ex.Visible==False))
      	ex = ActiveX("Excel.Application",NULL,false); 
      else
      	ex = ActiveX("Excel.Application",NULL,true);        
      end;
   else                // Трехзвенка
      ob = CreateObject ("rsax","TRsAxServer","RsAxServer",false);
      ex = ob.CreateComObject ("Excel.Application");
   end; 
	GetRegistryValue("BANK_INI\\ОБЩИЕ ПАРАМЕТРЫ\\ДИРЕКТОРИИ\\USERTEMPLSDIR",2,out);
   Fulloutput = FindPath(output, out);
   if (not Fulloutput)
      msgbox("Не найден шаблон");
      exit();
   end;
   obBook = ex.Workbooks.open(fulloutput,false); 
   obSheet = obBook.ActiveSheet();
 
// Зленко М. 19.04.2012 C-8523
MACRO format_vertical(cell)
   obSheet.Range(cell).HorizontalAlignment = xlGeneral;
   obSheet.Range(cell).VerticalAlignment = xlBottom ;
   obSheet.Range(cell).WrapText = False ;
   obSheet.Range(cell).Orientation = 90 ;
   obSheet.Range(cell).AddIndent = False ; 
   obSheet.Range(cell).IndentLevel = 0 ;
   obSheet.Range(cell).ShrinkToFit = False ;
   obSheet.Range(cell).ReadingOrder = xlContext ;
   obSheet.Range(cell).MergeCells = False ;
   obSheet.Range(cell).Columns.AutoFit;
END;   
    
   obSheet.Range("A"+1).Value = "Номер правила";                   format_vertical("A"+1) ;
   obSheet.Range("B"+1).Value = "Номер бэк-офиса";                 format_vertical("B"+1) ;             
   obSheet.Range("C"+1).Value = "Статус";                          format_vertical("C"+1) ;
   obSheet.Range("D"+1).Value = "Дебет";               
   obSheet.Range("E"+1).Value = "Кредит";              
   obSheet.Range("F"+1).Value = "Исключение Дт";        
   obSheet.Range("G"+1).Value = "Исключение Кт";             
   obSheet.Range("H"+1).Value = "Вид платежа";             
   obSheet.Range("I"+1).Value = "Происхождение";               
   obSheet.Range("J"+1).Value = "Валюта";	                         format_vertical("J"+1) ;
   obSheet.Range("K"+1).Value = "Системный тип счета Дт";          format_vertical("K"+1) ;
   obSheet.Range("L"+1).Value = "Системный тип счета Кт";          format_vertical("L"+1) ;
   obSheet.Range("M"+1).Value = "Пользовательский тип счета Дт";   format_vertical("M"+1) ;
   obSheet.Range("N"+1).Value = "Пользовательский тип счета Кт";   format_vertical("N"+1) ;
   obSheet.Range("O"+1).Value = "Сервер БД (строка соединения)";               
   obSheet.Range("P"+1).Value = "Процедура";	        
   obSheet.Range("Q"+1).Value = "Автовыполнение шага зачисления";  format_vertical("Q"+1) ;          
   obSheet.Range("R"+1).Value = "Описание условия";		         
   obSheet.Range("S"+1).Value = "Запрос на исполнение выгрузки";   format_vertical("S"+1) ;             
  
   
   
                

end;

macro undeftostr(val)
	if (valtype(val) == v_undef)
		return "";
	else
		return val;
	end;
end;


macro writeBody(data)
	var i;
	i = 3;
	message("Печать в Excel...");
	InitProgress(-1, "", "Печать таблицы маршрутизации");
   while (data.movenext)
   	obSheet.Cells(i,1).Value = string(undeftostr(data.value("RULE_ID")));	
   	obSheet.Cells(i,2).Value = string(undeftostr(data.value("BO_ID")));	
   	obSheet.Cells(i,3).Value = string(undeftostr(data.value("STATE")));	
   	obSheet.Cells(i,4).Value = string(undeftostr(data.value("DEB_ACCMASK")));	
   	obSheet.Cells(i,5).Value = string(undeftostr(data.value("KRED_ACCMASK")));	
   	obSheet.Cells(i,6).Value = string(undeftostr(data.value("DEB_ACCMASK_SKIP")));	
   	obSheet.Cells(i,7).Value = string(undeftostr(data.value("KRED_ACCMASK_SKIP")));	
   	obSheet.Cells(i,8).Value = string(undeftostr(data.value("DOCKIND_CASE")));	
   	obSheet.Cells(i,9).Value = string(undeftostr(data.value("ORIGIN_CASE")));	
   	obSheet.Cells(i,10).Value= string(undeftostr(data.value("CUR_MASK")));	
   	obSheet.Cells(i,11).Value= string(undeftostr(data.value("DEB_SYS_ACCTYPE_CASE")));	
   	obSheet.Cells(i,12).Value= string(undeftostr(data.value("KRED_SYS_ACCTYPE_CASE")));	
   	obSheet.Cells(i,13).Value= string(undeftostr(data.value("DEB_USER_ACCTYPE_CASE")));	
   	obSheet.Cells(i,14).Value= string(undeftostr(data.value("KRED_USER_ACCTYPE_CASE")));	
   	obSheet.Cells(i,15).Value= string(undeftostr(data.value("CONNSTRING")));	
   	obSheet.Cells(i,16).Value= string(undeftostr(data.value("EXTPROCNAME")));	
   	obSheet.Cells(i,17).Value= string(undeftostr(data.value("EXECCARRY_TYPE")));	
   	obSheet.Cells(i,18).Value= string(undeftostr(data.value("NOTE")));	
   	obSheet.Cells(i,19).Value= string(undeftostr(data.value("NEED_ASK")));	
   	i = i + 1;
   	UseProgress(i);
   end; 
   RemProgress();
end;

macro osvInExcel()
	var data;
	data = calculate(chapter, begindate, enddate);
	openExcel(output);
	writeBody(data);
	Ex.visible = true;
	message("Готово");
end;

/*Точка входа в макрос*/

	osvInExcel();




