import rsbdataset;
var reportdate = date("04.12.2009");
initprogress(10,"производится расчет");
var rsd, sql, i = 1;
while (reportdate <date("05.12.2009"))
useprogress(int(i));
i = i+1;
/*
sql = " select a.*, (a.st+a.kt-a.dt-a.end) from "+
" (select t_account, rsb_account.kreditac(t_account,t_chapter,t_code_currency,to_date('"+reportdate+"','DD-MM-YYYY'),to_date('"+reportdate+"','DD-MM-YYYY')) as kt "+
" , rsb_account.debetac(t_account,t_chapter,t_code_currency,to_date('"+reportdate+"','DD-MM-YYYY'),to_date('"+reportdate+"','DD-MM-YYYY')) as dt, "+
" rsb_account.restac (t_account,t_code_currency,TO_DATE ('"+(reportdate-1)+"', 'DD-MM-YYYY'), t_chapter, NULL) as st, "+
" rsb_account.restac (t_account,t_code_currency,TO_DATE ('"+reportdate+"', 'DD-MM-YYYY'), t_chapter, NULL) as end "+
" from daccount$_dbt where t_chapter = 3) a "+
" where (a.st+a.kt-a.dt)!=a.end ";
*/


sql = " select a.*, (a.st+a.kt-a.dt-a.end) from "+
" (select t_account, rsb_account.kredita(t_account,t_chapter,to_date('"+reportdate+"','DD-MM-YYYY'),to_date('"+reportdate+"','DD-MM-YYYY')) as kt "+
" , rsb_account.debeta(t_account,t_chapter,to_date('"+reportdate+"','DD-MM-YYYY'),to_date('"+reportdate+"','DD-MM-YYYY')) as dt, "+
" rsb_account.resta (t_account,TO_DATE ('"+(reportdate-1)+"', 'DD-MM-YYYY'), t_chapter, NULL) as st, "+
" rsb_account.resta (t_account,TO_DATE ('"+reportdate+"', 'DD-MM-YYYY'), t_chapter, NULL) as end "+
" from daccount_dbt where t_chapter = 3) a "+
" where (a.st+a.kt-a.dt)!=a.end ";
 
rsd = trsbdataset(sql);
[###############](reportdate);
[############################# ############### ################## ##################### ####################### ######################]
("Счет", "Кредит", "Дебет", "Остаток на начало", "Остаток на конец", "Недостаток");
while (rsd.movenext())
[############################# ############### ################## ##################### ####################### ######################]
(rsd.value(0),rsd.value(1),rsd.value(2),rsd.value(3),rsd.value(4),rsd.value(5));
end;
reportdate=reportdate+1;
end;