/*
Результат измерения статистики за период
Тихомиров А.Н.
*/

Import RSD, Календарь, globals;

var rsd, cmd, date_begin = {curdate}, date_end = {curdate};

if ( (getdate(date_begin,"Дата начала периода")) and (getdate(date_end,"Дата окончания периода")) )

cmd = rsdcommand("SELECT t_name, t_param, amount, sec, t_flag, "+
     "  CASE "+
     "     WHEN sec > t_flag "+
     "        THEN CHR (0) "+
     "        ELSE CHR (88) "+
     "  END CASE "+
 " FROM (SELECT t_name, t_param, amount, "+
 "              ROUND (DURATION / amount * 3600 * 24, 2) AS sec, t_flag "+
 "         FROM (SELECT   spr.t_name, usr.t_param, "+
 "                        SUM (usr.t_timeend - usr.t_timebegin) DURATION, "+
 "                        SUM (DECODE (NVL (usr.t_amount, 1), "+
 "                                     0, 1, "+
 "                                     NVL (usr.t_amount, 1) "+
 "                                    ) "+
 "                            ) amount, "+
 "                        spr.t_flag "+
 "                   FROM usr_timestat_dbt usr, dllvalues_dbt spr "+
 "                  WHERE spr.t_list = 5001 "+
 "                    AND spr.t_element = usr.t_operationid "+
 "                    AND TRUNC (usr.t_timebegin) BETWEEN ? "+
 "                                                    AND ? "+
 "               GROUP BY spr.t_name, usr.t_param, spr.t_flag "+
 "               ORDER BY spr.t_name))");
 cmd.addparam("db",RSDBP_IN,date_begin);
 cmd.addparam("de",RSDBP_IN,date_end);
 cmd.execute;
 rsd = rsdrecordset(cmd);
 [Отчет по статистике за период c ########## по ##########](date_begin, date_end);
[ ┌──────────────────────────────────────────┬─────────────┬────────────┬─────────────┬────────┬─────┐
  │##########################################│#############│############│#############│########│#####│]

 ("Наименование операции","Параметры","Количество","Время выполнения":w,"Норматив","Соблюдение":w);

 while (rsd.movenext())
[ ├──────────────────────────────────────────┼─────────────┼────────────┼─────────────┼────────┼─────┤
  │##########################################│#############│############│#############│########│#####│]
 (rsd.value(0),rsd.value(1):z:c,int(rsd.value(2)):z:c,int(rsd.value(3)):z:c:f,rsd.value(4):z:c,rsd.value(5):c);

 end;
[ └──────────────────────────────────────────┴─────────────┴────────────┴─────────────┴────────┴─────┘

Параметры запуска отчета влияют на результат выполнения

];
else
end;
