/* Володина В.                             */
/*С-31309 21.08.14                         */
/*Выписка,структурированная по контрагентам*/

import globals;
import oralib,  BANKINTER;
import keycodes;
import rcw,RSD;
import PTInter,cb_sql;
import Календарь, VBAConst;
import "lib_lang.mac",OprInter,treport,payminter,LikePy;
import "fastexcel.mac";
   var contragentSelect,recordcount = 1;
private   var ob,ex,obBook,pathfile,path,dataCount;
   var filen = "convp.lbr";
private var script = "",
            excludeBankList = "",
            MenuChoise1, 
            param_div,    
            param_numc,    
            param_acc,     
            param_datab,   
            param_datae;  
import "fg_Life_parm.mac";  


private var SQL,cmd,n, i=5,inn,name,bname,deb,cred,osn,db,de,acc,
            select_acc,
            cmd_acc,
            acc_record;

 var  depChoice="";             

import keycodes;
import "fastexcel.mac";
import PTInter,cb_sql;

record Department ("dp_dep.dbt");
record Pmpaym ( pmpaym ); 
 
private Var fgBank = fg_life_subject({OurBank});   

GetRegistryValue("BANK_INI\\ОБЩИЕ ПАРАМЕТРЫ\\ДИРЕКТОРИИ\\LBRDIR",2,path);

 pathfile = FindPath(filen,path);
	if (not pathfile)
		msgbox("Не найдена LBR");
		exit();
	end;

var dlg = TRecHandler("convp",pathfile,true);


private macro cutTextCodeToStr(_str) /*приведеие данных из полей формы к sql строке для оператора IN*/
          var mas:Tarray=tarray();
          var i:integer = 0, i1 = 0;
          var CodeToStr = "",f;
              mas(mas.size) = ","; mas(mas.size) = ";"; /*список проверяемых символов, можно расширить */
              i = 0; i1 = 0;
          while (i1<mas.size)
             f = split(trim(_str),mas(i1));
             CodeToStr = "";
             while (i<f.size(f))
                CodeToStr = CodeToStr + "','" + trim(f(i)) ;
                i = i + 1;      
             end;
             _str = substr(CodeToStr,4);
             i = 0; i1 = i1+1;
          end;
          return(substr(CodeToStr,3)+"'");
        end;

MACRO SetTypeColumns(aw:tarray); /*Создаем двумерный массив с форматами столбцов*/
           var w1=tarray(true); w1(0)=1; w1(1)=2; aw(0)=w1; /* формат столбца - Text     */
           var w2=tarray(true); w2(0)=2; w2(1)=2; aw(1)=w2; /* формат столбца - Text     */
           var w3=tarray(true); w3(0)=3; w3(1)=2; aw(2)=w3; /* формат столбца - Text     */
           var w4=tarray(true); w4(0)=4; w4(1)=2; aw(3)=w4; /* формат столбца - General  */
           var w5=tarray(true); w5(0)=5; w5(1)=1; aw(4)=w5; /* формат столбца - General  */
           var w6=tarray(true); w6(0)=6; w6(1)=1; aw(5)=w6; /* формат столбца - Text     */
           var w7=tarray(true); w7(0)=7; w7(1)=1; aw(6)=w7; /* формат столбца - Text     */
           var w8=tarray(true); w8(0)=8; w8(1)=1; aw(7)=w8; /* формат столбца - Text     */
           var w9=tarray(true); w9(0)=9; w9(1)=2; aw(8)=w9; /* формат столбца - Text     */
END;/*macro*/

MACRO splitTime()  /* перевод времени в формат ЧЧ_ММ_СС для вставки в имя файла */
 private var timesec = string(Time);
 private var splittimesec; 
    splittimesec = Substr(timesec,1,2)+"_"+substr(timesec,4,2)+"_"+substr(timesec,7,2);
    return splittimesec;
END;


Macro FormStrGround(acc, bDate, eDate, INN)
   var str = "";
   if (ValType(INN) == V_UNDEF) return " "; end;

    var cmd = RsdCommand("SELECT   to_char(pr.t_ground) gr "
                         "  FROM   dpmrmprop_dbt pr, dpmpaym_dbt pm "
                         " WHERE      PR.T_PAYMENTID = PM.T_PAYMENTID "
                         "         AND (PM.T_PAYERACCOUNT = ? "
                         "              OR PM.T_RECEIVERACCOUNT = ?) "
                         "         AND PM.T_VALUEDATE BETWEEN TO_CHAR (?, 'dd.mm.yyyy') "
                         "                                AND  TO_CHAR (?, 'dd.mm.yyyy') "
                         "         AND (usr_get_INN (pr.T_PAYERINN) = ? "
                         "              OR usr_get_INN (pr.T_RECEIVERINN) = ?)" );

   cmd.addParam("",   RSDBP_IN, acc);   
   cmd.addParam("",   RSDBP_IN, acc);   
   cmd.addParam("",   RSDBP_IN, date(bDate));   
   cmd.addParam("",   RSDBP_IN, date(eDate));   
   cmd.addParam("",   RSDBP_IN, INN);    
   cmd.addParam("",   RSDBP_IN, INN);    
   var rs = RsdRecordset(cmd);
   
   while(rs.movenext())
      str = str +  rs.value("gr");
   end;
   return str;
end;

MACRO ContragentsReport() /* Конструктор запроса, создание транспортного файла и открытие его Экселем */
    message("Построение запроса к БД");
    initprogress(-1);
private var dd:date,      /*|                                            */
            tt:time,      /*|  это переменные для использования FileInfo */
            ii:integer,   /*|                                            */
            ss:string;    /*|                                            */
   var   TimeSecond = splitTime();
   var   NameTranspFile:string = "Report_"+TimeSecond;
   var   SPNameTranspFile = GetTxtFileName(NameTranspFile);

  NameTranspFile = substr(SPNameTranspFile,12);     /* имя файла без пути */

    setOutput(SPNameTranspFile);  
       
/*-------------------------------- main select body -------------------------*/
    contragentSelect ="SELECT   CASE "+
     "       WHEN INSTR ( "+
     "               CASE "+
     "                  WHEN PM.T_PAYERACCOUNT = '"+dlg.rec.acc+"' "+
     "                  THEN "+
     "                     PR.T_RECEIVERINN "+
     "                  ELSE "+
     "                     PR.T_PAYERINN "+
     "               END, "+
     "               '/' "+
     "            ) != 0 "+
     "       THEN "+
     "          SUBSTR ( "+
     "             CASE "+
     "                WHEN PM.T_PAYERACCOUNT = '"+dlg.rec.acc+"' "+
     "                THEN "+
     "                   PR.T_RECEIVERINN "+
     "                ELSE "+
     "                   PR.T_PAYERINN "+
     "             END, "+
     "             1, "+
     "             INSTR ( "+
     "                CASE "+
     "                   WHEN PM.T_PAYERACCOUNT = '"+dlg.rec.acc+"' "+
     "                   THEN "+
     "                      PR.T_RECEIVERINN "+
     "                   ELSE "+
     "                      PR.T_PAYERINN "+
     "                END, "+
     "                '/' "+
     "             ) "+
     "             - 1 "+
     "          ) "+
     "       ELSE "+
     "          CASE "+
     "             WHEN PM.T_PAYERACCOUNT = '"+dlg.rec.acc+"' "+
     "             THEN "+
     "                PR.T_RECEIVERINN "+
     "             ELSE "+
     "                PR.T_PAYERINN "+
     "          END "+
     "    END "+
     "       INN, "+
     "    CASE "+
     "       WHEN PM.T_PAYERACCOUNT = '"+dlg.rec.acc+"' "+
     "       THEN "+ 
     "          PR.T_RECEIVERNAME "+
     "       ELSE "+
     "          PR.T_PAYERNAME "+
     "    END "+
     "       name, "+
     "    CASE "+
     "       WHEN PM.T_PAYERACCOUNT = '"+dlg.rec.acc+"' "+
     "       THEN "+
     "          PR.T_RECEIVERBANKNAME "+
     "       ELSE "+
     "          PR.T_PAYERBANKNAME "+
     "    END "+
     "       bname, "+
     "    CASE "+
     "       WHEN PM.T_PAYERACCOUNT = '"+dlg.rec.acc+"' THEN PM.T_AMOUNT "+
     "       ELSE 0 "+
     "    END "+
     "       deb, "+
     "    CASE "+
     "       WHEN PM.T_RECEIVERACCOUNT = '"+dlg.rec.acc+"' "+
     "       THEN "+ 
     "          PM.T_AMOUNT "+
     "       ELSE "+
     "          0 "+
     "    END "+
     "       cred, "+
     "   pr.t_ground osn "
"  FROM   dpmrmprop_dbt pr, dpmpaym_dbt pm "+
"  WHERE   PR.T_PAYMENTID = PM.T_PAYMENTID "+
"         AND (PM.T_PAYERACCOUNT = '"+dlg.rec.acc+"' "+
"              OR PM.T_RECEIVERACCOUNT = '"+dlg.rec.acc+"') "+
"         AND PM.T_VALUEDATE BETWEEN TO_DATE ('"+dlg.rec.db+"', 'dd.mm.yyyy') "+
"                                AND  TO_DATE ('"+dlg.rec.de+"', 'dd.mm.yyyy') order by inn";

    useprogress(2);
    message("Получение данных");
    var dataContr = TRsbDataSet(contragentSelect);
    message("Формирование транспортного файла");
    dataCount = 2;  
    dataCount = dataCount+1;
    useprogress(dataCount);         
          var  prim_select1= "  select  inn, "+
                             "  name, "+
                             "  dbms_lob.substr( wm_concat(distinct  bname)) as bname, "+
                             "  to_char(count(osn)) kol, "+
                             "  sum(deb) deb, "+
                             "  sum(cred) cred,  "+
                             "  trunc(((sum(deb)*100)/(select sum(d.t_amount) from dpmpaym_dbt d where   d.T_PAYERACCOUNT = '"+dlg.rec.acc+"'  "+
                             "  AND d.T_VALUEDATE BETWEEN TO_DATE ('"+dlg.rec.db+"', 'dd.mm.yyyy') "+
                             "  AND  TO_DATE ('"+dlg.rec.de+"', 'dd.mm.yyyy' ))),2)  procdeb, "+
                             "  trunc(((sum(cred)*100)/(select sum(d.t_amount) from dpmpaym_dbt d where    d.T_RECEIVERACCOUNT = '"+dlg.rec.acc+"' "+
                             "  and d.T_VALUEDATE BETWEEN TO_DATE ('"+dlg.rec.db+"', 'dd.mm.yyyy') "+
                             "  AND  TO_DATE ('"+dlg.rec.de+"', 'dd.mm.yyyy' ))),2) proccred  "+
                             //Gurin S. 28.07.2015 I-00577848-2
                             //"  wm_concat(distinct  osn) as osn "+
                             "  from(" + contragentSelect + ") group by inn,name order by inn ";
       // var  query_first_d1 = RSDRecordset(RSDCommand(prim_select1), RSDVAL_CLIENT, RSDVAL_Static );
           var query_first_d1 = TRsbDataSet(prim_select1);
       /*   var  prim_select2= "  select  inn,"+
                             "  wm_concat(distinct  osn) as osn "+
                             " from(" + contragentSelect + ") group by inn order by inn ";                           
        //  var  query_first_d2 = RSDRecordset(RSDCommand(prim_select2), RSDVAL_CLIENT, RSDVAL_Static ); 
          var query_first_d2 = TRsbDataSet(prim_select2); */
//debugbreak;
          while( query_first_d1.movenext())// and query_first_d2.movenext())
                   var in1 = string(query_first_d1.value(0)) ;
                   var name = string(query_first_d1.value(1)) ;
                   var bname = string(query_first_d1.value(2)) ;
                   var kol = string(query_first_d1.value(3)) ; 
                   var deb = money(query_first_d1.value(4), 2);
                   var procdeb = string(query_first_d1.value(6)) ;
                   var proccred = string(query_first_d1.value(7)) ; 
                   var cred = money(query_first_d1.value(5), 2); 
                   //Gurin S. 28.07.2015 I-00577848-2 
                   var osn = FormStrGround(dlg.rec.acc, dlg.rec.db, dlg.rec.de, query_first_d1.value(0)); //string(query_first_d1.value(8)) ;                   
                           println( in1 + "@" + 
                                    name + "@" +
                                    bname + "@"+
                                    kol + "@" +                               
                                    deb + "@" +
                                    procdeb  + "@" + 
                                    cred + "@"+
                                    proccred  + "@"+
                                    osn+"@" );   
                                                
                      
                   recordcount = recordcount + 1;                    
             end;/*while*/     
             RemProgress();
         setOutput(NULL,TRUE);
    CopyFile(NameTranspFile,"$c:\\rspar\\"+NameTranspFile, TRUE);                                      /* копирование транспортного файла на терминал */
    ob = CreateObject ("rsax","TRsAxServer","RsAxServer",IsStandAlone());                              /* создание объекта для работы с приложениями  */
    ex = ob.CreateComObject ("Excel.Application", true);                                               /* Active X, запуск Экселя                     */
                                                                                                       /*                                             */
    if(not(GetFileInfo("$c:\\rspar\\"+NameTranspFile,@dd,@tt,@ii,@ss)));                               /* проверка успешности копирования и наличия   */
       println("не мог найти на локальном диске файл "+NameTranspFile+"          \n останавливаюсь");  /* файла на терминале пользователя             */
       exit(0);
    end;
    useprogress(dataCount+1);
    ss = substr(ss,2);
    var aw=tarray(true); 
    SetTypeColumns(aw);
    obBook = ex.Workbooks.opentext (ss, 866, 1, 1,2,false,false,false,false,false,true,"@",aw,1,"."," ",true,false); /*  открытие транспортного файла       */
   
END;/*macro ContragentsReport()*/

Macro formatExcel()
    message("Форматирование книги Excel");
    useprogress(dataCount+2);
    private var i = 1; 
    var obSheet = ex.Sheets(1);
  
     while(recordcount >= i)                                        /* передается число строк в рекордсете           */
       obSheet.Range("A"+i+":I"+i).Interior.Color =15395562;      /* в диапазоне с записанными данными заливаем    */
       i = i + 2;                                                  /* через одну строки светло серым                */
    end;
 var sl = "SELECT   OB.T_CODE innn, CL.T_NAME nam "+
            " FROM   dobjcode_dbt ob, dparty_dbt cl, daccount_dbt ac "+
            " WHERE       OB.T_OBJECTID = AC.T_CLIENT "+
            "        AND AC.T_CLIENT = CL.T_PARTYID "+
            "         AND OB.T_CODEKIND = 16 "+
            "       AND OB.T_OBJECTTYPE = 3 "+
            "       AND AC.T_ACCOUNT = '"+dlg.rec.acc+"' ";
        // debugbreak;
 var Das = TRsbDataSet(sl);
 Das.movenext(); 
          
  ex.Sheets(1).Rows("11:1").Insert(-4121); 
   obSheet.Range("11:1").HorizontalAlignment = -4108;//xlCenter; /* горизонтальное выравнивание                   */
   obSheet.Range("A10").Select;                                    /* выбор ячейки и последующее                    */
   obSheet.Range("A10:I11").Interior.Color =12632256; //1;                   
 //  obSheet.Range("A10:I11").Font.Colorindex = 2;
   obsheet.Range("A10:I11").font.Size = 12        ; 
   obSheet.Range("A11:I11").Select;
   obSheet.Range("A11:I11").HorizontalAlignment = xlCenter;
 // obSheet.Range("A11:I11").VerticalAlignment = xlTop  ;
   obSheet.Range("A11:I11").WrapText = True            ;  
   obsheet.Range("C3:C8").Select;
   obsheet.Range("C3:C8").Name = "Calibri"    ;
   obsheet.Range("C3:C8").font.Size = 11        ;
   obsheet.Range("C3:C8").Font.Bold = True;    
  obSheet.Range("A11:I11").RowHeight = 48.00;    
   ex.Sheets(1).Cells(3,3).Value="Выписка по счету,структурированная по контрагентам";
   ex.Sheets(1).Cells(4,3).Value= Das.innn ;
   ex.Sheets(1).Cells(5,3).Value=Das.nam;
   ex.Sheets(1).Cells(6,3).Value="Счет №"+dlg.rec.acc;
   ex.Sheets(1).Cells(7,3).Value="Выписка за период с "+dlg.rec.db+" по "+dlg.rec.de;
   ex.Sheets(1).Cells(8,3).Value={Name_Bank};

   ex.Sheets(1).Range("A10:C10").MergeCells=true;
   ex.Sheets(1).Cells(10,1).Value="Реквизиты контрагента";
   ex.Sheets(1).Range("E10:F10").MergeCells=true;   
   ex.Sheets(1).Cells(10,5).Value="Сумма списаний";
   ex.Sheets(1).Range("G10:H10").MergeCells=true;  
   ex.Sheets(1).Cells(10,7).Value="Сумма поступлений";
    
   ex.Sheets(1).Cells(11,1).Value="ИНН Контрагента";
   ex.Sheets(1).Cells(11,2).Value="Наименование контрагента";
   ex.Sheets(1).Cells(11,3).Value="Банки Контрагента";
   ex.Sheets(1).Cells(11,4).Value="Колисчество операций";
   ex.Sheets(1).Cells(11,5).Value="В рублях";
   ex.Sheets(1).Cells(11,6).Value="В % от суммы за период";
   ex.Sheets(1).Cells(11,7).Value="В рублях";
   ex.Sheets(1).Cells(11,8).Value="В % от суммы за период";
   ex.Sheets(1).Cells(11,9).Value="Назначение платежей"; 
   ex.Sheets(1).Range("A:A").ColumnWidth=15;
   ex.Sheets(1).Range("B:B").ColumnWidth=20;
   ex.Sheets(1).Range("C:C").ColumnWidth=50;
   ex.Sheets(1).Range("D:D").ColumnWidth=13;
   ex.Sheets(1).Range("E:E").ColumnWidth=12;
   ex.Sheets(1).Range("F:F").ColumnWidth=12;
   ex.Sheets(1).Range("G:G").ColumnWidth=12;
   ex.Sheets(1).Range("H:H").ColumnWidth=12;
   ex.Sheets(1).Range("I:I").ColumnWidth=70; 
    
  
  i=i+10;
      obSheet.Range("A"+(i)+":I"+(i)+" ").Interior.Color = 12632256;
      obSheet.Range("A10:I"+(i)+" ").Borders.Weight=2;
      ex.Sheets(1).Cells(i,4).Value="ИТОГО";         
      ex.Sheets(1).Cells(i,5).Value="=СУММ(E12:E"+(i-1)+")" ;
      ex.Sheets(1).Cells(i,6).Value="100%";
      ex.Sheets(1).Cells(i,7).Value="=СУММ(G12:G"+(i-1)+")";    
      ex.Sheets(1).Cells(i,8).Value="100%";
    

   ex.visible = true;
end;/*macro*/

MACRO Event (dlg, cmd, id, key) 
       //вспомогательное заполнение массива для построения скроллинга
    macro addCol (ar, ind, fld, head, width, rdonly)
        ar.value (ind * 6) = fld;
        ar.value (ind * 6 + 1) = head;
        ar.value (ind * 6 + 2) = width;
        ar.value (ind * 6 + 3 ) = 2;  // fldType
        ar.value (ind * 6 + 4 ) = -1; // decPoint
        ar.value (ind * 6 + 5 ) = 0;  // reserv
    end;    
    
    
    macro EvProc(acc_record, cmd_acc, id, key)
       if(( cmd == DLG_KEY ) and ( KEY==KEY_Enter ))
          return CM_SELECT;
       end;
    end;     
    
    macro EventHandler (rs, cmd, id, key )
       if (cmd == DLG_INIT)
           if (not AddMultiAction (rs, 316)) 
               msgbox ("Не удалось выполнить AddMultiAction ()");
           end;
       end;      
      if(depChoice)
       if ((cmd == DLG_KEY) and ((key == 13) or (KEY==KEY_ESC)))
           return CM_SELECT;
        end;
      else 
        if ((cmd == DLG_KEY) and (key == 13))
           return CM_SELECT;
        end; 
      end;  

       if (cmd == DLG_MSELEND)// and (key == 316)) // F2
           return CM_MSEL_STOP_CLEARALL;
       end;
    end;       

 if(cmd == DLG_INIT)
       message("~F2~ продолжить, ~F3~ справочник, ~ESC~ выход ");
        dlg.rec.db = {curDate};    
        dlg.rec.de = {curDate};
      
      UpdateFields(dlg);
 end;
  
 if (cmd == DLG_REMFOCUS)
       if (FldName(dlg,id)=="db")
          if ( dlg.rec.db > {curdate} )
             MsgBox("Дата начала периода больше даты текущего операционного дня"); 
             return CM_CANCEL;
          end;
       end;
       if (FldName(dlg,id)=="de")
          if ( dlg.rec.de > {curdate} )
             MsgBox("Дата конца периода больше даты текущего операционного дня"); 
             return CM_CANCEL;
          end;
       end;
     
       UpdateFields(dlg); 
 end;

 if (cmd==DLG_KEY)
      if (KEY==KEY_ESC)
           return  exit(1);;
              
      elif (KEY==KEY_F1)
       msgbox("HELP YOURSELF");
        return CM_Ignore;   
        
      elif (KEY==KEY_F9)
        return CM_Ignore;  
        
      elif (KEY==KEY_F3)
        var col = TArray();
            if (FldName(dlg,id) == "db")
                   dlg.rec.db = GetDateByCalendar ({curDate});
            end;
            if (FldName(dlg,id) == "de")
                    dlg.rec.de = GetDateByCalendar ({curDate});
             end;
       
       
           

           if (FldName(dlg,id) == "Acc")
               depChoice="";
               addCol(col,0, "Счет", "Счет",20, true);
               addCol(col,1, "Наименование", "Наименование", 15, true);
               //addCol(col,2, "Остаток", "Остаток",10, true);       
                
	           select_acc ="select AC.T_ACCOUNT ACCOUNT, AC.T_NAMEACCOUNT NAMEACCOUNT from daccount_dbt ac where AC.T_CHAPTER=1  and AC.T_OPEN_CLOSE<>'X' and AC.T_ACCOUNT like '4%'";
               cmd_acc = RSDCommand(select_acc);
               acc_record = RSDRecordset( cmd_acc, RSDVAL_CLIENT, RSDVAL_STATIC );
               
               if (RunScroll(acc_record,col,2,"Счет",@EventHandler,"Счета клиентов","ВАЖНО! ~Enter~-выбора одного значения, ~F2~ -сохранить множественный выбор , ~Esc~-выход", true))
                  if(depChoice)
                    dlg.rec.Acc= substr(depChoice,2);                   
                  else
                    dlg.rec.Acc=acc_record.value(0);                   
                  end; 
                                
                  UpdateFields(dlg);
               end;
           end; 
     elif ( KEY == KEY_F2 )  
         Return CM_SAVE;
         db=dlg.rec.db;
         de=dlg.rec.de;                
         
        
            
     elif (KEY==KEY_UP)    Return 0 ;

     elif (KEY==KEY_DOWN)  return 0;
     
     elif (KEY==KEY_LEFT)  return 0;
     
     elif (KEY==KEY_RIGHT)  return 0; 
    
     elif (KEY==KEY_TAB) return 0;

     elif (KEY==KEY_ENTER) return 0;     
     
     else
           Return CM_IGNORE;
     end;           
  
    end; /* end cmd==DLG_KEY*/
END;

  if (RunDialog(dlg,"Event"))        
    ContragentsReport();
    formatExcel();
      println("                                                         ");
      println("                                                         ");
      println("                                       ОТЧЕТ СФОРМИРОВАН ");

  end;













