import bankinter, rsbdataset, globals;
var cnt, sum, startdate, choice;
array arr;
arr(0) = "‚ àã¡«ïå"; 
arr(1) = "‚ ¢ «îâ¥"; 

MACRO GetDocs (begdate, iscurr)
var rs, str;

if (iscurr)
str = "SELECT   pr.t_number, pm.t_payeraccount, pm.t_receiveraccount, pm.t_amount " +
      "    FROM dpmpaym_dbt pm, dpmrmprop_dbt pr, dpmprop_dbt pp, dpscpord_dbt ps " +
      "   WHERE pr.t_paymentid = pm.t_paymentid " +
      "     AND pr.t_shifroper = '01' " +
      "     AND ps.t_orderid = pm.t_paymentid " +
      "     AND pm.t_paymstatus = 32000 " +
      "   AND pm.t_valuedate  between  TO_DATE ('"+begdate+"', 'dd.mm.yyyy') and " +
      "                                TO_DATE ('"+begdate+"', 'dd.mm.yyyy') " +
      "     AND ps.t_origin != 2 " +
      "     AND (   SUBSTR (pm.t_payeraccount, 1, 3) BETWEEN '405' AND '407' " +
      "          OR SUBSTR (pm.t_payeraccount, 1, 5) IN ('40807', '40820')) " +
      "     AND pp.t_paymentid = pm.t_paymentid " +
      "     AND pp.t_debetcredit = 1 " +
      "     AND pp.t_issender = CHR (0) " +
      "     AND pp.t_bankcode IN ('044525986', 'PRBMRUMM') " +
      "     AND pm.t_payer != -1 " +
      "     AND pm.t_fiid != 0 " +
      "ORDER BY pm.t_amount " ;


else
str = "SELECT pr.T_NUMBER, pm.T_PAYERACCOUNT, pm.T_RECEIVERACCOUNT, pm.t_amount " +
      "  FROM dpmpaym_dbt pm, dpmrmprop_dbt pr, dpmprop_dbt pp, dpspayord_dbt ps " +
      " WHERE pr.t_paymentid = pm.t_paymentid " +
      "   AND pr.t_shifroper = '01' " +
      "   AND ps.t_orderid = pm.t_paymentid " +
      "   AND pm.t_paymstatus = 32000 " +
      "   AND pm.t_valuedate  between  TO_DATE ('"+begdate+"', 'dd.mm.yyyy') and " +
      "                                TO_DATE ('"+begdate+"', 'dd.mm.yyyy') " +
      "   AND ps.t_origin != 2 " +
      "   AND (   SUBSTR (pm.t_payeraccount, 1, 3) BETWEEN '405' AND '407' " +
      "        OR SUBSTR (pm.t_payeraccount, 1, 5) IN ('40807', '40820')) " +
      "   AND pp.t_paymentid = pm.t_paymentid " +
      "   AND pp.t_debetcredit = 1 " +
      "   AND pp.t_issender = CHR (0) " +
      "   AND pp.t_bankcode = '044525986' " +
      "   AND pm.t_payer != -1 " +
      "   AND pm.t_fiid = 0 " +
      "   order by pm.t_amount " ;
end;

 rs = trsbdataset(str);
 cnt = 0;
 sum = 0;
 while (rs and rs.movenext)
 [³ ########## ³ #################### ³ #################### ³ ############### ³]
 (rs.T_NUMBER, rs.T_PAYERACCOUNT, rs.T_RECEIVERACCOUNT, money(rs.t_amount):a);
 cnt = cnt+1;
 sum = sum+ money(rs.t_amount);
 end;


END;

MACRO main (sDate, iscurr)
var cur;
 if (iscurr)
   cur = "¢ «îâ¥";
 else
   cur = "àã¡«ïå";
 end;



 [                †ãà­ « ¢­ãâà¨ª«¨¥­âáª¨å ¯« â¥¦¥© ¢ #
                               §  #
  ÚÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
  ³ ########## ³ #################### ³ #################### ³ ############### ³
  ÃÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´]
  (cur, sdate, "®¬¥à":c:w, "« â¥«ìé¨ª":c:w, "®«ãç â¥«ì":c:w, "‘ã¬¬ ":c:w);

 GetDocs(sdate, iscurr);

 [ÃÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
  ³ ########## ³ ####################                        ³ ############### ³]
 ("ˆ’ƒ", cnt:l, sum:a);

 [ÀÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ];

END;

   choice = menu(arr, "Š ª®© ®âç¥â ¢ë¯ãáª ¥¬?","Š ª®© ®âç¥â ¢ë¯ãáª ¥¬?",null,null);
     if (choice < 0)
        exit(1);
     end;
  startDate = date() - 1;
  if ( not GetDate( startDate, "‚¢¥¤¨â¥ ­ ç «ì­ãî ¤ âã ®âç¥â  :" ) )
    exit(1);
  else
    if (startDate > {curdate})
      msgbox("‡­ ç¥­¨¥ ¤ âë "+string(startDate)+" ¢¢¥¤¥­® ­¥¢¥à­® !!!");
      exit(1);
    end;

    if(startdate == date(0,0,0))
       startdate = "01.01.0001";
    end;
  end;
     if (choice < 0)
        exit(1);
     elif(choice == 0)
        main(startdate, false);
     else
        main(startdate, true);
     end;


