import rsd;
import treport;

var SQLQuery:string;
var title:string;

macro PrintStuff (title, SQLQuery)
    var RS = RSDRecordset(SQLQuery);
    var table = CTableReport();

    println (title);

    if ((rs) and (rs.moveNext))
        table.addColumn("Лицевой|счет", 20, AL_RIGHT);
        table.addColumn("Тип|счета", 5, AL_RIGHT);

        table.printHead();
    
        table.printStringTransferByWord(rs.value("t_account"), rs.value("t_type_account"));
    
        while (rs.moveNext)
            table.printStringTransferByWord(rs.value("t_account"), rs.value("t_type_account"));
        end;

        table.printBottom();
    else
        println ("Нет данных для отчета");
    end;
end;

SQLQuery = "select ac.t_account, ac.t_type_account"
  + "\n" + "  from daccount_dbt ac"
  + "\n" + " where substr (ac.t_balance, 1, 3) in ('706', '707')"
  + "\n" + "   and instr (ac.t_type_account, 'Н') = 0"
  + "\n" + "   and substr (ac.t_account, 6, 3) != '810'";


PrintStuff("Номера рублевых покрытий валютных лицевых счетов  б/счетов 706, 707 не имеющих типа Н", SQLQuery);

SQLQuery = "select ac.t_account, ac.t_type_account"
  + "\n" + "  from daccount_dbt ac"
  + "\n" + " where substr (ac.t_balance, 1, 3) not in ('706', '707')"
  + "\n" + "   and instr (ac.t_type_account, 'Н') != 0"
  + "\n" + "   and substr (ac.t_account, 6, 3) != '810'";

PrintStuff("Номера рублевых покрытий остальных валютных лицевых счетов, кроме 706,707, имеющих тип Н", SQLQuery);

