/************************************************************************/
/*         Автоматизированная банковская система RS-Bank                */
/*                 Copyright (c) R-Style Software Lab 2006              */
/*                                                                      */
/*  Имя файла      : prbcbuy.mac                                        */
/*                                                                      */
/*  Описание       : Печать поручения на покупку валюты.                */
/*                                                                      */
/*  Программист    : Локтюшин В.Ю.                                      */
/*                                                                      */
/*  Создан         : 17.05.06                                           */
/*                                                                      */
/************************************************************************/
           
import prbc,rsexts,rsbdataset;
import "fg_Life_parm.mac"; /* EVG 18/04/2012 */

private macro CreateWordApplication()

var startAX, WordApplication;

  if (isStandAlone())
     return ActiveX("Word.Application");
  else
     startAX = CreateObject("rsax", "TRsAxServer", "LoansAxServer", isStandalone());
     WordApplication = startAX.CreateComObject("Word.Application");
     WordApplication.Visible = true;
     return WordApplication;
  end;

end;

private macro ShowReportOnTerminal( WordApp, WordDoc )
  
  var DocFileName : string, TermFileName : string;

  DocFileName = SplitFile( GetTxtFileName("") );

  DocFileName = MergeFile( DocFileName, "fm_prn_" + string(UserNumber), ".doc" );

  DocFileName = MergeFile( GetCurDir(), DocFileName );

  WordApp.visible = true; 
end;

MACRO GetNameByCode (code, codekind)
  var rs, str;
  str = "SELECT t_name " +
        "FROM dparty_dbt pt, dobjcode_dbt oc " +
        "WHERE     oc.t_code = '"+code+"' " +
        "      AND oc.t_objecttype = 3 " +
        "      AND oc.t_codekind = " +codekind+
        "      AND oc.t_state = 0 " +
        "      AND pt.t_partyid = oc.t_objectid ";
  rs = trsbdataset(str);
  if(rs and rs.movenext)
     return rs.name;
  else
     return "" ;
  end;
END;

MACRO GetDateAndTime(v_paymentid, v_date, v_time)
  var rs, str;
    str = "SELECT  op.t_syst_date, op.t_syst_time " +
          "FROM doproper_dbt op " +
          "WHERE op.t_documentid = lpad("+v_paymentid+",34,'0')"; 
  rs = trsbdataset(str);
  if(rs and rs.movenext)
     setparm(1,rs.syst_date);
     setparm(2,rs.syst_time);
     return true;
  else
     return false ;
  end;
END;

MACRO PrintSELLrder(ncopy:integer):bool

  debugbreak;
  RECORD RecordAdress ( adress );

  ClearRecord( RecordAdress );
  НайтиЮридическийАдресСубъекта( pr_pmpaym.rec.Payer, RecordAdress );
  
  var   BuyCost :PrintBuyCost = PrintBuyCost(pr_pmrmprop, pr_pmpaym, pr_ps_bcord, pr_credit);

  var WordApp, WordDoc;
  var FullDotFileName : string;
  var sys_date, sys_time;
  var DotFileName, out;

  ARRAY SellBankName;
  strsplit( BuyCost.SellBankName, SellBankName, 93, 49, 2 );  

  /* EVG 18/04/2012 */
  var fgBank = fg_life_subject( {OurBank} );

   
  
  DotFileName = "Sell_Currency.dot";
  GetRegistryValue("BANK_INI\\ОБЩИЕ ПАРАМЕТРЫ\\ДИРЕКТОРИИ\\USERTEMPLSDIR",2,out);
  FullDotFileName = FindPath(DotFileName, out);                    
        if (not FullDotFileName)
                msgbox("Не найдена LBR");
                exit();
        end;



  WordApp = CreateWordApplication();

  if( WordApp )
    
    WordDoc = WordApp.Documents.Add( FullDotFileName );
    if( WordDoc )
        //msgbox(pr_pmpaym.rec.paymentid);
        getdateandtime(pr_pmpaym.rec.paymentid, sys_date, sys_time);

        WordDoc.Bookmarks("PayerName").Range.Text         =  BuyCost.PrpmPayerName;
        WordDoc.Bookmarks("PayerINN").Range.Text          =  BuyCost.PrpmPayerINN;
        WordDoc.Bookmarks("PayerPhoneNumber").Range.Text  =  BuyCost.PhoneNumber;
        WordDoc.Bookmarks("DocNumber").Range.Text         =  BuyCost.PmrmNumber;
        WordDoc.Bookmarks("Date_String").Range.Text       =  string(BuyCost.PmrmDate:m);
        WordDoc.Bookmarks("Currency").Range.Text          =  BuyCost.ISOCode;
        /* EVG 18/04/2012 Для Газэнергобанка */
        if( fgBank.is_GEB )
           WordDoc.Bookmarks("Amount_Rur").Range.Text     =  BuyCost.Amount;
        end;
        WordDoc.Bookmarks("Amount_Curr").Range.Text       =  BuyCost.PayAmount;
        WordDoc.Bookmarks("PayerAccount").Range.Text      =  BuyCost.PayerAccount;
        WordDoc.Bookmarks("RecAccount").Range.Text        =  BuyCost.RecAccount;
        WordDoc.Bookmarks("NameBank").Range.Text          =  GetNameByCode(BuyCost.BankCode,3);
        WordDoc.Bookmarks("BankCode").Range.Text          =  BuyCost.BankCode;
        WordDoc.Bookmarks("CorrAcc").Range.Text           =  BuyCost.CorrAcc;
        WordDoc.Bookmarks("Rate").Range.Text              =  BuyCost.Rate;
        WordDoc.Bookmarks("ValueDate").Range.Text         =  sys_date; //BuyCost.ValueDate;
        WordDoc.Bookmarks("SysTime").Range.Text           =  sys_time;
 

      if( IsStandAlone() )
        WordApp.Visible = TRUE;
      else
        ShowReportOnTerminal( WordApp, WordDoc );
      end; 

    end; /*if( WordDoc )*/
  end; /*if( WordApp )*/

  return TRUE;
  
END;

           
           
/* Печать аккредитива */
MACRO PrintDocument(ncopy:integer):bool
  var DocKind:integer = pr_pmpaym.rec.DocKind;

  if( DocKind != PS_BUYCURORDER )
    MsgBox("Данный вид документа не поддерживается макросом");
    return FALSE;
  end;

  return PrintSELLrder(ncopy);
END;

           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           











                                 

                                               
                                               


   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
                                
                                               
                                              
                                               

