/*
$Name:             Prcspsio3352u.mac
$Module:           ББ и РКО
$Description:      Печать объявления на взнос наличными 3352-У
*/

import prcs;


/* Печать объявления на взнос наличными */
MACRO PrintDocumentCashOrder( d : TCashOrderPrintData3352,ncopy:integer):bool

  var index : integer;
  array ArrayGround, ArrayClient, ArrayPayerBankName, ArrayReceiverBankName, ArrayReceiverName;
  array arraySumInWords1;
  array officerPost1, officerPost2, officerPost3;
  array officerShortName1, officerShortName2, officerShortName3;

  StrSplit(d.ArraySum.value(0), arraySumInWords1, 61, 46, 2);
  StrSplit(d.Client, ArrayClient, 33, 25, 3);
  StrSplit(d.ReceiverName, ArrayReceiverName, 33, 22, 3);
  StrSplit(d.PayerBankName, ArrayPayerBankName, 60, 45, 2);
  StrSplit(d.ReceiverBankName, ArrayReceiverBankName, 60, 45, 2);
  StrSplit(d.Ground, ArrayGround, 80, 80, 2);

  StrSplit(d.officerPost, officerPost1, 20, null, 2);
  StrSplit(d.officerShortName , officerShortName1, 13, null, 2);

  StrSplit(d.officerPost, officerPost2, 17, null, 2);
  StrSplit(d.officerShortName, officerShortName2, 12, null, 2);

  StrSplit(d.officerPost, officerPost3, 19, null, 2);
  StrSplit(d.officerShortName, officerShortName3, 12, null, 2);


  if(officerPost1(1) == "") officerPost1(1) = officerPost1(0); officerPost1(0) = ""; end;
  if(officerShortName1(1) == "") officerShortName1(1) = officerShortName1(0); officerShortName1(0) = ""; end;

  if(officerPost2(1) == "") officerPost2(1) = officerPost2(0); officerPost2(0) = ""; end;
  if(officerShortName2(1) == "") officerShortName2(1) = officerShortName2(0); officerShortName2(0) = ""; end;

  if(officerPost3(1) == "") officerPost3(1) = officerPost3(0); officerPost3(0) = ""; end;
  if(officerShortName3(1) == "") officerShortName3(1) = officerShortName3(0); officerShortName3(0) = ""; end;
  
  
  while( ncopy > 0 )

    /*Объявление*/
    [                                        ┌───────────────────┐  ┌ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┐    
      Объявление на взнос наличными          │Код формы документа│  │Отрывной талон к объявлению│
                                             │  по ОКУД 0402001  │  │на взнос наличными №#######│
                                             └───────────────────┘  └ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┘
                                                                                                 
                                 ┌─────────┐ #######################┌───────────────────────────┐
                ОБЪЯВЛЕНИЕ     N │ ####### │  ────────────────────  │    Место для наклейки     │
                                 └─────────┘           Дата         │     отрывного талона      │
                                                ДЕБЕТ               │                           │
                                        ┌───────────────────────────├───────────────────────────┤
      От кого ######################### │счет № ####################│  ###    ################# │
      ################################# └───────────────────────────┤                           │
      #################################         КРЕДИТ              │                           │
      ──────────────────────────────────┬───────────────────────────┤                           │
      Получатель ###################### │счет № ####################│  ###    ################# │
      ################################# │       ####################│  ###    ################# │] 
      
     (d.Number:l, 
      usr_getFullDate(d.DateStr):c, 
      d.Number:c, 
      ArrayClient(0), d.PayerAccount:l, d.FICode, d.AmountStr:r, 
      ArrayClient(1), 
      ArrayClient(2), 
      ArrayReceiverName(0), d.CreditList.value(0).Account:l, d.CreditList.value(0).FICode, d.CreditList.value(0).Amount:r,
      ArrayReceiverName(1), d.CreditList.value(1).Account:l, d.CreditList.value(1).FICode, d.CreditList.value(1).Amount:r); 
      //ArrayReceiverName(2), d.CreditList.value(2).Account:l, d.CreditList.value(2).FICode, d.CreditList.value(2).Amount:r); 
      
    index = 2;
    while( index < d.CreditList.size )   
    [                                   │       ####################│  ###    ################# │]
      (d.CreditList.value(index).Account:l, d.CreditList.value(index).FICode, d.CreditList.value(index).Amount:r);      
    index = index + 1;
    end;
    [                                   │                           │        Сумма цифрами      │
                                        └───────────────────────────┼───────────────────────────┤     
       ИНН ############            Счет № ######################### │                           │]
      (d.ReceiverINN, d.CreditList2.value(0).Account:l);
    index = 1;
    while( index < d.CreditList2.size )
    [                                     ######################### │                           │]
      (d.CreditList2.value(index).Account:l);
      index = index + 1;
    end;    
    

     
    [                                                               │  в том числе по символам: │
      ──────────────────────────────────────────────────────────────┼─────────┬─────────────────┤
      Наименование банка-вносителя                                  │  символ │       сумма     │
       ############################################# БИК ########## ├─────────┼─────────────────┤
       ############################################################ │   ####  │ ##############  │
      Наименование банка-получателя                                 │   ####  │ ##############  │
       ############################################# БИК ########## │   ####  │ ##############  │
       ############################################################ │   ####  │ ##############  │
      Сумма прописью ############################################## │   ####  │ ##############  │
      ############################################################# │   ####  │ ##############  │]

      (ArrayPayerBankName(0), d.BIC1,
       ArrayPayerBankName(1), d.ArraySym.value(0):c, MakeMoneyStr3352(d.ArrayPartSum.value(0)):r, 
       d.ArraySym.value(1):c, MakeMoneyStr3352(d.ArrayPartSum.value(1)):r,  
       ArrayReceiverBankName(0), d.BIC2, d.ArraySym.value(2):c, MakeMoneyStr3352(d.ArrayPartSum.value(2)):r, 
       ArrayReceiverBankName(1), d.ArraySym.value(3):c, MakeMoneyStr3352(d.ArrayPartSum.value(3)):r,  arraySumInWords1(0):r,
       d.ArraySym.value(4):c, MakeMoneyStr3352(d.ArrayPartSum.value(4)):r,arraySumInWords1(1):r, 
       d.ArraySym.value(5):c, MakeMoneyStr3352(d.ArrayPartSum.value(5)):r );

    if( d.ArraySym.size <= 6 )
    [  ############################################################ └─────────┴─────────────────┘]     
      (d.ArraySum.value(1));
    else
    [  ############################################################ │   ####  │ ##############  │]
      (d.ArraySum.value(1), d.ArraySym.value(6):c, MakeMoneyStr3352(d.ArrayPartSum.value(6)):r );
      index = 7;
       while( index < d.ArraySym.size )
    if(d.ArraySym.value(index) != "")
    [                                                               │   ####  │ ##############  │]
      (d.ArraySym.value(index):c, MakeMoneyStr3352(d.ArrayPartSum.value(index)):r );

      end;
    [                                                               └─────────┴────────────────┘]
    end;
    index = index + 1;
    end;
    [                           
      Источник поступления                                                                         
       ################################################################################
       ################################################################################

      Вноситель ________________
                (личная подпись)  
     ####################          #############
     ####################          #############
     ___________________  ________ _____________  ___________________  ________  ____________    
         (наименование     (личная    (фамилия,     (наименование      (личная    (фамилия,     
          должности)       подпись)   инициалы)      должности)        подпись)   инициалы)      ]

    (ArrayGround(0), ArrayGround(1), officerPost1(0):c, officerShortName1(0):c, officerPost1(1):c,  officerShortName1(1):c);               

      StrSplit(d.Client, ArrayClient, 62, 54, 2);
      StrSplit(d.ReceiverName, ArrayReceiverName, 62, 51, 2);

    /*Квитанция*/  
    [ ───────────────────────────┬──────────┬───────────────────────────────────────────────────
                    Квитанция  N │ #######  │      ####################### ┌───────────────────┐
                                 └──────────┘       ────────────────────   │Код формы документа│
                                                            Дата           │  по ОКУД 0402001  │
                                                                           └───────────────────┘
                                                                     ┌─────────────────────────┐
      От кого ###################################################### │Для зачисления на счет(а)│
      ############################################################## │                         │
      Получатель ################################################### │  ####################   │ 
      ############################################################## │  ####################   │ ]
      
      (d.Number:c, usr_getFullDate(d.DateStr):c,
      ArrayClient(0), 
      ArrayClient(1), 
      ArrayReceiverName(0), d.CreditList.value(0).Account:l,
      ArrayReceiverName(1), d.CreditList.value(1).Account:l );

       index = 2;
    while( index < d.CreditList.size )
    [                                                                │####################     │ ]
      ( d.CreditList.value(index).Account:l );
      index = index + 1;
    end;
    [ ИНН ############                                               ├─────────────────────────┤ ]
      ( d.ReceiverINN,
        d.CreditList.value(0).FICode,  d.CreditList.value(0).Amount:r );
    index = 1;
    //while( index < d.CreditList.size )
    //[                                                                │ ###   ################# │ ]
    //   ( d.CreditList.value(index).FICode,  d.CreditList.value(index).Amount:r );
    //  index = index + 1;
    //end;
    [                                                                │ ###   ################# │ ]
    ("", MakeMoneyStr3352(d.AmountStr:r));                           
    [                                                                │  Сумма (суммы) цифрами  │
      Наименование банка-вносителя                                   └─────────────────────────┘
      ####################################################################################
      ##################################################################### БИК ##########       
      Наименование банка-получателя                                                             
      ####################################################################################       
      ##################################################################### БИК ##########       
       Сумма прописью ####################################################################
      ####################################################################################
                                                                            ───────────           
      Источник поступления                                                   (цифрами)
       ################################################################################
       ################################################################################    
                 #################         ############
                 #################         ############
          Место   _______________  ________  _________  _______________  ________  __________
          печати   (наименование   (личная   (фамилия,   (наименование   (личная   (фамилия,
         (штампа)   должности)     подпись)  инициалы)    должности)     подпись)  инициалы)     ]



        (ArrayPayerBankName(0),
         ArrayPayerBankName(1), d.BIC1,
         ArrayReceiverBankName(0), 
         ArrayReceiverBankName(1), d.BIC2,
         d.ArraySum.value(0):r,
         d.ArraySum.value(1):r,
         ArrayGround(0),
         ArrayGround(1), officerPost2(0):c, officerShortName2(0):c,officerPost2(1):c, officerShortName2(1):c) ;
         
    /*Ордер*/         
    
      StrSplit (d.Client, ArrayClient, 33, 25, 3);
      StrSplit(d.ReceiverName, ArrayReceiverName, 33, 22, 3);
    
    [ ───────────────────────────┬──────────┬────────────────────────────────────────────────────
                        Ордер  N │ #######  │     ########################┌───────────────────┐
                                 └──────────┘      ────────────────────   │Код формы документа│
                                                           Дата           │  по ОКУД 0402001  │
                                                                          └───────────────────┘
                                                  ДЕБЕТ                   
                                        ┌───────────────────────────┬───────────────────────────┐                                                  
      От кого ######################### │счет № ####################│  ###   #################  │
      ################################# └───────────────────────────┤                           │
      #################################             КРЕДИТ          │                           │
      ──────────────────────────────────┬───────────────────────────┤                           │
      Получатель ###################### │счет № ####################│  ###   #################  │
      ################################# │       ####################│  ###   #################  │] 
      

 
     (d.Number:c, usr_getFullDate(d.DateStr:c), 
      ArrayClient(0), d.PayerAccount:l, d.FICode, d.AmountStr:r, 
      ArrayClient(1), 
      ArrayClient(2), 
      ArrayReceiverName(0), d.CreditList.value(0).Account:l, d.CreditList.value(0).FICode, d.CreditList.value(0).Amount:r,
      ArrayReceiverName(1), d.CreditList.value(1).Account:l, d.CreditList.value(1).FICode, d.CreditList.value(1).Amount:r); 

      
    index = 2;
    while( index < d.CreditList.size )
    if(d.CreditList.value(index).Account != "")
    [                                   │       ####################│  ###   #################  │]
      (d.CreditList.value(index).Account:l, d.CreditList.value(index).FICode, d.CreditList.value(index).Amount:r);       
    end;
      index = index + 1;
    end;
    [                                   │                           │       Сумма цифрами       │             │
                                        └───────────────────────────┼───────────────────────────┤     
      ИНН ############             Счет № ######################### │                           │]
      (d.ReceiverINN, d.CreditList2.value(0).Account:l);
    index = 1;
    while( index < d.CreditList2.size )
    [                                     ######################### │                           │]
      (d.CreditList2.value(index).Account:l);
      index = index + 1;
    end;
     
    [                                                               │  в том числе по символам: │
      ──────────────────────────────────────────────────────────────┼─────────┬─────────────────┤
      Наименование банка-вносителя                                  │  символ │       сумма     │
       ############################################# БИК ########## ├─────────┼─────────────────┤
       ############################################################ │   ####  │ ##############  │
      Наименование банка-получателя                                 │   ####  │ ##############  │
       ############################################# БИК ########## │   ####  │ ##############  │
       ############################################################ │   ####  │ ##############  │
      Сумма прописью ############################################## │   ####  │ ##############  │
      ############################################################# │   ####  │ ##############  │]

      (ArrayPayerBankName(0), d.BIC1,
       ArrayPayerBankName(1), d.ArraySym.value(0):c, MakeMoneyStr3352(d.ArrayPartSum.value(0)):r, 
       d.ArraySym.value(1):c, MakeMoneyStr3352(d.ArrayPartSum.value(1)):r,  
       ArrayReceiverBankName(0), d.BIC2, d.ArraySym.value(2):c, MakeMoneyStr3352(d.ArrayPartSum.value(2)):r, 
       ArrayReceiverBankName(1), d.ArraySym.value(3):c, MakeMoneyStr3352(d.ArrayPartSum.value(3)):r, arraySumInWords1(0):r,
       d.ArraySym.value(4):c, MakeMoneyStr3352(d.ArrayPartSum.value(4)):r, 
       arraySumInWords1(1):r, d.ArraySym.value(5):c, MakeMoneyStr3352(d.ArrayPartSum.value(5)):r);

    if( d.ArraySym.size <= 6 )
    [  ############################################################ ├─────────┴────────┬────────┤]
      (d.ArraySum.value(1));
    else
    [  ############################################################ │   ####  │ ##############  │]
      (d.ArraySum.value(1), d.ArraySym.value(6):c, MakeMoneyStr3352(d.ArrayPartSum.value(6)):r );
    index = 7;
       while( index < d.ArraySym.size )
    [                                                               │   ####  │ ##############  │]
      (d.ArraySym.value(index):c, MakeMoneyStr3352(d.ArrayPartSum.value(index)):r );
      index = index + 1;
      end;
    [                                                               ├─────────┴────────┬────────┤]
    end;
    [                                                               │ Шифр документа   │   ##   │
                                                                    └──────────────────┴────────┘]
      (d.ShifrOper:c);                                                                             
    [ Источник поступления                                                                         
       ################################################################################
       ################################################################################
       ###################           ############
       ###################           ############
       ___________________  ________  ___________  ___________________  ________  ____________    
         (наименование     (личная    (фамилия,     (наименование      (личная    (фамилия,     
          должности)       подпись)   инициалы)      должности)        подпись)   инициалы)      ]


      (ArrayGround(0),
       ArrayGround(1),           
       officerPost3(0):c,  officerShortName3(0):c, officerPost3(1):c,  officerShortName3(1):c
     );                                                      
    
    ncopy = ncopy - 1;
  end;

  return TRUE;

end;

macro PrintDocument(ncopy:integer):bool
  var DocKind:integer = pr_pmpaym.rec.DocKind;
  var data : TCashOrderPrintData3352 = TCashOrderPrintData3352();
  
  if( DocKind != 410/*CASH_PS_INCORDER*/  )
    MsgBox("Данный вид документа не поддерживается макросом");
    return FALSE;
  end;
  data.Init( pr_pmpaym, pr_pmrmprop, pr_pscshdoc );
  if( pr_PrintEA )
    PrintEAHeader();
  end;
  
  return PrintDocumentCashOrder(data,ncopy);
end;