import BankInter, RSD, globals;

var zapros,  zapros2, zapros3 , zapros4 :RSDRecordset;
var SQLQuery, SQLQuery_2, SQLQuery_3 , SQLQuery_4:string  = "";
var counter  :integer = 0;
var Arm;

/*13.03.2013 Chesnokov D.S. логгирование запуска для поиска неиспользуемых макросов*/
ExecmacroFile("lib_log.mac", "LogProcedure", "Arm_user3.mac");

SQLQuery = " select p.t_oper, p.t_name, p.t_szidentprogram, p.t_codedepart , part.t_name ,  T_USERBLOCKED "
	         +" from dperson_dbt p, dparty_dbt part ,DDP_DEP_DBT dep"
		 +" where not exists (select t_user "
				+ " from dperson_lnk_dbt "
				+ " where t_user = p.t_oper) "
		  +" and P.T_USERCLOSED !='X' "
                +" and dep.t_code =  p.t_codedepart  "
                +" and dep.t_partyid = part.t_partyid  "	  
                +" order by p.t_oper"; //p.t_codedepart, 
zapros = RSDRecordset(SQLQuery); /*результат запроса*/

[
	##########

	Список пользователей без типового АРМа

	┌───────────────────┬───────────────────────────────────────────────────┬──────────────┬─────┬──────────────────────────────┐
	│    Подключенные   │                         Узел                      │    Номер     │Блок.│            Ф.И.О.            │
	│       модули      │                           ТС                      │ пользователя │  X  │        операциониста         │
	├───────────────────┼───────────────────────────────────────────────────┼──────────────┼─────┼──────────────────────────────┤]({CurDate} );

while (zapros.moveNext)
counter = counter + 1;
/* 
// запрос узла по внутреней ТС
SQLQuery_4 =" select t_code1, t_code2 "
	         +" from dop_otdel_dbt"
		 +" where t_dateend = '01.01.0001' and t_oper = "+ zapros.value(0)+";";	      
zapros4 = RSDRecordset(SQLQuery_4);

	if(zapros4.moveNext)
[       │################## │ ###-###  │     ######   │ #############################│] 
        (zapros.value(2):r, zapros4.value(0), zapros4.value(1):l, zapros.value(0):r, zapros.value(1));
	else
[       │################## │ НеУказан │     ######   │ #############################│] 
        (zapros.value(2):r,                                       zapros.value(0):r, zapros.value(1));
        end;

// узлы по дистрибутивной ТС
*/
[       │################## │###################################################│     ######   │  #  │ #############################│] 
        (zapros.value(2):r, zapros.value(4):r,  zapros.value(0):r, zapros.value(5) ,  zapros.value(1));

end;
[       └───────────────────┴───────────────────────────────────────────────────┴──────────────┴──────────────────────────────┘];
          
[       ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
        │Всего сотрудников, не подключеных к АРМ: #######                                                                    │ 
        └────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘](Counter:l);    
