import rsbdataset, bankinter, globals;

/*13.03.2013 Chesnokov D.S. логгирование запуска для поиска неиспользуемых макросов*/
ExecmacroFile("lib_log.mac", "LogProcedure", "check_symbols.mac");

var rs, str, str1;


str = "SELECT t_date_carry, t_numb_document, " +
      "       TO_CHAR (t_shifr_oper || '/' || SUBSTR (t_kind_oper, 2, 1)) t_shv, " +
      "       t_account_payer, t_account_receiver, t_sum, t_ground " +
      "  FROM darhdoc_dbt arhdoc " +
      " WHERE t_date_carry = TO_DATE ('"+string({curdate}-1)+"', 'DD.MM.YYYY') " +
      "   AND t_result_carry != 23 " +
      "   AND (   (t_account_payer LIKE '20202810%') " +
      "        OR (t_account_receiver LIKE '20202810%') " +
      "        OR (t_account_payer LIKE '20206810%') " +
      "        OR (t_account_receiver LIKE '20206810%') " +
      "        OR (t_account_payer LIKE '20207810%') " +
      "        OR (t_account_receiver LIKE '20207810%')) " +
      "   AND NOT (    (t_account_payer LIKE '20202810%') " +
      "            AND (t_account_receiver LIKE '20202810%')) " +
      "   AND NOT EXISTS (SELECT * " +
      "                     FROM dsymbcash_dbt dcash " +
      "                    WHERE dcash.t_applicationkey(+) = " +
      "                          TO_CHAR (arhdoc.t_iapplicationkind, 'fm09999') " +
      "                          || arhdoc.t_applicationkey) " ;



var path:string;

GetRegistryValue("PRBB\\CHECKSYMBOLSPATH",2,path);
setoutput(path + "symbols_" +string({curdate}-1)+ ".txt",true);//

rs = trsbdataset(str);

println("\n===================================\n"+date+" - "+time+"\n");
   [|    Дата    | Шифр/Вид |     Плительщик       |      Получатель      |      Сумма      |                   Основание документа                         |  
    |------------+----------+----------------------+----------------------+-----------------+---------------------------------------------------------------|];
while (rs and rs.movenext)
   [| ########## | ######## | #################### | #################### | ############### | ############################################################# |] 
   (date(rs.t_date_carry), rs.t_shv, rs.t_account_payer, rs.t_account_receiver, money(rs.t_sum), rs.t_ground:w);
end;


setoutput(null,true);
exit(1);

