import rsbdataset, bankinter, globals;

/*13.03.2013 Chesnokov D.S. логгирование запуска для поиска неиспользуемых макросов*/
ExecmacroFile("lib_log.mac", "LogProcedure", "check_comiss.mac");

var rs, str, str1;


str = "SELECT   oks.t_name step, COUNT (1) cnt " +
      "    FROM dsfinv_dbt inv, doprdocs_dbt od, doproper_dbt oo, " +
      "         doproper_dbt ook, dsfdefcom_dbt dc, dsfcomiss_dbt com, " +
      "         doprkdoc_dbt okd, doprstep_dbt os, doprostep_dbt oks, " +
      "         dpmpaym_dbt pm " +
      "   WHERE inv.t_invoicestatus <> 4 " +
      "     AND inv.t_servicekind = 3 " +
      "     AND oo.t_dockind = 59 " +
      "     AND oo.t_documentid = LPAD (inv.t_invoiceid, 34, '0') " +
      "     AND oo.t_id_operation = od.t_id_operation " +
      "     AND od.t_dockind IN (29, 70, 201, 202, 15, 410, 420) " +
      "     AND dc.t_invoiceid = inv.t_invoiceid " +
      "     AND dc.t_commnumber = com.t_number " +
      "     AND dc.t_feetype = com.t_feetype " +
      "     AND okd.t_dockind = od.t_dockind " +
      "     AND ook.t_documentid = od.t_documentid " +
      "     AND ook.t_id_operation = os.t_id_operation " +
      "     AND oks.t_blockid = os.t_blockid " +
      "     AND oks.t_number_step = os.t_number_step " +
      "     AND os.t_isexecute = 'R' " +
      "     AND pm.t_documentid = ook.t_documentid " +
      "     AND pm.t_dockind = ook.t_dockind " +
      "GROUP BY oks.t_name " ;

str1 = "SELECT   inv.t_docnumber, inv.t_payeraccount payeraccount, " +
       "         inv.t_beneaccount beneaccount, inv.t_payername payername, " +
       "         okd.t_name docname, pm.t_paymentid docid, inv.t_totalamount amount, " +
       "         pm.t_valuedate enddate, com.t_code comcode, com.t_name comname, " +
       "         oks.t_name step, " +
       "         (CASE WHEN oks.t_name LIKE '%картотек%№2%' THEN 'X' ELSE ' ' END) k2 " +
       "    FROM dsfinv_dbt inv, doprdocs_dbt od, doproper_dbt oo, doprstep_dbt ops, " +
       "         doproper_dbt ook, dsfdefcom_dbt dc, dsfcomiss_dbt com, doprkdoc_dbt okd, " +
       "         doprstep_dbt os, doprostep_dbt oks, dpmpaym_dbt pm " +
       "   WHERE inv.t_invoicestatus <> 4 " +
       "     AND inv.t_servicekind = 3 " +
       "     AND oo.t_dockind = 59 " +
       "     AND oo.t_documentid = LPAD (inv.t_invoiceid, 34, '0') " +
       "     AND oo.t_id_operation = ops.t_id_operation " +
       "     AND ops.t_id_step = 1 " +
       "     AND oo.t_id_operation = od.t_id_operation " +
       "     AND ops.t_id_step = od.t_id_step " +
       "     AND od.t_dockind IN (29, 70, 201, 202, 15, 410, 420) " +
       "     AND dc.t_invoiceid = inv.t_invoiceid " +
       "     AND dc.t_commnumber = com.t_number " +
       "     AND dc.t_feetype = com.t_feetype " +
       "     AND okd.t_dockind = od.t_dockind " +
       "     AND ook.t_documentid = od.t_documentid " +
       "     AND ook.t_dockind = od.t_dockind " +
       "     AND ook.t_id_operation = os.t_id_operation " +
       "     AND oks.t_blockid = os.t_blockid " +
       "     AND oks.t_number_step = os.t_number_step " +
       "     AND oks.t_blockid = os.t_blockid " +
       "     AND os.t_isexecute = 'R' " +
       "     AND pm.t_documentid = ook.t_documentid " +
       "     AND pm.t_dockind = ook.t_dockind " +
       "--and oks.T_NAME in ('Исполнение оплаты картотеки №2','Зачисление') " +
       "ORDER BY k2, pm.t_valuedate " ;



var path:string;

GetRegistryValue("PRBB\\CHECKCOMISSPATH",2,path);

setoutput(path+"comiss_" +{curdate}+ ".txt",true);//



rs = trsbdataset(str);

println("\n===================================\n"+date+" - "+time);
while (rs and rs.movenext)
   [########################################################## | ########## | ] 
   (rs.step, int(rs.cnt) );
end;


rs = trsbdataset(str1);

println("\n\n");
   [|Номер док  |      Плательщик      |      Получатель      |             Наименование плательщика                |         Вид документа        |ИД документа|     Сумма     |    Дата    |  Комиссия  |            Наименование комиссии            |            Наименование шага            | К2 | 
    |-----------+----------------------+----------------------+-----------------------------------------------------+------------------------------+------------+---------------+------------+------------+---------------------------------------------+-----------------------------------------+----|]; 

while (rs and rs.movenext)
   [|########## | #################### | #################### | ################################################### | ############################ | ########## | ############# | ########## | ########## | ########################################### | ####################################### | ## |] 
   (rs.t_docnumber:r, rs.payeraccount, rs.beneaccount, rs.payername:w, rs.docname, rs.docid:l, money(rs.amount):r, date(rs.enddate), rs.comcode,  rs.comname:w, rs.step:w, rs.k2);
end;


setoutput(null,true);
exit(1);

