// 19.06.2012 vihrov модифицировал под 2030
// 30.05.2014 DPN I-00491128-2 Адаптация под 31
import BankInter, rsd, globals;
import "KeyCodes.mac";

import globals;
import oralib,  BANKINTER;
import keycodes;
import rcw,RSD;
import PTInter,cb_sql;
import cur_bank;

var RecordSet;
var app;

  macro GetOperName(NumOper:integer):string
  var select:string = "";
  var rs:object;
   
    select = "SELECT t_name FROM dperson_dbt "+
             "WHERE t_oper = "+NumOper+"";
    rs = execSQLselect(select);
    while(rs.moveNext())
      return string (rs.Value(0));
    end;
    return "";  
  end;



MACRO Отчет_распоряжения(applic) // главная функция

//var RecordSet, command,i=1,RecordSet1, command1, DocSet,in;
var flag;                                                                       //vihrov 01-11-2009     
var Select, Data;
var glavbuh = "", bankname = "";

//30.05.2014 DPN I-00491128-2 Сделал отчёт универсальным
/*
if(_PRBB_BANK())
   glavbuh = "Альховой  Л.Э.";
   bankname = "ОАО АКБ \"Пробизнесбанк\", г.Москва";
Elif (_VUZ_BANK())
   glavbuh = "Беляевских С.Л.";
   bankname = "ОАО \"ВУЗ-БАНК\", г.Екатеринбург";
end;
*/
bankname = ({name_Bank});

/* EVG Вывод отчёта на экран по каждому нажатию F7 */
var txtPath = "..\\TxtFile\\correct_ispr." + UserNumber();
SetOutPut(txtPath, false);

flag=0;                                                                         //vihrov 03-11-2009

//30.05.2014 DPN I-00491128-2 Адаптация под 31
       Select = " SELECT DAC.T_ACCTRNID, dac.t_oper, dac.t_numb_document, dac.t_date_carry, " +
                " dac.t_account_payer, dac.t_account_receiver, DAC.T_SUM_NATCUR, dac.t_ground " +
                " FROM dacctrn_dbt dac " +
                " WHERE DAC.T_ACCTRNID = '" + applic + "' AND INSTR (t_ground, 'курсова') = 0 ";


       Data = ExecSQLSelect(Select);

    while(Data.moveNext())
//      msgbox (string (Data.Value(1)));
//    end;                                                                      //vihrov 03.11.2009
       flag=1;                                                                     //vihrov 03.11.2009

[

                                                 Главному бухгалтеру ##################





                                         С П Р А В К А

              о проведении проверки правильности совершения операций
              и ведения бухгалтерского учета в ######################################



        В ходе проведения проверки, осуществленной  ########## г., выявлены
        следующие нарушения учета операций операционистом #################################################

        -------T----------T--------------------T--------------------T--------------T-----T--------------------------------------------------------------------------------------------------------------------------------------------┐
        │№     │   Дата   │       Дебет        │      Кредит        │    Сумма     │№    │                                Основание                                                                                                   │
        │док.  │ проводки │                    │                    │              │опер.│                                                                                                                                            │
        +------+----------+--------------------+--------------------+--------------+-----+--------------------------------------------------------------------------------------------------------------------------------------------+
        │######│##########│####################│####################│##############│#####│############################################################################################################################################│
        │      │          │                    │                    │              │     │                                                                                                                                            │
        L------+----------+--------------------+--------------------+--------------+-----+---------------------------------------------------------------------------------------------------------------------------------------------


        В целях устранения выявленных нарушений необходимо принять меры по
        исправлению указанных ошибочных бухгалтерских операций.




        Начальник отдела текущего контроля
        банковских операций                               ##############################



        ##########


] (glavbuh, bankname, {CurDate}, GetOperName(Data.Value(1)),       /*app ,*/
        Data.Value(2), Date(Data.Value(3)), Data.Value(4), Data.Value(5), Data.Value(6), Data.Value(1), Data.Value(7),
        GetOperName({oper}), {CurDate} );
    end; //while                                                                //vihrov 03.11.2009

    if (flag==0) [                                                                  
                     В ходе проведения проверки, осуществленной   ########## г.,    
                            нарушения учета операций не выявлены                    
    ] ({CurDate});                                                                  //vihrov 03.11.2009
                                                                                    //vihrov 03.11.2009
    end;                                                                            //vihrov 03.11.2009

    /* EVG Вывод отчёта на экран по каждому нажатию F7 */
    SetOutPut(null, false);
    ViewFile (txtPath);

END;



MACRO calculate(RecordSet:@variant)

  var CmdText, Command;
  var col = TArray;

     macro AddCol (ar,ind, fld, head, width, rdonly)
       ar.value (ind * 6)     = fld;
       ar.value (ind * 6 + 1) = head;
       ar.value (ind * 6 + 2) = width;
       ar.value (ind * 6 + 3 ) = 2;   // fldType
       ar.value (ind * 6 + 4 ) = -1;  // decPoint
       ar.value (ind * 6 + 5 ) = 0;   // reserv
     end;


  AddCol (col, 0, "t_corrdocnumber", "Номер", 20, true);
  AddCol (col, 1, "t_oper", "Опер.", 8, true);
  AddCol (col, 2, "t_closedate", "Дата", 10, true);
  AddCol (col, 3, "t_fi_code", "валюта", 7, true);
//  AddCol (col, 4, "t_applicationkey", "код", 30, true);

//30.05.2014 DPN I-00491128-2 Адаптация под 31
  CmdText  = " SELECT   DISTINCT (ispr.t_corrdocnumber), doc.t_oper, pm.t_closedate, fin.t_fi_code, ispr.T_ACCTRNID " +
             " FROM   daccispr_dbt ispr, dcb_doc_dbt doc, dfininstr_dbt fin, dpmpaym_dbt pm " +
             " WHERE   ispr.t_documentid = doc.t_documentid " +
             " AND doc.t_state = 50 " +
             " AND fin.t_fiid = doc.t_code_currency " +
             " AND pm.t_documentid = doc.t_documentid " +
             " AND pm.t_fiid = fin.t_fiid " +
             " AND pm.t_dockind = 70 " +
             " ORDER BY   ispr.t_corrdocnumber " ; 


  Command = RSDCommand(CmdText);
  Command.Execute();
  RecordSet = RSDRecordSet(Command, RSDVAL_CLIENT, RSDVAL_STATIC);

  return col;
END;


MACRO scroll ();  
  var RecordSet;
  var col = TArray;

     
     macro EvProc (RecordSet, Command, id, key )

        if ((Command == DLG_KEY) and (key == 27))     //Esc
           return CM_CANCEL;       
        elif ((Command == DLG_KEY) and (key == 321))    //F7
           app = RecordSet.Value(4);
           Отчет_распоряжения(app);
           return CM_IGNORE;
        end;  

     end;

  col = calculate(@RecordSet);

  RunScroll(RecordSet, 4, col, "isprScrol", @EvProc, "Список распоряжений", "~F7~ Отчет ~Esc~ выход", false);      

END;

   scroll();
   exit(1);
