/*──────────────────────────────────────────────────────────────────────────┐
  RS-Bank 5.00                                          АКБ "Пробизнесбанк"

  File Name  : CUR_BANK.MAC
  Description: Параметры банка
  Опис. ф-ий : 
  History    : 29.10.2003 Байков Д.В.

               18.08.2009 Гуцу Е.В. Макрос перенесен на V.6

└───────────────────────────────────────────────────────────────────────────*/
/* EVG
import ClnInter;*/


Const NumCurBank = 70000 ; /* номер текущего банка в справочнике клиентов */

Const BIC_PRBB      = "044525986",
      BIC_VUZ       = "046577781",
      BIC_VOLGA     = "046311808",
      BIC_BALAKOVO  = "046359822",
      BIC_ENGELS    = "046375825",
      BIC_VOLGOGRAD = "041806835",
      BIC_ULYANOVSK = "047308902",
      BIC_IOB       = "042406718", 
      BIC_VORON     = "042007755",
      BIC_BANK24RU  = "046577859",
      BIC_GEB       = "042908701",
      BIC_OBNINSK   = "042913709" ;

Const INN_PRBB      = "7729086087",
      INN_VUZ       = "6608007473",
      INN_VOLGA     = "6454027396",
      INN_ULYANOVSK = "6454027396",
      INN_IOB       = "3730002630",
      INN_VORON     = "6454027396",
      INN_BANK24RU  = "6608007890",
      INN_GEB       = "4026006420" ;

Const KPP_PRBB      = "997950001",
      KPP_VUZ       = "667101001",
      KPP_VOLGA     = "645501001",
      KPP_BALAKOVO  = "643902001",
      KPP_ENGELS    = "644902001",
      KPP_VOLGOGRAD = "344401001",
      KPP_ULYANOVSK = "732502001",
      KPP_IOB       = "370201001",
      KPP_VORON     = "366402001" ;

Const Front_ID_PRBB      = 252,
      Front_ID_VUZ       = 2519,
      Front_ID_VOLGA     = 133,
      Front_ID_BALAKOVO  = 209,
      Front_ID_ENGELS    = 208,
      Front_ID_VOLGOGRAD = 127,
      Front_ID_ULYANOVSK = 7743,
      Front_ID_IOB       = 536,
      Front_ID_VORON     = 9000,
      Front_ID_BANK24RU  = 3424,
      Front_ID_GEB       = 1963;

Const PathBase_PRBB      = "\\\\rsdbprbb\\rsb$\\rsb\\DBFILE\\",
      PathBase_DOP_PRBB  = "\\\\oday2\\rsb\\rsbdop\\DBFILE\\",
      PathBase_VUZ       = "\\\\rsdbvuz\\rsb\\rsb\\DBFILE\\" ,
      PathBase_VOLGA     = "\\\\rsdbevs\\rsb$\\rsb\\DBFILE\\" ,
      PathBase_BALAKOVO  = "\\\\oday2e\\rsb\\rsbb\\DBFILE\\" ,
      PathBase_ENGELS    = "\\\\rsdbeve\\rsb$\\rsb\\DBFILE\\" ,
      PathBase_VOLGOGRAD = "\\\\rsdbevv\\rsb\\rsb\\DBFILE\\" ,
      PathBase_ULYANOVSK = "\\\\rsdbevu\\rsb\\rsb\\DBFILE\\" ,
      PathBase_IOB       = "\\\\rsdbiob\\rsb\\rsb\\DBFILE\\" ,
      PathBase_VORON     = "\\\\rsdbvoron\\rsb$\\rsb\\DBFILE\\" ;

//file fCur_Bank ("bank.dbt", "goto98.def") ;
//  open(fCur_Bank) ;
//  rewind(fCur_Bank) ;
//  prev(fCur_Bank) ;

/* ------------------------------------------------------------------------ */
macro _MFO_Bank()
//  return fCur_Bank.MFO_Bank ;
/* EVG */
private var {MFO_Bank};

  return {Mfo_bank};
end ; /* _MFO_Bank */

/* ------------------------------------------------------------------------ */
macro _Name_Bank_Front(BIC)

  if( ValType(BIC) == V_UNDEF )
    BIC = _MFO_Bank() ;
  end ;
   
  if(BIC == BIC_PRBB)
    return "PRBB";
  elif(BIC == BIC_VUZ)
    return "VUZ";
  elif(BIC == BIC_VOLGA)
    return "VOLGA";
  elif(BIC == BIC_BALAKOVO)
    return "BALAKOVO";
  elif(BIC == BIC_ENGELS)
    return "ENGELS";
  elif(BIC == BIC_VOLGOGRAD)
    return "VOLGOGRAD";
  elif(BIC == BIC_ULYANOVSK)
    return "ULYANOVSK";
  elif(BIC == BIC_IOB)
    return "IVOB";
  elif(BIC == BIC_VORON)
    return "VORON";
  else
    return "";
  end;
end;

/* ------------------------------------------------------------------------ */
macro _PRBB_BANK(BIC)

  if( ValType(BIC) == V_UNDEF )
    BIC = _MFO_Bank() ;
  end ;

  if( BIC == BIC_PRBB )
    return true ;
  end ;
  return false ;
end ; // _PRBB_BANK

/* ------------------------------------------------------------------------ */
macro _VUZ_BANK(BIC)

  if( ValType(BIC) == V_UNDEF )
    BIC = _MFO_Bank() ;
  end ;

  if( BIC == BIC_VUZ )
    return true ;
  end ;
  return false ;
end ; // _VUZ_BANK

/* ------------------------------------------------------------------------ */
macro _VOLGA_BANK(BIC)

  if( ValType(BIC) == V_UNDEF )
    BIC = _MFO_Bank() ;
  end ;

  if( BIC == BIC_VOLGA )
    return true ;
  end ;
  return false ;
end ; // _VOLGA_BANK

/* ------------------------------------------------------------------------ */
macro _BALAKOVO_BANK(BIC)

  if( ValType(BIC) == V_UNDEF )
    BIC = _MFO_Bank() ;
  end ;

  if( BIC == BIC_BALAKOVO )
    return true ;
  end ;
  return false ;
end ; // _BALAKOVO_BANK

/* ------------------------------------------------------------------------ */
macro _ENGELS_BANK(BIC)

  if( ValType(BIC) == V_UNDEF )
    BIC = _MFO_Bank() ;
  end ;

  if( BIC == BIC_ENGELS )
    return true ;
  end ;
  return false ;
end ; // _ENGELS_BANK

/* ------------------------------------------------------------------------ */
macro _VOLGOGRAD_BANK(BIC)

  if( ValType(BIC) == V_UNDEF )
    BIC = _MFO_Bank() ;
  end ;

  if( BIC == BIC_VOLGOGRAD )
    return true ;
  end ;
  return false ;
end ; // _VOLGOGRAD_BANK

/* ------------------------------------------------------------------------ */
macro _ULYANOVSK_BANK(BIC)

  if( ValType(BIC) == V_UNDEF )
    BIC = _MFO_Bank() ;
  end ;

  if( BIC == BIC_ULYANOVSK )
    return true ;
  end ;
  return false ;
end ; // _ULYANOVSK_BANK

/* ------------------------------------------------------------------------ */
macro _IOB_BANK(BIC)

  if( ValType(BIC) == V_UNDEF )
    BIC = _MFO_Bank() ;
  end ;

  if( BIC == BIC_IOB )
    return true ;
  end ;
  return false ;
end ; // _IOB_BANK

/* ------------------------------------------------------------------------ */
macro _VORON_BANK(BIC)

  if( ValType(BIC) == V_UNDEF )
    BIC = _MFO_Bank() ;
  end ;

  if( BIC == BIC_VORON )
    return true ;
  end ;
  return false ;
end ; // _VORON_BANK

/* ------------------------------------------------------------------------ */
macro _BANK24RU_BANK(BIC)

  if( ValType(BIC) == V_UNDEF )
    BIC = _MFO_Bank() ;
  end ;

  if( BIC == BIC_BANK24RU )
    return true ;
  end ;
  return false ;
end ; // _BANK24RU_BANK

/* ------------------------------------------------------------------------ */
macro _GEB_BANK(BIC)

  if( ValType(BIC) == V_UNDEF )
    BIC = _MFO_Bank() ;
  end ;

  if( BIC == BIC_GEB )
    return true ;
  end ;
  return false ;
end ; // _GEB_BANK

/* ------------------------------------------------------------------------ */
macro _OBNINSK_BANK(BIC)

  if( ValType(BIC) == V_UNDEF )
    BIC = _MFO_Bank() ;
  end ;

  if( BIC == BIC_OBNINSK )
    return true ;
  end ;
  return false ;
end ; // _OBNINSK_BANK

// ---------------------------------------------------------------------------
// Банк входит в группу 
macro PRBB_BankGroup(BIC)

  if( _PRBB_BANK(BIC)      or   _VUZ_BANK(BIC)       or
      _VOLGA_BANK(BIC)     or   _BALAKOVO_BANK(BIC)  or
      _ENGELS_BANK(BIC)    or   _VOLGOGRAD_BANK(BIC) or
      _ULYANOVSK_BANK(BIC) or   _IOB_BANK(BIC)       or
      _VORON_BANK(BIC)     or   _BANK24RU_BANK(BIC)  or
      _GEB_BANK(BIC)       or   _OBNINSK_BANK(BIC)
    )
    return true ;
  end ;

  return false ;

end ; // PRBB_BankGroup
/*
// ---------------------------------------------------------------------------
// Название текущего банка
macro _NAME_BANK(BIC_Bank)
return _NameBank_PlaceBank( BIC_Bank );
/*
var f_bank ;

  if( ( ValType(BIC_Bank) == V_UNDEF ) or ( BIC_Bank == _MFO_Bank() ) )
    return fCur_Bank.Name_Bank ;
  else

    if( BIC_Bank == BIC_VUZ )
      f_bank = TbFile("bank.dbt", "R", 0, PathBase_VUZ + "bank.dbt", "goto98.def") ;

    elif( BIC_Bank == BIC_VOLGA )
      f_bank = TbFile("bank.dbt", "R", 0, PathBase_VOLGA + "bank.dbt", "goto98.def") ;

    elif( BIC_Bank == BIC_ENGELS )
      f_bank = TbFile("bank.dbt", "R", 0, PathBase_ENGELS    + "bank.dbt", "goto98.def") ;

    elif( BIC_Bank == BIC_VOLGOGRAD )
      f_bank = TbFile("bank.dbt", "R", 0, PathBase_VOLGOGRAD + "bank.dbt", "goto98.def") ;

    else
      f_bank = TbFile("bank.dbt", "R", 0, PathBase_PRBB + "bank.dbt", "goto98.def") ;

    end ;

    f_bank.Rewind ;
    f_bank.Prev ;
    return f_bank.Rec.Name_Bank ;
  end ;
*/
end ; /* _NAME_BANK */
*/
/* ------------------------------------------------------------------------ */
macro _CorAc_BANK()
private var {CORAC_Bank};
//  return fCur_Bank.CORAC_Bank ;
  return {CORAC_Bank};

end ; /* _NAME_BANK */

/* ------------------------------------------------------------------------ */
macro ShortBank()
  private var {Name_Bank};
  var len=index({Name_Bank},",");
  if(len > 0)
    return SubStr({Name_Bank},1,len-1);
  end;
  return {Name_Bank};
end;

/* ------------------------------------------------------------------------ */
MACRO PlaceBank( BIK )
   file _bank (bankdprt);   /* Справочник отделений банков */

   _bank.MFO_Depart = BIK;
   _bank.Corr_Acc   = "";
   if (( getGE(_bank) ) and ( _bank.MFO_Depart == BIK ))
     return _bank.szPlace + " " + _bank.NamePlace;
   end;
   return "";
END;

/* ------------------------------------------------------------------------ */
MACRO _NameBank_PlaceBank( BIK )
 file _bank (bankdprt);   /* Справочник отделений банков */

  if( ValType(BIK) == V_UNDEF )
    BIK = _MFO_Bank();
  end;

  _bank.MFO_Depart = BIK;
  _bank.Corr_Acc   = "";
  if ( getGE(_bank) and ( _bank.MFO_Depart == BIK ))
    if(index(_bank.Kind_Depart,_bank.szPlace + _bank.NamePlace) == 0)
      return trim(_bank.Name_Depart) + ", " + _bank.szPlace + " " + _bank.NamePlace ;
    else
      return trim(_bank.Name_Depart) ;
    end;
/*
    if(index(_bank.Kind_Depart,"Ф") == 0)
      return trim(_bank.Name_Depart) + ", " + _bank.szPlace + " " + _bank.NamePlace ;
    else
      if(index(_bank.Kind_Depart,"С") == 0)
        return trim(_bank.Name_Depart) ;
      else
        return trim(_bank.Name_Depart) + ", " + _bank.szPlace + " " + _bank.NamePlace ;
      end;
    end;
*/
  end;

  return "";
END;

/* ------------------------------------------------------------------------ */
macro _PRBB_BANK_NAME()
  return PlaceBank("044525986") ;
end ; /* _PRBB_BANK_NAME */

/* ------------------------------------------------------------------------ */
MACRO InnBank()
file f_client (client) key 0 ;

  f_client.Client = NumCurBank ;
  if( GetEQ(f_client) )
    /* EVG
    return GetClientInn(NumCurBank) ;*/
  end ;
  return "" ;
END ; /* InnBank */

/* ------------------------------------------------------------------------ */
MACRO PRBB_GetClientKPP(client)
  private file f_regdoc (regdoc) key 0 ;
  f_regdoc.Client = Client;
  f_regdoc.RDKind = 101;
  if(GetEQ(f_regdoc))
    return f_regdoc.RegNum;
  end;
  return "";
END;

/* ------------------------------------------------------------------------ */
MACRO _KppBank()
file f_client (client) key 0 ;

  f_client.Client = NumCurBank ;
  if( GetEQ(f_client) )
//    return f_client.kpp ;
    return PRBB_GetClientKPP(f_client.Client) ;
  end ;
  return "" ;
END ; /* KppBank */

/* ------------------------------------------------------------------------ */
MACRO ОсновнойРегистрационныйНомер()
file cl_info (claddfrm) key 0 ;

  cl_info.Client = NumCurBank ;
  if( GetEQ(cl_info) )
    return cl_info.RegNumber ;
  end ;
  return "" ;
END ; 

/* ------------------------------------------------------------------------ */
macro CorAccInter(NumSchem, Code_Currency, fBase, O)   /* коррсчет */

  if( ValType(NumSchem) == V_UNDEF )
    NumSchem = 0 ;
  end ;
  if( ValType(Code_Currency) == V_UNDEF )
    Code_Currency = 0 ;
  end ;

  if( ValType(fBase) == V_UNDEF )
    fBase = TbFile("corschem.dbt", "R", 0) ;
  end ;

  fBase.Rec.Code_Currency = Code_Currency ;
  fBase.Rec.Number = NumSchem ;

  if( fBase.GetEQ )
    if(ValType(O) == V_UNDEF)
      return fBase.Rec.FDebetCAD ;   //Банк дебет начальные
    else
      if(O == 0)
        return fBase.Rec.ODebetCAD ; //Банк дебет ответные
      elif(O == 1)
        return fBase.Rec.OKreditCAD ;//Банк кредит ответные
      elif(O == 2)
        return fBase.Rec.FKreditCAD ;//Банк кредит начальные
      end;   
    end;
  end ;
  return "" ;
end ; /* CorAccInter */

/* ------------------------------------------------------------------------ */
macro _UnknAcc(NumSchem, Code_Currency)   /* счет невыясненых */
file fCorSchem_cur (corschem) key 0 ;

  if( ValType(NumSchem) == V_UNDEF )
    NumSchem = 0 ;
  end ;
  if( ValType(Code_Currency) == V_UNDEF )
    Code_Currency = 0 ;
  end ;

  fCorSchem_cur.Code_Currency = Code_Currency ;
  fCorSchem_cur.Number = NumSchem ;

  if( GetEQ(fCorSchem_cur) )
    return fCorSchem_cur.UnknK ;
  end ;
  return "" ;
end ; /* _UnknAcc */

/* ------------------------------------------------------------------------ */
/*06.03.04 avv Возвращает счета, наим. и пачку схемы переоценки, вх.пар-ры: глава и номер схемы*/
macro _Orschem_Acc(chapter, orschem, СчетОтрицКурсРазниц, СчетПоложКурсРазниц, Name, NumbPack)
file fOrschem_ (orscheme) key 1;
   SetParm(2,"");
   SetParm(3,"");
   SetParm(4,"");
   SetParm(5,0);
   fOrschem_.Chapter = chapter;
   fOrschem_.Number  = orschem;
   if (GetEQ(fOrschem_))
      SetParm(2,fOrschem_.AccountHeight);
      SetParm(3,fOrschem_.AccountDown);
      SetParm(4,fOrschem_.Name);
      SetParm(5,fOrschem_.Number_Pack);
      return true;
   end;
   return false;
end;

/* ------------------------------------------------------------------------ */
MACRO _TelefonCurBank()                 /*avv первый телефон (до запятой)*/
file f_client (client) key 0 ;
  f_client.Client = NumCurBank ;
  if( GetEQ(f_client) )
    return substr(f_client.szPhoneNumber,1,index(f_client.szPhoneNumber,",")-1) ;
  end ;
  return "" ;
END ; /* InnBank */

/* ------------------------------------------------------------------------ */
MACRO _TelefonAll()                     /*dash полностью*/
file f_client (client) key 0 ;
  f_client.Client = NumCurBank ;
  if( GetEQ(f_client) )
    return f_client.szPhoneNumber;
  end ;
  return "" ;
END ; 

/* ------------------------------------------------------------------------ */
MACRO _OKONHCurBank()
file f_client (client) key 0 ;
  f_client.Client = NumCurBank ;
  if( GetEQ(f_client) )
    return substr(f_client.CodeForms,20,10);
  end ;
  return "" ;
END ; /* InnBank */

// ---------------------------------------------------------------------------
// Название текущего банка
macro _NAME_BANK(BIC_Bank)
/*
var f_bank ;
*/
  if( ( ValType(BIC_Bank) == V_UNDEF )/* or ( BIC_Bank == _MFO_Bank() ) */)
    //return fCur_Bank.Name_Bank ;
    return {NAME_BANK};
  else
    return _NameBank_PlaceBank( BIC_Bank );
  end;
/*

    if( BIC_Bank == BIC_VUZ )
      f_bank = TbFile("bank.dbt", "R", 0, PathBase_VUZ + "bank.dbt", "goto98.def") ;

    elif( BIC_Bank == BIC_VOLGA )
      f_bank = TbFile("bank.dbt", "R", 0, PathBase_VOLGA + "bank.dbt", "goto98.def") ;

    elif( BIC_Bank == BIC_BALAKOVO )
      f_bank = TbFile("bank.dbt", "R", 0, PathBase_BALAKOVO  + "bank.dbt", "goto98.def") ;

    elif( BIC_Bank == BIC_ENGELS )
      f_bank = TbFile("bank.dbt", "R", 0, PathBase_ENGELS    + "bank.dbt", "goto98.def") ;

    elif( BIC_Bank == BIC_VOLGOGRAD )
      f_bank = TbFile("bank.dbt", "R", 0, PathBase_VOLGOGRAD + "bank.dbt", "goto98.def") ;

    else
      f_bank = TbFile("bank.dbt", "R", 0, PathBase_PRBB + "bank.dbt", "goto98.def") ;

    end ;

    f_bank.Rewind ;
    f_bank.Prev ;
    return f_bank.Rec.Name_Bank ;
  end ;
*/
end ; /* _NAME_BANK */

// --------------------------------------------------------------------------
// Фронтовое ID банка
macro Front_ID_Bank(BIC)

  if( _PRBB_BANK(BIC) )
    return Front_ID_PRBB ;

  elif( _VUZ_BANK(BIC) )
    return Front_ID_VUZ ;

  elif( _VOLGA_BANK(BIC) )
    return Front_ID_VOLGA ;

  elif( _BALAKOVO_BANK(BIC) )
    return Front_ID_BALAKOVO ;

  elif( _ENGELS_BANK(BIC) )
    return Front_ID_ENGELS ;

  elif( _VOLGOGRAD_BANK(BIC) )
    return Front_ID_VOLGOGRAD ;

  elif( _ULYANOVSK_BANK(BIC) )
    return Front_ID_ULYANOVSK ;

  elif( _IOB_BANK(BIC) )
    return Front_ID_IOB ;

  elif( _VORON_BANK(BIC) )
    return Front_ID_VORON ;

  elif( _BANK24RU_BANK(BIC) )
    return Front_ID_BANK24RU ;

  elif( _GEB_BANK(BIC) )
    return Front_ID_GEB ;

  end ;

  return 0 ;
end ; // Front_ID_Bank

