/************************************************************************/
/*          Автоматизированная банковская система RS-Bank v6.0          */
/*                                                                      */
/*               Copyright (c) R-Style Ukraine                          */
/*                                                                      */
/*  Имя файла        :                                                  */
/*                                                                      */
/*  Описание         : макрос отчета обороты по счету за период         */
/*                                                                      */
/*  Программист      : Вихров Д.В.                                      */
/*                                                                      */
/*  Создан           : 27.11.2009                                       */
/*                                                                      */
/************************************************************************/


//import globals;
//import frontcommon
//import "..\\mac.usr\\юЄырфър\\disa_debet_svodn.mac";
import globals, oralib,  FIInter,rsbdataset,OprInter,SprAcc, "UpddateAcc.mac","VBAconst.mac";

//import frontcommon;
/*
var KEY_F2=316;
var KEY_F3=317;
var KEY_F9=323;
var KEY_ESC=27;
var KEY_ENTER=13;
*/
var ds_main, sql_main;
var ds_kl,ds_c4;
var sql,code;
var client:string;
var ob,ex,obBook,obSheet;
var out, output = "nostrooborot.xls", fulloutput;                            
var path = "", pathfile = "",    filen = "RSU.lbr";
var ex_stroka=10;
var end_select_stroka:integer,begin_select_stroka:integer;
var kod_fi;

/* Коркин И.Н. раскомментировал строку и добавил пару переменных */
/* вихров снова закаментил. переменные вынесены в файл vbaconst  */
//var xlTop    = -4160, xlBottom = -4107, xlRight  = -4152, xlLeft   = -4131, xlContext = -5002, xlGeneral = 1;

//var xlTop    = -4160, xlBottom = -4107, xlRight  = -4152, xlLeft   = -4131;

GetRegistryValue("BANK_INI\\ОБЩИЕ ПАРАМЕТРЫ\\ДИРЕКТОРИИ\\LBRDIR",2,path);
filen = "RSU.lbr";
pathfile = FindPath(filen,path);
	if (not pathfile)
		msgbox("Не найдена LBR");
		exit();
	end;
var dlg = TRecHandler("spracc",pathfile,True);
var kind_account:string="?";


private MACRO GetClientByAccount(account,code)
private var rsc:object = Null, str="";

  if(code == 0)
    str=string(" select t.* from daccount_dbt t where  t.t_account='",account,"'");    
    rsc=execSQLselect(str);
    if( rsc.moveNext())
      return rsc.value("t_client");
    else
        //msgbox ("счет",account," не найден ");
        return 0;
    end;
  else
    str=string(" select t.* from daccount$_dbt t where t.t_account='",account,"'");    
    rsc=execSQLselect(str);
    if( rsc.moveNext())
      return rsc.value("t_client");
    else
        //msgbox ("счет ",account,"  не найден ");
        return 0;
    end;
  end;
END;

macro c4etname(c);
	var s="select * from daccount_dbt where t_account='"+c+"'";
	var ds=trsbdataset(s);
	while (ds.movenext())
		return ds.value("t_nameaccount");
	end;
end;

macro format_select;
	obSheet.Range("A"+(begin_select_stroka-1)+":C"+end_select_stroka).select;
	ex.Selection.Borders(xlDiagonalDown).LineStyle = xlNone;
  ex.Selection.Borders(xlDiagonalUp).LineStyle = xlNone;
  ex.Selection.Borders(xlEdgeLeft).LineStyle = xlContinuous;
	ex.Selection.Borders(xlEdgeLeft).Weight = xlThin;
	ex.Selection.Borders(xlEdgeLeft).ColorIndex = xlAutomatic;
  ex.Selection.Borders(xlEdgeTop).LineStyle = xlContinuous;
  ex.Selection.Borders(xlEdgeTop).Weight = xlThin;
  ex.Selection.Borders(xlEdgeTop).ColorIndex = xlAutomatic;
  ex.Selection.Borders(xlEdgeBottom).LineStyle = xlContinuous;
  ex.Selection.Borders(xlEdgeBottom).Weight = xlThin;
  ex.Selection.Borders(xlEdgeBottom).ColorIndex = xlAutomatic;
  ex.Selection.Borders(xlEdgeRight).LineStyle = xlContinuous;
  ex.Selection.Borders(xlEdgeRight).Weight = xlThin;
  ex.Selection.Borders(xlEdgeRight).ColorIndex = xlAutomatic;
  ex.Selection.Borders(xlInsideVertical).LineStyle = xlContinuous;
  ex.Selection.Borders(xlInsideVertical).Weight = xlThin;
  ex.Selection.Borders(xlInsideVertical).ColorIndex = xlAutomatic;
  ex.Selection.Borders(xlInsideHorizontal).LineStyle = xlContinuous;
  ex.Selection.Borders(xlInsideHorizontal).Weight = xlThin;
  ex.Selection.Borders(xlInsideHorizontal).ColorIndex = xlAutomatic;
  obSheet.Range("A"+end_select_stroka+":C"+end_select_stroka).Select;
  ex.Selection.Font.Bold = True;
END;

MACRO day_imya_valuty(valuta)
	private var s:string="select distinct(t_name),t_fiid from dfininstr_dbt where t_fi_code='"+valuta+"'";
	var ds=trsbdataset(s);
	if (ds.movenext()) 
		kod_fi=ds.value("t_fiid"); 
		return ds.value("t_name"); 
	else 
		kod_fi="неизвестная валюта";
		return "неизвестная валюта"; 
	end;
END;

MACRO day_ostatok(c4_,d_e_); 
	private var s="select t_kind_account,"+
    						"case substr(t_account,6,3) "+
        				"when '810' then abs(rsb_account.resta  ( acc.t_account,          to_date ( '"+d_e_+"', 'DD.MM.YYYY' ),    acc.t_chapter,   null  ))   "+
        				"else            abs(rsb_account.restac ( acc.t_account, t_fiid,  to_date ( '"+d_e_+"', 'DD.MM.YYYY' ),    acc.t_chapter,   null  ))  "+
    						"end as rest from daccount_dbt acc , dfininstr_dbt fin "+
								"where t_account='"+c4_+"' and fin.t_fi_code=substr(t_account,6,3) ";
	private var ds1=trsbdataset(s);
	kind_account="?";
	if (ds1.movenext()) 
		kind_account=ds1.value("t_kind_account");
		return ds1.value("rest"); 
	else 
		kind_account="?";
		return -0.001; 
	end;
END;

MACRO format_r(stolb,stroka);
  obSheet.Range(stolb+stroka).select;
  ex.selection.HorizontalAlignment = xlRight;
  ex.selection.VerticalAlignment = xlBottom ;
  ex.selection.WrapText = False;
  ex.selection.Orientation = 0;
  ex.selection.AddIndent = False;
  ex.selection.IndentLevel = 0;
  ex.selection.ShrinkToFit = False;
  ex.selection.ReadingOrder = xlContext;
  ex.selection.MergeCells = False;
END;


MACRO day_name_clienta(t_c4,nada_imya);
	var s:string="select p.t_name,f.t_ccy from dparty_dbt p, daccount$_dbt,dfininstr_dbt f where t_client=t_partyid and t_account='"+t_c4+"' and t_fiid=t_code_currency";
	var d=trsbdataset(s);
	if (d.movenext())
		if (nada_imya==0) return d.value("t_ccy"); 
		else return 						(d.value("t_ccy")+" "+d.value("t_name")); 
		end;
	else
		return "";
	end;
END;


MACRO day_name_c4eta(t_c4);
	var s:string="select t_nameaccount from daccount$_dbt where t_account ='"+t_c4+"'";
	var d=trsbdataset(s);
	if (d.movenext())
		return d.value("t_nameaccount");
	else
		return "-";
	end;

END;


macro outputinexel(d_b,d_e)
	var ds1,summa_c4eta,summa_valuta,new_client,new_valuta;
	var tek_c4et, pred_c4et,nomer_provodki,tek_valuta,pred_valuta,tek_client,pred_client;
	var begin:bool;
//	msgbox("d_b= "+(d_b-1));
	ex_stroka=9;
	sql="select t_code_currency val, t_account_payer, t_account_receiver, t_sum, t_ground "+
			"from darhdoc$_dbt "+
			"where     t_account_payer like '30114%' "+
	    "and t_date_carry >= to_date ( '"+d_b+"', 'DD.MM.YYYY' ) and t_date_carry <= to_date ( '"+d_e+"', 'DD.MM.YYYY' ) "+
      "and t_result_carry <> 23 "+
			"order by substr ( t_account_payer, 6, 3 ), substr ( t_account_payer, 9, 12 ),t_sum ";
	//getstring(sql);
	obSheet.Range("c"+6).Value="С "+d_b+"   ПО "+d_e;
	ds1=trsbdataset(sql);
	summa_c4eta=0.0; summa_valuta=0;new_client=true; new_valuta=true;
	pred_valuta="hz"; pred_c4et="hz";nomer_provodki=1;
	begin=true;
	while (ds1.movenext())

	  tek_c4et=ds1.value("t_account_payer");
	  tek_valuta=substr(tek_c4et,6,3);
		tek_client=substr(tek_c4et,9,12);
 if (not(begin))
		if (tek_client!=pred_client)
			obSheet.Range("A"+ex_stroka).Value="ИТОГО по счету "+pred_c4et+" "+day_name_clienta(pred_c4et,0);
			obSheet.Range("D"+ex_stroka).Value=summa_c4eta; 
			summa_c4eta=0;ex_stroka=ex_stroka+2;
			nomer_provodki=1;
		end;
		if (pred_valuta!=tek_valuta) 
			obSheet.Range("A"+ex_stroka).Value="ИТОГО по валюте "+day_name_clienta(pred_c4et,0);
			obSheet.Range("D"+ex_stroka).Value=summa_valuta;
			summa_valuta=0;summa_c4eta=0;
			ex_stroka=ex_stroka+2;
		end;
 end;
		if (tek_client!=pred_client) 
			obSheet.Range("b"+ex_stroka).Value="              "+tek_c4et+"  "+day_name_clienta(tek_c4et,1);
			ex_stroka=ex_stroka+1;
		end;

		obSheet.Range("A"+ex_stroka).select;
		ex.Selection.NumberFormat = "@";
		obSheet.Range("A"+ex_stroka).Value=nomer_provodki;
		nomer_provodki=nomer_provodki+1;
		obSheet.Range("B"+ex_stroka).Value=day_name_c4eta(ds1.value("t_account_receiver"));
		obSheet.Range("c"+ex_stroka).select;
		ex.Selection.NumberFormat = "@";
		obSheet.Range("c"+ex_stroka).Value=ds1.value("t_account_receiver");
		obSheet.Range("d"+ex_stroka).Value=ds1.value("t_sum"); 
		summa_c4eta=summa_c4eta+ds1.value("t_sum"); summa_valuta=summa_valuta+ds1.value("t_sum");
		obSheet.Range("e"+ex_stroka).Value=ds1.value("t_ground");




		ex_stroka=ex_stroka+1;


    pred_valuta=tek_valuta; 
    pred_client=tek_client;
    pred_c4et=tek_c4et;
  	begin=false;
	end;
			obSheet.Range("A"+ex_stroka).Value="ИТОГО по счету "+pred_c4et+" "+day_name_clienta(pred_c4et,0);
			obSheet.Range("D"+ex_stroka).Value=summa_c4eta; 
			summa_c4eta=0;ex_stroka=ex_stroka+2;
			obSheet.Range("A"+ex_stroka).Value="ИТОГО по валюте "+day_name_clienta(pred_c4et,0);
			obSheet.Range("D"+ex_stroka).Value=summa_valuta;
			summa_valuta=0;summa_c4eta=0;


//	obSheet.Range("A"+ex_stroka).Value="ИТОГО: ";
//	obSheet.Range("b"+ex_stroka).Value=summa;
//	end_select_stroka=ex_stroka;
//	format_select;
//	ex_stroka=ex_stroka+3;


//	obSheet.Range("A"+ex_stroka).Value="ИТОГО: "; /
//	obSheet.Range("b"+ex_stroka).Value=summa;
//	end_select_stroka=ex_stroka;
//	format_select;
end;




macro EvMacro (dlg, cmd, id, key)

  if (cmd==DLG_INIT)
    	message("~F2~ продолжить,  ~ESC~ выход");
     dlg.rec.BeginDate = {curdate};
     dlg.rec.EndDate   = {curdate};
     dlg.rec.acc ="nostro";
  end;

  if (cmd == DLG_REMFOCUS)
    if (FldName(dlg,id)=="Acc")
/*       if (StrLen(dlg.rec.acc) < 20)
          MsgBox("Длина счета менее 20 символов");
          return CM_CANCEL;
       elif (not GetAccount(StrSubst(dlg.rec.acc, ".", "")))
          MsgBox("Счет отсутствует в справочнике лицевых счетов");
          return CM_CANCEL;
       else
       		if (substr(dlg.rec.acc,6,3)=="810") code=0; else code=1; end;
          Client = GetClientByAccount(dlg.rec.acc,  Code);
          //Branch = GetBranchByAccount(dlg.rec.acc,  Code);
       end;*/
    elif (FldName(dlg,id)=="BeginDate")
       if ( dlg.rec.BeginDate > dlg.rec.EndDate ) 
          MsgBox("Дата начала больше даты окончания отчетного периода");
          return CM_CANCEL;
       elif ( dlg.rec.BeginDate > {curdate} )
          MsgBox("Дата начала больше даты текущего операционного дня"); 
          return CM_CANCEL;
       end;
    elif (FldName(dlg,id)=="EndDate") 
       if (dlg.rec.EndDate < dlg.rec.BeginDate )
          MsgBox("Дата окончания меньше даты начала отчетного периода"); 
          return CM_CANCEL;
       elif ( dlg.rec.EndDate > {curdate} )
          MsgBox("Дата окончания больше даты текущего операционного дня");
          return CM_CANCEL;
       end;
    end;
    UpdateFields(dlg); 
  end;    






  if (cmd==DLG_KEY)
    if (KEY==KEY_F9)
	return CM_ignore;
    end; //if F9

    if (KEY==KEY_ENTER)
	return CM_ignore;
    end; //if F9

    if (KEY==KEY_F3)

      return CM_Ignore;
    end; //if F3

    if (KEY==KEY_F2)
/*      if (dlg.rec.date_name_field >{curdate})
	msgbox("─рЄр сюы№°х фрЄ√ Єхъє∙хую юяхЁрЎшюээюую фэ ");
	return cm_ignore;
      end;*/
    if (IsStandAlone()) // Двухзвенка
      if ((ValType(ex)!=V_UNDEF) and (ex.Visible==False))
        ex = ActiveX("Excel.Application",NULL,false); 
      else
        ex = ActiveX("Excel.Application",NULL,true);
      end;
    else // Трехзвенка
      ob = CreateObject ("rsax","TRsAxServer","RsAxServer",false);
      ex = ob.CreateComObject ("Excel.Application",true);
    end; 
		GetRegistryValue("BANK_INI\\ОБЩИЕ ПАРАМЕТРЫ\\ДИРЕКТОРИИ\\USERTEMPLSDIR",2,out);
		Fulloutput = FindPath(output, out);                    
		if (not Fulloutput)
			msgbox("Не найдена LBR");
			exit();
		end;
		obBook = ex.Workbooks.open(fulloutput); 

		obSheet = obBook.ActiveSheet(); 
		ex.visible=true;
		outputinexel(dlg.rec.begindate,dlg.rec.enddate);
      return CM_save;
    end; //if F2

    if (KEY==KEY_ESC)
      exit(1);
      return CM_CANCEL;
    end; //if esc

  end; //if DLG_KEY
END; //evmacro





if(rundialog(dlg,"evmacro")) 
  println();
	println("													ОТЧЕТ СФОРМИРОВАН В EXCEL");
  println();
	println("											для продолжения работы нажмите ESC");
end;

