/******************************************************************************/
/*                     R-Style SoftLab, RS-Bank V6                            */
/******************************************************************************/
/*                                                                            */
/*          Работа с пользовательской штатной структурой                      */
/*                                                                            */
/*  Макрос: tst_ot.mac                                                        */
/*  Дата  :   25.06.09                                  Володченков Е.В.      */
/*  GSP 29.08.2012 Перенес печать отчета по привязке внутрь дочернего макроса */
/******************************************************************************/
//Lavrenov: 20.06.2012 I-00211098-1
//Gurin: 17.08.2012 I-00237162-2

import BankInter,rsbdataset;
import oralib, likepy;

record dlg    (otdel ,"otdels.lbr") dialog;
record dlg_op (opers ,"otdels.lbr") dialog;


var RecordSet;
var exitscroll = false;

var kod1,kod2,name,tmp=0,tmp1=0,tmp3=0, date1,date2;
var ischanged=false, isexit=false, isexit1 = false, isexit2 = false;

// 2012-05-22 zip_z. I-00196407 
// @desc: проверка пользовательского ввода: если введенный код подразделения не существует, вернет false
macro checkOperDprt (code1:integer, code2:integer):bool
    var sql = "SELECT * FROM dotdels_dbt where t_code1 = :code1 and t_code2 = :code2";
    sql = execSqlSelect (sql, makeArray (SQLParam ("code1", code1), SQLParam ("code2", code2)));
    return sql.moveNext ();
end;


MACRO GetNameByOper(oper)
  var rs,str;
  str = "select t_name from dperson_dbt where t_oper = "+oper;
  rs = trsbdataset(str);
  if(rs and rs.movenext)
    return rs.name;
  end;
  return "Нет такого пользователя!";
END;

/* Коркин И.Н. по заявке I-062488 */
macro checkBeginDate(begindate, enddate, oper1)
	var query, data, enddate_;
      if (enddate=="") //Gurin 17.08.2012 I-00237162-2
          enddate_ = "31.12.9999";
      else 
          enddate_ = enddate;
      end;
      debugbreak;
	query = "   SELECT   t_datebegin, t_dateend, t_code1, t_code2 "
   + "\n" + "    FROM   dop_otdel_dbt "
   + "\n" + "   WHERE   (t_dateend >= TO_DATE ('" + begindate + "') "
   + "\n" + "                OR t_dateend = TO_DATE ('01.01.0001')) "
   + "\n" + "           and (t_datebegin <= TO_DATE ('" + begindate + "') "
   + "\n" + "                OR t_datebegin >= TO_DATE ('" + begindate + "')) "                     //Gurin 17.08.2012 I-00237162-2
   + "\n" + "           and t_datebegin <= TO_DATE ('" + enddate_ + "')"                            //Gurin 17.08.2012 I-00237162-2
   + "\n" + "           and t_oper = " + oper1;                              
   data = TRsbDataset(query);
   if (data.movenext)
   	return msgbox("Дата открытия пересекается с периодом с " + date(data.value(0)) + " по " + date(data.value(1)) +" подразделение " + data.value(2) + "." + data.value(3));
   	return false;
   else
       return true;
   end;	
end;

/*********************Обрабоччики**************************/


macro Otd_dlg_oper(dlg_op, cmd, id, key)    //  редактирование опера по F5
  message("~F2/F9~ Подтвердить");
  var CmdText,Command, date11, date22;
  var col = TArray;
  macro AddCol (ar,ind, fld, head, width, rdonly)
	ar.value (ind * 6)     = fld;
  	ar.value (ind * 6 + 1) = head;
	ar.value (ind * 6 + 2) = width;
	ar.value (ind * 6 + 3 ) = 2;   // fldType
       ar.value (ind * 6 + 4 ) = -1;  // decPoint
  	ar.value (ind * 6 + 5 ) = 0;   // reserv
  end;
  debugbreak;
  if ( RecordSet.value(4) == date(" 1.01.0001 (00:00:00.00)"))
  date11 = "01.01.0001";
  else
  date11 = date(RecordSet.value(4));
  end;
  if ( RecordSet.value(5) == date(" 1.01.0001 (00:00:00.00)"))
  date22 = "01.01.0001";
  else
  date22 = date(RecordSet.value(5));
  end;

  if ( cmd == DLG_INIT )
 	 dlg_op.kod1 = kod1;
 	 dlg_op.kod2 = kod2;
 	 dlg_op.oper_id = name;
 	 dlg_op.oper_fio = GetNameByOper(name);
	  dlg_op.date_b = RecordSet.value(4); 
 	 dlg_op.date_e = RecordSet.value(5);
 	 UpdateFields(dlg_op);
  end;
  macro EvPr (RecordSet, Command, id, key )
  	if ((Command == DLG_KEY) and (key == 13))
       	dlg_op.oper_id =  RecordSet.value(0);
          	dlg_op.oper_fio =  RecordSet.value(1);
		name =  RecordSet.value(0);
	   	UpdateFields(dlg_op);
        	return CM_select;  
       end;
  END;

    if( cmd == DLG_KEY ) 
           if ((key == 316) or (key == 323)) // F2 F9  подтверждение редактирования
debugbreak;
	      	if ( ( dlg_op.date_b == date(0,0,0) ) and ( dlg_op.date_e != date(0,0,0) ) )
    	    		CmdText = " update dop_otdel_dbt "+
				   " set t_datebegin = to_date ('01.01.0001','dd.mm.yyyy'), "+
			          "     t_dateend   = to_date ('"+ dlg_op.date_e + "','dd.mm.yyyy')  "+
                               " where t_oper = "+dlg_op.oper_id+
			          " and  t_code1 = "+dlg_op.kod1+
			          " and  t_code2 = "+dlg_op.kod2+
               	          " and    t_dateend   = to_date ('"+ (date22) + "','dd.mm.yyyy')  "+
                               " and t_datebegin = to_date ('"+ (date11) + "','dd.mm.yyyy') ";

       
	    		Command = RSDCommand(CmdText);
           		Command.Execute();
	    		CmdText = "commit";
           		Command = RSDCommand(CmdText);
           		Command.Execute();
              end;
	      	if ( ( dlg_op.date_b != date(0,0,0) ) and ( dlg_op.date_e == date(0,0,0) ) )
    	    		CmdText = " update dop_otdel_dbt "+
				   " set t_datebegin = to_date ('"+ dlg_op.date_b +"','dd.mm.yyyy'), "+
			          "     t_dateend   = to_date ('01.01.0001','dd.mm.yyyy')  "+
                               " where t_oper = "+dlg_op.oper_id+
			          " and  t_code1 = "+dlg_op.kod1+
			          " and  t_code2 = "+dlg_op.kod2+
               	          " and    t_dateend   = to_date ('"+ (date22) + "','dd.mm.yyyy')  "+
                               " and t_datebegin = to_date ('"+ (date11) + "','dd.mm.yyyy') ";

       
	    		Command = RSDCommand(CmdText);
           		Command.Execute();
	    		CmdText = "commit";
           		Command = RSDCommand(CmdText);
           		Command.Execute();
              end;
	      	if ( ( dlg_op.date_b == date(0,0,0) ) and ( dlg_op.date_e == date(0,0,0) ) )
    	    		CmdText = " update dop_otdel_dbt "+
				   " set t_datebegin = to_date ('01.01.0001','dd.mm.yyyy'), "+
			          "     t_dateend   = to_date ('01.01.0001','dd.mm.yyyy')  "+
                               " where t_oper = "+dlg_op.oper_id+
			          " and  t_code1 = "+dlg_op.kod1+
			          " and  t_code2 = "+dlg_op.kod2+
               	          " and    t_dateend   = to_date ('"+ (date22) + "','dd.mm.yyyy')  "+
                               " and t_datebegin = to_date ('"+ (date11) + "','dd.mm.yyyy') ";

       
	    		Command = RSDCommand(CmdText);
           		Command.Execute();
	    		CmdText = "commit";
           		Command = RSDCommand(CmdText);
           		Command.Execute();
              end;
	      	if ( ( dlg_op.date_b != date(0,0,0) ) and ( dlg_op.date_e != date(0,0,0) ) )
    	    		CmdText = " update dop_otdel_dbt "+
				   " set t_datebegin = to_date ('"+ dlg_op.date_b +"','dd.mm.yyyy'), "+
			          "     t_dateend   = to_date ('"+ dlg_op.date_e +"','dd.mm.yyyy')  "+
                               " where t_oper = "+dlg_op.oper_id+
			          " and  t_code1 = "+dlg_op.kod1+
			          " and  t_code2 = "+dlg_op.kod2+
               	          " and    t_dateend   = to_date ('"+ (date22) + "','dd.mm.yyyy')  "+
                               " and t_datebegin = to_date ('"+ (date11) + "','dd.mm.yyyy') ";

       
	    		Command = RSDCommand(CmdText);
           		Command.Execute();
	    		CmdText = "commit";
           		Command = RSDCommand(CmdText);
           		Command.Execute();
              end;


           ischanged=true; 

	    dlg_op.kod1 = 0;
	    dlg_op.kod2 = 0;
	    dlg_op.oper_id  = 0;
           dlg_op.date_b = date(0,0,0);
	    dlg_op.date_e = date(0,0,0);
           return CM_Save;
       end
    end;



  if( (id==2)and(key==317))
  	AddCol (col, 0, "t_oper", "Номер", 10, true);
       AddCol (col, 1, "t_name", "Имя", 35, true);
       CmdText = "SELECT t_oper , t_name  "+
                 "FROM dperson_dbt "+
                 "Order by t_oper";

      	Command = RSDCommand(CmdText);
       Command.Execute();
       RecordSet = RSDRecordSet(Command, RSDVAL_CLIENT, RSDVAL_STATIC);
       runScroll(RecordSet, 2, col, null, @EvPr, "Пользователи", false);
  end;
end;

macro Otd_dlg_oper_v(dlg_op, cmd, id, key)    // ввод опера
  message("~F2/F9~ Подтвердить");
  var CmdText,Command;
  var col = TArray;
  macro AddCol (ar,ind, fld, head, width, rdonly)
	ar.value (ind * 6)     = fld;
  	ar.value (ind * 6 + 1) = head;
	ar.value (ind * 6 + 2) = width;
	ar.value (ind * 6 + 3 ) = 2;   // fldType
       ar.value (ind * 6 + 4 ) = -1;  // decPoint
  	ar.value (ind * 6 + 5 ) = 0;   // reserv
  end;
  macro EvPr (RecordSet, Command, id, key )
  	if ((Command == DLG_KEY) and (key == 13))
       	dlg_op.oper_id =  RecordSet.value(0);
          	dlg_op.oper_fio =  RecordSet.value(1);
		name =  RecordSet.value(0);
	   	UpdateFields(dlg_op);
        	return CM_select;  
       end;
  END;
 if ( cmd == DLG_INIT )
 	 dlg_op.kod1 = kod1;
	  dlg_op.kod2 = kod2;
	  UpdateFields(dlg_op);
 end;
    if( cmd == DLG_KEY ) 
           if ((key == 316) or (key == 323)) // F2 F9  подтверждение редактирования
              if (not checkBeginDate(dlg_op.date_b, dlg_op.date_e, dlg_op.oper_id))
                return cm_ignore;
              end;
              
              // 2012-05-22 zip_z. I-00196407   >
              if (not checkOperDprt (dlg_op.kod1, dlg_op.kod2))
                msgbox ("Подразделение (код1 = " + dlg_op.kod1 + "; код2 = " + dlg_op.kod2 + ") отсутствует в справочнике");
                return cm_ignore;
              end;
              // < zip_z. 
              
              if ( ( dlg_op.date_b == date(0,0,0) ) and ( dlg_op.date_e != date(0,0,0) ) )
                CmdText = " insert into dop_otdel_dbt "+
				   " (t_oper,t_datebegin,t_dateend,t_code1,t_code2) "+
                     	   " values ( "+dlg_op.oper_id+",to_date('01.01.0001','dd.mm.yyyy'), " +
			          " to_date('"+dlg_op.date_e+"','dd.mm.yyyy'),"+dlg_op.kod1+","+dlg_op.kod2+")";
	
           		Command = RSDCommand(CmdText);
           		Command.Execute();
	    		CmdText = "commit";
           		Command = RSDCommand(CmdText);
           		Command.Execute();
		end;
		if ( ( dlg_op.date_b != date(0,0,0) ) and ( dlg_op.date_e == date(0,0,0) ) )
	    		CmdText = " insert into dop_otdel_dbt "+
				   " (t_oper,t_datebegin,t_dateend,t_code1,t_code2) "+
                     	   " values ( "+dlg_op.oper_id+",to_date('"+dlg_op.date_b+"','dd.mm.yyyy'), " +
			          " to_date('01.01.0001','dd.mm.yyyy'),"+dlg_op.kod1+","+dlg_op.kod2+")";
	
           		Command = RSDCommand(CmdText);
           		Command.Execute();
    		CmdText = "commit";
           		Command = RSDCommand(CmdText);
           		Command.Execute();
		end;
		if ( ( dlg_op.date_e == date(0,0,0) ) and ( dlg_op.date_b == date(0,0,0) ) )
	    		CmdText = " insert into dop_otdel_dbt "+
				   " (t_oper,t_datebegin,t_dateend,t_code1,t_code2) "+
                     	   " values ( "+dlg_op.oper_id+",to_date('01.01.0001','dd.mm.yyyy'), " +
			          " to_date('01.01.0001','dd.mm.yyyy'),"+dlg_op.kod1+","+dlg_op.kod2+")";
	
           		Command = RSDCommand(CmdText);
           		Command.Execute();
	    		CmdText = "commit";
           		Command = RSDCommand(CmdText);
           		Command.Execute();
		end;
		if ( ( dlg_op.date_b != date(0,0,0) ) and ( dlg_op.date_e != date(0,0,0) ) )
	    		CmdText = " insert into dop_otdel_dbt "+
				   " (t_oper,t_datebegin,t_dateend,t_code1,t_code2) "+
                     	   " values ( "+dlg_op.oper_id+",to_date('"+dlg_op.date_b+"','dd.mm.yyyy'), " +
			          " to_date('"+dlg_op.date_e+"','dd.mm.yyyy'),"+dlg_op.kod1+","+dlg_op.kod2+")";
	
           		Command = RSDCommand(CmdText);
           		Command.Execute();
	    		CmdText = "commit";
           		Command = RSDCommand(CmdText);
           		Command.Execute();
		end;


           ischanged=true; 

	    dlg_op.kod1 = 0;
	    dlg_op.kod2 = 0;
	    dlg_op.oper_id  = 0;
           dlg_op.date_b = date(0,0,0);
	    dlg_op.date_e = date(0,0,0);
           return CM_Save;
       end
    end;

  if( (id==2)and(key==317))
  	AddCol (col, 0, "t_oper", "Номер", 10, true);
       AddCol (col, 1, "t_name", "Имя", 35, true);
       CmdText = "SELECT t_oper , t_name  "+
                 "FROM dperson_dbt "+
                 "Order by t_oper";

      	Command = RSDCommand(CmdText);
       Command.Execute();

       RecordSet = RSDRecordSet(Command, RSDVAL_CLIENT, RSDVAL_STATIC);
       runScroll(RecordSet, 2, col, null, @EvPr, " ~Enter~   Выбор", false);
  end;

end;

macro Otd_dlg(dlg, cmd, id, key);    // редактирование подразделений - нулевой уровень    (по F5)
      var CmdText,Command;
	message("~F2/F9~ Подтвердить");

   if ( cmd == DLG_INIT )
    dlg.kod1   = RecordSet.value(0);
    dlg.kod2   = RecordSet.value(1);
    dlg.name   = RecordSet.value(2);
    dlg.date_b = RecordSet.value(3);
    dlg.date_e = RecordSet.value(4);
    UpdateFields(dlg);

   elif ( cmd == DLG_REMFOCUS ) 
     return CM_IGNORE;
   elif( cmd == DLG_KEY ) 
	if ((key == 316) or (key == 323)) // F2 F9  подтверждение редактирования
          // msgbox(dlg.date_b,"||",dlg.date_e);
           //Lavrenov: 20.06.2012 I-00211098-1 проверка на длинну Названия
           if(strlen(dlg.name)>55)
             msgbox("Длинна поля \"Навание\" превышает 55 символов ("+strlen(dlg.name)+"). ");
             return CM_IGNORE;
           end;
	    if( (dlg.date_b == date(0,0,0)) and (dlg.date_e != date(0,0,0) ))
   	    	CmdText = " update dotdels_dbt "+
                     	" set t_name   = '"+ dlg.name+"' , "+
                     	"     t_date_b = to_date ('01.01.0001','dd.mm.yyyy'), "+
                     	"     t_date_e = to_date ('"+ dlg.date_e + "','dd.mm.yyyy')  "+
                     	" where  t_code1 = "+ dlg.kod1 +
                     	"   and  t_code2 = "+ dlg.kod2;
           	Command = RSDCommand(CmdText);
           	Command.Execute();
	    	CmdText = "commit";
           	Command = RSDCommand(CmdText);
           	Command.Execute();
           END;
	    if( (dlg.date_e == date(0,0,0)) and (dlg.date_b != date(0,0,0) ))
   	    	CmdText = " update dotdels_dbt "+
                     	" set t_name   = '"+ dlg.name+"' , "+
                     	"     t_date_b = to_date ('"+ dlg.date_b +"','dd.mm.yyyy'), "+
                     	"     t_date_e = to_date ('01.01.0001','dd.mm.yyyy')  "+
                     	" where  t_code1 = "+ dlg.kod1 +
                     	"   and  t_code2 = "+ dlg.kod2;
           	Command = RSDCommand(CmdText);
           	Command.Execute();
	    	CmdText = "commit";
           	Command = RSDCommand(CmdText);
           	Command.Execute();
           END;
    	    if( (dlg.date_e == date(0,0,0)) and (dlg.date_b == date(0,0,0) ))
   	    	CmdText = " update dotdels_dbt "+
                     	" set t_name   = '"+ dlg.name+"' , "+
                     	"     t_date_b = to_date ('01.01.0001','dd.mm.yyyy'), "+
                     	"     t_date_e = to_date ('01.01.0001','dd.mm.yyyy')  "+
                     	" where  t_code1 = "+ dlg.kod1 +
                     	"   and  t_code2 = "+ dlg.kod2;
           	Command = RSDCommand(CmdText);
           	Command.Execute();
	    	CmdText = "commit";
           	Command = RSDCommand(CmdText);
           	Command.Execute();
           END;
    	    if( (dlg.date_e != date(0,0,0)) and (dlg.date_b != date(0,0,0) ))
   	    	CmdText = " update dotdels_dbt "+
                     	" set t_name   = '"+ dlg.name+"' , "+
                     	"     t_date_b = to_date ('"+dlg.date_b+"','dd.mm.yyyy'), "+
                     	"     t_date_e = to_date ('"+dlg.date_e+"','dd.mm.yyyy')  "+
                     	" where  t_code1 = "+ dlg.kod1 +
                     	"   and  t_code2 = "+ dlg.kod2;
           	Command = RSDCommand(CmdText);
           	Command.Execute();
	    	CmdText = "commit";
           	Command = RSDCommand(CmdText);
           	Command.Execute();
           END;


           ischanged=true; 

	    dlg.kod1 = 0;
	    dlg.kod2 = 0;
	    dlg.name = "";
           dlg.date_b = date(0,0,0);
	    dlg.date_e = date(0,0,0);
           return CM_Save;
       end;
   end;
   return CM_DEFAULT; 
    
end;

macro Otd_dlg1(dlg, cmd, id, key);    // редактирование подразделений - первый уровень   (по F5)
    var CmdText,Command;
    message("~F2/F9~ Подтвердить");

   if ( cmd == DLG_INIT )
    dlg.kod1 = kod1;
    dlg.kod2 = kod2;
    dlg.name = name;
    dlg.date_b =  date1;//RecordSet.value(3);
    dlg.date_e =  date2;//RecordSet.value(4);

    UpdateFields(dlg);

   elif ( cmd == DLG_REMFOCUS ) 
     return CM_IGNORE;
   elif( cmd == DLG_KEY ) 
	if ((key == 316) or (key == 323)) // F2 F9  подтверждение редактирования
           //Lavrenov: 20.06.2012 I-00211098-1 проверка на длинну Названия 
           if(strlen(dlg.name)>55)
             msgbox("Длинна поля \"Навание\" превышает 55 символов ("+strlen(dlg.name)+"). ");
             return CM_IGNORE;
           end;

	    if( (dlg.date_b == date(0,0,0)) and (dlg.date_e != date(0,0,0) ))
   	    	CmdText = " update dotdels_dbt "+
                     	" set t_name   = '"+ dlg.name+"' , "+
                     	"     t_date_b = to_date ('01.01.0001','dd.mm.yyyy'), "+
                     	"     t_date_e = to_date ('"+ dlg.date_e + "','dd.mm.yyyy')  "+
                     	" where  t_code1 = "+ dlg.kod1 +
                     	"   and  t_code2 = "+ dlg.kod2;
           	Command = RSDCommand(CmdText);
           	Command.Execute();
	    	CmdText = "commit";
           	Command = RSDCommand(CmdText);
           	Command.Execute();
           END;
	    if( (dlg.date_e == date(0,0,0)) and (dlg.date_b != date(0,0,0) ))
   	    	CmdText = " update dotdels_dbt "+
                     	" set t_name   = '"+ dlg.name+"' , "+
                     	"     t_date_b = to_date ('"+ dlg.date_b +"','dd.mm.yyyy'), "+
                     	"     t_date_e = to_date ('01.01.0001','dd.mm.yyyy')  "+
                     	" where  t_code1 = "+ dlg.kod1 +
                     	"   and  t_code2 = "+ dlg.kod2;
           	Command = RSDCommand(CmdText);
           	Command.Execute();
	    	CmdText = "commit";
           	Command = RSDCommand(CmdText);
           	Command.Execute();
           END;

	    if( (dlg.date_e == date(0,0,0)) and (dlg.date_b == date(0,0,0) ))
   	    	CmdText = " update dotdels_dbt "+
                     	" set t_name   = '"+ dlg.name+"' , "+
                     	"     t_date_b = to_date ('01.01.0001','dd.mm.yyyy'), "+
                     	"     t_date_e = to_date ('01.01.0001','dd.mm.yyyy')  "+
                     	" where  t_code1 = "+ dlg.kod1 +
                     	"   and  t_code2 = "+ dlg.kod2;
           	Command = RSDCommand(CmdText);
           	Command.Execute();
	    	CmdText = "commit";
           	Command = RSDCommand(CmdText);
           	Command.Execute();
           END;
    	    if( (dlg.date_e != date(0,0,0)) and (dlg.date_b != date(0,0,0) ))
   	    	CmdText = " update dotdels_dbt "+
                     	" set t_name   = '"+ dlg.name+"' , "+
                     	"     t_date_b = to_date ('"+dlg.date_b+"','dd.mm.yyyy'), "+
                     	"     t_date_e = to_date ('"+dlg.date_e+"','dd.mm.yyyy')  "+
                     	" where  t_code1 = "+ dlg.kod1 +
                     	"   and  t_code2 = "+ dlg.kod2;
           	Command = RSDCommand(CmdText);
           	Command.Execute();
	    	CmdText = "commit";
           	Command = RSDCommand(CmdText);
           	Command.Execute();
           END;


           ischanged=true; 

	    dlg.kod1 = 0;
	    dlg.kod2 = 0;
	    dlg.name = "";
           dlg.date_b = date(0,0,0);
	    dlg.date_e = date(0,0,0);
           return CM_Save;
       end;
   end;
   return CM_DEFAULT; 
end;

macro Otd_dlg_v(dlg, cmd, id, key);      /// для ввода подразделений  по F9
   var CmdText,Command, query, data;
  
   if ( cmd == DLG_INIT )
      if (tmp1!=0)
	   dlg.kod1 = tmp;
          UpdateFields(dlg);
      else
	   dlg.kod1 = tmp3;
      end;
       message("~F2/F9~ Подтвердить")	 ;
   elif ( cmd == DLG_REMFOCUS ) 

     return CM_IGNORE;
   elif( cmd == DLG_KEY ) //I?iaa?ee ia ia?aoea eeaaeo

      if ((key == 316) or (key == 323))    // F2 F9  подтверждение сохранения отдела

       /* Коркин И.Н. Проверка на дублирование отдела. По заявке I-025959 */
       query = " select * from dotdels_dbt "
       + "\n" + "where t_code1 = " + dlg.kod1
       + "\n" + "and t_code2 = " + dlg.kod2;
       data = RSDRecordSet(query);
       if (data.movenext)
       	msgbOX("Подразделение с кодами " + dlg.kod1 + " "  + dlg.kod2 + " уже существует.");
  	    	return CM_IGNORE;
       end;


	    if( (dlg.date_b == date(0,0,0)) and (dlg.date_e != date(0,0,0) ))
      	   	 CmdText = " insert into dotdels_dbt "+
                     	" (t_code1, t_code2,t_name,t_date_b,t_date_e) "+
				" values ( "+dlg.kod1+","+dlg.kod2+",'"+dlg.name+"',to_date('01.01.0001','dd.mm.yyyy'),to_date('"+date(dlg.date_e)+"','dd.mm.yyyy'))";
             	Command = RSDCommand(CmdText);
           	Command.Execute();
	    	CmdText = "commit";
           	Command = RSDCommand(CmdText);
           	Command.Execute();
           end;
		
	    if((dlg.date_e == date(0,0,0)) and (dlg.date_b != date(0,0,0)) )
      	   	 CmdText = " insert into dotdels_dbt "+
                     	" (t_code1, t_code2,t_name,t_date_b,t_date_e) "+
				" values ( "+dlg.kod1+","+dlg.kod2+",'"+dlg.name+"',to_date('"+dlg.date_b+"','dd.mm.yyyy'),to_date('01.01.0001','dd.mm.yyyy'))";
             	Command = RSDCommand(CmdText);
           	Command.Execute();
	    	CmdText = "commit";
           	Command = RSDCommand(CmdText);
           	Command.Execute();
           end;
           if((dlg.date_e == date(0,0,0)) and (dlg.date_b == date(0,0,0)) )
      	   	 CmdText = " insert into dotdels_dbt "+
                     	" (t_code1, t_code2,t_name,t_date_b,t_date_e) "+
				" values ( "+dlg.kod1+","+dlg.kod2+",'"+dlg.name+"',to_date('01.01.0001','dd.mm.yyyy'),to_date('01.01.0001','dd.mm.yyyy'))";
             	Command = RSDCommand(CmdText);
           	Command.Execute();
	    	CmdText = "commit";
           	Command = RSDCommand(CmdText);
           	Command.Execute();
           end;


           ischanged=true; 

	    dlg.kod1 = 0;
	    dlg.kod2 = 0;
	    dlg.name = "";
           dlg.date_b = date(0,0,0);
	    dlg.date_e = date(0,0,0);

           return CM_Save;
       end;
   end;
   return CM_DEFAULT;
end;

/*********Скролинги***********************/

macro scroll_2 (id1,id2); //пользователи

  var CmdText,Command;
  var col = TArray;

  macro AddCol (ar,ind, fld, head, width, rdonly)
	ar.value (ind * 6)     = fld;
	ar.value (ind * 6 + 1) = head;
	ar.value (ind * 6 + 2) = width;
	ar.value (ind * 6 + 3 ) = 2;   // fldType
	ar.value (ind * 6 + 4 ) = -1;  // decPoint
	ar.value (ind * 6 + 5 ) = 0;   // reserv
  end;

  macro EvProc2 (RecordSet, Command, id, key )
      	if ((Command == DLG_KEY) and (key == 319))  //f5
	     	kod1 = RecordSet.value(0);
      		kod2 = RecordSet.value(1);
     		name = RecordSet.value(2);
		RunDialog (dlg_op, @Otd_dlg_oper);
          	if(ischanged)
                   return CM_Select;
              end;
                 
     	elif ((Command == DLG_KEY) and (key == 27))   // Esc
            	isexit2 = true;
              return cm_select;
	elif ((Command == DLG_KEY) and (key == 322))   //   F8
	       var CmdText,d_b, d_e;
	      	if(MSGBOXEX("Вы точно хотите удалить пользователя",MB_YES+MB_NO,IND_YES)==IND_YES)       ///////////// тут
       	       //debugbreak();
		if((recordSet.value(4) == "01.01.0001")
		   or (recordSet.value(4) == "01.01.0001 (00:00:00.00)")
		   or (recordSet.value(4) == ""))
				d_b = string("01.01.0001");
			else
				d_b = date(recordSet.value(4));
			end;
			//if(recordSet.value(5) == "01.01.0001 (00:00:00.00)")
         		if((recordSet.value(5) == "01.01.0001")
         		   or (recordSet.value(5) == "01.01.0001 (00:00:00.00)")
         		   or (recordSet.value(5) == ""))
				d_e = string("01.01.0001");
			else
				d_e = date(recordSet.value(5))
			end;
			
			CmdText = "delete from dop_otdel_dbt "+
		   		" where t_oper  = "+ RecordSet.value(2)+
                 		"   and t_code1 = "+ RecordSet.value(0)+
		   		"   and t_code2 = "+ RecordSet.value(1)+
				"  and  t_datebegin = to_date ('"+d_b+"','dd.mm.yyyy') "+
			    	"  and  t_dateend   = to_date ('"+d_e+"','dd.mm.yyyy') ";
		  //     msgbox(CmdText);
			Command = RSDCommand(CmdText);
			Command.Execute();

              	CmdText = "commit";
              	Command = RSDCommand(CmdText);
              	Command.Execute();
              	return cm_select;
		else
			return cm_cancel;
		end;
                            
	elif ((Command == DLG_KEY) and (key == 323))  //f9 ввод пользователя
		if(RecordSet.movenext)
			kod1 = RecordSet.value(0);
      			kod2 = RecordSet.value(1);
		else
			kod1 = id1;
			kod2 = id2;
		end;
		RunDialog (dlg_op, @Otd_dlg_oper_v);
		if(ischanged)
                   return CM_Select;
              end;
      	end;


  end;

  AddCol (col, 0, "t_code1", "Код 1", 6, true);
  AddCol (col, 1, "t_code2", "Код 2", 7, true);
  AddCol (col, 2, "t_oper", "ID", 7, true);
  AddCol (col, 3, "t_name", "Название", 30, true);
  AddCol (col, 4, "db", "Дата открытия", 10, true);
  AddCol (col, 5, "de", "Дата закрытия", 10, true);
 
                                                                                     //4            5
 CmdText = "SELECT op_ot.t_code1, op_ot.t_code2, pers.t_oper , pers.t_name, nvl(op_ot.t_datebegin, '01.01.0001') as db, nvl(op_ot.t_dateend, '01.01.0001') as de "+
          "FROM DOP_OTDEL_DBT op_ot,  dperson_dbt pers "+
          "WHERE op_ot.t_code1 = "+ id1 +
          "  and op_ot.t_code2 = "+ id2 +
          "  and  pers.t_oper = op_ot.t_oper "+
	   "   order by pers.t_oper";
//DEBUGBREAK();              
Command = RSDCommand(CmdText);
Command.Execute();
RecordSet = RSDRecordSet(Command, RSDVAL_CLIENT, RSDVAL_STATIC);
runScroll(RecordSet, 6, col, null, @EvProc2, "Пользователи", "~F5~ Редактирование  ~F9~ Ввод нового  ~F8~ Удалить запись  ", false);  

end; 



macro scroll_1 (idw);     // первая ветка

  var CmdText,Command;
  var col = TArray;

  macro AddCol (ar,ind, fld, head, width, rdonly)
	ar.value (ind * 6)     = fld;
	ar.value (ind * 6 + 1) = head;
	ar.value (ind * 6 + 2) = width;
	ar.value (ind * 6 + 3 ) = 2;   // fldType
	ar.value (ind * 6 + 4 ) = -1;  // decPoint
	ar.value (ind * 6 + 5 ) = 0;   // reserv
  end;

  macro EvProc1 (RecordSet, Command, id, key )
	if ((Command == DLG_KEY) and (key == 319))  //f5
		kod1  = RecordSet.value(0);
      		kod2  = RecordSet.value(1);
     		name  = RecordSet.value(2);
	   	if(RecordSet.value(3) == date(0,0,0))
			date1 = date(0,0,0);
		else
			date1 = RecordSet.value(3);
		end;
		if(RecordSet.value(4)==date(0,0,0))
			date2 = date(0,0,0);
	   	else
			date2 = RecordSet.value(4);
          	end;    
		RunDialog (dlg, @Otd_dlg1);
	  //	if(ischanged)
                   return CM_Select;
          //    end;
	elif ((Command == DLG_KEY) and (key == 32))   // пробел  (список пользователей)
		isexit2 = false;
		while(not isexit2)
             		scroll_2(RecordSet.value(0),RecordSet.value(1))  ;
		end;
     	elif ((Command == DLG_KEY) and (key == 27))   // Esc             //тут
            	isexit1 = true;
		
              return cm_select;
	elif ((Command == DLG_KEY) and (key == 322))  //f8 удаление подразделения
		var CmdText;
	     	if(MSGBOXEX("Вы точно хотите удалить подразделение||и всех привязанных к нему пользователей?",MB_YES+MB_NO,IND_YES)==IND_YES)
       	
			CmdText = "delete from dotdels_dbt "+
                 		"   where t_code1 = "+ RecordSet.value(0)+
				"     and t_code2 = "+ RecordSet.value(1);
			Command = RSDCommand(CmdText);
			Command.Execute();

              	CmdText = "commit";
              	Command = RSDCommand(CmdText);
              	Command.Execute();

			CmdText = "delete from dop_otdel_dbt "+
                 		"   where t_code1 = "+ RecordSet.value(0)+
		   	  	"     and t_code2 = "+ RecordSet.value(1);
			Command = RSDCommand(CmdText);
			Command.Execute();

              	CmdText = "commit";
              	Command = RSDCommand(CmdText);
              	Command.Execute();

			
              	return cm_select;
		else
			return cm_cancel;
		end;   


	elif ((Command == DLG_KEY) and (key == 323))  //f9 ввод подразделения
		if(RecordSet.movenext)
		     tmp1 = RecordSet.value(1);
		     tmp  = RecordSet.value(0);
		else
		     tmp1 = 0;
                   tmp3  = idw;
		end;
		RunDialog (dlg, @Otd_dlg_v);
		if(ischanged)
                   return CM_Select;
              end;
      	end;
  end;

  AddCol (col, 0, "t_code1",  "Код 1",         6,  true);
  AddCol (col, 1, "t_code2",  "Код 2",         7,  true);
  AddCol (col, 2, "t_name",   "Название",      30, true);    
  AddCol (col, 3, "t_date_b", "Дата открытия", 10, true);
  AddCol (col, 4, "t_date_e", "Дата закрытия", 10, true);

  //Gurin S. 21.07.2014 I-00502998-2
  CmdText = "SELECT t_code1 , t_code2, nvl(t_name,chr(1)) t_name, t_date_b, t_date_e "+
            "FROM dotdels_dbt "+
            "WHERE t_code1 = "+ idw+
            "  and t_code2 != 0 "+
	     "Order by t_code2 ";
              
  Command = RSDCommand(CmdText);
  Command.Execute();

  RecordSet = RSDRecordSet(Command, RSDVAL_CLIENT, RSDVAL_STATIC);
  runScroll(RecordSet, 5, col, null, @EvProc1, "Оргструктура", "~F5~ Редактирование  ~F9~  Ввод новой записи  ~Space~  Пользователи ", false);        
  return CM_select;    
end;


macro scroll ();  //    нулевая ветка
  var CmdText,Command;
  var col = TArray;
  macro AddCol (ar,ind, fld, head, width, rdonly)
    ar.value (ind * 6)     = fld;
    ar.value (ind * 6 + 1) = head;
    ar.value (ind * 6 + 2) = width;
    ar.value (ind * 6 + 3 ) = 2;   // fldType
    ar.value (ind * 6 + 4 ) = -1;  // decPoint
    ar.value (ind * 6 + 5 ) = 0;   // reserv
  end;
     macro EvProc (RecordSet, Command, id, key )
        if ((Command == DLG_KEY) and (key == 13)) // Enter
	     	isexit1 = false;
		while(not isexit1)
	       	scroll_1(RecordSet.value(0));
	     	end;
	elif ((Command == DLG_KEY) and (key == 27))   // Esc
            	isexit = true;
              return cm_select;
	elif ((Command == DLG_KEY) and (key == 321))  //f7    //редактирование
		ExecMacroFile("Arm_user2");
//      ViewFile ("..\\TxtFile\\arm_user2." + UserNumber()); GSP
		//main();
	elif ((Command == DLG_KEY) and (key == 319))  //f5    //редактирование
		RunDialog (dlg, @Otd_dlg);
              return cm_select;
      	elif ((Command == DLG_KEY) and (key == 323))  //f9 ввод подразделения
		RunDialog (dlg, @Otd_dlg_v);
              if(ischanged)
                   return CM_Select;
              end;
	elif ((Command == DLG_KEY) and (key == 322))  //f8 удаление подразделения
		var CmdText;
	     	if(MSGBOXEX("Вы точно хотите удалить подразделение, его подчинённые подразделения||и всех привязанных к ним пользователей?",MB_YES+MB_NO,IND_YES)==IND_YES)
       	
			CmdText = "delete from dotdels_dbt "+
                 		"   where t_code1 = "+ RecordSet.value(0);
			Command = RSDCommand(CmdText);
			Command.Execute();

              	CmdText = "commit";
              	Command = RSDCommand(CmdText);
              	Command.Execute();

			CmdText = "delete from dop_otdel_dbt "+
                 		"   where t_code1 = "+ RecordSet.value(0);
			Command = RSDCommand(CmdText);
			Command.Execute();

              	CmdText = "commit";
              	Command = RSDCommand(CmdText);
              	Command.Execute();
              	return cm_select;
		else
			return cm_cancel;
		end;   
      	end;   
     end;

  AddCol (col, 0, "t_code1", "Код 1", 6, true);
  AddCol (col, 1, "t_code2", "Код 2", 7, true);
  AddCol (col, 2, "t_name", "Название", 30, true);
  AddCol (col, 3, "t_date_b", "Дата открытия", 10, true);
  AddCol (col, 4, "t_date_e", "Дата закрытия", 10, true);

  CmdText = "SELECT t_code1 , t_code2, t_name , t_date_b, t_date_e "+
            "FROM dotdels_dbt "+
            "WHERE t_code2 = 0 "+
            "Order by t_code1 ";

  Command = RSDCommand(CmdText);
  Command.Execute();

  RecordSet = RSDRecordSet(Command, RSDVAL_CLIENT, RSDVAL_STATIC);
  runScroll(RecordSet, 5, col, null, @EvProc, "Оргструктура", "~Enter~  Выбор  ~F5~ Редактирование  ~F9~  Ввод новой записи  ~F7~ Отчет по пользователям", false);
end;


while (not isexit)
  scroll();
end;
exit(1);
          