/****************************************************************************/
/*                     R-Style SoftLab, RS-Bank V6                          */
/****************************************************************************/
/*         Смена ответственного по счетам, документам, картотекам           */                                                           
/*  Макрос: user_chg.mac                                                    */
/*  Создан:   17.06.09                                            Лапик А.А.*/
/*  Изменен:  05.07.2012 C-449-5                                 Гурин С. Н.*/
/*            03.07.2013 R-212987-2                              Gurin S.   */
/*            22.10.2013 I-00436398-2                            Gurin S.   */
/*            18.03.2014 I-00473070-2 Адаптация 2031             Gurin S.   */
/****************************************************************************/

Import BankInter, rsbdataset, "globals.mac";
import rsd;
import "cb_sql.mac";
import treport;
record Person     ("person.dbt");
record OldPerson  ("person.dbt");

/*08.10.2014 Gurin S. логгирование запуска*/
ExecmacroFile("lib_log.mac", "LogProcedure", "user_chg.mac");

//====================================редактировал Агеев С.В.
var path:string;
var WorkFiles, errCode;
var lbr_name="user_chg.lbr";

GetRegistryValue("BANK_INI\\ОБЩИЕ ПАРАМЕТРЫ\\ДИРЕКТОРИИ\\LBRDIR",2,path);
path = FindPath(lbr_name, path);
var dlg = TRecHandler("users2", path, TRUE);

GetRegistryValue("BANK_INI\\ОБЩИЕ ПАРАМЕТРЫ\\ДИРЕКТОРИИ\\WORKDIR", V_STRING, WorkFiles, errCode); // Gurin C-449-5
  if ( errCode > 0 )
    msgbox("Проверьте наличие настройки: BANK_INI\\ОБЩИЕ ПАРАМЕТРЫ\\ДИРЕКТОРИИ\\WORKDIR");
    return false;
  end;
//===========================================================

/* Номер узла териториальной структуры */ //Gurin C-449-5
private macro GetName(code)
var sql, cmd, rs; 

    sql = " SELECT t_name "
          " FROM ddp_dep_dbt "
          " WHERE t_code = :code ";

    cmd = RSDCommand(sql);
    cmd.AddParam ("code", RSDBP_IN, code);
    cmd.execute;
    rs = RSDRecordset (cmd);

    while (rs and rs.movenext())
        return(rs.value("t_name"));
    end;
end;

MACRO dialog_obr(dlg, cmd, id, key);
	message(" ~ESC~ Выход   ~F2~ Сменить ответственных   ~F3~ Выбор операциониста из справочника");
	var CmdText, command;
       var name1, name2;


/* переменные для вывода списка измененных счетов */
var zapros :RSDRecordset;
var SQLQuery :string  = "";
var counter  :integer = 0;
var i=0;
/* окончание переменных для вывода списка измененных счетов */


	if ((key == 317) and (id == 0))
		listoper(OldPerson);
              dlg.rec.User_old = Oldperson.oper;
		dlg.rec.fio      = Oldperson.name;
		name1        = person.name;
              UpdateFields(dlg);
	elif ((key == 317) and (id == 2))
		listoper(Person);
              dlg.rec.User_new = person.oper;
		dlg.rec.fionew   = person.name;
		name2        = person.name;

              UpdateFields(dlg);
	elif (key == 316)
		if ((dlg.rec.User_old == 0) and (dlg.rec.User_new == 0)) 
		msgbox("Необходимо заполнить все поля!");
		/*elif ((dlg.rec.User_old == dlg.rec.User_new))                         //Gurin C-449
		msgbox("Номера старого и новых пользователей не должны совпадать");*/
		else 
	        
                var sql = " SELECT count(t_account) "
                          " FROM daccount_dbt "
                          " WHERE t_oper =:old_oper"
                          " and t_open_close != 'З'";

                var cmd_ = RSDCommand(sql);
                    cmd_.AddParam ("old_oper", RSDBP_IN,dlg.rec.user_old);
                    cmd_.execute;
                var rs = RSDRecordset(cmd_);

                    while (rs and rs.movenext())
                        var sql1 = " SELECT t_account, t_client, t_nameaccount "
                                   " FROM daccount_dbt "
                                   " WHERE t_oper =:old_oper"
                                   " and t_open_close != 'З'";
                        var cmd1 = RSDCommand(sql1);
                            cmd1.AddParam ("old_oper", RSDBP_IN, dlg.rec.user_old);
                            cmd1.execute;
                        var rs1 = RSDREcordset(cmd1);

                        //InitProgress(int(rs.value(0))," ~Ctrl-Brk~ Прервать", "Смена ответственного пользователя" );

                        RslDefCon.BeginTrans(); 
                        BegAction(10, "Ждите, идет обработка...",true);
                        while (rs1 and rs1.movenext()) 
                           // i=i+1;
                        //UseProgress( i );

                            CmdText = " Begin "                                                      +
                                      " UPDATE daccount_dbt "                                        +
                                      " SET t_branch = (SELECT t_codedepart "                        +
                                      "                                 FROM dperson_dbt "           +
                                      "                                 WHERE t_oper =?) "           +
                                      " WHERE t_oper =?"                                             +
                                      " AND t_account =?;"                                           +
                                     
                                      //" UPDATE daccount$_dbt "                                       +
                          	          //" SET t_branch = (SELECT t_codedepart "                        +
                              	   //"                                 FROM dperson_dbt "           +
                              	   //"                                 WHERE t_oper =?) "           +
                                      //" WHERE t_oper =?"                                             +
                                      //" AND t_account =?;"                                           +
                                      
                                      " UPDATE daccount_dbt "                                        +
       	                        " Set t_oper = ? "                                             +
              	                 " Where t_oper = ? "                                           +
                                      " AND t_account =?;"                                           +

                                      //" UPDATE daccount$_dbt "                                       +
       	                        //" Set t_oper = ? "                                             +
              	                 //" Where t_oper = ? "                                           +
                                      //" AND t_account = ?;"                                          +

                                      " UPDATE dsfcontr_dbt "                                        +
                                      " SET t_branch = (SELECT t_codedepart "                        +
                                      "                 FROM dperson_dbt "                           +
                                      "                 WHERE t_oper =?)"                            +
                                      " WHERE t_object = ?"                                          +
                                      " AND EXISTS (SELECT 1 "                                       +
                                      "             FROM dsfcontr_dbt "                              +
                                      "             WHERE t_object = ?);"                            +

                                      " UPDATE dclient_dbt "                                         +
                                      "    SET t_oper = ? "                                          +
                                      "  WHERE t_partyid = (SELECT DISTINCT(t_client) "              +
                                      "                               FROM daccount_dbt "            +
                                      "                              WHERE t_account = ? "           +
                                      "                                    and t_oper = ?); "        + 
                                      " end;";                                                       
                             
	                     Command = RSDCommand(CmdText);
                            Command.AddParam ("1", RSDBP_IN,dlg.rec.user_new);
                            Command.AddParam ("2", RSDBP_IN,dlg.rec.user_old);
                            Command.AddParam ("3", RSDBP_IN,rs1.value(0));
                            //Command.AddParam ("4", RSDBP_IN,dlg.rec.user_new);
                            //Command.AddParam ("5", RSDBP_IN,dlg.rec.user_old);
                            //Command.AddParam ("6", RSDBP_IN,rs1.value(0));
                            Command.AddParam ("7", RSDBP_IN,dlg.rec.user_new);
                            Command.AddParam ("8", RSDBP_IN,dlg.rec.user_old);
                            Command.AddParam ("9", RSDBP_IN,rs1.value(0));
                            //Command.AddParam ("10", RSDBP_IN,dlg.rec.user_new);
                            //Command.AddParam ("11", RSDBP_IN,dlg.rec.user_old);
                            //Command.AddParam ("12", RSDBP_IN,rs1.value(0));
                            Command.AddParam ("13", RSDBP_IN,dlg.rec.user_new);
                            Command.AddParam ("14", RSDBP_IN,rs1.value(0));
                            Command.AddParam ("15", RSDBP_IN,rs1.value(0));
                            Command.AddParam ("16", RSDBP_IN,dlg.rec.user_new);
                            Command.AddParam ("17", RSDBP_IN,rs1.value(0));
                            Command.AddParam ("18", RSDBP_IN,dlg.rec.user_old);
           	              Command.Execute(); 
                        end;
                        RslDefCon.CommitTrans();
                         EndAction(10);
                        //RemProgress();
                    end;
                  
/* вывод списка измененных счетов */
var TxtFileDir = WorkFiles; //Gurin C-449-5
var TxtFileName = TxtFileDir + "\\protocol2." + String({oper});

SetOutPut(TxtFileName + ".txt", false);
[
		Результат смены ответственного исполнителя:
                                                               опер      Ф.И.О.
		По счетам ответственный исполнитель сменен с   ##### ##########################
              						  на   ##### ##########################
              Дата ##########, время ########, операционист #####
             ](dlg.rec.user_old, dlg.rec.fio, dlg.rec.user_new, dlg.rec.fionew, date, time, {oper});

             var table = CTableReport;
                 //Gurin C-449-5
                 table.addcolumn("Переданные счета",23, AL_CENTER); 
                 table.addcolumn("Клиент",8, AL_CENTER);
                 table.addcolumn("Название счета",55, AL_LEFT);
                 table.addcolumn("Старый номер узла ТС",20, AL_CENTER);
                 table.addcolumn("Новый номер узла ТС",20, AL_CENTER);
                 table.addcolumn("Старый № отв. исполн.",20, AL_CENTER);
                 table.addcolumn("Новый № отв. исполн.",20, AL_CENTER);
                 table.printhead("");
      
                 SQLQuery = " select t_account, t_client, t_nameaccount, t_oper, t_branch" +
	                     " from daccount_dbt"+
		              " Where t_oper = "+ dlg.rec.user_new+
                            " and t_open_close != 'З'"
		              " order by t_account ";

         	   zapros = RSDRecordset(RsdCommand(SQLQuery)); /*результат запроса*/
                     //InitProgress(int(rs.value(0))," ~Ctrl-Brk~ Прервать", "Формирование протокола" );
                     //Gurin C-449-5
                     BegAction(10, "Ждите, формируется протокол...");
	              while (zapros.moveNext)
                     //UseProgress( counter );
                        table.printstringtransferbyword(zapros.value(0), zapros.value(1), zapros.value(2), GetName(OldPerson.codedepart), GetName(zapros.value(4)), OldPerson.oper, zapros.value(3));
                        counter = counter + 1;
                     end;                                                                                            
                     //RemProgress();
                     EndAction(10);
                 table.printbottom();

                 println(" Всего передано счетов:" + counter);
                 msgbox("Создан файл ", "protocol2." + String({oper}), ".txt в каталоге ", TxtFileDir);

                 SetOutput (NULL, true);
                 ViewFile(TxtFileName + ".txt");                 

		return CM_SAVE;
		end;		
       end;
  
END;

RunDialog (dlg, @dialog_obr);

//exit(1);





