// -------------------------------------------------------------------------------------------------
// @filename: lib_party.mac
// @author  : 2013-02-19 zip_z. 
// @desc    : библиотека процедур для работы с субъектами экономики
// @changes : none
// -------------------------------------------------------------------------------------------------

const PT_NAME_EMPTY = ""; // наименование не задано

// @desc: получить полное имя субъекта
macro PT_GetPartyName (clientid:integer):string
    var ret = PT_NAME_EMPTY;
    var sql = "select t_name from dparty_dbt where t_partyid = :id";
    sql = execSqlSelect (sql, makeArray (SqlParam ("id", clientid)));
    if (sql.moveNext ())
        ret = sql.value ("t_name", null, V_STRING);
    end;
    return ret;
end;


// @desc: получить дополнительное (вида nametypeid) имя субъекта
macro PT_GetPartyNameAdd (clientid:integer, nametypeid:integer):string
    var ret = PT_NAME_EMPTY;
    var sql = "select t_name from dpartyname_dbt where t_partyid = :id and t_nameTypeId = :nametypeid";
    sql = execSqlSelect (sql, makeArray (SqlParam ("id", clientid), SqlParam ("nametypeid", nametypeid)));
    if (sql.moveNext ())
        ret = sql.value ("t_name", null, V_STRING);
    end;
    return ret;
end;