/************************************************************************/
/*          Автоматизированная банковская система RS-Bank v6.0          */
/*                                                                      */
/*               Copyright (c) R-Style Ukraine                          */
/*                                                                      */
/*  Имя файла        : R_DocDay505.mac                                  */
/*                                                                      */
/*  Описание         : Контрольная ведомость по операциям               */
/*	                 (Документы конвертации)                        */
/*                                                                      */
/*  Программист      : Ойкин В.А                                        */
/*                                                                      */
/*  Создан           : 13.08.2008                                       */
/*                                                                      */
/************************************************************************/


import "Rep_DocDay.mac";

var RepFileName;

RepFileName = "..\\txtfile\\DocDay575." + UserNumber();
NameRep = "Баланс\\Документы конвертации";

if (RunDialog(dlg,"HandleEvent"))
          if(NumDepart == "")
            Report5(RepFileName,"","","Баланс\\Документы конвертации"," not in('30110', '30114', '30115') and (tad.T_BALANCE like 'ОВП%' or tak.T_BALANCE like 'ОВП%') ",1);
	   else
            Report7(RepFileName,"","","Баланс\\Документы конвертации"," not in('30110', '30114', '30115') and (tad.T_BALANCE like 'ОВП%' or tak.T_BALANCE like 'ОВП%') ",1);
	   end;	
end;

exit(1);