//-----------------------------------------------------------------------------
// Назначение: Макрос выгрузки платежей для загрузки в АСВКБ 
// Описание  : для Пробизнесбанка
// Авторы    : Стручков А.Тихомиров А. 19.12.2008
//-----------------------------------------------------------------------------

//11.07.2012 vihrov C-12122 смена диапазонов кодовASVKB.mac
// KS 22.11.2013 Предварительная адаптация под 31ю сборку
// DPN 30.04.2014 C-28764-6 - Шестизначная нумерация ВУЗ

import "pm_note.mac",Rsbdataset;
import payminter, oralib, globals;

Import "fg_Life_parm.mac"; //14.08.2012 vihrov смена кодов

private var cod_in_asvkb:string = ""; //14.08.2012 vihrov смена кодов
private var fgBank1;  //14.08.2012 vihrov смена кодов

private var {CurDate};

macro ASVKB(Pmpaym,pmrmprop,pmco,режим,Macros,ZachSpis,account,flV)
record pmprop("pmprop");
var PaymentObj:Rsbpayment=Rsbpayment(Pmpaym.paymentId);
record ctg( "objattr" );//для записи категории
var i=0;
var sumPoCodam:money;//сумма по нескольким кодам\паспортам сделок
var Oldstr,NewStr,ObrStr,pos=1,
 posVO, sep=";",flag=0, sepVO="{",
da,noteV,err_mes,count,
cod643,AcNer,SumValContr,ObrStr1,posVO1, path;
If (Macros==1)
ElIf(Macros==2)
ElIf(Macros==3)
ElIf(Macros==4)
End;

getRegistryValue("PS\\REQOPENACC\\173-ФЗ СЧЕТА НЕРЕЗИДЕНТОВ\\ПУТЬ К ФАЙЛУ OPLATA.D",V_string,path);
path=path+"Oplata.d";
paymentobj.Categories.GetFirst( 117, {curdate}, ctg );

//Возвращает 5тизначный код ВО
private macro GetCodVO(element:integer)
  var query:string = "select t_code from dllvalues_dbt where t_list=1805 and t_element=" + element;
  var rs:RsdRecordset = execSQLselect(query);
  if( rs.moveNext() )
    return rs.Value(0);
  else
  msgbox("Ошибка получения ");
   return "";
  end;
end;
//Возвращает код валюты и заменяет 810 на 643
private macro GetFiCod(fi:integer)
if( fi==-1)
return "643";//Проверить
End;
  var query:string = "select t_fi_code from dfininstr_dbt where t_fiid=" + fi;
  var rs:RsdRecordset = execSQLselect(query);
  if( rs.moveNext() )
   If(rs.Value(0)==810)
   cod643="643";
      return Cod643;
   else
     return rs.Value(0);
   End;
  else
  msgbox("Ошибка получения кода валюты!");
   return "";
  end;
end;
//Возвращает числовой код(3) страны нерезидента или 643
private macro GetNrCC(ZS:integer)
  var query:string;
  var rs:RsdRecordset;
  var BankID:integer;
  
  if (ZS==1)  // Tikh Проверяем по дт счету и вставляем его
 BankID=pmpaym.receiverbankID;
  else
 BankID=pmpaym.payerbankID;
end;
 query = "select T_NRCountry from dparty_dbt where t_partyID=" + BankID;
 rs = execSQLselect(query);

  if( rs.moveNext() )
   if (rs.Value(0)=="")
   return"643";
   end;
    return rs.Value(0);
  else
  msgbox("Ошибка получения кода СВИФТ");
   return "";
  end;
end;

private macro Get1Code_xvost(ZS:integer)
    var query:string;
    var rs:RsdRecordset;
    var Subj;
    if (ZS==1)
        Subj=pmpaym.receiver;
    elif(ZS==2)
        Subj=pmpaym.payer;
    end; 
//query = "select t_code "+
//query = "select ltrim(substr(t_code, 7),0) "+  //14.08.2012 vihrov C-12122 смена диапазонов кодов
//"from dobjcode_dbt pa  "+
//"where pa.t_codekind=1 and pa.T_OBJECTID ="+subj ;
//"where pa.t_codekind=1 and and pa.t_objecttype = 3 and pa.t_state = 0 and pa.T_OBJECTID ="+subj ; //14.08.2012 vihrov C-12122 смена диапазонов кодов

//30.04.2014 C-28764-6 DPN  - Шестизначная нумерация ВУЗ
    query = " select substr(t_code, length(t_code)-5) " +
            " from dobjcode_dbt pa " +
            " where pa.t_codekind=1 " +
            " and pa.t_objecttype = 3 " +
            " and pa.t_state = 0 " +
            " And TRANSLATE (pa.T_CODE, '_0123456789/ ', '_') IS NULL ";  


rs = execSQLselect(query);
if( rs.moveNext() )
if (rs.Value(0)=="")
    return "0000!"; //ну нет кода((( - надо искать
end;
//return rs.Value(0);
return string(rs.Value(0)); //14.08.2012 vihrov C-12122 смена диапазонов кодов
else
SetOutput(null,true); 
println("клиент ",subj," -  Ошибка получения кода 1"); //не отработал запрос
SetOutput(path,true); 
return "000!!";
end;
end;//macro


private macro cod_iz_c4eta(c4:string) : bool
	private var ds = trsbdataset ("select 1 from dobjatcor_dbt where t_objecttype = 4 and t_groupid = 110 and t_object = '010000000'||'" + c4 + "'");
	if (ds and ds.movenext())
		return true;
	else
		return false;
	end;
onerror(e)
	msgbox("ошибка запроса категории \n"+e.message);
	exit(0);
end;

/*private macro day_cod_iz_c4eta(c4:string) : string

	private macro new_client(x:string) : bool
		private var den_x:date = date("29.09.2012");
		private var sql = "SELECT	LENGTH (LTRIM (SUBSTR (t_code, 3), '0')) " + 
      "  FROM	dobjcode_dbt, daccount_dbt " +
      " WHERE	t_objectid = t_client AND t_objecttype = 3 AND t_codekind = 1 AND t_state = 0 AND t_account = '" + x + "' " ;
		private var ds = trsbdataset(sql);
		if (ds and ds.movenext())
			if (ds.value(0) <= 5)
				return false;
			elif (ds.value(0) == 6)
				return true;
			else
				msgbox(" для клиента по счету " + x + " код вида 1 имеет длину больше шесть знаков. останавливаюсь. вернулся код " + ds.value(0));
				exit(0);
			end;
		else
			msgbox("для клиента по счету " + x + " не найден код вида 1. останавливаюсь.");
			exit(0);
		end;
	end;

	if ((int(substr(c4, 1, 5)) >= 40107) and (int(substr(c4, 1, 5)) <= 40807)) //можно вначале проверить старый клиент (тогда выхгрузить 5 с хвоста) или новый, тогда принадлежность к балансовому рассмотреть. будет покороче маленько, но переписывать лень.
		if (new_client(c4))
			return substr(c4, 15);
		else
			return substr(c4, 16);
		end;
	else
		if (new_client(c4))
			return (substr(c4, 12, 1) + substr(c4, 16));
		else
			return substr(c4, 16);
		end;
	end;
end;*/

//30.04.2014 C-28764-6 DPN  - Шестизначная нумерация ВУЗ
private macro day_cod_iz_c4eta(c4:string) : string
    var  cod:string;
    private macro new_client(x:string,cod_1:string) : bool
        private var den_x:date = date("29.09.2012");
        private var sql = " SELECT LENGTH (LTRIM (SUBSTR (t_code, 3), '0')), SUBSTR (t_code, length(t_code)-5) " + 
                          " FROM dobjcode_dbt, daccount_dbt " +
                          " WHERE t_objectid = t_client AND t_objecttype = 3 AND t_codekind = 1 AND t_state = 0 AND t_account = '" + x + "' " ;
        private var ds = trsbdataset(sql);
        if (ds and ds.movenext())
            if (ds.value(0) <= 6)
                cod_1 =ds.value(1);
                setParm(1, cod_1);
                return true;
            else               
                msgbox(" для клиента по счету " + x + " код вида 1 имеет длину больше шесть знаков. останавливаюсь. вернулся код " + ds.value(0));
                return false;
                exit(0);
            end;
        else
            msgbox("для клиента по счету " + x + " не найден код вида 1. останавливаюсь.");
            exit(0);
        end;
    end;

    if ((int(substr(c4, 1, 5)) >= 40107) and (int(substr(c4, 1, 5)) <= 40807))
        if (new_client(c4,cod))
            return cod;
        end;
    else
        if (new_client(c4, cod))
            return (substr(c4, 12, 1) +substr(cod, 2));
        end;
    end;
end;

private macro Code350(pass,Cvo)  //Tikh Проставление 18 позиции, если валютная операция, то ставим
        
     var PS, fl=1,code,PosCode=0;
     var Passf=pass;
  
 debugbreak;
if (Cvo=="{35010}")                       //Tikh Для Примечаний
  
     while (fl!=0)
     PS=index(pass,"/");
     PosCode=PosCode+PS;
     if(Ps!=0)
       pass=substr(pass,Ps+1);
     else
       Code=substr(Passf,PosCode-1,1);
       fl=0;
     end;
     end;

      return Code;
    
   elIf (Cvo=="{35020}")                   
     while (fl!=0)                         
     PS=index(pass,"/");
     PosCode=PosCode+PS;
     if(Ps!=0)
       pass=substr(pass,Ps+1);
     else
       Code=substr(Passf,PosCode-1,1);
       fl=0;
     end;
     end;

      return Code;
    else
      return " "; 
   
   end;
END;

private macro Code990(Cvo)  //Tikh Проставление 18 позиции, если валютная операция, то ставим
     
  if (Cvo=="{99010}") 
      return int(ReadNoteForPayment(paymentObj.paymentID,115))//Берем 115 примечание
    else
      return " "; 
   end;
END;

private macro BankID(ZS) //Tikh Название банка

if (ZS==1)  
    return pmrmprop.payerbankname;
  else
    return pmrmprop.receiverbankname;
end;
END;

private macro SWIFT(ZS)   //Str!
var IDBankaN;
 if (ZS==2)  // Str! определяем чей СВИФТ код берем (Списание=получателя)
 IDBankaN=pmpaym.receiverbankID;
  else
 IDBankaN=pmpaym.payerbankID;
end;  
  var sql="SELECT t_code FROM dobjcode_dbt WHERE t_codekind = 6 AND T_ObjectId="+IDBankaN;
  var rs:RsdRecordset = execSQLselect(sql);
  if( rs.moveNext() )
    return rs.Value(0);
  else
   return "";
  end;
end;




private macro HPID(SWIFT,ZS) //Str! Определяем поля 25 от 24
var IDBankaN;
if (ZS==2)  // Str! определяем чей СВИФТ код берем (Списание=получателя)
 IDBankaN=pmpaym.receiverbankID;
  else
 IDBankaN=pmpaym.payerbankID;
end;  
 
var sql="select T_notresident from dparty_dbt where T_PartyID="+IDBankaN;
var rs:RsdRecordset = execSQLselect(sql);
IF(SWIFT=="");

  if( rs.moveNext() )
   If (rs.Value(0)=="X");
   return "НР"  //для нерезидентов без СВИФТА
   Else
   return " ";  //для резидентов
   End;
  else
  msgbox("Ошибка определения резедентности");
  return " ";   //для тех кто не может определиться с резедентностью)))
  end;

  
Else
return " "; //если СВИФТКод заполнен
End;
END;//macro



private macro CodeW //Tikh Забираем категорию 402Ф

paymentobj.Categories.GetFirst(3,{curdate},ctg);
return ctg.nameobject;

END;

Private Macro SumVal(Sum,Cour)   //Tikh Макрос для расчета суммы валюты для вида валютной операции
 if (Cour==0)
 return Sum;
 end;
  Return Sum*double(Cour);  
End;


Private Macro SwiftCode // Tikh Отбираем код Swift для платежа (референс)
  var SW="";
  var sl;
  var DataS;            //Tikh Ищем последний референс Swift

 sl = "select dwlmes_dbt.t_Trn,dpmpaym_dbt.t_PaymentID from dwlpm_dbt, dpmpaym_dbt, dwlmeslnk_dbt, dwlmes_dbt"+ 
   " where dwlpm_dbt.t_PaymentID = dpmpaym_dbt.t_PaymentID"+
" and dwlpm_dbt.t_WlPmNum = 0"+
" and dwlpm_dbt.t_Direct = CHR(0)"+
" and dwlmeslnk_dbt.t_ObjKind = 501"+
" and dwlmeslnk_dbt.t_ObjID = dwlpm_dbt.t_WlPmID"+
" and dwlmeslnk_dbt.t_MesID = ( select max(l2.t_MesID)"+
                              "  from dwlmeslnk_dbt l2"+
                              "  where l2.t_ObjKind = 501"+
                              "  and l2.t_ObjID = dwlpm_dbt.t_WlPmID )"+ 
" and dwlmes_dbt.t_MesID = dwlmeslnk_dbt.t_MesID";
      
      DataS = TRsbDataSet(sl);

   while (DataS.movenext())
       if (DataS.PaymentID==pmpaym.PaymentID)
    SW=dataS.Trn;
  end;
  end;
  if (SW!="")
    return SW;                   //Tikh Если код есть, возвращаем
   else 
    return pmrmprop.number;      //Tikh Если кода нет, то номер ПП
  end;

END;


Private Macro Note(Nota)
       If (nota!="")
          return nota;
         else
          return " ";
       end;
END;


SetOutput(path,true);


//Проверка суммы платежей
//формат строки Паспорт_сделки или 0{код_валютной операции5}сумма; код из панели не используется
/* Считать примечание 111 Платежа при обнаружении там "{"
разбиваем ее на паспорт, код и сумму по ним*/

sumPoCodam=0;
Oldstr=ReadNoteForPayment(paymentObj.paymentID,111);
//нашли разделитель делим строку
if(index(Oldstr,sep)>0)
flag=1;
end;

While(Flag!=0)
     Pos=index(Oldstr,Sep); //ищем разделитель ; в остатке строки
     PosVO=index(Oldstr,SepVO);   //и второй там же (что бы длинна поаспорта нас не волновала)
     if(Pos!=0)
 ObrStr=substr(OldStr,1,Pos-1);
 OldStr=substr(OldStr,Pos+1);       //остаток строки на новый круг
//паспорт, код и сумма

ObrStr1=substr(ObrStr,PosVO);
PosVO1=index(Obrstr1,SepVO);
While (PosVO1!=0)
PosVO1=index(Obrstr1,SepVO);

sumPoCodam=sumPoCodam+money(substr(ObrStr1,PosVO1+7)); //Tikh Считаем сумму//Поправил

ObrStr1=substr(ObrStr1,index(ObrStr1,"{")+1);
PosVO1=index(Obrstr1,SepVO);
End;//wh
     else
        Flag=0;//когда в остатке строки не нашли разделителя(строка кончиться) - разбор закончен
     end;  
End;
If (sumPoCodam!=0)
 If (sumPoCodam!=pmpaym.amount)
Msgbox("Сумма не верна!"+" В Примечаниях "+sumPoCodam+", в платеже "+pmpaym.amount); //Не знаю, что банку требуется.Напечатать вернуть пусто? Пока так
SetOutput(path,true);
println("Ошибка выгрузки платежа №"+pmrmprop.number+". Сумма платежа не совпадает с суммой кодов ВО");
SetOutput(null,true);
return 0;
End;  
End;  

// Tikh Теперь создаем файл выгрузки

//Анализируем плательщика

Oldstr=ReadNoteForPayment(paymentObj.paymentID,111);
//нашли разделитель делим строку

if(index(Oldstr,sep)>0)
flag=1;                        //Сначала для платежей с Alt+V


While(Flag!=0)
     Pos=index(Oldstr,Sep); 
     PosVO=index(Oldstr,SepVO);   
     if(Pos!=0)
 ObrStr=substr(OldStr,1,Pos-1);
 OldStr=substr(OldStr,Pos+1);       

ObrStr1=substr(ObrStr,PosVO);
count=0;
PosVO1=index(Obrstr1,SepVO);
While (PosVO1!=0)

SetOutput(path,true);

PosVO1=index(Obrstr1,SepVO);

// нужна ли Проверка?: паспорт == 0, то паспорт=" " ?


//debugbreak;
                    cod_in_asvkb = substr(account,16); //14.08.2012 vihrov смена кодов
                    fgBank1 = fg_life_subject({OurBank});  //14.08.2012 vihrov смена кодов

					if (fgBank1.is_prbb) //14.08.2012 vihrov смена кодов
						if (cod_iz_c4eta)
							cod_in_asvkb = day_cod_iz_c4eta(account);
						else
							cod_in_asvkb = get1code_xvost(ZachSpis);
						end;
					end;


println(strsubst(
/*substr(account,16)+
//Базовый идентификатор Клиента Банка  pmpaym.payer,косо, надо КОД из 5.0 
*/
cod_in_asvkb+ //только 5тизначная концовка, равная коду из 5.00, вообще то нужен весь
//Направление платежа:
//1 - зачисление/2 - списание
"#"+ZachSpis+
//Номер счета
"#"+account+
//"#"+GetCodVO(pmco.VO_code)+              Для ALT+V
"#"+string(substr(ObrStr1,PosVO1+1,5))+     //Tikh Для примечания
"#"+GetFiCod(pmpaym.fiid)+
//"#"+pmpaym.amount+                       Для Alt+V
"#"+money(substr(ObrStr1,PosVO1+7))+      //Tikh Для Примечания
"#"+GetFICod(pmco.contractfiid)+
"#"+SumVal(money(substr(ObrStr1,PosVO1+7)),ReadNoteForPayment(paymentObj.paymentID,116))+
//код страны банка*
"#"+GetNrCC(ZachSpis)+
//"#"+pmco.passportnumber+                 Для Alt+V
"#"+ string(substr(ObrStr,1,PosVO-1))+     //Tikh Из примечания
"#"+string(pmrmprop.date:f)+
"#"+pmrmprop.number+
"#"+string(pmpaym.valuedate:f)+
"#"+SwiftCode+                            //Tikh для РУБ 11 поле для ВАЛ нужен референс из СВИФТовки
"#"+" "+                                   //_15_ не используется
"#"+Note(ReadNoteForPayment(paymentObj.paymentID,119))+       //  Примечание
"#"+pmrmprop.ground+
"#"+Code350(string(substr(ObrStr,1,PosVO-1)),string(substr(ObrStr1,PosVO1,7)))+  //разобрать паспорт и выбрать цифру перед четветым символом "/"
"#"+Code990(string(substr(ObrStr1,PosVO1,7)))+                             //Примечание 105, если 99010
"#"+" "+                                 //Код страны банка-нерезидента - пусто
"#"+ctg.nameObject+                      //Поле21 - подумать
"#"+BankID(ZachSpis)+                    //Просто для банка Swift для банка
/*"#"+PaymentObj.payerName+        // ? пока так

"#"+PaymentObj.ReceiverBankName+ */
"#"+" "+                                 //только в ББ PaymentObj.PayerBankCode
"#"+Swift(ZachSpis)+                               //свифтовый код
"#"+HPID(Swift(ZachSpis),ZachSpis)+                                //"НР", если нет свифтового кода
"#"+pmpaym.paymentId+
"#"+" "+                                 //ИНН иностранного, не надо
"#"+string(pmprop.transferdate:f)+
"#"+GetFiCod(pmprop.payfiid)+
"#"+SumVal(money(substr(ObrStr1,PosVO1+7)),ReadNoteForPayment(paymentObj.paymentID,117))+ //30 Сумма в валюте корр счета
"#"+CodeW+                               //31 Код вида 402Ф
"#"+Note(ReadNoteForPayment(paymentObj.paymentID,112))+                                 //32 Направление платежа для формы
"#"+Note(ReadNoteForPayment(paymentObj.paymentID,113))+  //Примечание для формы
"#"+Note(ReadNoteForPayment(paymentObj.paymentID,114))+  // Примечание для нужд банка
"#"+Note(ReadNoteForPayment(paymentObj.paymentID,118))+"#" // Дата предоставления справки
 ,"##","# #"));                          //там где нет ничего ставим пробел

 
ObrStr1=substr(ObrStr1,index(ObrStr1,"{")+1);
PosVO1=index(Obrstr1,SepVO);

End;//wh
     else
        Flag=0;//когда в остатке строки не нашли разделителя(строка кончиться) - разбор закончен
     end;  
 End;
SetOutput(null,true);
   msgbox("Выгружено в файл Oplata.d по операциям в примечаниях");


   else //Если примечание пустой, анализируем Alt+V

   debugbreak;

if (pmco.VO_code==0)  //Анализируем Alt+V, если пусто уточняем
 if (flV==0)   
msgbox("Не выгружен из-за отсутствия кодов ВО");
SetOutput(null,true);  
  return 0; 
  end;
end;

debugbreak;
                    cod_in_asvkb = substr(account,16); //14.08.2012 vihrov смена кодов
                    fgBank1 = fg_life_subject({OurBank});  //14.08.2012 vihrov смена кодов
               // DPN 30.04.2014 C-28764-6 - Шестизначная нумерация ВУЗ
					if (fgBank1.is_prbb or fgBank1.is_VUZ) //14.08.2012 vihrov смена кодов
						if (cod_iz_c4eta(account))
							cod_in_asvkb = day_cod_iz_c4eta(account);
						else
							cod_in_asvkb = get1code_xvost(ZachSpis);
						end;
					end;


println(strsubst(
//Базовый идентификатор Клиента Банка  pmpaym.payer,косо, надо КОД из 5.0

//substr(account,16)+      
cod_in_asvkb+  //11.07.2012 vihrov C-12122 смена диапазонов кодов
//Направление платежа:
//1 - зачисление/2 - списание
"#"+ZachSpis+
//Номер счета
"#"+account+
"#"+GetCodVO(pmco.VO_code)+             // Для ALT+V
//"#"+string(substr(ObrStr1,PosVO1,7))+     //Tikh Для примечания
"#"+GetFiCod(pmpaym.fiid)+
"#"+pmpaym.amount+                      // Для Alt+V
//"#"+money(substr(ObrStr1,PosVO1+7))+      //Tikh Для Примечания
"#"+GetFICod(pmco.contractfiid)+
"#"+SumVal(pmpaym.amount,ReadNoteForPayment(paymentObj.paymentID,116))+      //Здесь передаем на весь платеж
//код страны банка*
"#"+GetNrCC(ZachSpis)+
"#"+pmco.passportnumber+               //  Для Alt+V
//"#"+ string(substr(ObrStr,1,PosVO-1))+     //Tikh Из примечания
"#"+string(pmrmprop.date:f)+
"#"+pmrmprop.number+
"#"+string(pmpaym.valuedate:f)+
"#"+SwiftCode+                       //для РУБ 11 поле для ВАЛ нужен референс из СВИФТовки
"#"+" "+                                   //_15_ не используется
"#"+pmco.contractnumber+                   
"#"+pmrmprop.ground+
"#"+Code350(pmco.passportnumber,"{"+GetCodVO(pmco.VO_code)+"}")+  //разобрать паспорт и выбрать цифру перед четветым символом "/"
"#"+Code990("{"+GetCodVO(pmco.VO_code)+"}")+                             //Примечание 105, если 99010 Здесь передаем для Alt+V
"#"+" "+                                 //Код страны банка-нерезидента - пусто
"#"+ctg.nameObject+                      //Поле21 - подумать
"#"+BankID(ZachSpis)+                    //Просто для банка Swift для банка
"#"+" "+                                 //только в ББ PaymentObj.PayerBankCode
"#"+Swift(ZachSpis)+                               //свифтовый код
"#"+HPID(Swift(ZachSpis),ZachSpis)+                                //"НР", если нет свифтового кода
"#"+pmpaym.paymentId+
"#"+" "+                                 //ИНН иностранного, не надо
"#"+string(pmprop.transferdate:f)+
"#"+GetFiCod(pmprop.payfiid)+
"#"+SumVal(pmpaym.amount,ReadNoteForPayment(paymentObj.paymentID,117))+ //30 Сумма в валюте корр счета. Здесь на весь платеж
"#"+CodeW+                               //31 Код вида 402Ф
"#"+Note(ReadNoteForPayment(paymentObj.paymentID,112))+                                 //32 Направление платежа для формы
"#"+Note(ReadNoteForPayment(paymentObj.paymentID,113))+  //Примечание для формы
"#"+Note(ReadNoteForPayment(paymentObj.paymentID,114))+  // Примечание для нужд банка
"#"+Note(ReadNoteForPayment(paymentObj.paymentID,118))+"#" // Дата предоставления справки
 ,"##","# #"));                          //там где нет ничего ставим пробел


if (pmco.VO_code==0)  //Анализируем Alt+V
SetOutput(null,true);  
msgbox("Выгружено в файл Oplata.d без кодов ВО");

  return 0; 

end;
 
SetOutput(null,true); 
 msgbox("Выгружено в файл Oplata.d с одним кодом по AlT+V");

end; 

End;

macro clear()
var path1;
getRegistryValue("PS\\REQOPENACC\\173-ФЗ СЧЕТА НЕРЕЗИДЕНТОВ\\ПУТЬ К ФАЙЛУ OPLATA.D",V_string,path1);
path1=path1+"Oplata.d";
SetOutput(path1,false);
SetOutput(null,true);
MsgBox("Файл очищен");
return 0
end;