/*Входящие претензии                                         */
/*                                                           */
/*                                                           */
/*Тихомиров А.Н. 15.03.2010               Версия 1.0         */
import rsd, RsbDataSet, globals, календарь;
import "diver.mac";

// KS 28.11.2011 ОТПРАВКА ПИСЕМ-УВЕДОМЛЕНИЙ В LOTUS
import "send_claim.mac";

private var COL, CMD, CMDTEXTCNT, RS, COMMAND, CMDTEXT, RECORDSET, EVPROC, INFO;
private var Fulloutputl, outl, outputl="pracc.lbr", number, sql, flag; 
private var Fulloutput2, out2, output2="claim.lbr", SEQ, initiat, initiator_text, reg_date, acc, claim_1, claim_2, claim_3, claim_id1;                    
GetRegistryValue("BANK_INI\\ОБЩИЕ ПАРАМЕТРЫ\\ДИРЕКТОРИИ\\LBRDIR",2,out2);
Fulloutput2 = FindPath(output2, out2);
   if (not Fulloutput2)
      msgbox("Не найдена LBR");
      exit();
   end;

var dlg3 = TRecHandler("claim", fulloutput2, TRUE); 

private macro cl_date1(claimid, regdate)
debugbreak;
var c = rsdcommand ("select t_sysdate from dacclmcng_dbt where t_changedocid =  ?");
c.addparam("CI",RSDBP_IN,claimid);
c.execute();
var r = rsdrecordset(c);
debugbreak;
if (r.movenext())
if ((date(r.value(0)) - regdate) == 0)
return false;
else
return true;
end;
else
return false;
end;
end;



private macro Arhdate1(regdate)
var c = rsdcommand ("select 1 from usr_claim where t_datefrom > sysdate");
c.execute();
var r = rsdrecordset(c);
debugbreak;
if (r.movenext())
return true;
else
return false;
end;
end;


private macro Arhdate2(regdate)
var c = rsdcommand ("select 1 from usr_claim where t_enterdate > ?");
c.addparam("date",RSDBP_IN,regdate);
c.execute();
var r = rsdrecordset(c);
debugbreak;
if (r.movenext())
return true;
else
return false;
end;
end;


 /*Обработчик диалоговой панели ввода исходных данных для печати*/
MACRO Event3 (dlg, cmd, id, key) 

   var const_mess = "~F2~ Продолжить ~ESC~ Выход ";

   /*Первоначальная инициализация полей*/
   if(cmd == DLG_INIT)
//      SEQ = getSEQ()+1;
      GenerateReference(1000011,SEQ);
      dlg.rec.number  = SEQ;
      dlg.rec.reg_date = {curdate};
      if (Initiat == 1)
      dlg.rec.party_reg = GetInitiator(acc);
      else
      dlg.rec.party_reg = "";
      end;
      message(const_mess);
      UpdateFields(dlg); 
   end;
   
   /*Установка подсказок в строке состояния*/
   if (cmd==DLG_SETFOCUS)
     if (FldName(dlg,id)=="reg_date")
       message(" ~F3~ Выбор даты из календаря "+const_mess);
    end;
   end;
   
   if (cmd == DLG_REMFOCUS)
      UpdateFields(dlg); 
   end;

   if (cmd == DLG_KEY)
     /*Выход из диалогового окна формирования отчета*/
     if (KEY == KEY_ESC)
       if (SEQ)
       RestoreReference(1000011,SEQ);
       end;
       return 0;//CM_CANCEL;
     /*Выбор данных из списка*/
     elif ( KEY == KEY_F3)
        /*Выбор даты из календаря*/
        if (FldName(dlg,id) == "Reg_date")
          dlg.rec.reg_date = GetDateByCalendar ({curDate});
        end;
        
     elif ( KEY == KEY_F2 )        //Проверки при вводе
			debugbreak;
             if (cl_date1(claim_id1, dlg.rec.reg_date))
                msgbox("Дата ввода претензии не совпадает с датой регистрации");
                Return CM_IGNORE;
               end;
             
           
           
           if (Arhdate2(dlg.rec.reg_date)) 
            IF (gettrue(true,"Есть зарегистрированные претензии следующей датой. необходимо проверить диапазон номеров. Сохранить?"));
               if (string(dlg.rec.number) != SEQ)
                if (RestoreReference(1000011,SEQ))
                 msgbox("Ошибка определения референса");
                 Return CM_IGNORE;
                end;
                SEQ = dlg.rec.number;
               else
                SEQ = dlg.rec.number;
               end;
              reg_date = dlg.rec.reg_date;


             if (strlen(dlg.rec.party_reg) > 0)
               initiator_text = dlg.rec.party_reg;
             else
               initiator_text = " ";
             end;
             Return CM_SAVE;
           else
            Return CM_IGNORE;
           end;
          else
               if (string(dlg.rec.number) != SEQ)
                if (RestoreReference(1000011,SEQ))
                 msgbox("Ошибка определения референса");
                 Return CM_IGNORE;
                end;
                SEQ = dlg.rec.number;
               else
                SEQ = dlg.rec.number;
               end;
              reg_date = dlg.rec.reg_date;
             if (strlen(dlg.rec.party_reg) > 0)
               initiator_text = dlg.rec.party_reg;
             else
               initiator_text = " ";
             end;
             Return CM_SAVE;
          
          end;
     elif (( KEY != 336 ) and ( KEY != 328 ))         //Проверки при вводе
            Return CM_IGNORE;
     end;
   end;
        
END;


 /*Обработчик диалоговой панели ввода исходных данных для печати*/
MACRO Event6 (dlg, cmd, id, key) 

   var const_mess = "~F2~ Продолжить ~ESC~ Выход ";

   /*Первоначальная инициализация полей*/
   if(cmd == DLG_INIT)
      dlg.rec.number  = Claim_1;
      dlg.rec.reg_date = Claim_2;
      dlg.rec.party_reg = Claim_3;
      message(const_mess);
      UpdateFields(dlg); 
   end;
   
   /*Установка подсказок в строке состояния*/
   if (cmd==DLG_SETFOCUS)
     if (FldName(dlg,id)=="reg_date")
       message(" ~F3~ Выбор даты из календаря "+const_mess);
    end;
   end;
   
   if (cmd == DLG_REMFOCUS)
      UpdateFields(dlg); 
   end;

   if (cmd == DLG_KEY)
     /*Выход из диалогового окна формирования отчета*/
     if (KEY == KEY_ESC)
       RestoreReference(1000011,SEQ);
       return 0;//CM_CANCEL;
     /*Выбор данных из списка*/
     elif ( KEY == KEY_F3)
        /*Выбор даты из календаря*/
        if (FldName(dlg,id) == "Reg_date")
          dlg.rec.reg_date = GetDateByCalendar ({curDate});
        end;
        
     elif ( KEY == KEY_F2 )        //Проверки при вводе
			debugbreak;
             if (cl_date1(claim_id1, dlg.rec.reg_date))
                msgbox("Дата ввода претензии не совпадает с датой регистрации");
                Return CM_IGNORE;
               end;
             
              
              SEQ = dlg.rec.number;
              reg_date = dlg.rec.reg_date;
             if (strlen(dlg.rec.party_reg) > 0)
               initiator_text = dlg.rec.party_reg;
             else
               initiator_text = " ";
             end;
             Return CM_SAVE;
          
     elif (( KEY != 336 ) and ( KEY != 328 ))         //Проверки при вводе
            Return CM_IGNORE;
     end;
   end;
        
END;



 /*Обработчик диалоговой панели ввода исходных данных для печати*/
MACRO Event4 (dlg, cmd, id, key) 

   var const_mess = "~F9~ Редактировать ~ESC~ Выход ";

   /*Первоначальная инициализация полей*/
   if(cmd == DLG_INIT)
      dlg.rec.number  = Claim_1;
      dlg.rec.reg_date = Claim_2;
      dlg.rec.party_reg = Claim_3;
      message(const_mess);
      UpdateFields(dlg); 
   end;
   
   if (cmd == DLG_KEY)
     /*Выход из диалогового окна формирования отчета*/
     if (KEY == KEY_ESC)
       return 0;//CM_CANCEL;
     elif (( KEY == KEY_F9 ))        //Проверки при вводе
         if (ВходитВГруппу({oper},176))
           Return CM_SAVE;
         else
           msgbox("Вы не принадлежите группе Редактирование входящего номера претензии");
           Return CM_IGNORE;
         end;
      else
           Return CM_IGNORE; 
     end;
   end;
        
END;


private macro Reg_claim_ch(claimid)
var cmd = rsdcommand("insert into usr_claim values (?, ?, ?, ?, ?, CHR(88), chr(88), sysdate, chr(0), chr(0)) ");
cmd.addparam("claimid",RSDBP_IN, claimid);
cmd.addparam("SEQ",RSDBP_IN, SEQ);
cmd.addparam("Reg_date",RSDBP_IN, Reg_date);
cmd.addparam("Initiator",RSDBP_IN, Initiator_text);
cmd.addparam("Oper",RSDBP_IN, {oper});
//cmd.addparam("datefrom",RSDBP_IN, {curdate});
cmd.execute;
sendClaimMails(claimid);// KS 28.11.2011 ОТПРАВКА ПИСЕМ-УВЕДОМЛЕНИЙ В LOTUS
return true;
end;

private macro Upd_claim_ch(claimid)
var cmd = rsdcommand("update usr_claim set t_flag = chr(0) where t_claimid = ? and t_flag = chr(88)  AND t_changedoc = CHR(88)");
cmd.addparam("claimid",RSDBP_IN, claimid);
cmd.execute;
Reg_claim_ch(Claimid);
sendClaimMails(claimid);// KS 28.11.2011 ОТПРАВКА ПИСЕМ-УВЕДОМЛЕНИЙ В LOTUS
return true;
end;

private macro read_ch(claimid)
var cmd = rsdcommand("SELECT * "+
"  FROM usr_claim  "+
" WHERE t_claimid = ? "+
"   AND t_flag = CHR(88) "+
"   AND t_changedoc = CHR(88) ");
cmd.addparam("acc", RSDBP_IN, claimid);
var rsd = rsdrecordset(cmd);
if (rsd.movenext())
  claim_1 = rsd.value(1);
  claim_2 = rsd.value(2);
  claim_3 = rsd.value(3);
  return 1;
end;
end;


macro enter_reg_ch(claimid, init, account, flag)
claim_id1 = claimid;
dlg3 = TRecHandler("claim", fulloutput2, TRUE); 
initiat = init;
acc = account;
 if (not flag)
if (RunDialog(dlg3, "Event3"))
  Reg_claim_ch(claimid);
end;
 else
if (RunDialog(dlg3, "Event6"))
  Upd_claim_ch(claimid);
 end;
end;
return 0;
end;

macro read_reg_ch(claimid, init, account)
dlg3 = TRecHandler("claimb", fulloutput2, TRUE); 
acc = account;
initiat = init;
read_ch(claimid);
if (RunDialog(dlg3, "Event4"))
  enter_reg_ch(claimid, init, account, 1);
end;
return 0;
end;


MACRO viewclaimscroll(claimid, init, account)
  var RecordSet,rs,s;
  var choice,CmdText,CmdTextCnt,Command, cmd;
  var col = TArray;
  var quest = false;
  number=0;

  CmdText = "SELECT cl.t_changedocid, cl.t_docdate, cl.t_docnumber, decode(cl.t_comment,chr(1),' ',cl.t_comment), 'Налоговые органы' as t_initiator, "+
"       usr.t_flag, val.t_name "+
"  FROM dllvalues_dbt val, dacclmcng_dbt cl  "+
"       LEFT JOIN "+
"       (SELECT * "+
"          FROM usr_claim "+
"         WHERE t_changedoc = CHR (88) AND t_flag = CHR (88)) usr "+
"       ON usr.t_claimid = cl.t_changedocid "+
" WHERE cl.t_claimid = ? AND cl.t_initiator = 1 and val.t_list = 2524 and val.t_element = cl.t_changekind";

  CmdTextCnt = "select count(1) "+
"  FROM dacclmcng_dbt cl "+
"       LEFT JOIN "+
"       (SELECT * "+
"          FROM usr_claim "+
"         WHERE t_changedoc = CHR (88) AND t_flag = CHR (88)) usr "+
"       ON usr.t_claimid = cl.t_changedocid "+
" WHERE cl.t_claimid = ? AND cl.t_initiator = 1";


   macro EvProc (RecordSet, Command, id, key )
      debugbreak;
      if ((Command == DLG_KEY) and (key == KEY_ENTER))
         if (recordset.value(5) == "X")
//           read_reg_ch(recordset.value(0), 1, "40702810508220025890"); //(claimid, init, account)
           read_reg_ch(recordset.value(0), init, account)
         else
//           enter_reg_ch(recordset.value(0), 1, "40702810508220025890");//(claimid, init, account)
           enter_reg_ch(recordset.value(0), init, account)
         end;
             flag=1;
         return CM_cancel;
      elif ((Command == DLG_KEY) and (key == KEY_ESC))
         return 0;
      else
         return cm_ignore;
      end;
   end;

   macro AddCol (ar,ind, fld, head, width, rdonly)
      ar.value (ind * 6)     = fld;
      ar.value (ind * 6 + 1) = head;
      ar.value (ind * 6 + 2) = width;
      ar.value (ind * 6 + 3 ) = 2;   // fldType
      ar.value (ind * 6 + 4 ) = -1;  // decPoint
      ar.value (ind * 6 + 5 ) = 0;   // reserv
   end;


   AddCol (col, 1, "t_docdate", "Дата документа", 10, true);
   AddCol (col, 2, "t_docnumber", "Номер документа", 5, true);
   AddCol (col, 3, "t_initiator", "Инициатор ограничения", 12, true);
   AddCol (col, 4, "t_name", "Вид изменения", 12, true);
   AddCol (col, 5, "t_comment", "Комментарий", 30, true);
   AddCol (col, 0, "t_flag", "Зарегистрировано", 10, true);

   Cmd = RSDCommand(CmdTextcnt);
//   cmd.addparam("id",RSDBP_IN,89056); //claimid
   cmd.addparam("id",RSDBP_IN,claimid); //claimid
   Cmd.Execute();
   rs = RSDRecordSet(Cmd);

   Command = RSDCommand(CmdText);
//   command.addparam("id",RSDBP_IN,89056);//claimid
   command.addparam("id",RSDBP_IN,claimid);//claimid
   Command.Execute();

   if(rs and rs.movenext)
      if(rs.value(0) >= 1)  /***************************************************************/
         RecordSet = RSDRecordSet(Command, RSDVAL_CLIENT, RSDVAL_STATIC);
         runScroll(RecordSet, 6, col, null, @EvProc, "Регистрация отменяющих документов", "~Enter~   Выбор", false);
      else
        msgbox("Отсутствуют введенные Изменяющие документы");
/*         RecordSet = RSDRecordSet(Command);
         if(RecordSet and RecordSet.movenext)
            info      = RecordSet.value(2);
         else
             number=0;
             RunDialog(dlg, "Event");
             flag=1;
             return 0;
         end;*/
      end;
   end;

return info;

END;


macro viewclaim (claimid, init, account)
flag=1;
while (flag)
  flag=0;
 viewclaimscroll(claimid, init, account);//(claimid, init, account);
end;
return info;                       
end;