/*Отправка сообщений в лотус по картам СКС I-101998*/
/*Тихомиров А.Н.*/
/*Gurin S. N. 22.08.2012 C-13529*/
/* Изменен : 19.03.2013 zmp C-7534 */
/*06.06.2013 Chesnokov D.S. по R-199784 отключил отправку уведомлений в Lotus по СКС если документ из ИК*/
import rsd, bankinter, globals, календарь;

import "frontcommon.mac";
private var oConn_lib = ActiveX("ADODB.Connection");
private var MaskAcc, TypeAcc, mail, errCode; //Gurin S. N. 22.08.2012 C-13529
private var Flag; //Gurin S. N. 22.08.2012 C-13529

//Gurin S. N. 22.08.2012 C-13529
GetRegistryValue("PRBB\\СКС_ЛОТУС\\МАСКА_СЧЕТА", V_STRING, MaskAcc, errCode);
  if (( MaskAcc == "" ) or (errCode > 0))
      MaskAcc = "^40702810..9|^40802810..9|^40703810..9|^40602810..9";
  end;

GetRegistryValue("PRBB\\СКС_ЛОТУС\\ТИП_СЧЕТА", V_STRING, TypeAcc, errCode);
  if (( TypeAcc == "" ) or (errCode > 0))
      Flag = False
  else
      Flag = True;
  end;

GetRegistryValue("PRBB\\СКС_ЛОТУС\\ПОЛУЧАТЕЛЬ", V_STRING, mail, errCode);
  if (( mail == "" ) or (errCode > 0))
      mail = "КДЦ-пластик, БЭК";
  end;


private macro TypeSKS(account, dockind, origin);
var r, s, r1, s1, sql; //Gurin S. N. 22.08.2012 C-13529
s = rsdcommand("SELECT   t_usertypeaccount  FROM   daccount_dbt  WHERE   t_account = ? AND t_chapter = 1");
s.addparam("acc", RSDBP_IN, account);
r = rsdrecordset(s);
if ( (r.movenext) and (strlen(r.value(0)) > 0))

   sql = "SELECT   1 "+
   "  FROM   DUAL "+
   " WHERE   REGEXP_LIKE ( "+
   "               ?, "+
   "               ? "+
   "            ) " +
   "         AND INSTR (?, 'T') = 0 "+
   "         AND INSTR (?, 'G') = 0 ";

   if (Flag==True) //Gurin S. N. 22.08.2012 C-13529
       sql = sql +
       "         AND INSTR (?, ?) <> 0 ";
   end;
   sql = sql+
   "         AND REGEXP_LIKE (?, '^70|^320|^322|^201|^202|^16|^27') "+
   "         AND REGEXP_LIKE (SUBSTR (?, 6, 3), '^810') "+
   "         AND REGEXP_LIKE (?, '^[0-9]$|^[0-9][0-9]$|^[0-9][0-9][0-9]$|1600$') ";
    s1 = rsdcommand(sql);
    s1.addparam("acc2", RSDBP_IN, account);
    s1.addparam("MaskAcc", RSDBP_IN, MaskAcc );
    s1.addparam("type1", RSDBP_IN, r.value(0));
    s1.addparam("type2", RSDBP_IN, r.value(0));
    if (Flag==True)
        s1.addparam("type3", RSDBP_IN, r.value(0));
        s1.addparam("typeacc", RSDBP_IN, TypeAcc);
    end;
    s1.addparam("dockind", RSDBP_IN, dockind);
    s1.addparam("acc3", RSDBP_IN, account);
    s1.addparam("origin", RSDBP_IN, origin);
    s1.execute;
    r1 = rsdrecordset(s1);
     if (r1.movenext)
         return 1;
     end;
 return 0;
end;
end;


/*Kozina*/
private macro TypeSKS_GT(account, dockind, origin);
var r, s, r1, s1;
s = rsdcommand("SELECT   t_usertypeaccount  FROM   daccount_dbt  WHERE   t_account = ? AND t_chapter = 1");
s.addparam("acc", RSDBP_IN, account);
r = rsdrecordset(s);
if ( (r.movenext) and (strlen(r.value(0)) > 0))

   s1 = rsdcommand("SELECT   1 "+
   "  FROM   DUAL "+
   " WHERE   REGEXP_LIKE ( "+
   "               ?, "+
   "               '^40702810..9|^40802810..9|^40703810..9|^40602810..9' "+
   "            ) "+
   "         AND (INSTR (?, 'T') <> 0 "+
   "              OR INSTR (?, 'G') <> 0) "+
   "         AND REGEXP_LIKE (?, '^70|^320|^322|^201|^202|^16|^27') "+
   "         AND REGEXP_LIKE (SUBSTR (?, 6, 3), '^810') "+
   "         AND REGEXP_LIKE (?, '^[0-9]$|^[0-9][0-9]$|^[0-9][0-9][0-9]$|1600$') ");
    s1.addparam("acc2", RSDBP_IN, account);
    s1.addparam("type1", RSDBP_IN, r.value(0));
    s1.addparam("type2", RSDBP_IN, r.value(0));
    s1.addparam("dockind", RSDBP_IN, dockind);
    s1.addparam("acc3", RSDBP_IN, account);
    s1.addparam("origin", RSDBP_IN, origin);
    r1 = rsdrecordset(s1);
     if (r1.movenext)
       return 1;
     end;
 return 0;
end;
end;


/*Подключение к фронту*/
macro Send_l_pm(paymentobj, origin)
  var oConn = oConn_lib, connstr, rsd_conn, rsd_proc;
  var theme = "";
  var text = "";
  var ID = 73;
 // var mail = "КДЦ-пластик, БЭК"; //Gurin S. N. 22.08.2012 C-13529
  array aInpM, aOutM;

 debugbreak;
 /*19.03.2013 zmp C-7534 - указываю в теме письма наименование банка*/
 /*06.06.2013 Chesnokov D.S. по R-199784 отключил отправку уведомлений в Lotus по СКС если документ из ИК*/
if ((paymentobj.origin != 2) and (TypeSKS(paymentobj.payeraccount, paymentobj.dockind, paymentobj.origin)))
   theme = string("Банк: ", {NAME_BANK}, " ", date(), " ", time()," Проведено"," списание с СКС по корпоративным картам. ");
   text  = string("Банк: ", {MFO_BANK} ,{NAME_BANK}, " Клиент: ", substr(paymentobj.payeraccount,16), " Счет: ", paymentobj.payeraccount, " Номер документа: ", paymentobj.number, " Сумма: ", paymentobj.baseamount, " Дата документа: ", paymentobj.date, " Дата значения: ",paymentobj.valuedate, " Операционист: ",paymentobj.oper, " Исполнитель: RS-Bank ", {oper} );
   //mail = "КДЦ-пластик, БЭК";
elif ((paymentobj.origin != 2) and (TypeSKS(paymentobj.receiveraccount, paymentobj.dockind, paymentobj.origin)))
   theme = string("Банк: ", {NAME_BANK}, " ", date(), " ", time()," Проведено"," пополнение СКС по корпоративным картам." );
   text  = string("Банк: ", {MFO_BANK} ,{NAME_BANK}, " Клиент: ", substr(paymentobj.receiveraccount,16), " Счет: ", paymentobj.receiveraccount, " Номер документа: ", paymentobj.number, " Сумма: ", paymentobj.baseamount, " Дата документа: ", paymentobj.date, " Дата значения: ",paymentobj.valuedate, " Операционист: ",paymentobj.oper, " Исполнитель: RS-Bank ", {oper} );
   //mail = "КДЦ-пластик, БЭК";
elif (TypeSKS_GT(paymentobj.payeraccount, paymentobj.dockind, origin))
   theme = string("Банк: ", {NAME_BANK}, " ", date(), " ", time()," Проведено"," списание с СКС по таможенным картам. ");
   text  = string("Банк: ", {MFO_BANK} ,{NAME_BANK}, " Клиент: ", substr(paymentobj.payeraccount,16), " Счет: ", paymentobj.payeraccount, " Номер документа: ", paymentobj.number, " Сумма: ", paymentobj.baseamount, " Дата документа: ", paymentobj.date, " Дата значения: ",paymentobj.valuedate, " Операционист: ",paymentobj.oper, " Исполнитель: RS-Bank ", {oper} );
   //mail = "Anna A Kozina/IT/Probusiness Bank@prbb";
   mail = "TCard";
elif (TypeSKS_GT(paymentobj.receiveraccount, paymentobj.dockind, origin))
   theme = string("Банк: ", {NAME_BANK}, " ", date(), " ", time()," Проведено"," пополнение СКС по таможенным картам." );
   text  = string("Банк: ", {MFO_BANK} ,{NAME_BANK}, " Клиент: ", substr(paymentobj.receiveraccount,16), " Счет: ", paymentobj.receiveraccount, " Номер документа: ", paymentobj.number, " Сумма: ", paymentobj.baseamount, " Дата документа: ", paymentobj.date, " Дата значения: ",paymentobj.valuedate, " Операционист: ",paymentobj.oper, " Исполнитель: RS-Bank ", {oper} );
   mail = "TCard";
else   
  return 0;
end;    

   
   /* Инициализация параметров */
   aInpM(0) = 1;
//   aInput(1) = ;
   aInpM(2) = ID; /*ID из фронта*/
//   aInput(3) = "";
//   aInput(4) = "";
//   aInput(5) = "";
   aInpM(6) = 0;
   aInpM(7) = {curdate};
   aInpM(8) = theme;
   aInpM(9) = text;
   aInpM(10) = mail;
   asize(aOutM,0);
   
//По ТЗ, лучше возьмем из строки соединения, для ЮЛ
   rsd_conn = rsdrecordset(rsdcommand("select connstring from usr_route_parm where rule_id = 4"));
   if (rsd_conn.movenext())
     connstr = rsd_conn.value(0);
   else
     msgbox("Строка соединения не найдена");
     return 0;
   end;

/*Это строка для Тестовой базы, там таблица маршрутизации отсутствует*/
   conn2front(oConn, connstr);

   rsd_proc = RSADORecordset(ExecuteFrontProcEx("iud_f_notice", aInpM, oConn));
   /* Если осталось открытое соединение, закрываем */
   if (oConn and (oConn.State == 1) )
      oConn.Close();
   end;
  return 0;
END;
