/*++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

   EVG Макрос выполнения шага операции по переносу остатка с одного валютного 
       счёта на другой валютный счёт без переноса покрытия. Предназначен для 
       сворачивания счетов ОВП.

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*/
Import BankInter, PaymInter, Cbsttls;

var PaymentObj : RsbPayment;


macro ExecuteStep( doc, primdoc )
  
  var stat = 0;
  
  var ВалютныйДокумент = RsbAccTransaction;
  var Memorial : RsbMemorialOrder = RsbMemorialOrder( PaymentObj.DocumentID );

  ВалютныйДокумент.Chapter          = Memorial.Chapter;
  ВалютныйДокумент.FIID             = Memorial.Code_Currency;
  ВалютныйДокумент.Sum              = PaymentObj.PayerAmount;
  ВалютныйДокумент.AccountPayer     = PaymentObj.PayerAccount;
  ВалютныйДокумент.AccountReceiver  = PaymentObj.ReceiverAccount;
  ВалютныйДокумент.Numb_Document    = PaymentObj.Number;
  ВалютныйДокумент.Date_Carry       = PaymentObj.ValueDate;
  ВалютныйДокумент.Ground           = PaymentObj.Ground;
  ВалютныйДокумент.TypeDocument     = Memorial.TypeDocument;
  ВалютныйДокумент.Number_Pack      = PaymentObj.NumberPack;
  ВалютныйДокумент.Shifr_Oper       = PaymentObj.ShifrOper;
  ВалютныйДокумент.Kind_Oper        = Memorial.Kind_Oper;
  ВалютныйДокумент.Department       = PaymentObj.Department;
  ВалютныйДокумент.UserTypeDocument = Memorial.UserTypeDocument;

  ВалютныйДокумент.NoEquivalentCarry = true; /* проводка без покрытия */

  ВалютныйДокумент.Date_Rate = PaymentObj.ValueDate;

  if( not ВалютныйДокумент.Carry() )
    stat = 1;
    msgbox( "Ошибка при вставки проводки" );
  end;

  
  // Статус платежа меняем на "Завершенный платеж"
  PaymentObj.PaymStatus = PM_FINISHED;
  // Изменяем дату списания со счета плательщика
  PaymentObj.PayerChargeOffDate = PaymentObj.ValueDate;

  if( УстановитьСтатусыПлатежа( OPR_PAYM_STATE, OPR_PM_ST_CLOSE ) )
    msgbox("Ошибка при установке сегментов статуса экземпляра операции");
    return 1;
  end;

  return stat;

end;
