/*16.07.08 R-Style Ukraine          */ 
/*Ž¯ ­ á¥­ª® ž.”. „«ï à®¡¨§­¥á¡ ­ª */
/*’¨å®¬¨à®¢ €.. ”®à¬  –¥­­®áâ¨*/
import globals, get_mfo, FIInter, ReportInter, PTInter, "bbprncom.mac", "prnlib.mac";
import prpmbuff; //pr_pmpaym, pr_pmrmprop
import oralib;


private const NATCUR            = 0;


var pr_cb_doc:TRecHandler  = TRecHandler("cb_doc.dbt", "bank.def");

MACRO printCB_DOC(cbdoc, pmpaym, rm, NumCopy)

  var Payer,
      Receiver,
      BIC_Payer       = "",
      BIC_Receiver    = "",
      CorAcc_Payer    = "",
      CorAcc_Receiver = "",
      NameDocument    = "",
      Sum,
      SumR,
      dateDoc,
      ground,
      oper_name,
      passport,
      rsd,
      cmd,
      Document_name, 
      pn = "";

  var FIOOper         = "",
      FIOKontr        = "",
      InitOper        = 0,
      DateKontr;       

  /* ®¤£®â®¢ª  áâà®ª ª ¯¥ç â¨ */
  ARRAY SS, SG, SBP, DD, pp, DN;

  cmd  =  "select NK.T_NOTEKIND, USR_NOTETEXT.ConvertRAWtoSTRING(NT.T_TEXT, NK.T_NOTETYPE) T_TEXT "+
          "from dnotekind_dbt nk, dnotetext_dbt nt " +
          "WHERE NK.T_NOTEKIND = NT.T_NOTEKIND " +
          "and nk.T_OBJECTTYPE = 70 and NT.T_DOCUMENTID (+) = lpad('" + pmpaym.PaymentId + "',34,'0')";
  rsd = RSDRecordset(cmd);

  Document_name = "";
  Passport = "";
  DN(0) = "";
  DN(1) = "";
  oper_name = "";

  while(rsd.MoveNext())
   if (rsd.value(0) == 101)
     DN(0) = rsd.value(1);
   elif (rsd.value(0) == 102)
     DN(1) = rsd.value(1);
   elif (rsd.value(0) == 103)
     Document_name = rsd.value(1);
   elif (rsd.value(0) == 104)
     pn = rsd.value(1);
   elif (rsd.value(0) == 105)
     Passport = rsd.value(1);
   elif (rsd.value(0) == 106)
     oper_name = rsd.value(1);
   end;
  end;

  if( pmpaym.ValueDate > Date(0, 0, 0) )
     dateDoc = pmpaym.ValueDate;
  else
     dateDoc = {curdate};
  end;

  /*  áç¥â áã¬¬ë ¢ àã¡«ïå */
  if(cbdoc.Code_Currency != NATCUR)
    ConvSum( SumR, pmpaym.Amount, dateDoc, cbdoc.Code_Currency );
  else SumR = "";
  end;
  Sum = CurToStrAlt( pmpaym.Amount, null, null, GetISOCode( cbdoc.Code_Currency ) );

  Payer    = pr_pmrmprop.rec.PayerName;
  Receiver = pr_pmrmprop.rec.ReceiverName;

 ground = rm.ground;



 while (index(ground,"+")>0)
 if (strlen(oper_name) == 0)
         if (strlen(substr(ground,1,index(ground,"+")))>0)
           oper_name = substr(ground,1,index(ground,"+"));
         else
           cmd = rsdcommand("select t_name from dperson_dbt where t_oper = ?");
           cmd.addparam("id",RSDBP_IN,pmpaym.oper);
           cmd.execute();
           rsd = rsdrecordset(cmd);
           if (rsd.movenext())
              oper_name = rsd.name;
           else
              oper_name = "Žè¨¡ª ";
           end;

         end;
 elif (strlen(Document_name) == 0)
        Document_name = substr(ground,1,(index(ground,"+")-1));
 else
        passport = substr(ground,1,(index(ground,"+")-1));
 end;
 ground = substr(ground,(index(ground,"+")+1));
 end;
 
  strsplit( {Name_Bank},          SBP,   43,43,3 );
  strsplit( Sum,                  SS,    69, 69, 2);
  strsplit( ground,            SG,    69, 69, 3);
  strsplit( Document_name,            DD,    69, 69, 2);
  strsplit( passport,            pp,    69, 69, 2 );

  /* ®«ãç¨âì ”ˆŽ ®¯¥à æ¨®­¨áâ  ¯® ¥£® ¨¤¥­â¨ä¨ª â®àã */
  macro GetFIOOper(OperID:integer):string
     file Person  ("person.dbt"); 
   
       Person.Oper = OperID;
     if (GetEQ(Person))
        return Person.Name;  
     end; 
  end;
  /* ®«ãç¨âì áâ âãá ®¯¥à æ¨¨  */
  macro GetOprStat(PaymentID:integer, KindOper:integer, DocKind:integer):bool
     var select:string = "";
     var rs:object;
     var stat:bool = false;
     
     select = "SELECT * FROM doproper_dbt "+
              "WHERE t_kind_operation = "+KindOper+" "+
              "AND t_dockind = "+DocKind+" "+
              "AND t_documentid LIKE '%"+PaymentID+"' ";

     rs = ExecSQLSelect(select);
     while (rs.moveNext())
        InitOper  = int(rs.Value("t_init_oper"));
        DateKontr = date(rs.Value("t_syst_date")); //   â®â á«ãç ©, ¥á«¨ ¯®­ ¤®¡¨âáï ¢ë¢®¤¨âì á¨áâ¥¬­ã ¤ âã,   ­¥ ¤ âã ®¯¥à¤­ï
        //DateKontr = date(rs.Value("t_start_date")); 
        stat = true;
     end;
     return stat;

  end;

  FIOOper  = GetFIOOper(cbdoc.oper);
  if (GetOprStat(pmpaym.PaymentId, cbdoc.Kind_Operation, pmpaym.DocKind))
     if ( (pmpaym.PaymStatus > 0) and (InitOper != 0))
        FIOKontr = GetFIOOper(InitOper);
     end;
  end;
  if (DateKontr < dateDoc)
     DateKontr = dateDoc;
  end;
  
  while(NumCopy != 0)
/*® § ï¢ª¥ 47058€ „®à ¡®âª  ü ¤®¢¥à¥­­®áâ¨*/

[####################################              ”®à¬  ‚Ž-2*

        Œ…ŒŽˆ€‹œ›‰ Ž„… Ž ‚›„€—… –…Ž‘’…‰ ü ############# 

                     #########################

ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿   
³    ‚­¥¡ « ­á®¢ë©                                     ³
³        áç¥â                        ‘ã¬¬              ³
ÃÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
³„³ ########################### ³                      ³
ÃÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´    ##############    ³
³Š³ ########################### ³                      ³
ÀÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ

    ®«ãç¨«:  #######################################
    „®¢¥à¥­­®áâì ü ######### ®â ##############

     ¨¬¥­®¢ ­¨¥ æ¥­­®áâ¥© ¨ ¤®ªã¬¥­â®¢:
    #################################################################   
    #################################################################

    Žá­®¢ ­¨¥:
    #################################################################
    #################################################################
    #################################################################

     á¯®àâ:#########################################################
    ¢ë¤ ­ ###########################################################
    #################################################################

    ‘ã¬¬  ¯à®¯¨áìî:
    #################################################################
    #################################################################

    à¨«®¦¥­¨¥ ­  __________ «¨áâ å

    Š®­âà®«¥à _____________________ ®«ãç â¥«ì __________________

    ˆá¯®«­¨â¥«ì ___________________ Š áá¨à ___________________


]
({Name_Bank}:r,
rm.number,
dateDoc:m,
pmpaym.PayerAccount,
pmpaym.Amount:l:f,
pmpaym.ReceiverAccount,
oper_name,
DN(0),
DN(1),
DD(0),
DD(1),
SG(0),
SG(1), 
SG(2), 
pn,
PP(0),
PP(1),
SS(0),
SS(1)

);

    NumCopy = NumCopy - 1;
  end;

END;


MACRO PrintDocument( ncopy:integer):bool
 var DocKind:integer = pr_pmpaym.rec.DocKind;

 if( DocKind != 70/*DLDOC_MEMORIALORDER*/ )
   MsgBox("„ ­­ë© ¢¨¤ ¤®ªã¬¥­â  ­¥ ¯®¤¤¥à¦¨¢ ¥âáï ¬ ªà®á®¬");
   return FALSE;
 end;
 
 debugbreak;

 printCB_DOC    (pr_cb_doc.rec, pr_pmpaym.rec, pr_pmrmprop.rec, ncopy);
 return TRUE;
END;
