/* г==================================================================┐ */
/*         Автоматизированная банковская система RS-Bank v5.0           */
/*                 Copyright (c) R-Style Software Lab 1998              */
/*                                                                      */
/*  Имя файла        : comminit.mac                                     */
/*                                                                      */
/*  Описание         : Макрос инициализации операции периодической      */
/*                     комиссии (операция 4601)                         */
/*                                                                      */
/*  Программист      : Гуцу Е.В.                                        */
/*                                                                      */
/*  Создан           : 09.12.2009                                       */
/*                                                                      */
/* L==================================================================- */

record defcom(sfdefcom);


MACRO InitOperation( KindOp, KindDoc, docaddr )

debugbreak;
  SetBuff(docaddr, defcom);

  msgbox (KindOp, " - ", KindDoc, " - ", defcom.CommNumber, " - ",defcom.SkippedByMacro);

  if (defcom.SkipedByMacro == "X")
     return 1;
  end;

  return 0;
END;


  






