/* 28.01.2010 Ярмольчук А.Ю. */

import bankinter, cb_sql, oralib;

const Группа_доступа_для_сброса = 163;
/*
 Проверить или входит опер в заданную группу СУД. Процедура взята из diver.mac
*/
Macro ВходитВГруппу(Oper,IdGroup)
 var stat = true; 
 var select, recSet, command;
 select = "SELECT t_name FROM DACSGROUP_DBT WHERE T_GROUPID = " + IdGroup;
 command = RSDCommand(select);
 command.execute();
 recSet = RSDRecordSet(command, RSDVAL_CLIENT, RSDVAL_STATIC);
 if (recSet and recSet.moveNext())
   select = "select * from DACSGROUPOPER_DBT where T_GROUPID = "+ IdGroup +" and T_OPER = " + Oper;
   command = RSDCommand(select);
   command.execute();
   recSet = RSDRecordSet(command, RSDVAL_CLIENT, RSDVAL_STATIC);
   if (not(recSet and recSet.moveNext()))
    stat = false;
   end;
  else 
   msgbox("Группа с номером " + IdGroup + " не найдена");
   stat = false;
 end;
 return stat;
End;


macro main
 //Gurin S. 30.01.2014 Адаптация 2031
 var {oper}, rub_acc_1=-1, val_acc_1=-1, rub_acc_2=-1, val_acc_2=-1, rs;

 if (ВходитВГруппу ({oper}, Группа_доступа_для_сброса))

    if (GetTrue (false,"ВНИМАНИЕ! Будут удалены пользовательские типы 'Y' всех лицевых счетов! Удалить?"))


       rs = ExecSQLSelect("select count (*) from daccount_dbt where T_USERTYPEACCOUNT like '%Y%' and t_code_currency = 0");
       if (rs.movenext)
          rub_acc_1=int (rs.value (0));
       end;

       rs = ExecSQLSelect("select count (*) from daccount_dbt where T_USERTYPEACCOUNT like '%Y%' and t_code_currency != 0");
       if (rs.movenext)
          val_acc_1=int (rs.value (0));
       end;

       [До выполнения процедуры
        =======================
        Рублевых счетов с признаком 'Y': ##########
    
        Валютных счетов с признаком 'Y': ##########

       ] (int (rub_acc_1), int (val_acc_1));


       if (not WriteFiscLog (OLstrproc, "Начинается сброс подтверждений остатков лицевых счетов. Необработано: рублевых: "+string (rub_acc_1)+"\nвалютных: "+string (val_acc_1)))
          println ("Журнализация начала процедуры не выполнена");
       end;

         //Tikh Переписал
//       sql_execute ("update daccount_dbt  set T_USERTYPEACCOUNT = replace (T_USERTYPEACCOUNT, 'Y') where T_USERTYPEACCOUNT like '%Y%'","Выполняется сброс признака 'Y' на рублевых счетах", false);
         sql_execute ("          UPDATE daccount_dbt p SET p.t_usertypeaccount = CASE WHEN length(p.t_usertypeaccount) > 1 THEN replace (T_USERTYPEACCOUNT, 'Y') ELSE replace (T_USERTYPEACCOUNT, 'Y', chr(1)) END WHERE p.T_USERTYPEACCOUNT like '%Y%' and t_code_currency = 0","Выполняется сброс признака 'Y' на рублевых счетах", false);
//       sql_execute ("update daccount$_dbt set T_USERTYPEACCOUNT = replace (T_USERTYPEACCOUNT, 'Y') where T_USERTYPEACCOUNT like '%Y%'","Выполняется сброс признака 'Y' на валютных счетах", false);
         sql_execute ("          UPDATE daccount_dbt p SET p.t_usertypeaccount = CASE WHEN length(p.t_usertypeaccount) > 1 THEN replace (T_USERTYPEACCOUNT, 'Y') ELSE replace (T_USERTYPEACCOUNT, 'Y', chr(1)) END WHERE p.T_USERTYPEACCOUNT like '%Y%' and t_code_currency != 0","Выполняется сброс признака 'Y' на валютных счетах", false);

       rs = ExecSQLSelect("select count (*) from daccount_dbt where T_USERTYPEACCOUNT like '%Y%' and t_code_currency = 0");
       if (rs.movenext)
          rub_acc_2=int (rs.value (0));
       end;

       rs = ExecSQLSelect("select count (*) from daccount_dbt where T_USERTYPEACCOUNT like '%Y%' and t_code_currency != 0");
       if (rs.movenext)
          val_acc_2=int (rs.value (0));
       end;

       [После выполнения процедуры
        =======================
        Рублевых счетов с признаком 'Y': ##########
    
        Валютных счетов с признаком 'Y': ##########

       ] (int (rub_acc_2), int (val_acc_2));

       if ((rub_acc_2==0) and (val_acc_2==0))
          println ("Признаки подтверждений остатков лицевых счетов сброшены. ", date,"  ", time, " Выполнил операционист № ",{oper});
       else
          println ("Внимание! Не все счета были обработаны. Необходимо повторить процедуру!");
       end;

       if (not WriteFiscLog (OLstrproc, "Сброс подтверждений остатков лицевых счетов выполнен. Осталось необработано: рублевых: "+string (rub_acc_2)+"\nвалютных:"+string (val_acc_2)))
          println ("Журнализация завершения процедуры не выполнена");
       end;


    else
       println ("Удаление пользовательских типов не выполнено. Отказ пользователя от совершения этой операции");
    end;
 else
    msgbox ("Внимание! Вам запрещено выполнять данную операцию.|Вы не входите в группу СУД № "+Группа_доступа_для_сброса+" Удаление признака Y со счетов");
 end;
end;

main;