/*──────────────────────────────────────────────────────────────────────────┐
  RS-Bank 6.0                                          R-Style Software Lab

  File Name   : mo2161u.mac.mac
  Created     : 25.08.2009
  Programmer  : Попова О.
  Description : Печатная форма МО по ф.2161-У
                для одновалютного мемордера

└───────────────────────────────────────────────────────────────────────────*/



import "pr2161.mac", "pr2161lib.mac";

private VAR CopyCont = 1;          /* Кол-во копий                         */

var pr_cb_doc:TRecHandler = TRecHandler("cb_doc.dbt", "bank.def");

private macro typeacc(account, chapter)
var cmd = rsdcommand ("select 1 from daccount_dbt where t_account = ? and t_usertypeaccount like '%А%' and t_chapter = ?");
cmd.addparam("acc",RSDBP_IN, account);
cmd.addparam("chapter",RSDBP_IN, chapter);
var rsd = rsdrecordset(cmd);
if (rsd.movenext())
return true;
else
return false;
end;
end;


MACRO PrintDocument(ncopy: integer):bool
debugbreak;

ground = pr_pmrmprop.rec.ground;
var Document_name = "";
var cmd, rsd;
array pass, docum;
 
 If (index(ground,"+")>0)
        document_name = substr(ground,1,(index(ground,"+")-1));
//        ground = "Чековая книжка "+ substr(ground,(index(ground,"+")+1));
        ground = substr(ground,(index(ground,"+")+1));
 else
//        ground = "Чековая книжка "+ ground;
 end;

 strsplit(document_name,docum,100,60,2);
  

  post ="     Наименование ценностей и документов:   "+docum(0)+"\n"+
"\n"+
"   "+docum(1);

  name = "МЕМОРИАЛЬНЫЙ ОРДЕР ПО ВЫДАЧЕ ЦЕННОСТЕЙ";

  pre_post = "  Подписи  \n"+
"                            \n"+
"  Контролер______________  Кассир_________________ \n"+
" \n"+
"  Исполнитель____________  \n"+
" \n"+
" \n"+
"  Приложение: __________________________________  документов  на __________листах \n\n";


  var ReportData = СформироватьОтчетДляОдновалютногоМО( pr_cb_doc );
  CopyCont = ncopy;
  
  while(CopyCont)
    ReportData.PrintReport();
    CopyCont = CopyCont - 1;
  end;
  return true;

END;