
//LVV 08.12.2014 I-00537160-2 адаптация под 31
import "keycodes.mac";   

array mn, me;
var shifr, kind, m, cmd12, sh, k12;
var Fulloutput2, out2, output2="ShifrKind.lbr";                    

GetRegistryValue("BANK_INI\\ОБЩИЕ ПАРАМЕТРЫ\\ДИРЕКТОРИИ\\LBRDIR",2,out2);
Fulloutput2 = FindPath(output2, out2);
if (not Fulloutput2)
	msgbox("Не найдена LBR");
	exit();	
end;

var dlg2 = TRecHandler("sk", fulloutput2, TRUE); 

mn(0) = "01 | Списано, зачислено по платежному поручению ";
mn(1) = "02 | Оплачено, зачислено по платежному требованию";
mn(2) = "03 | Оплачен наличными денежный чек";
mn(3) = "04 | Поступило наличными по объявлению на взнос наличными";
mn(4) = "05 | Оплачено, зачислено по требованию-поручению";
mn(5) = "06 | Оплачено, зачислено по инкассовому поручению";
mn(6) = "07 | Оплачено, поступило по расчетному чеку";
mn(7) = "08 | Открытие аккредитива, зачисление сумм неиспользованного, аннулированного аккредитива";
mn(8) = "09 | Списано, зачислено по мемориальному (расходному, приходному кассовому) ордеру";
mn(9) = "10 | Документы по погашению кредита, кроме поименованных выше";
mn(10) = "11 | Документы по выдаче кредита, зачислению кредита на счет, кроме поименованных выше";
mn(11) = "12 | Зачислено на основании авизо";
mn(12) = "13 | Расчеты с применением банковских карт";
mn(13) = "16 | Оплачено, зачислено по платежному ордеру";

me(0) =  "6 | Внутренние";
me(1) =  "3 | Кассовые";
me(2) =  "1 | Внешние";


Macro USK (documentid);   
	cmd12 = rsdcommand("update dcb_doc_dbt set t_kind_oper = ? where t_documentid = ?");
	cmd12.addparam ("Kind",RSDBP_IN,kind);
	cmd12.addparam ("Id",RSDBP_IN,documentid);
	cmd12.execute();
	cmd12 = rsdcommand("commit");
	cmd12.execute();

	cmd12 = rsdcommand("update dpmrmprop_dbt set t_shifroper = ? where t_paymentid = ?");
	cmd12.addparam ("Shifr",RSDBP_IN,shifr);
	cmd12.addparam ("Id",RSDBP_IN,documentid);
	cmd12.execute();
	cmd12 = rsdcommand("commit");
	cmd12.execute();
end;


/* EVG Обновление шифра / вида в проводках */
Macro UpdateCarry( autoK )
	var cmd;

	cmd = rsdcommand("update dacctrn_dbt set t_kind_oper = ?, t_shifr_oper = ? where t_acctrnid = ?");
	cmd.addparam ("Kind",RSDBP_IN, kind);
	cmd.addparam ("Shifr",RSDBP_IN, Shifr);
	cmd.addparam ("Id",RSDBP_IN, autoK);
	cmd.execute();
//	cmd = rsdcommand("commit");   
//	cmd.execute();
end;



/*Обработчик диалоговой панели ввода исходных данных для печати*/
MACRO Event2 (dlg, cmd, id, key) 

	var const_mess = "~F2~ Продолжить ~ESC~ Выход ";

	/*Первоначальная инициализация полей*/
	if(cmd == DLG_INIT)
		dlg.rec.Shifr  =sh;
		dlg.rec.kind = k12;
		UpdateFields(dlg); 
	end;

	/*Установка подсказок в строке состояния*/
	if (cmd==DLG_SETFOCUS)
		if (FldName(dlg,id)=="Shifr") 
			message(" ~F3~ Шифр операций "+const_mess);
		elif (FldName(dlg,id)=="Kind")
			message(" ~F3~ Шифр операций "+const_mess);
		end;
	end;

	if (cmd == DLG_KEY)
		/*Выход из диалогового окна формирования отчета*/
		if (KEY == KEY_ESC)
			return 0;
			return exit(1);//CM_CANCEL;
			/*Выбор данных из списка*/
		elif ( KEY == KEY_F3)
			/*Выбор подразделения банка из списка подразделений */
			if (FldName(dlg,id) == "Shifr")
				m = menu (mn, "Выберите шифр документа","Выберите шифр документа");
				if (m < 0)
					UpdateFields(dlg); 
				elif (m <13)
					if (strlen(string(m)) == 1)
						dlg.rec.shifr = string("0",(m+1));
					else
						dlg.rec.shifr = string(m+1);
					end;
				elif (m == 13)
					dlg.rec.shifr = string("16");
				end;
				UpdateFields(dlg); 
			end;
			if (FldName(dlg,id) == "Kind")
				m = menu (me, "Выберите вид документа","Выберите вид документа");
				if (m == 0)
					dlg.rec.kind = string(" 6");
				elif (m == 1)
					dlg.rec.kind = string(" 3");
				elif (m == 2)
					dlg.rec.kind = string(" 1");
				end;
				UpdateFields(dlg); 
			end;
							// ASV Добавил Ф9 на сэйв
		elif (( KEY == KEY_F2 )  or ( KEY == KEY_ENTER ) or (KEY == KEY_F9))     //Проверки при вводе
			shifr  = dlg.rec.shifr;
			kind = dlg.rec.kind;
			Return CM_SAVE;
		end;
	end;
END;


/* EVG 18/11/09 Добавил функциониальность обновления шифра/вида в проводках */
Macro UpdateSK (documentid, kind, shifr, isUpdatingCarry);
	sh = shifr;
	k12 = kind;
	debugbreak;
	if (RunDialog(dlg2, "Event2"))
		/* EVG */
		if (isUpdatingCarry)
			UpdateCarry(documentid);
		else
			uSK(documentid);
		end;
	else
		return 0;
	end;
end;
